### ISSUE TITLE
[Initial Version]

### ISSUE THREAD

**Issue by christocracy** [transistorsoft/flutter_background_fetch#1]
The plugin is almost ready for release to those watching this repo.

**Comment by christocracy** [comment]
`background_fetch` is now [released](https://pub.dartlang.org/packages/background_fetch)!

**Comment by radvansky-tomas** [comment]
Are the other plugins available in your callback ? https://github.com/flutter/flutter/issues/3671
@christocracy

**Comment by christocracy** [comment]
Other plugins meaning your own app dependencies?

Should be.

**Comment by radvansky-tomas** [comment]
@christocracy yes I did similar thing (with dart background execution, following some of your pattern) however I cannot invoke plugins from callback...I am trying to make simple thing...issue iOS local notification after remote notification is received...so this notification wakes up phone, callback is executed etc...but plugin does not exist. Some people described that this is because registration of plugin happens on start not really when app awakes from bcg state...

Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method show on channel dexterous.com/flutter/local_notifications)

**Comment by christocracy** [comment]
I will look into it.

**Comment by radvansky-tomas** [comment]
@christocracy https://github.com/flutter/engine/pull/6396 I dont think thats possible for know...therefore I cannot really see usage of any of those plugins. Lets say your background location or background fetch plugin is triggered...and you want to save location via firebase...or you want use any other native (plugin) feature...you just cannot...I am not saying that any of those issues are your fault :D ...but still until this is resolved, its unfinished :( Do you have any suggestion how to continue ? As now I am kind of stuck...My use case is pretty simple -> receive notification, process is in shared flutter logic (using plugins), and finally send local notification (plugin as well) ...Can we wake up app completely (not using headless dart) to have plugin access ?

**Comment by christocracy** [comment]
I have no trouble executing `#getCurrentPosition` from my [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation) plugin within a `BackgroundFetch` headless-task.

However, both these plugin are configured for running in headless mode.

```dart
void backgroundFetchHeadlessTask() async {
  bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
  print('*** [BackgroundGetch] HeadlessTask, location: $location');
  BackgroundFetch.finish();
}
```

**Comment by radvansky-tomas** [comment]
Ok. I will try to add headless support to local notif and try again. And let u know outcome

**Comment by christocracy** [comment]
I can use [`battery`](https://pub.dartlang.org/packages/battery#-readme-tab-) in a headless-task.

```dart
void backgroundFetchHeadlessTask() async {
  bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
  print('*** [BackgroundGetch] HeadlessTask, location: $location');

  // Get battery level
  var battery = new Battery();
  var level = await battery.batteryLevel;
  print('*** Battery level: $level');

  BackgroundFetch.finish();
}
```
```
I flutter : *** [BackgroundGetch] HeadlessTask, location: [Location {odometer: 11592.0, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 1.0, is_charging: true}, uuid: cc647f8c-a4f5-4949-b761-2248be801848, coords: {altitude: 44.8, heading: -1.0, latitude: 45.519229, accuracy: 12.1, speed: -1.0, longitude: -73.6171032}, is_moving: false, timestamp: 2018-11-11T18:57:49.704Z}]
flutter : *** Battery level: 100
```

**Comment by radvansky-tomas** [comment]
Ok thank your for your work. I will test your plugin in my app and if it works i did some mistake :(

**Comment by christocracy** [comment]
I can use [shared_preferences]() in a `BackgroundFetch` headless task to update a count of number of fetch events received.

```dart
void backgroundFetchHeadlessTask() async {
  // Get current-position from BackgroundGeolocation
  bg.Location location = await bg.BackgroundGeolocation.getCurrentPosition(samples: 1);
  print('*** [BackgroundFetch] HeadlessTask, location: $location');

  // Get battery level
  var battery = new Battery();
  var level = await battery.batteryLevel;
  print('*** Battery level: $level');

  // Keep track of number of times we receive fetch events in SharedPreferences.
  int fetchEventCount = 0;
  SharedPreferences prefs = await SharedPreferences.getInstance();
  if (prefs.get("fetch-count") != null) {
    fetchEventCount = prefs.getInt("fetch-count");
  }
  prefs.setInt("fetch-count", ++fetchEventCount);
  print('*** Fetch count: $fetchEventCount');
  
  BackgroundFetch.finish();
}
```

**Comment by christocracy** [comment]
>Lets say your background location or background fetch plugin is triggered...and you want to save location via firebase

I will be porting `BackgroundGeolocation`'s *firebase-adapter* to Flutter soon.  Here's the [React Native version](https://github.com/transistorsoft/react-native-background-geolocation-firebase)

**Comment by radvansky-tomas** [comment]
Why do you need to port anything? Cant you just invoke firestore plugin to save loc ?

**Comment by radvansky-tomas** [comment]
So I am trying to change some of my firebase_messaging plugin code to support that headless execution with other plugins support as you have. But for some reason you have framework in code, not source. And I have no idea, what are you doing with callback. Could you please post code for releasing events back to flutter? 

So you register callback with your manager:
` [fetchManager addListener:PLUGIN_PATH callback:handler];`

but then actual event happens...and its catch by your framework, not plugin itself...and it triggers that callback...

And then flutter has to call finish method and invoke
`[fetchManager finish:PLUGIN_PATH result:result];`

Which is pretty much same as i need to do in my method:

```
- (bool)application:(UIApplication *)application
didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult result))completionHandler 
```

In my previous attempt I used:

```
    int64_t handle = [self getCallbackHandleForMsgId:kCallbackId];
    NSMutableArray* message = [[NSMutableArray alloc] init];
    [message addObject:[NSNumber numberWithLongLong:handle]];
    [message addObject:[NSNumber numberWithInt:event]];
    [message addObject:userInfo];
    
    [_callbackChannel
     invokeMethod:@""
     arguments:message];
```

But your pattern seem to use different technique

**Comment by radvansky-tomas** [comment]
I tried just to invoke eventsink(with message param), which seems to work...
However I am not sure if thats the correct way.

BTW how did you manage to obtain console output from headless task ? Every time my app fell to background state, flutter debugger disconnects with message Lost connection to device.

**Comment by radvansky-tomas** [comment]
eventSink(userInfo) doesnt work, as it is NULL :(

**Comment by christocracy** [comment]
TSBackgroundFetch is wrapped up in a Framework merely to allow me to transplant the functionality across frameworks:
- Cordova
- React Native
- NativeScript
- Flutter
- pure native apps.

The source for it is here:
https://github.com/transistorsoft/transistor-background-fetch

**Comment by radvansky-tomas** [comment]
Thank you. Will investigate it further

**Comment by laoqiu** [comment]
@christocracy BackgroundFetch is very good!

I want to send data to server when background received event, but network look like unavailable.
can u help me ?

**Comment by christocracy** [comment]
@laoqiu If you're having issues, you should post a separate issue.

**Comment by christocracy** [comment]
Ok, first working version of Firebase Adapter for BackgroundGeolocation is pushed to the Git repo (Not yet published to pub.dev).
https://github.com/transistorsoft/flutter_background_geolocation_firebase

You must install from Git until it's published.

First Follow the Setup Guides.
