### ISSUE TITLE
How to CONFIG Background fetch only once at the time of first installation

### ISSUE THREAD

**Issue by Satish-Eruvaka** [transistorsoft/flutter_background_fetch#100]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
Follow the readme exactly as documented.

**Comment by Satish-Eruvaka** [comment]
But in readme doc, I didn't found any mater related to this issue.

**Comment by christocracy** [comment]
You must call #configure **each time the app launches**.

**Comment by Satish-Eruvaka** [comment]
we were giving minimumFetchInterval, then if I open the app it calculates from that time but it right?

**Comment by christocracy** [comment]
Yes.

**Comment by Satish-Eruvaka** [comment]
but I was using background fetch to get latest notifications for every one hour, even the client was using our app regularly, so they didn't get notifications bcoz every time they were opening the time was move on to next hour.
