### ISSUE TITLE
I was using background fetch to get latest notifications for every one hour, but didn't get notifications bcoz every time opening app, may be the minumumFetchInterval time was move on to next hour.

### ISSUE THREAD

**Issue by Satish-Eruvaka** [transistorsoft/flutter_background_fetch#101]

**Comment by christocracy** [comment]
If you open your app, you’re free to perform a request to get your “latest notifications” at that time.

**Comment by Satish-Eruvaka** [comment]
But its not like that, I already fetch notifications for every 1 hour using this library. So there is no meaning if I again call for notifications every time I opened my application.
