### ISSUE TITLE
[BUG] Module 'background_fetch' not found in IOS

### ISSUE THREAD

**Issue by sedobrengocce** [transistorsoft/flutter_background_fetch#103]
**Your Environment**
* Plugin version: 0.5.4
* Platform: iOS
* OS version: 10.15
* Device manufacturer / model: NA
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en_US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

* Plugin config
BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.ANY
    ), backgroundCallbackTask).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
      Crashlytics.instance.log('[BackgroundFetch] configure ERROR: $e');
    });

**To Reproduce**

1. In Xcode, open Runner.xcworkspace in your app’s ios folder.
2. Select Product > Scheme > Runner.
3. Select Product > Destination > Generic iOS Device.
4. Select Product > Archive to produce a build archive.

**Debug logs**
- ios XCode logs, 
 Build Failed: Modul 'background_fetch' not found

**Additional context**
The app build when build for simulator

**Comment by christocracy** [comment]
Works in the `/example` app in this repo.  Problem is on your end.
![](https://dl.dropbox.com/s/rga2k2ka831b5wg/Screenshot%202020-03-24%2009.35.21.png?dl=1)

I would:
```
$ flutter build ios
$ cd ios
$ pod install
```
- Restart XCode
- *Product->Clean*

**Comment by sedobrengocce** [comment]
Thanks. It worked

**Comment by wterrill** [comment]
hmm... same problem.   the build, pod install, clean  fix didn't work.    Running 1.21.0-6.0.pre.17

**Comment by CRdeGraaf** [comment]
This error of modules not being found can occur when in xcode you accidentally file->open the .xcodeproj instead of the .xcworkspace

**Comment by tajchert** [comment]
For any future reference.

In my case it was the incorrect build target - I was building release target in XCode for an emulator.
Changing to debug fixed problem (emulator=debug, release = physical device).

**Comment by saranyalekshmanan** [comment]
This may help someone.

https://stackoverflow.com/a/68299585/8609394

PodFile -> Un comment platform :ios, '12.0' => Any version 

And Xcode -> Targets -> Runner -> Minimum Deployment Target -> 12.0 should be same
