### ISSUE TITLE
error: cannot find symbol     flutterEngine.getPlugins().add(new com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin())

### ISSUE THREAD

**Issue by nkenna** [transistorsoft/flutter_background_fetch#105]
Everything was working fine till this error came up:
C:\Users\Ugwumsinachi 

Nnadi\Documents\scanner\scanner_new\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:17: error: cannot find symbol
    flutterEngine.getPlugins().add(new com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin());
                                                                                 ^
  symbol:   class BackgroundFetchPlugin
  location: package com.transistorsoft.flutter.backgroundfetch
1 error 

I am working with VS Code. Please, how can I solve it. This is the output from my flutter doctor:
  flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1098], locale en-NG)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\Ugwumsinachi Nnadi\new_flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\sdk-tools-windows\tools\bin
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\sdk-tools-windows\tools\bin
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Infinix X606C • 03263258BG004059 • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 2 categories.

**Comment by christocracy** [comment]
Have you [Upgraded your pre 1.12 Flutter app](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?

**Comment by nkenna** [comment]
If I am missing something but my project was created with Flutter version 1.12.13+hotfix.8.
The project was building fine and all of a sudden, the error surfaced after I deleted the build folder so as to get a fresh debug build.

**Comment by christocracy** [comment]
I do not know what you've done to your project.

```
$ cd android
$ ./gradlew clean
```

**Comment by nkenna** [comment]
Thanks. I am recreating it again

**Comment by christocracy** [comment]
Update?

**Comment by nkenna** [comment]
I resolved it.
Followed your step then flutter pub cache clean

**Comment by christocracy** [comment]
Please close your issues when solved.

**Comment by nkenna** [comment]
Thanks
