### ISSUE TITLE
Play Sound in Background or Launch App

### ISSUE THREAD

**Issue by scullabyte** [transistorsoft/flutter_background_fetch#106]
**Is your feature request related to a problem? Please describe.**
I want a sound to play after x amount of time while the app is in the background. Currently the background service will run, but the app won't play the sound. I've tried using `audioplayers` and `audio_service` (which runs on a separate isolate) but neither will play the sound unless the app is focused in the foreground. Is there a way to force the app to come to the foreground or play the sound in ios while in the background? If not, is there a way to force the app to launch into the foreground?

**Comment by christocracy** [comment]
Did you enable *[x] Audio, Airplay and Picture in Picture* Background Mode?
![](https://dl.dropbox.com/s/6sbt4v7c4ajq571/Screenshot%202020-03-26%2014.47.40.png?dl=1)

**Comment by scullabyte** [comment]
welp... I feel stupid. It worked after enabled in the example app. For anyone that is struggling with this, `just_audio` doesn't work when launched in the bg for some reason, however, the `audioplayers` package will. thanks for the quick reply! closing now
