### ISSUE TITLE
For IOS I checked this scenario in simulator using 'Simulator background fetch' option in debug it was working fine. But for real devices it wasn't working.

### ISSUE THREAD

**Issue by Satish-Eruvaka** [transistorsoft/flutter_background_fetch#108]

**Comment by faldunate** [comment]
I have exactly the same problem, does anyone know the solution to this?

**Comment by christocracy** [comment]
If it works in the simulator, that's all you need to know that it works.

You need to periodically open your app to train Apple's machine-learning model.

Also, Apple stops background-fetch events if *user* terminates the app.

**Comment by Hisagar** [comment]
> If it works in the simulator, that's all you need to know that it works.
> 
> You need to periodically open your app to train Apple's machine-learning model.
> 
> Also, Apple stops background-fetch events if _user_ terminates the app.

having same issue!
how much time it require to train model and it there any way where we can periodically fetch our background service.

**Comment by christocracy** [comment]
>how much time it require to train model

Unknown.  Open your app several times / day.

> and it there any way where we can periodically fetch our background service.

That is the purpose of this plugin.  To periodically fire a callback in the background with which you would presumably contact your server.
