### ISSUE TITLE
Can we pass param from scheduleTask to BackgroundFetch.configure?

### ISSUE THREAD

**Issue by tony123S** [transistorsoft/flutter_background_fetch#109]
I need to upload image on background. I have found this plugin, but not sure is it suite with my case?

Here my repo

```
 BackgroundFetch.scheduleTask(TaskConfig(
            taskId: Consts.UPLOAD_IMAGE, delay: 50 // <-- milliseconds    // I would like to pass `title`, so I can use it later
            ));
```

**main**
```

Future<void> initPlatformState() async {
    // Step 1:  Configure BackgroundFetch as usual.
    BackgroundFetch.configure(BackgroundFetchConfig(minimumFetchInterval: 15),
        (String taskId) async {
      switch (taskId) {
        case Consts.UPLOAD_IMAGE:
          print(title);   // get from TaskConfig
          // submit image on background
          break;
        default:
          print("Default fetch task");
      }
      // Finish, providing received taskId.
      BackgroundFetch.finish(taskId);
    });
  }
```

Is it possible to do that?

**Comment by Sigura** [comment]
I think it possible for small images.

But maybe you want something else.

BackgroundFetch made for a short period of the job and suitable for short fetch operations.

But let's try, why not?

Ps: @christocracy, is it correct?

**Comment by tony123S** [comment]
@Sigura  
I using http to upload image to server. I need to pass two param, one is title and another is the imageList. How can I pass the two param from my repo class to here?
```

 BackgroundFetch.configure(BackgroundFetchConfig(minimumFetchInterval: 15),
        (String taskId) async {
      switch (taskId) {
        case Consts.UPLOAD_IMAGE:
          try {
            var count = 0;
            var request = http.MultipartRequest(
                "POST",
                Uri.parse(
                    "https://xxx"));
            request.fields['title'] =
               title;
            for (var i in imageUrl) {
              request.files.add(await http.MultipartFile.fromPath(
                'image' + "[" + count.toString() + "]",
                i,
              ));
              count++;
            }
            var streamedResponse = await request.send();
            var response = await http.Response.fromStream(streamedResponse);
                                         ......
          } catch (e) {
            print("e.toString());
          }
          break;
        default:
          print("Default fetch task");
      }
      BackgroundFetch.finish(taskId);
    });


```

**Comment by christocracy** [comment]
Store your required params in `SharedPreferences`, keyed to your `taskId`

**Comment by tony123S** [comment]
> Update: and it looks 100% suitable if you will make continue/chunks upload.

@Sigura  what if I want it to run only one time?

**Comment by tony123S** [comment]
> Store your required params in `SharedPreferences`, keyed to your `taskId`

Is this the only workaround?

**Comment by Sigura** [comment]
I'm not sure, but I think mobile OS can kill it.

(I think developer or product manager add an algorithm to OS to prevent long background tasks)

**Comment by christocracy** [comment]
> Is this the only workaround

Yes.

**Comment by tony123S** [comment]
If I want it only run once, how should I configure?

**Comment by christocracy** [comment]
> If I want it only run once, how should I configure?

`scheduleTask` is a one-shot *by default* (`periodic: false`)

**Comment by tony123S** [comment]
Thanks! Last question, if the image is uploading in `BackgroundFetch.configure`, when I exit the app, will the process get terminated?

**Comment by christocracy** [comment]
See api docs TaskConfig.stopOnTerminate, enableHeadless

**Comment by tony123S** [comment]
Wonder can I use local database instead of sharedPreferences since I have stored all data into local db.
