### ISSUE TITLE
Alarm triggered at random times

### ISSUE THREAD

**Issue by Nasrudin78** [transistorsoft/flutter_background_fetch#111]
I'm using background_fetch for triggering a bell sound at random dates , the problem is that seems to trigger the sound at requested time ,but also sounds 15 minutes in between for the requested alarms.

An example:  I scheduled these hours and the pluggin works well:
9:17
9:37
10:08
But for some reason the bell sounds also at 
9:26
9:41
9:55
10:08
(15 minutes in btw)

Why is it happening this behaviour?

I have the following code 

```
void schedule() {
    lDates = Dates.getRandomDates(numHours: _n);
    int acum = 0;
    lDates.insert(0, DateTime.now()); // For initial time.
    int diff = 0;
    for (int i = 0; i < lDates.length; i++) {
      DateTime elem = lDates[i];
      if (i + 1 < lDates.length) {
        DateTime nextElem = lDates[i + 1];
        diff = nextElem.difference(elem).inMilliseconds;
        acum += diff;

        BackgroundFetch.scheduleTask(TaskConfig(
            forceAlarmManager: true,
            taskId: i.toString(),
            delay: acum // <-- milliseconds
            ));
        
      }

    }
  }
```

and my main.dart:

```
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();

    BackgroundFetch.configure(
        BackgroundFetchConfig(minimumFetchInterval: 15, forceAlarmManager: true),
        (String taskId) async {

          var now = DateTime.now();
          print(">>>> [BackgroundFetch] taskId: $taskId at $now");

          BellFg.BellSound();

          BackgroundFetch.finish(taskId);
    });

    runApp(MyApp());
}
```

Thanks in advance!!!

**Comment by christocracy** [comment]
You're receiving `scheduleTask` + the periodic fetch task (`minimumFetchInterval: 15`)

**Comment by Nasrudin78** [comment]
Yeah.    It makes sense. I've filtered the tasks Id belonging to periodic fetch and its working as expected. Thank you 🙏
