### ISSUE TITLE
Is this suitable for timer app?

### ISSUE THREAD

**Issue by aldwnesx** [transistorsoft/flutter_background_fetch#114]
My app has a timer running. However when user locks the phone or the app goes tobackgroudn the timer stops. It continues when I open the app again.

I was thinking of using this package as a substitute.

Every 15 mins it get called, and I wil do some calculation e.g if user sets 30 mins timer, then this background fetch runs about every 15 mins so I just have a variable to keep track how many times it has run.... does this solve my requirement? 

I only need the timer to work when the app is in background and/or the phone is locked.

 IF the app is terminated it shouldn't do anything.

**Comment by christocracy** [comment]
- For Android, you can run a fairly reliable timer with scheduleTask and forceAlarmManager: true.

- For iOS:  *impossible*.

**Comment by aldwnesx** [comment]
> * forceAlarmManager

Thanks. Right now I am targeting android app only.

I only want my app to run code only when it's not terminated e.g when user uses the app and hits the home button to use other app or lock the phone. But if the app is terminated when user open app manager then it shouldn't do anything.. any idea? Should I use this package for this need?

**Comment by christocracy** [comment]
stopOnTerminate: true

**Comment by aldwnesx** [comment]
> stopOnTerminate: true

Thanks! 

Can I set the frequency to do it every let's say 30 or 60 mins or 15 is the max?

**Comment by christocracy** [comment]
Yes.  With `forceAlarmManager: true`, `60000ms` (1 min) is the *minimum*.  There is no *maximum*.
