### ISSUE TITLE
Is it possible to access platform-dependent plugins from headless tasks?

### ISSUE THREAD

**Issue by Alex-Evo** [transistorsoft/flutter_background_fetch#116]
I've been trying to implement some Bluetooth Low Energy operations using the [flutter_blue](https://pub.dev/packages/flutter_blue) plugin from a headless task, which didn't work out, because apparently, the native Android code for Bluetooth needs to run on the main thread, which I understand does not exist at that point. (That's at least what I figure from reading the official flutter [docs](https://flutter.dev/docs/development/platform-integration/platform-channels#jumping-to-the-ui-thread-in-android)).

Is there any working way to access plugins using native code from the headless task? I have tried spawning a [flutter_isolate](https://pub.dev/packages/flutter_isolate) from the function called by the handler (as they claim to support running those plugins with native code in an isolate), but that also didn't help. I assume that may be because there is just no active main UI thread that one could jump to?

Any hints would be appreciated, thanks!

**Comment by christocracy** [comment]
The `/example` app in this repo [interacts with the 3rd party plugin `shared_preferences`](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/lib/main.dart#L17) in its headless-task.

There should be no issue interacting with any other 3rd party plugin in the headless-task.

I suggest you clone this repo and boot the `/example` app and experiment with `flutter_blue` in its headless-task as a test.

**Comment by debasmitasarkar** [comment]
I have tried but it does not work. May be the issue with registerActivity() in flutter_blue plugin
??

**Comment by christocracy** [comment]
No plugin must ever do anything that interacts with an “Activity” in the headless state.  There is no “activity” in the headless state,

Another name for “headless” is “activity-less”

**Comment by debasmitasarkar** [comment]
Is it also possible to run a periodic  task in headless mode?

**Comment by christocracy** [comment]
It makes no difference, headless or not.

**Comment by Alex-Evo** [comment]
Thanks, @christocracy for the comment.

As far as I see it, 3rd party plugins using native code *can* work in headless mode (as the shared_preferences example shows), but from what I've seen, there are at least two reasons that would prevent them from working:
- If a plugin uses Java Native Interface (JNI) calls such as [cloud_firestore](https://pub.dev/packages/cloud_firestore)
- If a plugin uses ```invokeMethodUIThread(...)``` (which makes sense to me, as there would be no UI thread in headless mode if I understand it correctly...).

Can you confirm that, @christocracy?

**Comment by christocracy** [comment]
And the source for [BackgroundFetch.getUiHandler()](https://github.com/transistorsoft/transistor-background-fetch/blob/master/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BackgroundFetch.java#L44-L49)

```java
public static Handler getUiHandler() {
        if (uiHandler == null) {
            uiHandler = new Handler(Looper.getMainLooper());
        }
        return uiHandler;
    }
```

**Comment by christocracy** [comment]
As for JNI, my `flutter_background_geolocation` includes a JNI lib for optional encryption of HTTP request data.  It causes no issues in the headless state.

**Comment by christocracy** [comment]
The key is that no 3rd party plugin should attempt to reference the `Activity` while the app is headless, since it *will* be `null`.

**Comment by Alex-Evo** [comment]
@christocracy Thanks for these clarification. That should help me to figure things out with the respective 3rrd party plugins!

**Comment by mpiparo** [comment]
Hey all, sorry for popping in, but I have a very similar question and rather than start a new msg thread... just want to clarify what's being stated, if a 3rd party plugin requires an Activity, (the one I'm trying to get working uses com.google.android.gms.nearby) then I won't be able to run in a headless state?  Just double-checking if there are any solutions before I give up trying to get it to work.  thanks!

**Comment by christocracy** [comment]
In an Android app, the `Activity` = “the head” of your app.

When an Android app is terminated, that is “*Headless*”, there is no `Activity`.

Another name for “headless” is “activity-less”.

Any 3rd-party plugin that attempts to access the activity while your is running headless will find it to be `null`.

**Comment by mpiparo** [comment]
Thanks. yes, that's exactly what I'm seeing. Unfortunately the Google Nearby lib has NonNull requirements on the Activity params passed into its methods.  Appreciate the info. thanks.

**Comment by christocracy** [comment]
Most plugin developers are not even aware that an Android app may be launched headless.
