### ISSUE TITLE
[BUG] Error on backgroundFetchHeadlessTask

### ISSUE THREAD

**Issue by spalenzuela** [transistorsoft/flutter_background_fetch#118]
**Your Environment**
* Plugin version: 0.5.5
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Samsung S7
* Flutter info (`flutter info`, `flutter doctor`):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18363.592], locale es-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Proxy Configuration
[√] Connected device (1 available)

• No issues found!

**To Reproduce**
1.  In foreground app send the SMS
2. In background app send the SMS
3. After close app, Exception received

backgroundFetchHeadlessTask(String taskId) async {
  if (taskId == kNotificationTask) {
	  await Sendsms.onGetPermission();
	  if (await Sendsms.hasPermission())
		  await Sendsms.onSendSMS(number, message);		
  };
  BackgroundFetch.finish(taskId);
}

**Debug logs**
- Android: `$ adb logcat`
05-25 13:40:44.100 32645 32711 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke v
irtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference, null)
05-25 13:40:44.100 32645 32711 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
05-25 13:40:44.100 32645 32711 E flutter : #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
05-25 13:40:44.100 32645 32711 E flutter : <asynchronous suspension>
05-25 13:40:44.100 32645 32711 E flutter : #2      Sendsms.onGetPermission (package:sendsms/sendsms.dart:23:27)
05-25 13:40:44.100 32645 32711 E flutter : #3      SMS.sendEmergencySMS (package:careme/services/sms.dart:27:21)
05-25 13:40:44.100 32645 32711 E flutter : <asynchronous suspension>
05-25 13:40:44.100 32645 32711 E flutter : #4      _initScheduleNotification (package:careme/main.dart:89:21)
05-25 13:40:44.100 32645 32711 E flutter : <asynchronous suspension>
05-25 13:40:44.100 32645 32711 E flutter : #5      backgroundFetchHeadlessTask (package:careme/main.dart:190:42)
05-25 13:40:44.100 32645 32711 E flutter : <asynchronous suspension>
05-25 13:40:44.100 32645 32711 E flutter : #6      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:619:15
)
05-25 13:40:44.100 32645 32711 E flutter : #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
05-25 13:40:44.100 32645 32711 E flutter : #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.
dart:370:54)
05-25 13:40:44.100 32645 32711 E flutter : #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
05-25 13:40:44.100 32645 32711 E flutter : <asynchronous suspension>
05-25 13:40:44.100 32645 32711 E flutter : #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
05-25 13:40:44.100 32645 32711 E flutter : #11     _rootRun (dart:async/zone.dart:1126:13)
05-25 13:40:44.100 32645 32711 E flutter : #12     _CustomZone.run (dart:async/zone.dart:1023:19)
05-25 13:40:44.100 32645 32711 E flutter : #13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
05-25 13:40:44.100 32645 32711 E flutter : #14     _invoke3 (dart:ui/hooks.dart:302:10)
05-25 13:40:44.100 32645 32711 E flutter : #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)

**Comment by christocracy** [comment]
Background Fetch doesn’t involve permissions.

```
Unhandled Exception: PlatformException(error, Attempt to invoke v
irtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference, null)
```

FYI plugins can’t request permissions when app is terminated and headless.

**Comment by spalenzuela** [comment]
Thank you
