### ISSUE TITLE
Easy access to app termination event with optional callback

### ISSUE THREAD

**Issue by HeikoMueller** [transistorsoft/flutter_background_fetch#119]
**Is your feature request related to a problem? Please describe.**
 Flutter provides limited access to lifecycle events. Particularly an event that is triggered on app termination and that is clearly distinguishable from app pausing is missing to my knowledge. After having installed the Background Location plugin including flutter_backgeround_fetch, I see a [TSBackgroundFetch onAppTerminate] log triggered on app termination. However, I did not find an easy way to listen to this event. The "Terminate" Event in the background location plugin seems to relate to something else. 

**Describe the solution you'd like**
(1) An easy way to subscribe to the [TSBackgroundFetch onAppTerminate] event, for instance in the task scheduler of flutter_background_fetch. 
(2) It would be great if there was not only the event but also a callback that can be used for a few shut down tasks such as unsubscribing from event channels and similar cleanup tasks.

**Comment by christocracy** [comment]
There are existing APIs for hooking into flutter [life-cycle](https://medium.com/flutter-community/flutter-lifecycle-for-android-and-ios-developers-8f532307e0c7) events.

**Comment by christocracy** [comment]
> that can be used for a few shut down tasks such as unsubscribing from event channels

If your app is being terminated, there'll be no more event-channels to clean up.
