### ISSUE TITLE
[BUG] "Direct local .aar file dependencies are not supported when building an AAR." with build:gradle:4.0.0

### ISSUE THREAD

**Issue by sabinbajracharya** [transistorsoft/flutter_background_fetch#122]
**OSX | Linux**
* Plugin version: ^0.5.6
* Platform: Android

**To Reproduce**
1. Update build gradle tools to 4.0.0

**Debug logs**
>FAILURE: Build failed with an exception.

>* What went wrong:

>Execution failed for task ':background_fetch:bundleReleaseAar'.

>Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :background_fetch project caused this error: /Users/sabin/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.6/android/libs/tsbackgroundfetch-0.4.5.aar

**Comment by christocracy** [comment]
Do not use `gradle tools 4.0.0`.

**Comment by sabinbajracharya** [comment]
Ok thanks for the reply. Can I know more in detail?
 Is it an issue with latest version of gradle or gradle does not support aar dependency when building aar and this library needs a fix going forward?

**Comment by christocracy** [comment]
Correct.  Plugin setup steps will change in the future.  In the meantime, don’t use gradle tools v4.

https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/build.gradle#L16

**Comment by christocracy** [comment]
[0.6.0](https://github.com/transistorsoft/flutter_background_fetch/blob/master/CHANGELOG.md#060---2020-06-11) is published.  You must apply the new setup change as mentioned above.

**Comment by sabinbajracharya** [comment]
@christocracy Thanks!
