### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method requestAuthorization on channel flutter_health))

### ISSUE THREAD

**Issue by Ahmedibrahim66** [transistorsoft/flutter_background_fetch#123]
Hi, i am trying to read some health data in the background from google fit app and I used the health package to do so, when the app is running everything works as expected, on background task it also works,however in headless implementation i get this error 

![image](https://user-images.githubusercontent.com/49869195/83638576-08e1d100-a5b2-11ea-9e0a-b3534c463b8f.png)

the code 

```
void main() {
  runApp(MyApp());
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

```
/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask(String taskId) async {
  await initPlatformState();
  BackgroundFetch.finish(taskId);

}

Future<void> initPlatformState() async {
  DateTime startDate = DateTime.utc(2001, 01, 01);
  DateTime endDate = DateTime.now();

  backroundFetch();
  Future.delayed(Duration(seconds: 2), () async {


    if (_isAuthorized) {
      
      _isAuthorized = await Health.requestAuthorization();


      print('Authorized');

      bool weightAvailable = Health.isDataTypeAvailable(HealthDataType.WEIGHT);
      print("is WEIGHT data type available?: $weightAvailable");

      /// Specify the wished data types
      List<HealthDataType> types = [
        HealthDataType.WEIGHT,
        HealthDataType.HEIGHT,
//          HealthDataType.STEPS,
//          HealthDataType.BODY_MASS_INDEX,
//          HealthDataType.WAIST_CIRCUMFERENCE,
//          HealthDataType.BODY_FAT_PERCENTAGE,
//          HealthDataType.ACTIVE_ENERGY_BURNED,
//          HealthDataType.BASAL_ENERGY_BURNED,
        HealthDataType.HEART_RATE,
//          HealthDataType.BLOOD_PRESSURE_SYSTOLIC,
//          HealthDataType.BLOOD_PRESSURE_DIASTOLIC,
//          HealthDataType.RESTING_HEART_RATE,
//          HealthDataType.BLOOD_GLUCOSE,
//          HealthDataType.BLOOD_OXYGEN,
      ];

      _healthDataList = [];

      for (HealthDataType type in types) {
        /// Calls to 'Health.getHealthDataFromType'
        /// must be wrapped in a try catch block.b
        try {
          List<HealthDataPoint> healthData =
              await Health.getHealthDataFromType(startDate, endDate, type);
          _healthDataList.addAll(healthData);
        } catch (exception) {
          print(exception.toString());
        }
      }

      /// Print the results
      for (var x in _healthDataList) {
        print("Data point: $x");
      }

      /// Update the UI to display the results
      FirestoreService service = new FirestoreService();
      await service.addHealthModel(_healthDataList);

    } else {
      print('Not authorized');
    }
  });
}

void backroundFetch() {
  BackgroundFetch.configure(
          BackgroundFetchConfig(
            minimumFetchInterval: 15,
            forceAlarmManager: false,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.ANY,
          ),
          initPlatformState)
      .then((int status) {
    print('[BackgroundFetch] configure success: $status');
  }).catchError((e) {
    print('[BackgroundFetch] configure ERROR: $e');
  });
}
```

* Plugin version: background_fetch: ^0.5.6
* Platform: iOS or Android / Android
* OS version: Android 10
* Device manufacturer / model: Xiaomi Mi 9T
* Flutter info (`flutter info`, `flutter doctor`):

![image](https://user-images.githubusercontent.com/49869195/83626371-f9588d00-a59d-11ea-8d7f-2b83ab5aed7f.png)

is it not possible to fetch data the require authorization in headless tasks ?

**Comment by christocracy** [comment]
That plugin probably hasn’t been migrated to the new Flutter plugin api.  Post an issue at that plugin and ask them if this is so.

**Comment by christocracy** [comment]
Btw, it’s impossible to request any kind of permission when the app is in the headless state.  The app is terminated.

**Comment by Ahmedibrahim66** [comment]
> Btw, it’s impossible to request any kind of permission when the app is in the headless state. The app is terminated.

that is probably whats causing the issue, looks like i need to search for another way to do this, thanks alot chris

**Comment by Ahmedibrahim66** [comment]
Also i have a question
Does this plugin works when the app is terminated (removed from recent) ?
If i press the back button the headless background process will work,
however if i removed it from recent it will not work is that how this
package works?

**Comment by christocracy** [comment]
Headless = app terminate.

**Comment by Ahmedibrahim66** [comment]
> Headless = app terminated

I tried it on couple of different devices some of them worked as expected the others did not, it looks like  MiUi was blocking the background usage of the app which explains why headless fetching did not work on my phone and other xaiomi devices that i tried, i had to enable it in the settings for it to work probably

**Comment by christocracy** [comment]
http://dontkillmyapp.com
