### ISSUE TITLE
api call and local notification show when app terminated in ios

### ISSUE THREAD

**Issue by ziasultan2** [transistorsoft/flutter_background_fetch#124]
Hi is it possible to make api call and local notification when app got terminated by user. If possible please let me know how can I achieve this in iOS

**Comment by christocracy** [comment]
When user terminates an iOS app, everything is terminated.  Your iOS app will automatically re-launch in the background once the device moves ~200 meters beyond the last known location where the app was terminated.  When an iOS app is re-launched in the background, it is completely alive, just as if launched from the home-screen.
