### ISSUE TITLE
[BUG] Headless method on android Repeat fast when call my method inside

### ISSUE THREAD

**Issue by is10vmust** [transistorsoft/flutter_background_fetch#126]
**Your Environment**
* Plugin version: ^1.7.0
* Platform: iOS or Android
* OS version: Android 8-10
* Device manufacturer / model: Samsung g7 and pixil 3 xl emulater
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config
  allowIdenticalLocations: false,
        triggerActivities: 'on_foot, walking, running, in_vehicle, on_bicycle',
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        reset: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_VERBOSE,
        distanceFilter: 50.0, //aman-50
        stopTimeout: 1,
        autoSync: true,
        stopOnTerminate: false,
        foregroundService: true,
        startOnBoot: true,
        disableMotionActivityUpdates: true, 
        enableHeadless: true,
**To Reproduce**
in foreground everything is ok but when i kill the app the headless run the code faster x10 
this is my headless method: 
void backgroundGeolocationHeadlessTask(bg.HeadlessEvent headlessEvent) async {
  print("LOCATION PLUG-IN in BACKGROUND...");

  PreferenceUtils.init();
  kill();
  bleStatus();
  checkInternet();
  gps();
  // checkInterNetLive();
  BLE().scan();
  DatabaseHelper helper = new DatabaseHelper();
  helper.initializeDatabase();
  getUserLocation(helper);
}
**Debug logs**
/flutter ( 5991): [getCurrentPosition] Headless: [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 1.0, is_charging: false}, uuid: 8e5df7c7-4932-4a5a-9fd1-5f799a41384e, coords: {altitude: 5.0, heading: -1.0, latitude: 35.4219983, accuracy: 12.4, speed: -1.0, longitude: 30.0839983}, is_moving: false, timestamp: 2020-06-13T19:27:37.000Z}]
I/flutter ( 5991): ------------------35.4219983
I/flutter ( 5991): -----------------30.0839983
I/flutter ( 5991): -----------------12.4
I/flutter ( 5991): LOCATION PLUG-IN in BACKGROUND...
I/flutter ( 5991): ----------------------
I/flutter ( 5991): -----Ready to KIll----
I/flutter ( 5991): ----------------------
I/flutter ( 5991): ---------------------------> befor Active false
I/flutter ( 5991): LOCATION PLUG-IN in BACKGROUND...
/flutter ( 5991): [getCurrentPosition] Headless: [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 1.0, is_charging: false}, uuid: 8e5df7c7-4932-4a5a-9fd1-5f799a41384e, coords: {altitude: 5.0, heading: -1.0, latitude: 35.4219983, accuracy: 12.4, speed: -1.0, longitude: 30.0839983}, is_moving: false, timestamp: 2020-06-13T19:27:37.000Z}]
I/flutter ( 5991): ------------------35.4219983
I/flutter ( 5991): -----------------30.0839983
I/flutter ( 5991): -----------------12.4
I/flutter ( 5991): LOCATION PLUG-IN in BACKGROUND...
I/flutter ( 5991): ----------------------
I/flutter ( 5991): -----Ready to KIll----
I/flutter ( 5991): ----------------------
I/flutter ( 5991): ---------------------------> befor Active false
I/flutter ( 5991): LOCATION PLUG-IN in BACKGROUND...
/flutter ( 5991): [getCurrentPosition] Headless: [Location {odometer: 0.0, activity: {confidence: 100, type: still}, extras: {}, battery: {level: 1.0, is_charging: false}, uuid: 8e5df7c7-4932-4a5a-9fd1-5f799a41384e, coords: {altitude: 5.0, heading: -1.0, latitude: 35.4219983, accuracy: 12.4, speed: -1.0, longitude: 30.0839983}, is_moving: false, timestamp: 2020-06-13T19:27:37.000Z}]
I/flutter ( 5991): ------------------35.4219983
I/flutter ( 5991): -----------------30.0839983
I/flutter ( 5991): -----------------12.4
I/flutter ( 5991): LOCATION PLUG-IN in BACKGROUND...
I/flutter ( 5991): ----------------------
I/flutter ( 5991): -----Ready to KIll----
I/flutter ( 5991): ----------------------
I/flutter ( 5991): ---------------------------> befor Active false
I/flutter ( 5991): LOCATION PLUG-IN in BACKGROUND...

**Comment by christocracy** [comment]
You're probably creating an infinite loop for yourself.  You have to understand that *all* events arrive in the headless-task and executing `getCurrentPosition` **CREATES** events.

You need to use a `switch` statement and only execute `getCurrentPosition` for some particular event.

**Comment by is10vmust** [comment]
Thanks a lot sir
