### ISSUE TITLE
Any plan to implement BackgroundFetch on iOS

### ISSUE THREAD

**Issue by espositofulvio** [transistorsoft/flutter_background_fetch#129]
**Is your feature request related to a problem? Please describe.**
I'm writing an APP that needs to constantly fetch current data from a bluetooth sensor which monitors insuline temperature and send notifications in case of out of bounds values, once every 15 minutes on iOS is a bit too laggy for my use case.

**Describe the solution you'd like**
Implementing the new BackgroundFetch API in iOS should give the same level of functionality of the JobScheduler on Android from what I understand, but I'm not an iOS developer and am delegating flutter for cross compatibility

**Describe alternatives you've considered**
Implementing the API myself is not on the table as I don't develop on apple device at all, I've found other similar plugins which all seems a bit abandoned or sparingly developed.

**Comment by christocracy** [comment]
Sorry, this isn’t a limitation imposed by me, it’s a limitation imposed by Apple in the iOS operating system.

You need to escalate your request further up , to Apple themselves.

**Comment by espositofulvio** [comment]
Hi Chris,
I know the current limitation, but starting from iOS 13 there's a new API called BackgroundTasks (sorry, I got the name wrong in my first comment) which allows something more like Android's JobScheduler and it looks like it doesn't have the limitation of the API you are currently using.

**Comment by christocracy** [comment]
See [CHANGLOG](https://github.com/transistorsoft/flutter_background_fetch/blob/master/CHANGELOG.md#050---2020-02-03).

BGTaskScheduler was implemented in v5.

It changes nothing.

**Comment by espositofulvio** [comment]
Oh OK, didn't see that. I thought the new API could do a bit better (as I said, I don't know iOS quite well), I guess I have to settle for the 15 minutes then. Anyway, thanks for the pronto response and for the good work on this package, it's truly helpful!
Cheers

**Comment by christocracy** [comment]
> I thought the new API could do a bit better

I’d hoped It would turn out something like JobScheduler too.  In reality, it’s not.
