### ISSUE TITLE
[BUG] Android build fails for version 0.6.0

### ISSUE THREAD

**Issue by yannickvg** [transistorsoft/flutter_background_fetch#131]
**Your Environment**
* Plugin version: 0.6.0
* Platform: Android
* OS version: N/A
* Device manufacturer / model: N/A
* Flutter info (`flutter info`, `flutter doctor`): 
[✓] Flutter (Channel unknown, v1.17.2, on Mac OS X 10.15.5 19F101, locale en-BE)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)
* Plugin config

**To Reproduce**
1. launch an Android build with version 0.5.6 -> build works fine
2. launch an Android build with version 0.6.0 -> error

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processQaReleaseResources'.
> Could not resolve all task dependencies for configuration ':app:qaReleaseRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/
       - file:/Users/yannick/rmdy/code/flutter/sport_vlaanderen_vts/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/yannick/rmdy/code/flutter/sport_vlaanderen_vts/android/app/libs/com/transistorsoft/tsbackgroundfetch/
       - https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/
     Required by:
         project :app > project :background_fetch`

**Comment by christocracy** [comment]
See the CHANGELOG.

**Comment by yannickvg** [comment]
sorry, should have read that, thanks!

**Comment by TJMusiitwa** [comment]
Even after trying all the solutions presented here,I still end up with a build error.

Flutter version: 1.7.1
Background Fetch: 0.5.4

> Execution failed for task ':background_fetch:bundleProfileAar'.

> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :background_fetch project caused this error: /opt/hostedtoolcache/flutter/1.17.1-stable/x64/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.4/android/libs/tsbackgroundfetch-0.4.2.aar

How else may I approach this? 
Please note that I have already looked at the changelog and applied the change however the build still fails and returns the above error.

**Comment by christocracy** [comment]
Post your `android/build.gradle`

**Comment by TJMusiitwa** [comment]
Here it is
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
       }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by christocracy** [comment]
>Background Fetch: 0.5.4

Now look at the [CHANGELOG](https://github.com/transistorsoft/flutter_background_fetch/blob/master/CHANGELOG.md#060---2020-06-11) &mdash; what version of the plugin implements the new `maven url` config?

**Comment by TJMusiitwa** [comment]
It mentions **0.6.0** however even before adding the new url it was still returning the above error.
My _pubspec.yaml_ has `backgroundfetch:^0.5.4`

**Comment by christocracy** [comment]
>however even before adding the new url it was still returning the above error

I'm sure it was.  Because you were using `gradle-tools@4.0.0` and that version of gradle no longer allows "*Direct local .aar file dependencies when building an AAR*".

Now why don't go ahead and upgrade to `0.6.0` to make your problems go away?
