### ISSUE TITLE
Error in making release apk or running the app in release mode with license installed

### ISSUE THREAD

**Issue by msndvlpr** [transistorsoft/flutter_background_fetch#133]
**Your Environment**
* Plugin version:
 1.7.1
* Platform: 
Android
* OS version: 
7.0 and 8.0
* Device manufacturer / model: 
Samsung and Nokia
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.17763.1282], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 4.0)
[√] Connected device (1 available)
! Doctor found issues in 1 category.
* Plugin config

**To Reproduce**
run `flutter build apk --release` or `flutter run --release` commands in Android Studio terminal and gradle build failure will occur

**Debug logs**

**`flutter build apk --release` command outout:**
FAILURE: Build failed with an exception.
Where:
Build file 'C:\git-repository\flutter-agora\agora-flutter\android\build.gradle' line: 24
What went wrong:
A problem occurred evaluating root project 'android'.
A problem occurred configuring project ':app'.
Removing unused resources requires unused code shrinking to be turned on. See http://d.android.com/r/tools/shrink-resources.html for more information.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 2s

**`flutter run --release` command output:**
FAILURE: Build failed with an exception.
Where:
Build file 'C:\flutter-sdk\.pub-cache\hosted\pub.dartlang.org\background_fetch-0.5.6\android\build.gradle' line: 18
What went wrong:
A problem occurred evaluating root project 'background_fetch'.
Plugin with id 'com.android.library' not found.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 1s
The plugin background_fetch could not be built due to the issue above.

**Comment by christocracy** [comment]
>1.7.1

I assume you mean `flutter_background_geolocation @ 1.7.1`.

I suggest you update to latest [`flutter_background_geolocation @ 1.9.0`](https://pub.dev/packages/flutter_background_geolocation/versions)

See the [CHANGELOG](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/CHANGELOG.md)

**Comment by msndvlpr** [comment]
Yes exactly I meant `flutter_background_geolocation @ 1.7.1` and I issued in wrong place.
I close this issue and continue in `flutter_background_geolocation` github page if error persists.
Thanks
