### ISSUE TITLE
[BUG] Background  task stop after long time

### ISSUE THREAD

**Issue by spalenzuela** [transistorsoft/flutter_background_fetch#135]
**Your Environment**
* Plugin version: 0.5.5
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Samsung S7
* Flutter info (`flutter info`, `flutter doctor`):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18363.592], locale es-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Proxy Configuration
[√] Connected device (1 available)

• No issues found!

* Plugin config
BackgroundFetchConfig(
          forceAlarmManager: false,  //Same behavior with true
          minimumFetchInterval: 5,
          startOnBoot: true,
          stopOnTerminate: false,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE)

**To Reproduce**
1. Close app or restart device
2. Background task work fine
3. After several hours stop working

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
I have read this article: https://developer.android.com/training/monitoring-device-state/doze-standby#whitelisting-cases and I don't know if flutter_background_fetch have it implemented.

**Comment by christocracy** [comment]
You should get more consistent results, at the expense if higher battery usage, with `forceAlarmManager: true`.

You should also see http://dontkillmyapp.com and periodically unlock your device.

**Comment by spalenzuela** [comment]
I get the same result with 

 `forceAlarmManager: true`

Can you check the link I posted?

**Comment by christocracy** [comment]
Your linked article is not related to your problem.  There’s nothing in that link to “implement”.

The plugin uses `JobScheduler` or `AlarmManager` (when `forceAlarmManager: true`).

More likely it’s your operating system.  See http://dontkillmyapp.com

You can view the plugin’s Android code here, it’s open-source:

https://github.com/transistorsoft/transistor-background-fetch/tree/master/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch
