### ISSUE TITLE
[QUESTION] - Send local notification on iOS when app is terminated

### ISSUE THREAD

**Issue by antoine92190** [transistorsoft/flutter_background_fetch#139]
My use case is to send a local notification when entering / exiting geofences.

It works fine when the app is opened / in the background, but I'm having some difficulties finding  a way to make it work when the app is terminated.

I know that I can use `enableHeadless` property on Android to make this work.
But is there a way to get the same result on iOS?

**Comment by christocracy** [comment]
When an iOS geofence fires, the OS automatically relaunches your app in the background, just as if launched from the home screen.

Your onGeofence event will fire and you’re free to do anything you wish there, including post a local notification.

**Comment by antoine92190** [comment]
Ok thanks! Will try to make it work then
