### ISSUE TITLE
[BUG] background fetch is not running

### ISSUE THREAD

**Issue by MuhammedRefaat** [transistorsoft/flutter_background_fetch#141]
**My Environment** 
* Plugin version: 0.5.5 [newer versions causing conflicts in my side with other plugins]
* iOS
* OS version: 11.4.1
* Device manufacturer / model: iPad
* Flutter info (`flutter info`, `flutter doctor`):

> [✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.14.6 18G6020, locale en-AE)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.5)

* Plugin config
```
 // Configure BackgroundFetch.
    bgFetch.BackgroundFetch.configure(
        bgFetch.BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: bgFetch.NetworkType.NONE),
        (String taskId) async {
      // This is the fetch-event callback.
      print("[BackgroundFetch] Event received $taskId");
      bool newMessagesReceived = await MessageController.getNewMessages();
      if (newMessagesReceived) {
        showNotification(
            "You have new messages to check", getFlutterNotificationPlugin());
      }
      // IMPORTANT:  You must signal completion of your task or the OS can punish your app
      // for taking too long in the background.
      bgFetch.BackgroundFetch.finish(taskId);
    }).then((int status) {
      print('[BackgroundFetch] configure success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    });
```

**To Reproduce**
1.  doing the ios configuration changes as mentioned in the documentation.
2. using XCode, build and run the app in iOS physical device.
3. "simulate background fetch" in iOS and it works perfectly.
4. close the app and wait for more than 15 min.
5. no bg fetch is happening and no tasks are being handled.

**Debug logs**
- no logs are there as the app is closed, but when simulating bg fetch when app is running everything is working perfectly. 

**Additional context**
I created a new adHoc version and install on the device directly but got the same results as always.

**Comment by christocracy** [comment]
If it works in the simulator, that's all you need to know that it works.

Note also, that iOS background-fetch events no longer fire if you *terminate* the app.

iOS fetch events are unpredictable.  They probably won't come every 15 min.  More like once or twice / hour.
