### ISSUE TITLE
Not getting backgroundFetchHeadlessTask  after terminating app

### ISSUE THREAD

**Issue by sidkhore1002** [transistorsoft/flutter_background_fetch#142]
**Your Environment**
* Plugin version: ^0.5.1
* Platform: Android
* OS version: 28
* Device manufacturer / model:  Realme 3 pro
* Flutter info (`flutter info`, `flutter doctor`): 
[✓] Flutter (Channel master, v1.14.2-pre.53, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!

**Application.java**
```java
package com.app.anuroop;  // <-- replace this

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    BackgroundFetchPlugin.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

**Comment by christocracy** [comment]
Why are you implementing `Application.java`?

**Comment by sidkhore1002** [comment]
I also tried without application java, It is still not working. It is working fine for custom tasks but not getting headless event after 15 min when app is in terminated..

**Comment by sidkhore1002** [comment]
main.dart:

import 'dart:async';
import 'dart:convert';

import 'package:algolia/algolia.dart';
import 'package:anuroop/providers/favourite_provider.dart';
import 'package:anuroop/providers/filter_provider.dart';
import 'package:anuroop/providers/interest_provider.dart';
import 'package:anuroop/providers/new_interest_provider.dart';
import 'package:anuroop/services/algolia_service.dart';
import 'package:anuroop/services/api-service.dart';
import 'package:anuroop/services/firebase_service.dart';
import 'package:anuroop/services/loader.dart';
import 'package:anuroop/services/route_generator.dart';
import 'package:anuroop/widgets/loader.dart';
import 'package:background_fetch/background_fetch.dart';
import 'package:flutter/material.dart';
import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';

import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'configs/config.dart';
import 'configs/constants.dart';
import 'providers/compatibility-match-provider.dart';
import 'providers/edit_user_provider.dart';
import 'providers/user_provider.dart';

import 'services/intercom_service.dart';

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask(String taskId) async {
  print('In backgroundFetchHeadlessTask');

  SharedPreferences prefs = await SharedPreferences.getInstance();

  String a = prefs.getString("bachgroundFetchCount");

  String userData = prefs.getString(Constants.SHARED_PREF_LOGIN_DATA);    

  if(a != null){
    // a = (int.parse(a) + 1).toString();
    a = a+" headLess ";
  }
  else{
    a="1";
  }
  prefs.setString("bachgroundFetchCount", a);

  if(userData != null){
    Map userLoginData = jsonDecode(userData);

    String firebaseToken = "1";
    try {
      firebaseToken = await FirebaseService.getToken();
    } catch (e) {}

    //User Authentication info
    ApiService.getUserInfoV2(userLoginData['profileId'],userLoginData['password'], firebaseToken)
    .then((onResponse) async {      
      await prefs.setString("bachgroundFetchUserInfo", jsonEncode(onResponse));
      Map userDataObject = onResponse;
      prefs.setString("bachgroundFetchErrorStatus", "NoError");

      //User Profile info Algolia
      AlgoliaQuery userProfileInfoQuery;
      Algolia algolia = AlgoliaService.algolia;
      String searchIndex = (userDataObject['gender'] == 'Male')
          ? Config.ALGOLIA_MALE_INDEX
          : Config.ALGOLIA_FEMALE_INDEX;

      String profileId = 'profileId:' + userDataObject['profileID'].toString();
      userProfileInfoQuery = algolia.instance.index(searchIndex).setFilters(profileId);
      List userProfileInfo = [];
      userProfileInfo = (await userProfileInfoQuery.getObjects()).hits;
      prefs.setString("bachgroundFetchUserProfileInfo", jsonEncode(userProfileInfo[0].data));

      //User Interest List
      ApiService.getProfileInterestList(userDataObject['profileID'], userDataObject['tokenId'])
      .then((interestResponse) async{
        SharedPreferences prefs = await SharedPreferences.getInstance();
        prefs.setString("bachgroundFetchUserInterestResponse", jsonEncode(interestResponse));

        if(a != null){
          // a = (int.parse(a) + 1).toString();
          a = a+" headLess ";
          prefs.setString("bachgroundFetchCount", a);
        }
        else{
          a="1";
          prefs.setString("bachgroundFetchCount", a);
        }

      });
    }).catchError((onError) {
      var error = jsonDecode(onError);
      prefs.setString("bachgroundFetchErrorStatus", "Error");
      prefs.setString("bachgroundFetchErrorObject", jsonEncode(error));

    });
  }

  BackgroundFetch.finish(taskId);

  // if (taskId == 'flutter_background_fetch') {
  //   BackgroundFetch.scheduleTask(TaskConfig(
  //       taskId: "com.transistorsoft.customtask",
  //       delay: 5000,
  //       periodic: true,
  //       forceAlarmManager: true,
  //       stopOnTerminate: false,
  //       enableHeadless: true
  //   ));
  // }

}


void main() async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await IntercomService.initializeIntercom();
    FirebaseService.init();
  } catch (e) {}
  // WidgetFlutterBinding.ensureInitialized();
  runZoned(() {
    runApp(new Anuroop());

    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

    BackgroundFetch.start().then((int status) {
      print('[BackgroundFetch] start success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] start FAILURE: $e');
    });

  }, onError: FirebaseService.firebaseCrashlytics.recordError);
}

class Anuroop extends StatefulWidget {
  @override
  _AnuroopState createState() => _AnuroopState();
}

class _AnuroopState extends State<Anuroop> {
  String userData = "";
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    // this.setRootPage();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {

    BackgroundFetch.start().then((int status) {
      print('[BackgroundFetch] start success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] start FAILURE: $e');
    });

    print('In initPlatformState');

    // Configure BackgroundFetch.
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        forceAlarmManager: false,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE,
    ), _onBackgroundFetch).then((int status) {
      print('[BackgroundFetch] configure success: $status');

    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    });

    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

  void _onBackgroundFetch(String taskId) async {
    print('In _onBackgroundFetch');

    SharedPreferences prefs = await SharedPreferences.getInstance();
    // This is the fetch-event callback.

    String a = prefs.getString("bachgroundFetchCount");

    // if(taskId == "getUserInfoForPreferences"){
      String userData = prefs.getString(Constants.SHARED_PREF_LOGIN_DATA);    
      if(userData != null){
        
        Map userLoginData = jsonDecode(userData);

        String firebaseToken = "1";
        try {
          firebaseToken = await FirebaseService.getToken();
        } catch (e) {}
        
        //User Authentication info
        ApiService.getUserInfoV2(userLoginData['profileId'],userLoginData['password'], firebaseToken)
        .then((onResponse) async {        
          await prefs.setString("bachgroundFetchUserInfo", jsonEncode(onResponse));
          Map userDataObject = onResponse;
          prefs.setString("bachgroundFetchErrorStatus", "NoError");

          //User Profile info Algolia
          AlgoliaQuery userProfileInfoQuery;
          Algolia algolia = AlgoliaService.algolia;
          String searchIndex = (userDataObject['gender'] == 'Male')
              ? Config.ALGOLIA_MALE_INDEX
              : Config.ALGOLIA_FEMALE_INDEX;

          String profileId = 'profileId:' + userDataObject['profileID'].toString();
          userProfileInfoQuery = algolia.instance.index(searchIndex).setFilters(profileId);
          List userProfileInfo = [];
          userProfileInfo = (await userProfileInfoQuery.getObjects()).hits;
          prefs.setString("bachgroundFetchUserProfileInfo", jsonEncode(userProfileInfo[0].data));

          //User Interest List
          ApiService.getProfileInterestList(userDataObject['profileID'], userDataObject['tokenId'])
          .then((interestResponse) async{
            SharedPreferences prefs = await SharedPreferences.getInstance();
            prefs.setString("bachgroundFetchUserInterestResponse", jsonEncode(interestResponse));

            if(a != null){
              // a = (int.parse(a) + 1).toString();
              a = a+"*";
            }
            else{
              a="1";
            }
            // Persist fetch events in SharedPreferences
              prefs.setString("bachgroundFetchCount", a);
          });
        }).catchError((onError) {
          var error = jsonDecode(onError);
          prefs.setString("bachgroundFetchErrorStatus", "Error");
          prefs.setString("bachgroundFetchErrorObject", jsonEncode(error));

        });

      }
    // }

    BackgroundFetch.finish(taskId);
  }


  Widget getErrorWidget(FlutterErrorDetails error) {
    FirebaseService.trackEvent(
        eventName: "ERROR", parameters: error.toString());
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Icon(
              Icons.error_outline,
              color: Color(0xff481f6f),
              size: 80,
            ),
            SizedBox(
              height: 15,
            ),
            Flexible(
              child: Text(
                'Something went wrong.Please restart the application.',
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 16, color: Colors.black54),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {

    // this.getRootPage(context);
    FlutterStatusbarcolor.setStatusBarColor(Color(0xff481F6F));
    ErrorWidget.builder = getErrorWidget;
    return MultiProvider(
      providers: [
        ChangeNotifierProvider.value(
          value: UserProvider(),
        ),
        ChangeNotifierProvider.value(
          value: InterestProvider(),
        ),
        ChangeNotifierProvider.value(
          value: FavouriteProvider(),
        ),
        ChangeNotifierProvider.value(
          value: EditUserProvider(),
        ),
        ChangeNotifierProvider.value(
          value: FilterProvider(),
        ),
        ChangeNotifierProvider.value(
          value: CompatibilityMatchProvider(),
        ),
        ChangeNotifierProvider.value(
          value: NewInterestProvider(),
        ),
      ],
      child: MaterialApp(
        // home: userData =="" || userData == null ? Login(): TabScreen(),
        initialRoute:
            '/', // userData =="" || userData == null ? RoutePath.LOGIN_SCREEN: RoutePath.TABS_SCREEN,
        onGenerateRoute: RouteGenerator.generateRoute,
        // routes: {
        //   RoutePath.LOGIN_SCREEN: (ctx) => Login(),
        //   RoutePath.TABS_SCREEN: (ctx) => TabScreen(),
        //   RoutePath.REGISTER_SCREEN: (ctx) => RegistrationScreen(),
        //   RoutePath.TERMS_SCREEN: (ctx) => TermsAndConditionsScreen(),
        //   RoutePath.EVENTS_SCREEN: (ctx) => Events(),
        //   RoutePath.ABOUT_SCREEN: (ctx) => AboutAnuroop(),
        //   RoutePath.CONTACT_VIEWED_SCREEN: (ctx) => ContactViewedProfile(),
        //   RoutePath.RECENTLY_VIEWED_SCREEN: (ctx)=> RecentlyViewed(),
        //   RoutePath.PROFILE_PICTURE :(ctx) => ProfilePicture(),
        //   RoutePath.VIEW_PROFILE :(ctx) => ViewUserProfile2()
        //   // RoutePath.VIEW_PROFILE: (ctx)=> ViewUserProfileV2(),
        //   // RoutePath.WHO_VIEWED_MY_CONTACTS: (ctx) => Whoviewedmycontact(),
        //   // RoutePath.WHO_VIEWED_MY_FAVOURITES: (ctx) => WhoAddedMeToFavourites(),
        //   //RoutePath.WHO_VIEWED_MY_PROFILE: (ctx) => Whoviewedmyprofile(),
        // },
      ),
    );
  }
}

**Comment by sidkhore1002** [comment]
main.dart:

import 'dart:async';
import 'dart:convert';

import 'package:algolia/algolia.dart';
import 'package:anuroop/providers/favourite_provider.dart';
import 'package:anuroop/providers/filter_provider.dart';
import 'package:anuroop/providers/interest_provider.dart';
import 'package:anuroop/providers/new_interest_provider.dart';
import 'package:anuroop/services/algolia_service.dart';
import 'package:anuroop/services/api-service.dart';
import 'package:anuroop/services/firebase_service.dart';
import 'package:anuroop/services/loader.dart';
import 'package:anuroop/services/route_generator.dart';
import 'package:anuroop/widgets/loader.dart';
import 'package:background_fetch/background_fetch.dart';
import 'package:flutter/material.dart';
import 'package:flutter_statusbarcolor/flutter_statusbarcolor.dart';

import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'configs/config.dart';
import 'configs/constants.dart';
import 'providers/compatibility-match-provider.dart';
import 'providers/edit_user_provider.dart';
import 'providers/user_provider.dart';

import 'services/intercom_service.dart';

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask(String taskId) async {
  print('In backgroundFetchHeadlessTask');

  SharedPreferences prefs = await SharedPreferences.getInstance();

  String a = prefs.getString("bachgroundFetchCount");

  String userData = prefs.getString(Constants.SHARED_PREF_LOGIN_DATA);    

  if(a != null){
    // a = (int.parse(a) + 1).toString();
    a = a+" headLess ";
  }
  else{
    a="1";
  }
  prefs.setString("bachgroundFetchCount", a);

  if(userData != null){
    Map userLoginData = jsonDecode(userData);

    String firebaseToken = "1";
    try {
      firebaseToken = await FirebaseService.getToken();
    } catch (e) {}

    //User Authentication info
    ApiService.getUserInfoV2(userLoginData['profileId'],userLoginData['password'], firebaseToken)
    .then((onResponse) async {      
      await prefs.setString("bachgroundFetchUserInfo", jsonEncode(onResponse));
      Map userDataObject = onResponse;
      prefs.setString("bachgroundFetchErrorStatus", "NoError");

      //User Profile info Algolia
      AlgoliaQuery userProfileInfoQuery;
      Algolia algolia = AlgoliaService.algolia;
      String searchIndex = (userDataObject['gender'] == 'Male')
          ? Config.ALGOLIA_MALE_INDEX
          : Config.ALGOLIA_FEMALE_INDEX;

      String profileId = 'profileId:' + userDataObject['profileID'].toString();
      userProfileInfoQuery = algolia.instance.index(searchIndex).setFilters(profileId);
      List userProfileInfo = [];
      userProfileInfo = (await userProfileInfoQuery.getObjects()).hits;
      prefs.setString("bachgroundFetchUserProfileInfo", jsonEncode(userProfileInfo[0].data));

      //User Interest List
      ApiService.getProfileInterestList(userDataObject['profileID'], userDataObject['tokenId'])
      .then((interestResponse) async{
        SharedPreferences prefs = await SharedPreferences.getInstance();
        prefs.setString("bachgroundFetchUserInterestResponse", jsonEncode(interestResponse));

        if(a != null){
          // a = (int.parse(a) + 1).toString();
          a = a+" headLess ";
          prefs.setString("bachgroundFetchCount", a);
        }
        else{
          a="1";
          prefs.setString("bachgroundFetchCount", a);
        }

      });
    }).catchError((onError) {
      var error = jsonDecode(onError);
      prefs.setString("bachgroundFetchErrorStatus", "Error");
      prefs.setString("bachgroundFetchErrorObject", jsonEncode(error));

    });
  }

  BackgroundFetch.finish(taskId);

  // if (taskId == 'flutter_background_fetch') {
  //   BackgroundFetch.scheduleTask(TaskConfig(
  //       taskId: "com.transistorsoft.customtask",
  //       delay: 5000,
  //       periodic: true,
  //       forceAlarmManager: true,
  //       stopOnTerminate: false,
  //       enableHeadless: true
  //   ));
  // }

}


void main() async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await IntercomService.initializeIntercom();
    FirebaseService.init();
  } catch (e) {}
  // WidgetFlutterBinding.ensureInitialized();
  runZoned(() {
    runApp(new Anuroop());

    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

    BackgroundFetch.start().then((int status) {
      print('[BackgroundFetch] start success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] start FAILURE: $e');
    });

  }, onError: FirebaseService.firebaseCrashlytics.recordError);
}

class Anuroop extends StatefulWidget {
  @override
  _AnuroopState createState() => _AnuroopState();
}

class _AnuroopState extends State<Anuroop> {
  String userData = "";
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    // this.setRootPage();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {

    BackgroundFetch.start().then((int status) {
      print('[BackgroundFetch] start success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] start FAILURE: $e');
    });

    print('In initPlatformState');

    // Configure BackgroundFetch.
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        forceAlarmManager: false,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE,
    ), _onBackgroundFetch).then((int status) {
      print('[BackgroundFetch] configure success: $status');

    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    });

    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

  void _onBackgroundFetch(String taskId) async {
    print('In _onBackgroundFetch');

    SharedPreferences prefs = await SharedPreferences.getInstance();
    // This is the fetch-event callback.

    String a = prefs.getString("bachgroundFetchCount");

    // if(taskId == "getUserInfoForPreferences"){
      String userData = prefs.getString(Constants.SHARED_PREF_LOGIN_DATA);    
      if(userData != null){
        
        Map userLoginData = jsonDecode(userData);

        String firebaseToken = "1";
        try {
          firebaseToken = await FirebaseService.getToken();
        } catch (e) {}
        
        //User Authentication info
        ApiService.getUserInfoV2(userLoginData['profileId'],userLoginData['password'], firebaseToken)
        .then((onResponse) async {        
          await prefs.setString("bachgroundFetchUserInfo", jsonEncode(onResponse));
          Map userDataObject = onResponse;
          prefs.setString("bachgroundFetchErrorStatus", "NoError");

          //User Profile info Algolia
          AlgoliaQuery userProfileInfoQuery;
          Algolia algolia = AlgoliaService.algolia;
          String searchIndex = (userDataObject['gender'] == 'Male')
              ? Config.ALGOLIA_MALE_INDEX
              : Config.ALGOLIA_FEMALE_INDEX;

          String profileId = 'profileId:' + userDataObject['profileID'].toString();
          userProfileInfoQuery = algolia.instance.index(searchIndex).setFilters(profileId);
          List userProfileInfo = [];
          userProfileInfo = (await userProfileInfoQuery.getObjects()).hits;
          prefs.setString("bachgroundFetchUserProfileInfo", jsonEncode(userProfileInfo[0].data));

          //User Interest List
          ApiService.getProfileInterestList(userDataObject['profileID'], userDataObject['tokenId'])
          .then((interestResponse) async{
            SharedPreferences prefs = await SharedPreferences.getInstance();
            prefs.setString("bachgroundFetchUserInterestResponse", jsonEncode(interestResponse));

            if(a != null){
              // a = (int.parse(a) + 1).toString();
              a = a+"*";
            }
            else{
              a="1";
            }
            // Persist fetch events in SharedPreferences
              prefs.setString("bachgroundFetchCount", a);
          });
        }).catchError((onError) {
          var error = jsonDecode(onError);
          prefs.setString("bachgroundFetchErrorStatus", "Error");
          prefs.setString("bachgroundFetchErrorObject", jsonEncode(error));

        });

      }
    // }

    BackgroundFetch.finish(taskId);
  }


  Widget getErrorWidget(FlutterErrorDetails error) {
    FirebaseService.trackEvent(
        eventName: "ERROR", parameters: error.toString());
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Icon(
              Icons.error_outline,
              color: Color(0xff481f6f),
              size: 80,
            ),
            SizedBox(
              height: 15,
            ),
            Flexible(
              child: Text(
                'Something went wrong.Please restart the application.',
                textAlign: TextAlign.center,
                style: TextStyle(fontSize: 16, color: Colors.black54),
              ),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {

    // this.getRootPage(context);
    FlutterStatusbarcolor.setStatusBarColor(Color(0xff481F6F));
    ErrorWidget.builder = getErrorWidget;
    return MultiProvider(
      providers: [
        ChangeNotifierProvider.value(
          value: UserProvider(),
        ),
        ChangeNotifierProvider.value(
          value: InterestProvider(),
        ),
        ChangeNotifierProvider.value(
          value: FavouriteProvider(),
        ),
        ChangeNotifierProvider.value(
          value: EditUserProvider(),
        ),
        ChangeNotifierProvider.value(
          value: FilterProvider(),
        ),
        ChangeNotifierProvider.value(
          value: CompatibilityMatchProvider(),
        ),
        ChangeNotifierProvider.value(
          value: NewInterestProvider(),
        ),
      ],
      child: MaterialApp(
        // home: userData =="" || userData == null ? Login(): TabScreen(),
        initialRoute:
            '/', // userData =="" || userData == null ? RoutePath.LOGIN_SCREEN: RoutePath.TABS_SCREEN,
        onGenerateRoute: RouteGenerator.generateRoute,
        // routes: {
        //   RoutePath.LOGIN_SCREEN: (ctx) => Login(),
        //   RoutePath.TABS_SCREEN: (ctx) => TabScreen(),
        //   RoutePath.REGISTER_SCREEN: (ctx) => RegistrationScreen(),
        //   RoutePath.TERMS_SCREEN: (ctx) => TermsAndConditionsScreen(),
        //   RoutePath.EVENTS_SCREEN: (ctx) => Events(),
        //   RoutePath.ABOUT_SCREEN: (ctx) => AboutAnuroop(),
        //   RoutePath.CONTACT_VIEWED_SCREEN: (ctx) => ContactViewedProfile(),
        //   RoutePath.RECENTLY_VIEWED_SCREEN: (ctx)=> RecentlyViewed(),
        //   RoutePath.PROFILE_PICTURE :(ctx) => ProfilePicture(),
        //   RoutePath.VIEW_PROFILE :(ctx) => ViewUserProfile2()
        //   // RoutePath.VIEW_PROFILE: (ctx)=> ViewUserProfileV2(),
        //   // RoutePath.WHO_VIEWED_MY_CONTACTS: (ctx) => Whoviewedmycontact(),
        //   // RoutePath.WHO_VIEWED_MY_FAVOURITES: (ctx) => WhoAddedMeToFavourites(),
        //   //RoutePath.WHO_VIEWED_MY_PROFILE: (ctx) => Whoviewedmyprofile(),
        // },
      ),
    );
  }
}

**Comment by sidkhore1002** [comment]
..
