### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rrifafauzikomara** [transistorsoft/flutter_background_fetch#144]
Can I use this plugin to scheduled tasks on the background (when the app is closed) or on the foreground (when the app is opened)? For example, I want to run some tasks every 9 PM with support Android and iOS. It's possible?

**Comment by christocracy** [comment]
On Android, yes.  iOS, no.  iOS doesn't run tasks when app is terminated by the *user*.

**Comment by rrifafauzikomara** [comment]
Hi @christocracy 

How about user in iOS not terminated but only minimize the app, so the task is still run or not?

And also please don't close first, because I want to discuss first.

**Comment by christocracy** [comment]
>How about user in iOS not terminated but only minimize

*minimized* != *terminated*.

**Comment by rrifafauzikomara** [comment]
So the answered the task still run on the ios if the apps is minimeze?

**Comment by christocracy** [comment]
8Minimized* = background, wouldn’t you say?

What’s the name of this plugin?  *background*-fetch.

**Comment by rrifafauzikomara** [comment]
Yes, Minimized = background, but not kill or close the app. So using this plugin if the case on the iOS-like that, still can run the task on the background?
