### ISSUE TITLE
Need example of a periodic task to run every day at approximately 09:00:00 PM

### ISSUE THREAD

**Issue by rrifafauzikomara** [transistorsoft/flutter_background_fetch#145]
I'm always frustrated when read the documentation about my case like in the title. Is there an example for my case?

My case:

I want to execute my task/function (get the data from API, `let's say the name of this function is A`) every day at approximately 09:00:00 PM, and when the time is 09:00:00 PM, it will execute that `function A`, and when success execute the `function A`, on the success response will run the notification function (`let's sat the name of this function is B`) to show the notification.

Fyi, I already create `function A` and also drop the `function B` on the success response, but the problem is `how to trigger to run the function A when the time is 09:00:00 PM?`

**Comment by ydotmalik** [comment]
The simplest way is to get a background_fetch periodically, check if the time is greater than 9 PM, and if so run your code. Then maintain some state indicating that you already ran and check that state to not do anything when the background_fetch event runs again.

**Comment by rrifafauzikomara** [comment]
I think this package not supported for scheduled, for now, I just using android_alarm_manager.
