### ISSUE TITLE
Memory get cleared on moving from foreground to background

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [transistorsoft/flutter_background_fetch#147]
Once i open the app I start a socketIo connection inside the background fetch callback. And it's connected well, But once the app get moved to the background the socket connection get destroyed, And i had to run a periodic callback to reconnecting the socket again. The proccess which is running on the foreground get desteoyed on moving to background, And the same also happens on moving from the background to the termination level. I think that the memory get cleared on moving from every isolate to other. Is there any suggestions to fix this ? To keep the old memory as it is on moving to the background ?

**Comment by christocracy** [comment]
I wouldn’t expect a socket connection to stay alive  when an app is suspended, but I have no experience with sockets in Android / iOS.

**Comment by AlaaEldeenYsr** [comment]
Alright forget the sockets, Lets consider we have that counter ```int counter = 0;```  and we print and increment it in the both background fetch and headless tasks callbacks, Try to increment it before moving to the background, Then after moving to the background you will notice that its latest value is cleared and regenerated from the begging, In other meaning the memory is cleared and another on is generated.
I need to keep the memory as it is on moving to the background, Please help.
```dart
import 'package:flutter/material.dart';
import 'package:background_fetch/background_fetch.dart';

int counter = 0;

void backgroundFetchHeadlessTask(String taskId) async {
  print("Headless event: $counter");
  counter++;
  BackgroundFetch.finish(taskId);
}

void _onBackgroundFetch(String taskId) async {
  print("[BackgroundFetch] $counter");
  counter++;
  BackgroundFetch.finish(taskId);
}

void main() {
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

  BackgroundFetch.configure(
    BackgroundFetchConfig(
      minimumFetchInterval: 15,
      forceAlarmManager: false,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      requiresBatteryNotLow: false,
      requiresCharging: false,
      requiresStorageNotLow: false,
      requiresDeviceIdle: false,
      requiredNetworkType: NetworkType.NONE,
    ),
    _onBackgroundFetch,
  ).then((int status) {
    print('[BackgroundFetch] configure success: $status');
  }).catchError((e) {
    print('[BackgroundFetch] configure ERROR: $e');
  });

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('BackgroundFetch Example')),
        body: Container(),
      ),
    );
  }
}


```

![image](https://user-images.githubusercontent.com/52201392/91604717-76ae5680-e96f-11ea-9a09-554947f2efc2.png)

I'm using that command ```adb shell cmd jobscheduler run -f com.example.background_challenge 999```

**Comment by christocracy** [comment]
I would use SharedPreferences store the state of counter.

I wouldn’t expect that to persist between the `App` and headlessTask.

**Comment by AlaaEldeenYsr** [comment]
Of course but i can't store the socket connection in the SharedPreferences.
It would be great if it became possible in the future ( to make the memory persists between isolates )
Thank you master @christocracy

**Comment by christocracy** [comment]
> would be great if it became possible

From a pure Android application point-of-view, I can’t see how that would ever be possible.  The entire app process is terminated from memory when the app is terminated.

**Comment by AlaaEldeenYsr** [comment]
Yeah, I understand you, I just thought it can be handled by running the background fetch on a seperated or islotaed part of memory from the begining, So the counter from the begining is created on a different part of memory from the app, And that part of memory still the same even if the app is terminated. So i think i should run periodic task to pass this.
@christocracy Thank you master.

**Comment by AlaaEldeenYsr** [comment]
If you looked here at this package ```flutter_isolate``` you will find it working the same as i'm telling you, You will find the timer still working if you pressed the back button moving the app to the background, But unfortunately this package doesn't support the termination level.
So i'm trying to tell you that this is somehow not impossible, What do you think ? @christocracy 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_isolate/flutter_isolate.dart';

void isolate1(String arg) async {
  Timer.periodic(Duration(seconds: 1), (timer) => print("Timer Running From Isolate"));
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FlutterIsolate.spawn(isolate1, "hello");
  runApp(MyApp());
}
```

Here is the equivalent of the first example but the timer get stopped on pressing the back button moving the app to the background
```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:background_fetch/background_fetch.dart';

void _onBackgroundFetch(String taskId) async {
  Timer.periodic(Duration(seconds: 1), (timer) => print('[BackgroundFetch]'));
  BackgroundFetch.finish(taskId);
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  BackgroundFetch.configure(
    BackgroundFetchConfig(
      minimumFetchInterval: 15,
      forceAlarmManager: false,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
      requiresBatteryNotLow: false,
      requiresCharging: false,
      requiresStorageNotLow: false,
      requiresDeviceIdle: false,
      requiredNetworkType: NetworkType.NONE,
    ),
    _onBackgroundFetch,
  ).then((int status) {
    print('[BackgroundFetch] configure success: $status');
  }).catchError((e) {
    print('[BackgroundFetch] configure ERROR: $e');
  });

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('BackgroundFetch Example')),
        body: Container(),
      ),
    );
  }
}

```

**Comment by christocracy** [comment]
I'm familiar with these *state persistence* mechanisms.  That's quite a different thing than attempting to keep a web-socket alive when an app is terminated.  I think that's impossible.  See #98.
