### ISSUE TITLE
Behavior on iOS question

### ISSUE THREAD

**Issue by ydotmalik** [transistorsoft/flutter_background_fetch#148]
It seems on Android my callback will be called even if my app is closed. However it seems on iOS my callback will only be called if:
* my app is running in the background
* the phone is plugged into power
* and is only called every 15 minutes.

Is my understanding correct?

**Comment by christocracy** [comment]
- iOS halts background-fetch events when *user* terminates the app.
- If the user doesn't open the app *daily*, iOS halts events.
- iOS does not fire `BackgroundFetch.scheduleTask` unless the device is plugged into power.
- The minimum `fetchInterval` is 15 minutes but iOS will throttle this based upon app usage patterns.  If user doesn't open the app frequently, the `15` minutes might become only several times / day.
