### ISSUE TITLE
Accessing program objects in headless event

### ISSUE THREAD

**Issue by ydotmalik** [transistorsoft/flutter_background_fetch#149]
What is the recommended pattern for accessing program objects in a headless event? I store my program objects using [provider](https://pub.dev/packages/provider), which I store in the BuildContext associated with my top-level widget. This context isn't available in the headless event handler, which apparently must be a global function. To access my provider objects, I push something on to a Stream in my event handler, which I listen to on a StreamBuilder widget, but this change is requiring other parts of my code to change as well.

I could make the necessary objects global, but I wondering if there is a better way to access my program objects.

**Comment by christocracy** [comment]
Your Flutter app components exist in the Android `MainActivity`.  When an Android app is terminated, it’s the `MainActivity` which is terminated.

Your Flutter app doesn’t exist in the terminated state.

Another name for *Headless* is *Activity-less*.

**Comment by ydotmalik** [comment]
So I wouldn't be able to access my program objects anyway?

In a test program, I was able to generate notifications in a headless event using flutter_local_notifications.

**Comment by christocracy** [comment]
Use `SharedPreferences` to share data with the headless state.

**Comment by ydotmalik** [comment]
I see. I use Sembast as my db. I guess I could access that directly in the event. It'd still require refactoring my code.

If Flutter is not available in the headless state, how am I able to generate a local notification in the headless event handler?

**Comment by christocracy** [comment]
>If Flutter is not available in the headless state

I didn't say *Flutter* was not available in the headless state.  I said your Flutter *App* does not exist in the headless state.

`main.dart` *does* exist in the headless state.

```dart
void main() {  // <-- This method does NOT run in headless state.
  // Enable integration testing with the Flutter Driver extension.
  // See https://flutter.io/testing/ for more info.
  runApp(new MyApp());  // <-- MyApp does not exist in headless state.

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

**Comment by ydotmalik** [comment]
Thanks. Really appreciate fast responses. You support is top notch.
