### ISSUE TITLE
[BUG] Background and Foreground callbacks not happens from flavor-ed application

### ISSUE THREAD

**Issue by saravananmnm** [transistorsoft/flutter_background_fetch#150]
Am using background_fetch: ^0.6.0 version.

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-IN)
    • Flutter version 1.20.2 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision bbfbf1770c (4 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Genymotion 9 0 New (mobile) • 192.168.241.101:5555 • android-x86 • Android 9 (API 28)

• No issues found!

**Comment by saravananmnm** [comment]
`void mainCommon(AppConfig config) {
  WidgetsFlutterBinding.ensureInitialized();
  // Here would be background init code, if any
  diConfig(config);
  runApp(CourierAlliance(config));
  BackgroundService();

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
}

class CourierAlliance extends StatelessWidget {
 final AppConfig config;
  CourierAlliance(this.config);
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: config.appDisplayName,
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: SplashView(),
    );
  }
}`

**Comment by christocracy** [comment]
I don’t know what you mean and you’ve ignored the issue template (iOS or Android??).

**Comment by saravananmnm** [comment]
I have created flavored flutter application. Lets assume that we have dev,qa and uat environment.Now, i want to run the dev environment. Then how we can cofigure the background fetch. Because we have 3 main method and one common class for that flavored application.

Is it possible above mentioned cases.?

**Comment by christocracy** [comment]
background_fetch shouldn’t care about your flavors.
