### ISSUE TITLE
Document that scheduleTask only works for iOS 13+

### ISSUE THREAD

**Issue by tudor07** [transistorsoft/flutter_background_fetch#151]
Document this method: https://github.com/transistorsoft/flutter_background_fetch/blob/master/lib/background_fetch.dart#L474

**Comment by nazirjon-1997** [comment]
The background fetch does not work for me in a real device, but it works in the simulator, how to fix this?

**Comment by christocracy** [comment]
If it works on the simulator, that's all you need to know that it will work on a real device.

**Comment by nazirjon-1997** [comment]
I don't know it doesn't work in a real device

**Comment by christocracy** [comment]
- iOS halts events if user terminated app.
- iOS halts events if your app is not opened *daily*.
- iOS can require several days to tune its machine learning algorithm to fire events as expected.

If with simulated events, that's all you need to do to ensure everything is wired up on your end.  Everything else is beyond anyone's control.

**Comment by nazirjon-1997** [comment]
<img width="1151" alt="Снимок экрана 2021-01-17 в 18 52 15" src="https://user-images.githubusercontent.com/38754200/104848246-23747a80-58f5-11eb-9ae4-d576847d0f70.png">
How to fix it?

**Comment by christocracy** [comment]
Review Setup docs.

**Comment by nazirjon-1997** [comment]
<img width="577" alt="Снимок экрана 2021-01-17 в 18 56 05" src="https://user-images.githubusercontent.com/38754200/104848456-186e1a00-58f6-11eb-8c87-f6530d809aa2.png">
<img width="829" alt="Снимок экрана 2021-01-17 в 18 59 06" src="https://user-images.githubusercontent.com/38754200/104848461-1a37dd80-58f6-11eb-8626-b2836b5324dd.png">
I have everything done

**Comment by nazirjon-1997** [comment]
<img width="459" alt="Снимок экрана 2021-01-18 в 15 26 11" src="https://user-images.githubusercontent.com/38754200/104915338-891e4080-59a1-11eb-8385-0a7d8110267e.png">
my [BackgroundFetch] Event received function is not running. how is this understood?

**Comment by christocracy** [comment]
Have you tried the /example app is this repo?

**Comment by nazirjon-1997** [comment]
Yes, the example tried it worked in android and I now ran it in iOS but it does not work what to do?

**Comment by christocracy** [comment]
I just cloned this repo and launched a fresh instance of the `/example`.  Everything works as expected on my *iPhone 12 Pro* with *XCode 12.3*.   Both the `fetch` and `scheduleTask` events successfully fire using [simulated events](https://github.com/transistorsoft/flutter_background_fetch#-debugging)

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
````

```
(lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]

2021-01-18 10:09:48.019265-0500 Runner[18025:4422308] Simulating launch for task with identifier com.transistorsoft.fetch
2021-01-18 10:09:49.717762-0500 Runner[18025:4422908] Starting simulated task: <decode: missing data>
2021-01-18 10:09:49.718572-0500 Runner[18025:4422908] [TSBackgroundFetch handleBGAppRefreshTask]
2021-01-18 10:09:49.718965-0500 Runner[18025:4422908] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2021-01-18 10:09:49.721780-0500 Runner[18025:4422522] flutter: [BackgroundFetch] Event received: flutter_background_fetch

2021-01-18 10:09:49.724999-0500 Runner[18025:4422308] [TSBackgroundFetch finish] flutter_background_fetch (1 of 1)
2021-01-18 10:09:49.725129-0500 Runner[18025:4422308] Marking simulated task complete: <BGAppRefreshTask: com.transistorsoft.fetch>

(lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.customtask"]
2021-01-18 10:11:56.744275-0500 Runner[18025:4422308] Simulating launch for task with identifier com.transistorsoft.customtask
2021-01-18 10:11:59.363063-0500 Runner[18025:4423621] Starting simulated task: <decode: missing data>
2021-01-18 10:11:59.364461-0500 Runner[18025:4422522] flutter: [BackgroundFetch] Event received: com.transistorsoft.customtask
2021-01-18 10:11:59.367042-0500 Runner[18025:4422308] Marking simulated task complete: <BGProcessingTask: com.transistorsoft.customtask>
2021-01-18 10:11:59.369634-0500 Runner[18025:4422308] [TSBGTask destroy] com.transistorsoft.customtask
```

**Comment by nazirjon-1997** [comment]
I'm running the example, it didn't find Event received


flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.2, on Mac OS X 10.15.7 19H114 darwin-x64, locale ru)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

• No issues found!

(lldb) 2021-01-18 23:40:43.141312+0300 Runner[10199:3150626] [TSBackgroundFetch load]: (
)                                                                       
[TSBGAppRefreshSubscriber load]: {                                      
}                                                                       
[TSBackgroundFetch registerForTaskWithIdentifier: com.transistorsoft.customtask
fopen failed for data file: errno = 2 (No such file or directory)       
Errors found! Invalidating cache...                                     
fopen failed for data file: errno = 2 (No such file or directory)       
Errors found! Invalidating cache...                                     
[TSBackgroundFetch scheduleProcessingTask] <TSBGTask identifier=com.transistorsoft.customtask, delay=10, periodic=0 enabled=0>
[TSBGTask save]: <TSBGTask identifier=com.transistorsoft.customtask, delay=10, periodic=0 enabled=1>
[TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch       
flutter: [BackgroundFetch] configure success: 2

**Comment by christocracy** [comment]
How are you *simulating* a `fetch` task?

**Comment by nazirjon-1997** [comment]
did not understand the question, can you tell us more?

**Comment by christocracy** [comment]
I already mentioned *simulated events* above and provided a link the section in the README.  You didn't *actually* click that link?  I suggest you read the **entire** README.

![](https://dl.dropbox.com/s/p1d2raycm7ce0oo/Screen%20Shot%202021-01-18%20at%206.41.05%20PM.png?dl=1)

**Comment by nazirjon-1997** [comment]
(lldb) e -l objc - ( void ) [[BGTaskScheduler sharedScheduler ] _simulateLaunchForTaskWithIdentifier: @ " com.transistorsoft.fetch " ]
error: <user expression 5>:1:2: use of undeclared identifier 'l'
-l objc - ( void ) [[BGTaskScheduler sharedScheduler ] _simulateLaunchForTaskWithIdentifier: @ " com.transistorsoft.fetch " ] 

why doesn't the command work?

**Comment by nazirjon-1997** [comment]
I worked in the debug state when I add a command to debugging, and in the release state I do it, but I cannot add the command to debugging, what should I do?

**Comment by nazirjon-1997** [comment]
If you worked in debug, does debugging work without entering commands in the release?

**Comment by tudor07** [comment]
@christocracy what do you think?

**Comment by mzl1988** [comment]
> 我刚刚克隆了这个回购，并推出了一个新的实例。一切工作如预期的那样在我的_iPhone 12专业_版_与XCode 12.3。_使用模拟事件成功发射和[事件](https://github.com/transistorsoft/flutter_background_fetch#-debugging)`/example``fetch``scheduleTask`
> 
> ```
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-CA)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 12.3)
> [✓] Android Studio (version 4.0)
> [✓] VS Code (version 1.51.1)
> [✓] Connected device (2 available)
> ```
> 
> ```
> (lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]
> 
> 2021-01-18 10:09:48.019265-0500 Runner[18025:4422308] Simulating launch for task with identifier com.transistorsoft.fetch
> 2021-01-18 10:09:49.717762-0500 Runner[18025:4422908] Starting simulated task: <decode: missing data>
> 2021-01-18 10:09:49.718572-0500 Runner[18025:4422908] [TSBackgroundFetch handleBGAppRefreshTask]
> 2021-01-18 10:09:49.718965-0500 Runner[18025:4422908] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
> 2021-01-18 10:09:49.721780-0500 Runner[18025:4422522] flutter: [BackgroundFetch] Event received: flutter_background_fetch
> 
> 2021-01-18 10:09:49.724999-0500 Runner[18025:4422308] [TSBackgroundFetch finish] flutter_background_fetch (1 of 1)
> 2021-01-18 10:09:49.725129-0500 Runner[18025:4422308] Marking simulated task complete: <BGAppRefreshTask: com.transistorsoft.fetch>
> 
> (lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.customtask"]
> 2021-01-18 10:11:56.744275-0500 Runner[18025:4422308] Simulating launch for task with identifier com.transistorsoft.customtask
> 2021-01-18 10:11:59.363063-0500 Runner[18025:4423621] Starting simulated task: <decode: missing data>
> 2021-01-18 10:11:59.364461-0500 Runner[18025:4422522] flutter: [BackgroundFetch] Event received: com.transistorsoft.customtask
> 2021-01-18 10:11:59.367042-0500 Runner[18025:4422308] Marking simulated task complete: <BGProcessingTask: com.transistorsoft.customtask>
> 2021-01-18 10:11:59.369634-0500 Runner[18025:4422308] [TSBGTask destroy] com.transistorsoft.customtask
> ```

example IPhone real machine test is unsuccessful

**Comment by christocracy** [comment]
Your logs show a **successful** test.
