### ISSUE TITLE
[BUG] app terminated state, cannot get class objects.

### ISSUE THREAD

**Issue by saravananmnm** [transistorsoft/flutter_background_fetch#152]
CollectionDeliveryRepository repository; 
SaveOrdersDetailsDAO saveOrdersDetailsDAO; 
OrdersMasterDAO ordersMasterDAO;

these objects not able get already Injected singleton objects, while app is killed state.
i'm using kiwi dependency injection.

```dart
/// This "Headless Task" is run when app is terminated.
 void backgroundFetchHeadlessTask(String taskId)async {
   CollectionDeliveryRepository repository;
   SaveOrdersDetailsDAO saveOrdersDetailsDAO;
   OrdersMasterDAO ordersMasterDAO;
  print("[BackgroundFetch onTerminate] Headless event received: $taskId");
  DateTime timestamp = DateTime.now();
  // Read fetch_events from SharedPreferences
  // Add new event.
  if (await Utils.onCheckNetworkConnection()) {
    var orders = await ordersMasterDAO.getAllOrders(StringConstant.POD);
    var syncData = await saveOrdersDetailsDAO.getAllOrderDetails(orders);
    var savedOrders = await getSavedOrderDetails(repository, syncData,orders);
    pushAllSavedOrders(
        savedOrders, repository, ordersMasterDAO, saveOrdersDetailsDAO);
  }
  BackgroundFetch.finish(taskId);
}
```

**Comment by saravananmnm** [comment]
2020-09-14 21:48:47.625 11069-11105/com.courier_alliance.driver.dev E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'getAllOrders' was called on null.
    Receiver: null
    Tried calling: getAllOrders("STY10")
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
    #1      backgroundFetchHeadlessTask (package:courier_alliance/src/service/backgroundservice.dart:25:40)
    <asynchronous suspension>
    #2      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:619:15)
    #3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:432:55)
    #4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:385:33)
    #5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
    #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
    #7      _rootRun (dart:async/zone.dart:1190:13)
    #8      _CustomZone.run (dart:async/zone.dart:1093:19)
    #9      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
    #10     _invoke3 (dart:ui/hooks.dart:281:10)
    #11     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)

**Comment by christocracy** [comment]
You have ignored the issue template.  Edit your post and provide the following information that was requested:

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by saravananmnm** [comment]
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1082], locale en-IN)
    • Flutter version 1.20.2 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Genymotion 9 0 New (mobile) • 192.168.241.101:5555 • android-x86 • Android 9 (API 28)

• No issues found!

**Comment by christocracy** [comment]
>**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by christocracy** [comment]
Instead of adding noise to the issue by posting new messages **UPDATE** your original post.

**Comment by christocracy** [comment]
![](https://dl.dropbox.com/s/ybikpj0fo03firc/Screen%20Shot%202020-09-15%20at%2010.52.55%20AM.png?dl=1)

**Comment by ydotmalik** [comment]
Where are your objects stored? Whatever is in main() is not available within the headless event.

**Comment by christocracy** [comment]
I suggest you try the /example app in this repo.
