### ISSUE TITLE
Headless event passing taskId to flutter_background_fetch

### ISSUE THREAD

**Issue by shinewanna** [transistorsoft/flutter_background_fetch#154]
**To Reproduce**
Just Try headless event

I'm passing jsonEncode string to taskId, then i Decode the string to get my Object.
It's fine on normal background fetch, but in headless, the taskId is default "flutter_background_fetch" is showing.

It's normal or bug.
Can i get any way to get data in headless event?

**Comment by christocracy** [comment]
You are not providing your code.

**Comment by varunkamani** [comment]
Hi, @christocracy. I want to use this plugin just to execute the task when the app is in the background( I want to stop executing the task after the app gets killed). Will this plugin help me with that? (Android / iOS both)

**Comment by christocracy** [comment]
>Will this plugin help me with that?

Yes.

**Comment by christocracy** [comment]
Closed for ignoring issue template and providing no information.
