### ISSUE TITLE
Execution failed for task ':background_fetch:bundleDebugAar'.

### ISSUE THREAD

**Issue by TAREQ-AL-ABEDIN** [transistorsoft/flutter_background_fetch#155]
Execution failed for task ':background_fetch:bundleDebugAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :background_fetch project caused this error: /Users/annanovas/development/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.4/android/libs/tsbackgroundfetch-0.4.2.aar

I have tried the soultion you provided at this link:
https://github.com/transistorsoft/flutter_background_fetch/issues/99#issuecomment-602047128

But didn't able to solve the issue

**Comment by christocracy** [comment]
- You’ve ignored the issue template.
- see the CHANGELOG

**Comment by christocracy** [comment]
Also, please *search your error* **before** posting a new issue.

Duplicate #122
