### ISSUE TITLE
Periodic Task run at the same time every day

### ISSUE THREAD

**Issue by MichaelCodesThings** [transistorsoft/flutter_background_fetch#156]
I might of missed how this can be done in the docs. I am wondering how I could use this to run a task every day at the same time. I know I can set the minimumFetchInterval to 24 hours. However will it always run at say 03:00? Even if the user turns their phone off and on throughout the day. Is there a way to start the intervals at a specific time rather than when you initially run the config. Thank you for any help.

**Comment by christocracy** [comment]
Just use `scheduleTask` and calculate the interval yourself based on current time on device.

**Comment by MichaelCodesThings** [comment]
Hi, still confused. So I run the BackgroundFetchConfig with say a 24 hour interval time. Then when that happens I set a scheduleTask with a delay so it always goes off at 03:00? scheduleTask is a "oneshot" thing no?

**Comment by christocracy** [comment]
See API docs [scheduleTask](https://pub.dev/documentation/background_fetch/latest/background_fetch/BackgroundFetch/scheduleTask.html)

![](https://dl.dropbox.com/s/6e5tghc6wld298v/Screen%20Shot%202020-10-04%20at%207.10.25%20PM.png?dl=1)

If you call `scheduleTask` with a `taskId` that already exists, the existing *one-shot* will be cancelled and the new one scheduled.

**Comment by MichaelCodesThings** [comment]
I apologise in advance, I'm quite lost in how this package works it seems.

So the example has a background task running every 15 minutes (as that's the minimum android allows).
Every 15 minutes the code inside the configure will run, ok.
If I want a particular task to run at 03:00 every single day indefinitely you've suggested to use the scheduleTask method.

The configure and scheduleTask methods are only run when the app is actually open like in the example (in the initPlatformState method). If the app remains closed for several days, I still want to schedule that task to be complete at 03:00 every day, but the scheduleTask method won't be invoked.

Sorry to ask, are you able to show an example? Of how I could get a task to run once a day, every day (even if app remands closed for days on end) at say 03:00 in the morning. And that's all, only one task a day needs to happen. 

Would be a huge help if you could as I do want to use this package in my app, I'm just struggling to understand it properly :(

**Comment by christocracy** [comment]
On iOS it will be impossible to run a task “every day” at some particular time.

**Comment by MichaelCodesThings** [comment]
Ah I see, is it possible to have it roughly run between a few hours around that time?

**Comment by christocracy** [comment]
- If the user terminated your app, iOS will no longer fire any events, *at all*.
- it’s completely up to iOS’ own secret algorithm when events are fired.  This algorithm is presumably based upon how often the user interacts with your app.
- if the user doesn’t open your app *daily*, I’ve found that iOS **completely stops** firing events.

**Comment by MichaelCodesThings** [comment]
Did not realise that for iOS, bit annoying. Is it possible to do the daily task on Android?

**Comment by christocracy** [comment]
> Is it possible to do the daily task on Android.

Yes.  Use `scheduleTask`.  Experiment with it.

**Comment by MichaelCodesThings** [comment]
But this is where I'm struggling to see how that works? Was hoping for a bit of help on the matter.

**Comment by christocracy** [comment]
Show me your code (just the code where you’re using the plugin, not your *entire* component)

**Comment by MichaelCodesThings** [comment]
// Configure BackgroundFetch.
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15, 
        stopOnTerminate: false,
        enableHeadless: false,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE
    ), (String taskId) async {
      print("[BackgroundFetch] taskId: $taskId");
      switch (taskId) {
        case "my.custom.task":
          print('My custom task fired');
          break;
        default:
          print("Background Fetch event fired");
      }

      BackgroundFetch.finish(taskId);
    });

    // Calculated delay until 03:00. For testing just 15 minutes
    int delayMilliseconds = 900000;

    // Scheduled task events will be fired into the Callback provided to #configure method above.
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "my.custom.task",
        delay: delayMilliseconds,
        periodic: false
    ));


The code snippet feature in github doesn't seem to be working right, sorry for raw text format.

This snippet has the background fetch running every 15 minutes. I'm not sure how to get the scheduleTask to run every day at the calculated time. As I've delayed it by so much so it will run at 03:00. But if I say periodic to get it repeating, that won't be every 24 hours. So I need a new schduleTask to be create every day no?

**Comment by christocracy** [comment]
Do not *test* with a large interval provided to `scheduleTask`.  First test with a *small* interval, like 5s (`delay: 5000`)

**Comment by christocracy** [comment]
```
int delayMilliseconds = 900000;
```
This obviously isn’t going to schedule a task for 3:00 every day.

You need to calculate the difference in milliseconds between *current time* and *target time*.  That is your `delay`.

**Comment by MichaelCodesThings** [comment]
Is it right to create a new scheduleTask inside of the custom task for the next days task? As this is a one time task from when the user runs the app.

I put 900000 for testing as I originally thought I could only delay it by the minimum amount android would allow of every 15 minutes.

**Comment by christocracy** [comment]
> Is it right to create a new scheduleTask inside of the custom task for the next days task?

Yes, of course.

See api docs `scheduleTask` and `forceAlarmManager`.

**Comment by christocracy** [comment]
```
taskId: "my.custom.task"
```

It’s expected you’ll name your tasks accordingly, rather than using the default *example name*.

**Comment by MichaelCodesThings** [comment]
Of course with the name of the task. I've just named it that for testing and example purposes. 

`(String taskId) async {
      print("[BackgroundFetch] taskId: $taskId");
      switch (taskId) {
        case "my.custom.task":
          print('My custom task fired');
          BackgroundFetch.scheduleTask(TaskConfig(
              taskId: "my.custom.task2",
              delay: 10000,
              periodic: false
          ));
          // Send notification here
          break;
        case "my.custom.task2":
          print('My custom task fired 2');
          // Send notification here
          
          // No more scheduled tasks
          break;
        default:
          print("Background Fetch event fired");
      }

      BackgroundFetch.finish(taskId);
    });

    
    int delayMilliseconds = 10000;

    // Scheduled task events will be fired into the Callback provided to #configure method above.
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "my.custom.task",
        delay: delayMilliseconds,
        periodic: false
    ));`

I've got a test here where a task is scheduled after 10 seconds "my.custom.task".
When this fires, another scheduledTask is created but this time for "my.custom.task2"

Each task will send a notification, I've just commented send notification for ease of example.
When I tested this with the app open. The notifications appeared correctly, one after 10 seconds and the other 10 seconds after the first.

However, if I close the app after the first notification has appeared, the second never comes. As if the app needs to be open for the scheduled task to work?

**Comment by christocracy** [comment]
See api docs `enableHeadless`.  See it to `true` and register your headless task.

**Comment by MichaelCodesThings** [comment]
So I've registered the headlessTask like the example:

`BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);`

Inside that headless task is like so:

`
// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask(String taskId) async {
  print('[BackgroundFetch] Headless event received.');
  BackgroundFetch.scheduleTask(TaskConfig(
      taskId: "my.custom.task",
      delay: 10000,
      enableHeadless: true
  ));
// Send notification here
BackgroundFetch.finish(taskId);
}`

And the configure now looks like so:

`// Configure BackgroundFetch.
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE
    ), (String taskId) async {
      print("[BackgroundFetch] taskId: $taskId");
      switch (taskId) {
        case "my.custom.task":
          print('My custom task fired');
          backgroundFetchHeadlessTask(taskId);
          break;
        default:
          print("Background Fetch event fired");
      }
      BackgroundFetch.finish(taskId);
    });


    int delayMilliseconds = 10000;

    // Scheduled task events will be fired into the Callback provided to #configure method above.
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "my.custom.task",
        delay: delayMilliseconds,
        enableHeadless: true
    ));
`

The notifications stop after closing the app still. What am I missing?

**Comment by christocracy** [comment]
Please [learn to use syntax highlighting](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks).  Just Google “*Github syntax highlighting*”.

**Comment by MichaelCodesThings** [comment]
Have fixed issues

**Comment by christocracy** [comment]
>Have fixed issues

So the issue is *closed*?

Don't call your `headlessTask` like this:

```
  print('My custom task fired');
  backgroundFetchHeadlessTask(taskId);
```

Look what you're doing:  you have each callback calling `BackgroundFetch.finish(taskId)`.  You're calling it twice.

Also, the API for the headless-task is going to change in the next release.  It's soon going to accept and event-object `HeadlessEvent event` instead of `String taskId` and your code will break.

**Comment by MichaelCodesThings** [comment]
Sorry meant have fixed the syntax highlighting issues for this feed.

I think I've got a solution working... for now. When is the next release happing with the changes?

**Comment by christocracy** [comment]
>When is the next release happing with the changes?

Soon.  The change is simply an `onTimeout` event-handler, a signal from the native side that your task is about to timeout and that you should finish what you're doing *immediately* and call `BackgroundFetch.finish(taskId)`.
