### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LucasGeek** [transistorsoft/flutter_background_fetch#157]
**ERROR BUILD APK**

* Plugin version:
0.6.0

* Platform: iOS or Android
Android

* OS version:
Mac OS Catallina 10.15.5 (19F101)

* Device manufacturer / model:
Samsung s10

* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel unknown, 1.20.4, on Mac OS X 10.15.5 19F101, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Connected device (3 available)

* Plugin config
BackgroundFetch.configure(
      BackgroundFetchConfig(
        minimumFetchInterval: 15,
        forceAlarmManager: true,
        startOnBoot: true,
        enableHeadless: true,
        stopOnTerminate: false,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.ANY,
      ),
      (String taskId) async {
        try {
          debugPrint("=================> EXECUTANDO TASK BACKGROUND <=================");
          debugPrint("[BackgroundFetch] Event received $taskId");

          var repository = AppRepository();

          var genericT = await repository.updateTokenFirebase();
          var genericS = await repository.verifySendingData();
          var genericL = await repository.verifyEnviarLocal();

          debugPrint(genericL.message);

          if (genericL.success) {
            await notificationService.showNotificationStatic();

            var generic = await repository.enviarLocal();
            debugPrint(generic.message);

            await notificationService.cancelAll();
          }

          if (genericS.success) {
            await notificationService.showNotificationStatic();

            await repository.enviarEnviromental();
            await repository.enviarQuest();

            await notificationService.cancelAll();
          }

          BackgroundFetch.finish(taskId);
        } catch (e, s) {
          Crashlytics.instance.recordError(e, s, context: 'ERROR [BackgroundFetch]');
        }
      },
    ).then((int status) {
      debugPrint('[BackgroundFetch] configure success: $status');
    }).catchError((e, s) {
      Crashlytics.instance.recordError(e, s, context: '[BackgroundFetch] configure ERROR: $e');
      debugPrint('[BackgroundFetch] configure ERROR: $e');
    });

**To Reproduce**
1. Configure plugin in project
2. Build apk --release
3. Erro first screen (looping)

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`
In debug mode there are no errors, only when generating the apk (build) for production. The application crashes on the first screen and is in infinite looping

**Additional context**
I've been using the plugin "background_fetch 0.6.0" created by you, for a long time, but since the last update I've been experiencing a problem when I build the apk. The apk installed on any device crashes and doesn't work, but this is only in release, when I'm in debug mode the plugin works perfectly. I need to update the plugin, because the "0.5.6" version of the "background_fetch" plugin generates an error:

=========

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void h.b.c.a.b.a (java.lang.String, h.b.c.a.b $ a)' on a null object reference
       at io.flutter.plugin.common.MethodChannel.a (MethodChannel.java:14)
       at io.flutter.plugins.pathprovider.PathProviderPlugin.a (PathProviderPlugin.java:26)
       at br.com.ama.agente_municipal_ambiental.Application.registerWith (Application.java:14)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate (HeadlessTask.java:122)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch (HeadlessTask.java:4)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run (HeadlessTask.java)
       at android.os.Handler.handleCallback (Handler.java:789)
       at android.os.Handler.dispatchMessage (Handler.java:98)
       at android.os.Looper.loop (Looper.java:164)
       at android.app.ActivityThread.main (ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke (Method.java)
       at com.android.internal.os.Zygote $ MethodAndArgsCaller.run (Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

=========

**Comment by christocracy** [comment]
Show me the following files:

- `Application.java`
- `android/build.gradle`
- `AndroidManifest.xml` (redact any of your API keys as necessary)

**Comment by LucasGeek** [comment]
- Application.java // Application.kt

package br.com.ama.agente_municipal_ambiental

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.pathprovider.PathProviderPlugin
import io.flutter.view.FlutterMain
import rekab.app.background_locator.LocatorService
import com.tekartik.sqflite.SqflitePlugin
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import io.flutter.plugins.GeneratedPluginRegistrant 
import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterMain.startInitialization(this)

        LocatorService.setPluginRegistrant(this)
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
        BackgroundFetchPlugin.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry) {
        if (!registry!!.hasPlugin("io.flutter.plugins.pathprovider")) {
            PathProviderPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.pathprovider"))
        }

        if (!registry!!.hasPlugin("com.tekartik.sqflite.SqflitePlugin")) {
            SqflitePlugin.registerWith(registry.registrarFor("com.tekartik.sqflite.SqflitePlugin"))
        }
    }
}

- android/build.gradle

buildscript {
    ext.kotlin_version = '1.3.61'
    ext {
        compileSdkVersion   = 29
        targetSdkVersion    = 29
        supportLibVersion   = "1.0.2"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.31.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

- AndroidManifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="br.com.ama.agente_municipal_ambiental">

    <uses-permission android:name="android.permission.CALL_PHONE" android:required="true" />
    <uses-permission android:name="android.permission.INTERNET" android:required="true" />
    <uses-permission android:name="android.permission.CAMERA" android:required="true" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" android:required="true" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" android:required="true" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:required="true" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
        android:requestLegacyExternalStorage="true"
        android:name=".Application"
        android:label="ama"
        android:icon="@mipmap/ic_launcher">

        <meta-data android:name="com.google.android.geo.API_KEY"
            android:value="api-key"/>

        <meta-data android:name="io.flutter.network-policy"
            android:resource="@xml/network_security_config"/>
            
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>

        <receiver
            android:name="rekab.app.background_locator.LocatorBroadcastReceiver"
            android:enabled="true"
            android:exported="true"
            />








        <service
            android:name="rekab.app.background_locator.LocatorService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="true"
            />
        <service
            android:name="rekab.app.background_locator.IsolateHolderService"
            android:permission="android.permission.FOREGROUND_SERVICE"
            android:exported="true"
            />

        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />

        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <provider
            android:name="vn.hunghd.flutterdownloader.DownloadedFileProvider"
            android:authorities="${applicationId}.flutter_downloader.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"/>
        </provider>

        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:enabled="false"
            android:exported="false"
            tools:node="remove"/>

        <provider
            android:name="vn.hunghd.flutterdownloader.FlutterDownloaderInitializer"
            android:authorities="${applicationId}.flutter-downloader-init"
            android:exported="false">
            <meta-data
                android:name="vn.hunghd.flutterdownloader.MAX_CONCURRENT_TASKS"
                android:value="5" />
        </provider>

        <meta-data android:name="flutterEmbedding" android:value="2"/>
    </application>
</manifest>

**Comment by christocracy** [comment]
You are not supposed to use `setPluginRegistrant` anymore with latest Flutter.  See the [Setup in API docs](https://pub.dev/documentation/background_fetch/latest/background_fetch/BackgroundFetch/registerHeadlessTask.html).  You **don't even need to**  provide a custom `Application.java` / `Application.kotlin` anymore ever since Flutter `1.12`.

![](https://dl.dropbox.com/s/k3mhinu906o51qz/Screen%20Shot%202020-10-05%20at%209.15.20%20AM.png?dl=1)

>Flutter (Channel unknown, 1.20.4

You are using Flutter `1.20.4`, which **IS** `>= 1.12`.

Also, I see you're not using my [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation).

**Comment by LucasGeek** [comment]
But I have dependencies on other plugins that I need to run on this "registerWith". And how is it for me to use the FlutterFirebaseMessagingService setPluginRegistrant? This documentation says that I don't need to use "Application.kt" anymore, but it doesn't show how I can do it with other apps that need this configuration.

**Comment by christocracy** [comment]
How you manage your other plugin is up to you but with my plugin, you do **not** do this:

```
BackgroundFetchPlugin.setPluginRegistrant(this)
```

Get rid of it.

>I have dependencies on other plugins that I need to run on this "registerWith"

I suggest you see if your other plugin have upgraded to [the new Flutter Plugin API](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration).
