### ISSUE TITLE
[BUG] Plugin doesn't work on IOS 14 devices

### ISSUE THREAD

**Issue by racacere** [transistorsoft/flutter_background_fetch#158]
**Your Environment**
* Plugin version: 0.6.0
* Platform: iOS
* OS version: 14
* Device manufacturer / model: Reproduced on Iphone 7 and Iphone X
* Flutter info (`flutter info`, `flutter doctor`): 
```
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.7 19H2, locale en-CL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
```
* Plugin config
```Dart
BackgroundFetch.configure(BackgroundFetchConfig(
    minimumFetchInterval: 15,
    stopOnTerminate: false,
    enableHeadless: false,
    requiresBatteryNotLow: false,
    requiresCharging: false,
    requiresStorageNotLow: false,
    requiresDeviceIdle: false,
    requiredNetworkType: NetworkType.NONE
)
```
**To Reproduce**
1. Create a new Flutter project
2. Follow all configuration steps from the docs
3. Copy plugin's example project code on the main.dart file
4. Run the project on IOS
5. On the logs the config is successful but the background fetch event aren't showed on the principal screen `Listview` and aren't printed on the terminal.

**Debug logs**
- ios Flutter debug logs,
```
Launching lib/main.dart on iPhone 7 in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXX
Xcode build done.                                           31.5s
Connecting to VM Service at ws://localhost:57336/ws
flutter: [BackgroundFetch] configure success: 2
flutter: [BackgroundFetch] stop success: 2
flutter: [BackgroundFetch] start success: 2
flutter: [BackgroundFetch] stop success: 2
flutter: [BackgroundFetch] start success: 2
Application finished.
Exited (sigterm)
```

```
2020-10-07 12:16:03.572628-0300 Runner[914:268242] [TSBackgroundFetch load]: (
)
2020-10-07 12:16:03.573143-0300 Runner[914:268242] [TSBGAppRefreshSubscriber load]: {
    "flutter_background_fetch" = "<TSBGAppRefreshSubscriber identifier=flutter_background_fetch, executed=0, enabled=1>";
}
2020-10-07 12:16:03.791521-0300 Runner[914:268242] Metal API Validation Enabled
2020-10-07 12:16:04.142096-0300 Runner[914:268588] flutter: Observatory listening on http://127.0.0.1:60297/ICx4IdvmBps=/
2020-10-07 12:16:04.848211-0300 Runner[914:268242] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2020-10-07 12:16:05.502821-0300 Runner[914:268581] flutter: [BackgroundFetch] configure success: 2
2020-10-07 12:16:19.354455-0300 Runner[914:268242] [TSBackgroundFetch stop] (null)
2020-10-07 12:16:19.357333-0300 Runner[914:268581] flutter: [BackgroundFetch] stop success: 2
2020-10-07 12:16:20.483117-0300 Runner[914:268242] [TSBackgroundFetch start] (null)
2020-10-07 12:16:20.483393-0300 Runner[914:268242] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2020-10-07 12:16:20.527200-0300 Runner[914:268581] flutter: [BackgroundFetch] start success: 2
2020-10-07 12:16:24.290547-0300 Runner[914:268242] [TSBackgroundFetch stop] (null)
2020-10-07 12:16:24.291996-0300 Runner[914:268581] flutter: [BackgroundFetch] stop success: 2
2020-10-07 12:16:25.136801-0300 Runner[914:268242] [TSBackgroundFetch start] (null)
2020-10-07 12:16:25.137053-0300 Runner[914:268242] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2020-10-07 12:16:25.139434-0300 Runner[914:268581] flutter: [BackgroundFetch] start success: 2

```
**Additional context**
We detect that issue when our production app started to fails on execute `background_fetch` headless tasks on IOS 14 devices, one of this tasks has been configured using `flutter_background_geolocation` and others using just `background_fetch`.  To discard internal issues on our app, we tested `background_fetch` on a new clean flutter project using the docs example app and its works fine on Android devices, but it fails on IOS 14 devices.

**Comment by christocracy** [comment]
I don't see an issue here.  How are you *simulating* fetch events?

**Comment by racacere** [comment]
Sending app to background (not kiliing the app, just "minimize" it or blocking device). Before IOS 14, our app tracks position of the user and run background fetch tasks on this scenarios on both platforms without problems. Now the Android version works fine but in IOS the headless tasks aren't executed.

**Comment by christocracy** [comment]
>but in IOS the headless tasks aren't executed.

There's no such thing as "*headless tasks for iOS*".  That's an Android-only mechanism.

**Comment by racacere** [comment]
We have the following code to `background_fetch` and `flutter_background_geolocation` tasks, it worked fine on both platforms for about a year, until IOS 14. Maybe we configured that on a wrong way for IOS and it worked fine just for good luck.

The expected behavior is every time that a user sends app to background or block device, track his location (sending it to our backend) and execute a oneshot for some background tasks. We think that a way to accomplish this in IOS is define the tasks as `scheduleTask`, but we not sure about what value set on the `delay` parameter to get the expected behavior described above.

Can you help us with that?

```Dart
// Tasks registration
void main() {
  runApp(MyApp());
  bg.BackgroundGeolocation.registerHeadlessTask(headlessTask);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask2);
}

// Background Fetch config
BackgroundFetchConfig(
      minimumFetchInterval: 20,
      stopOnTerminate: false,
      enableHeadless: true,
      requiresBatteryNotLow: false,
      requiresCharging: false,
      requiresStorageNotLow: false,
      requiresDeviceIdle: false,
      requiredNetworkType: NetworkType.ANY
)

// Flutter Background Geolocation config
bg.BackgroundGeolocation.ready(bg.Config(
    desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
    distanceFilter: 30.0,
    stopOnTerminate: false,
    foregroundService: true,
    startOnBoot: true,
    logLevel: bg.Config.LOG_LEVEL_ERROR,
    reset: true,
    locationAuthorizationRequest: 'Always',
    enableHeadless: true,
    notification: bg.Notification(
      layout: 'background_geolocation_notification_layout',
      title: 'text',
      text: 'text',
      sticky: false,
      priority: bg.Config.NOTIFICATION_PRIORITY_HIGH
    )
)).then((bg.State state) {
  if (!state.enabled) { 
    bg.BackgroundGeolocation.start();
  }
});
```

**Comment by christocracy** [comment]
```
BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask2);
```

- You can't register multiple headless-tasks.
- I don't see any call to `BackgroundFetch.configure(backgroundFetchConfig)`
- It makes no sense to think about `registerHeadlessTask` in an iOS app.
- iOS `scheduleTask` seems to run only when a device is connected to power.
- iOS halts **all** events to `background_fetch` when *user* terminates the device.
- If the user doesn't open the app *daily*, iOS halts *all* events to `background_fetch`

**Comment by racacere** [comment]
Ok, we will try to implement that behavior in another way for IOS. But one last question, if `flutter_background_geolocation` uses `background_fetch` for its execution, the app can't track the user location in the following the following cases?

> - iOS halts all events to background_fetch when user terminates the device.
> - If the user doesn't open the app daily, iOS halts all events to background_fetch

**Comment by christocracy** [comment]
>if flutter_background_geolocation uses background_fetch for its execution, the app can't track the user location

**NO!**.  `background_fetch` is *not crucial* to the `background_geolocation`'s core *Philosophy of Operation*.  It uses `background_fetch` only for some minor house-keeping.

**Comment by racacere** [comment]
Ok, thank for you help. We will remove the headless tasks registration from the IOS app and we will try again to test the background geolocation logic.
