### ISSUE TITLE
[BUG] background_fetch 0.6.0 Build failed.

### ISSUE THREAD

**Issue by kyounglee** [transistorsoft/flutter_background_fetch#161]
**Your Environment**
* Plugin version: 0.6.0
* Platform: flutter dev. environment (iOS or Android)
* OS version:  
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**

1. include module : add background_fetch:^ 0.6.0 to pubspec.xml

2. insert example code of  background_fetch to main.dat in any existing project.
  ( didn't do anything except that)

import 'package:background_fetch/background_fetch.dart';

void backgroundFetchHeadlessTask(String taskId) async {
  print('=== [BackgroundFetch] Headless event received.');
  BackgroundFetch.finish(taskId);
}

Future main() async {
   ::
   ::
   BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}

3. After that, build step produces FAILURE like the following:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:minifyReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/D:/flutter/CherryTalk/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - http://devrepo.kakao.com:8088/nexus/content/groups/public/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Running Gradle task 'bundleRelease'...                             28.3s
Gradle task bundleRelease failed with exit code 1
Process finished with exit code 1

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

I'd like to know the next step to overcome this failure.

**Comment by christocracy** [comment]
Where’s the evidence?  Stacktrace?

**Comment by kyounglee** [comment]
This is not a runtime failure, a build step failure in flutter project using Android studio.

C:\flutter\bin\flutter.bat --no-color build appbundle
Running Gradle task 'bundleRelease'...  

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:minifyReleaseWithR8'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
   
    I ommited.. : the same as the above ones.

**Comment by christocracy** [comment]
You did not carefully follow the setup instructions.  Go back to the readme and follow the setup.

**Comment by kyounglee** [comment]
I've reread your readme again.
I found different versions are registered in your guide,  0.6.0 in title, 0.5.1 in Readme and 0.6.0 in Installing menu.
But not any thing specials.

Can you teach me what I am missing? (Reproducing step is simple as I mentioned)

**Comment by christocracy** [comment]
Don’t follow the version mentioned in readme, I always forget to manually update that.  Follow what https://pub.dev says is latest version.

**Comment by christocracy** [comment]
Duplicate #131

**Comment by kyounglee** [comment]
Thanks. I will follow that.
