### ISSUE TITLE
[BUG] Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected

### ISSUE THREAD

**Issue by HasanAlqaisi** [transistorsoft/flutter_background_fetch#162]
* Plugin version: 0.6.0
* Platform: Android
* OS version: Ubuntu 20.04.1 LTS
* Device manufacturer / model: Note 9
* Flutter info (`flutter info`, `flutter doctor`):
```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

```
* Plugin config
```
BackgroundFetch.configure(
                    BackgroundFetchConfig(
                      minimumFetchInterval: 60,
                      stopOnTerminate: false,
                    ), (String taskId) async {
                  switch (taskId) {
                    case 'com.hraa.weatherTask':
                    print('test');
                      break;
                    default:
                      break;
                  }
                  BackgroundFetch.finish(taskId);
                });
                BackgroundFetch.scheduleTask(TaskConfig(
                    taskId: "com.hraa.weatherTask",
                    stopOnTerminate: false,
                    startOnBoot: true,
                    enableHeadless: true,
                    delay: 10000, // milliseconds
                    periodic: true));
```

**Additional context**
After following the android setup I got this error:

e: ../the_weather/Application.kt: (16, 44): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org**

And here's my Application class code:

```
package com.example.the_weather

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
  override fun onCreate() {
    super.onCreate();
    BackgroundFetchPlugin.setPluginRegistrant(this);
  }

  override fun registerWith(registry: PluginRegistry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

**Comment by christocracy** [comment]
Where did you find the instructions to perform setup in a custom `Application.kt`?

**Comment by HasanAlqaisi** [comment]
> Where did you find the instructions to perform setup in a custom `Application.kt`?

I found it in the plugin page (setup guides) which direct me to this page : [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)

**Comment by christocracy** [comment]
You did not correctly follow the Setup.

According to your `$ flutter doctor`:

>Flutter (Channel stable, 1.22.2

Is `1.22.2` *greater than* or *less than* `1.12`?

![](https://dl.dropbox.com/s/67m5twdemay7zp5/Screen%20Shot%202020-10-24%20at%2012.56.49%20PM.png?dl=1)

**Comment by HasanAlqaisi** [comment]
Oh sorry, I haven't noticed this.. Thanks for replying
