### ISSUE TITLE
[BUG] [TSBackgroundFetch scheduleTask] ERROR:  Failed to submit task request: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"

### ISSUE THREAD

**Issue by misici234** [transistorsoft/flutter_background_fetch#163]
**Your Environment** Mac
* Plugin version: the latest from your GitHub repo
* Platform: iOS
* OS version: 13.6
* Device manufacturer / model: iPhone 11 simulator
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.5 19F101, locale en-CA)
    • Flutter version 1.22.0 at /Users/borismisic/Developer/SDKs/flutter
    • Framework revision d408d302e2 (4 weeks ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/borismisic/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 (mobile)                 • 265C0D76-578B-4365-87E7-B04FFE5B8834 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    ! Error: Boris’s iPhone is not connected. Xcode will continue when Boris’s iPhone is connected. (code -13)

• No issues found!

* Plugin config

**To Reproduce**
1. Downloaded your project from GitHub 
2. Opened example project in Android Studio
3. Run the project in iPhone 11 simulator
4. As soon as it starts I get 
Syncing files to device iPhone 11...
[TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
[TSBackgroundFetch scheduleProcessingTask] <TSBGTask identifier=com.transistorsoft.customtask, delay=10, periodic=0 enabled=0>
[TSBackgroundFetch scheduleTask] ERROR:  Failed to submit task request: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"
flutter: [BackgroundFetch] configure success: 2
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(1, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      BackgroundFetch.scheduleTask (package:background_fetch/background_fetch.dart:475:33)
#4      _MyAppState.initPlatformState (package:background_fetch_example/main.dart:109:21)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:<…>

**Debug logs**
- ios XCode logs, 
2020-10-24 23:34:26.106372-0400 Runner[21379:157852] [TSBackgroundFetch load]: (
)
2020-10-24 23:34:26.107018-0400 Runner[21379:157852] [TSBGAppRefreshSubscriber load]: {
    "flutter_background_fetch" = "<TSBGAppRefreshSubscriber identifier=flutter_background_fetch, executed=0, enabled=1>";
}
2020-10-24 23:34:26.351758-0400 Runner[21379:157852] [TSBackgroundFetch registerForTaskWithIdentifier: com.transistorsoft.customtask
2020-10-24 23:34:26.384306-0400 Runner[21379:158335] flutter: Observatory listening on http://127.0.0.1:59817/sNKjaf6vguQ=/
2020-10-24 23:34:27.206639-0400 Runner[21379:157852] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
2020-10-24 23:34:27.207224-0400 Runner[21379:157852] [TSBackgroundFetch scheduleProcessingTask] <TSBGTask identifier=com.transistorsoft.customtask, delay=10, periodic=0 enabled=0>
2020-10-24 23:34:27.207426-0400 Runner[21379:157852] [TSBackgroundFetch scheduleTask] ERROR:  Failed to submit task request: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"
2020-10-24 23:34:27.208315-0400 Runner[21379:158314] flutter: [BackgroundFetch] configure success: 2
2020-10-24 23:34:27.211172-0400 Runner[21379:158314] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(1, null, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      BackgroundFetch.scheduleTask (package:background_fetch/background_fetch.dart:475:33)
#4      _MyAppState.initPlatformState (package:background_fetch_example/main.dart:109:21)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#12     _rootRun (dart:async/zone.dart:1190:13)
#13     _CustomZone.run (dart:async/zone.dart:1093:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
2020-10-24 23:34:32.256889-0400 Runner[21379:158317] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
See the warning in *Debugging* section in readme about simulating tasks in iOS sim, that it doesn't work.

**Comment by loonix** [comment]
I get this issue when running in debug modey on my physical Iphone 14.

**Comment by christocracy** [comment]
> BGTaskSchedulerErrorDomain Code=1 

See iOS Docs:  [`BGTaskSchedulerErrorCodeUnavailable`](https://developer.apple.com/documentation/backgroundtasks/bgtaskschedulererrorcode/bgtaskschedulererrorcodeunavailable?language=objc)

<img width="964" alt="Screenshot 2023-06-29 at 12 16 19 PM" src="https://github.com/transistorsoft/flutter_background_fetch/assets/14999/22a56dc8-16bf-45af-828f-6c747a7ce930">
