### ISSUE TITLE
[BUG] iOS Simulator Crash when BackgroundFetch.scheduleTask

### ISSUE THREAD

**Issue by eldarkk** [transistorsoft/flutter_background_fetch#168]
When im runing on ios(13.3 ) Simulator, getting Error exception:
<img width="981" alt="Снимок экрана 2020-11-09 в 18 09 16" src="https://user-images.githubusercontent.com/6400167/98539665-ee292c00-22b6-11eb-89fe-5a804682b7a9.png">

**Plugin version:** background_fetch: '^0.5.1'
**Platform:** iOS
**OS version:** 13.3
**Device manufacturer / model:** Simulator iphone 8
**Flutter Doctor**
MacBook-Pro:flutter-app user$ flutter doctor -v
Unable to find any JVMs matching version "1.8".
Unable to find any JVMs matching version "1.8".
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.14.6 18G103, locale ru-KZ)
    • Flutter version 1.22.2 at /Users/user/flutter
    • Framework revision 84f3d28555 (4 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

⣯Unable to find any JVMs matching version "1.8".
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 14.0.2+12-46)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • A458694F-1CE6-4E1B-A222-339E140ACA95 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

**To Reproduce**
Code for scheduling background_fetch and customTask:
```dart
import 'dart:convert';
import 'dart:io';

import 'package:background_fetch/background_fetch.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'core/usecases/usecase.dart';
import 'domain/usecases/get_news_use_case.dart';
import 'injection_container.dart' as di;

const EVENTS_KEY = "fetch_events"; // for shared_preferences logger

// Android Headless handler, when app is terminated
void backgroundFetchHeadlessTask(String taskId) async {
  final bgManager = di.sl<BackgroundTaskManager>();
  final newsCount = await bgManager.getNews();
  updateSharedPreferences('Headless', taskId, newsCount);
  BackgroundFetch.finish(taskId);
}

class BackgroundTaskManager {
  BackgroundTaskManager._();
  factory BackgroundTaskManager() => _instance;
  static final BackgroundTaskManager _instance = BackgroundTaskManager._();

  Future<void> initPlatformState() async {
    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
    // Define background-fetch task
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 15,
                stopOnTerminate: false,
                enableHeadless: true,
                requiresBatteryNotLow: false,
                requiresCharging: false,
                requiresStorageNotLow: false,
                requiresDeviceIdle: false,
                requiredNetworkType: NetworkType.ANY),
            _onBackgroundFetch)
        .then((int status) {
      print('[BackgroundFetch] configure success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    });

    if (Platform.isIOS) {
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 5000,
          periodic: true,
          stopOnTerminate: false,
          requiredNetworkType: NetworkType.ANY));
    }
  }

  void _onBackgroundFetch(String taskId) async {
    final newsCount = await getNews();
    updateSharedPreferences('Background', taskId, newsCount);
    BackgroundFetch.finish(taskId);
  }

  Future<int> getNews() async {
    try {
      final useCase = di.sl<GetNewsUseCase>();
      final response = await useCase.call(NoParams());
      return response.fold((failure) {
        print(failure.toString());
        return -1;
      }, (success) {
        final map = success;
        if (map.keys.length > 0) {
          return map.keys.length;
        } else {
          return 0;
        }
      });
    } catch (ex) {
      print(ex.toString());
      return -1;
    }
  }
}

void updateSharedPreferences(String mode, String taskId, int count) async {
  DateTime timestamp = DateTime.now();
  SharedPreferences prefs = await SharedPreferences.getInstance();

  List<String> events = [];
  String json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  final str = "$timestamp: $mode, $taskId - $count";
  events.insert(0, str);
  print("\n===============\n$events\n===============");
  prefs.setString(EVENTS_KEY, jsonEncode(events));
}
```

**When i commented scheduleTask lines, crash has gone. 
When running on device im facing no crashes are there. Btw, is my code sufficiently good enough?**
```dart
   // if (Platform.isIOS) {
    //   BackgroundFetch.scheduleTask(TaskConfig(
    //       taskId: "com.transistorsoft.customtask",
    //       delay: 5000,
    //       periodic: true,
    //       stopOnTerminate: false,
    //       requiredNetworkType: NetworkType.ANY));
    // }
```

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
>Xcode 11.3.1, Build version 11C504

- You must use XCode 12.  The latest version of `background_fetch` implements the new iOS [`BGTaskScheduler`](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler?language=objc) API which didn't become available until XCode 12 (iOS 13).

![](https://dl.dropbox.com/s/o0mfrxs317xkwvh/Screen%20Shot%202020-11-09%20at%209.48.12%20AM.png?dl=1)

- Simulating `scheduleTask` does not work in the iOS SImulator.  See [Debugging](https://github.com/transistorsoft/flutter_background_fetch#-debugging) section in README:

![](https://dl.dropbox.com/s/6qsyw4oxewyalyw/Screen%20Shot%202020-11-09%20at%209.45.57%20AM.png?dl=1)
