### ISSUE TITLE
[BUG] Android headless task : E/AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by saravananmnm** [transistorsoft/flutter_background_fetch#170]
background_fetch: ^0.6.0

C:\Saravanan\Flutter_Sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)
    • Flutter version 1.22.1 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision f30b7f4db9 (5 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.courieralliance.driverca.dev, PID: 30160
    java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)
        at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onAttachedToEngine(FirebaseMessagingPlugin.java:60)
        at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(FirebaseMessagingPlugin.java:51)
        at com.courieralliance.driverca.Application.registerWith(Application.java:30)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by saravananmnm** [comment]
`public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {

    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
        LocatorService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        if (!registry.hasPlugin("com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin")) {
            BackgroundFetchPlugin.registerWith(registry.registrarFor("com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin"));
        }
        // I've only had to add this line to make it work
        if (!registry.hasPlugin("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin")) {
            FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        }
}
}`

**Comment by christocracy** [comment]
Why are Ignored issue template.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by saravananmnm** [comment]
C:\Saravanan\Flutter_Sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)
    • Flutter version 1.22.1 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision f30b7f4db9 (5 weeks ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by christocracy** [comment]
Where did you find instructions directing you to implement `BackgroundFetch` code in your custom `Application.java`?

**Comment by saravananmnm** [comment]
> Where did you find instructions directing you to implement `BackgroundFetch` code in your custom `Application.java`?

`class HeadLess {
  static String baseUrl = '';
  static String websoketUrl = '';
  static AppConfig config;
  static var container = KiwiContainer();

  static init(AppConfig mConfig) {
    config = mConfig;
    print('Base2: ${config.baseUrl ?? 'Empty'}');
  }

  static void backgroundFetchHeadlessTask(String taskId) async {
    DateTime timestamp = DateTime.now();
    print('Base: ${baseUrl ?? 'Empty'}');
    print("[BackgroundFetch onTerminate] Headless event received: $timestamp");
    container.clear();
    print('Base: ${baseUrl ?? 'Empty'}');
    await diConfig(null, baseUrl: baseUrl, webSocketUrl: websoketUrl);
    container = KiwiContainer();
    CustomLocationUpdates customLocationUpdates =
        container<CustomLocationUpdates>();
    CollectionDeliveryRepository repository =
        container<CollectionDeliveryRepository>();
    SaveOrdersDetailsDAO saveOrdersDetailsDAO =
        container<SaveOrdersDetailsDAO>();
    OrdersMasterDAO ordersMasterDAO = container<OrdersMasterDAO>();
    // Read fetch_events from SharedPreferences
    // Add new event.
    print('Headless Started ------------>');

    if (await Utils.onCheckNetworkConnection()) {
      if (await customLocationUpdates.getTrackUser()) {
        customLocationUpdates.updateDriverStatus(true);
        print('BG Location updated------------>');
      }

      var orders =
          await ordersMasterDAO.getAllOrders(ValueConstant.ORDER_UPLOADING);
      var syncData = await saveOrdersDetailsDAO.getAllOrderDetails(
          orders, ValueConstant.ORDER_UPLOADING);
      var savedOrders =
          await getSavedOrderDetails(repository, syncData, orders);
      print('BG Syncup updated------------>');
      if (savedOrders != null && savedOrders?.length != 0) {
        pushAllSavedOrders(
            savedOrders, repository, ordersMasterDAO, saveOrdersDetailsDAO);
      }
    }
    BackgroundFetch.finish(taskId);
  }
}`

`class HeadLess {
  static String baseUrl = '';
  static String websoketUrl = '';
  static AppConfig config;
  static var container = KiwiContainer();

  static init(AppConfig mConfig) {
    config = mConfig;
    print('Base2: ${config.baseUrl ?? 'Empty'}');
  }

  static void backgroundFetchHeadlessTask(String taskId) async {
    DateTime timestamp = DateTime.now();
    print('Base: ${baseUrl ?? 'Empty'}');
    print("[BackgroundFetch onTerminate] Headless event received: $timestamp");
    container.clear();
    print('Base: ${baseUrl ?? 'Empty'}');
    await diConfig(null, baseUrl: baseUrl, webSocketUrl: websoketUrl);
    container = KiwiContainer();
    CustomLocationUpdates customLocationUpdates =
        container<CustomLocationUpdates>();
    CollectionDeliveryRepository repository =
        container<CollectionDeliveryRepository>();
    SaveOrdersDetailsDAO saveOrdersDetailsDAO =
        container<SaveOrdersDetailsDAO>();
    OrdersMasterDAO ordersMasterDAO = container<OrdersMasterDAO>();
    // Read fetch_events from SharedPreferences
    // Add new event.
    print('Headless Started ------------>');

    if (await Utils.onCheckNetworkConnection()) {
      if (await customLocationUpdates.getTrackUser()) {
        customLocationUpdates.updateDriverStatus(true);
        print('BG Location updated------------>');
      }

      var orders =
          await ordersMasterDAO.getAllOrders(ValueConstant.ORDER_UPLOADING);
      var syncData = await saveOrdersDetailsDAO.getAllOrderDetails(
          orders, ValueConstant.ORDER_UPLOADING);
      var savedOrders =
          await getSavedOrderDetails(repository, syncData, orders);
      print('BG Syncup updated------------>');
      if (savedOrders != null && savedOrders?.length != 0) {
        pushAllSavedOrders(
            savedOrders, repository, ordersMasterDAO, saveOrdersDetailsDAO);
      }
    }
    BackgroundFetch.finish(taskId);
  }
}`

`void mainCommon(AppConfig config) async {
  WidgetsFlutterBinding.ensureInitialized();
  // Here would be background init code, if any
  CollectionDeliveryRepository repository;
  SaveOrdersDetailsDAO saveOrdersDetailsDAO;
  OrdersMasterDAO ordersMasterDAO;
  CustomLocationUpdates customLocationUpdates;

  await diConfig(config);
  HeadLess.baseUrl = config.baseUrl;
  HeadLess.websoketUrl = config.webSocketUrl;
  HeadLess.init(config);
  var container = KiwiContainer();
  if (Platform.isAndroid) {
    repository = container<CollectionDeliveryRepository>();
    saveOrdersDetailsDAO = container<SaveOrdersDetailsDAO>();
    ordersMasterDAO = container<OrdersMasterDAO>();
    customLocationUpdates = container<CustomLocationUpdates>();
    BackgroundService(repository, saveOrdersDetailsDAO, ordersMasterDAO,
        customLocationUpdates);
  }
  BackgroundFetch.registerHeadlessTask(HeadLess.backgroundFetchHeadlessTask);

 runApp(CourierAlliance(config));
  // Register to receive BackgroundFetch events after app is terminated.
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
}`

**Comment by christocracy** [comment]
That's not what I asked.  I asked you where **in the README** were you instructed to implement Java code for `BackgroundFetch` in a custom `Application.java` file?  I want to know **why** you did that.

**Comment by saravananmnm** [comment]
> ant to know **why** you did that.

Already i was commented on the top of this conversation.

**Comment by christocracy** [comment]
You are still *not* understanding my question.  I will ask again:

**WHY** did you implement code in `Application.java`.  Show me the link in this plugin's `README` **WHERE** you were instructed to implement Java code in your `Application.java`.

**Comment by saravananmnm** [comment]
> You are still _not_ understanding my question. I will ask again:
> 
> **WHY** did you implement code in `Application.java`. Show me the link in this plugin's `README` **WHERE** you were instructed to implement Java code in your `Application.java`.

Android setup

<img width="960" alt="bg" src="https://user-images.githubusercontent.com/23417457/98703657-bcd95a80-23a1-11eb-9303-74ec4dda61c2.png">

**Comment by christocracy** [comment]
The *link* I asked for is [here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#headless-mechanism-with-enableheadless-true).

Now:  What version of the Flutter SDK are you using?

**Comment by christocracy** [comment]
This is not a *meaningless* question in the Setup Guide:

![](https://dl.dropbox.com/s/ma45phqvru7cumk/Screen%20Shot%202020-11-10%20at%2011.47.11%20AM.png?dl=1)

**Comment by saravananmnm** [comment]
> The _link_ I asked for is [here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#headless-mechanism-with-enableheadless-true).
> 
> Now: What version of the Flutter SDK are you using?

[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18362.1139], locale en-IN)
• Flutter version 1.22.1 at C:\Saravanan\Flutter_Sdk\flutter
• Framework revision f30b7f4db9 (5 weeks ago), 2020-10-08 10:06:30 -0700
• Engine revision 75bef9f6c8
• Dart version 2.10.1

**Comment by christocracy** [comment]
Tell me *in your own words*:  **What version of the Flutter SDK are you using?**.

**Comment by saravananmnm** [comment]
> Tell me _in your own words_: **What version of the Flutter SDK are you using?**

 Flutter sdk version 1.22.1

**Comment by christocracy** [comment]
Now re-read the *Setup Guide* and follow the directions again.  Ask yourself: "*Is Flutter SDK `1.22.1` >= `1.12`?

![](https://dl.dropbox.com/s/5pqp5ofogsszysy/Screen%20Shot%202020-11-10%20at%2011.57.43%20AM.png?dl=1)

You have no business implementing any plugin code in `Application.java`.
