### ISSUE TITLE
Question: Are there any limits of background execution time?

### ISSUE THREAD

**Issue by masanag** [transistorsoft/flutter_background_fetch#173]
I’m planning on half an hour background tasks.
According to the following apple article, iOS have a background executing time limit (5 secs) by default.
[Extending Your App's Background Execution Time](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/extending_your_app_s_background_execution_time)

Can I execute half an hour tasks on background?

**Comment by christocracy** [comment]
iOS provides *exactly* 30 seconds of background-time to your callback.  That's it.  It cannot be extended.
