### ISSUE TITLE
ui_dart_state.cc(177)] Unhandled Exception: Null is not a valid value for the parameter 'error' of type 'Object'

### ISSUE THREAD

**Issue by mdridley** [transistorsoft/flutter_background_fetch#175]
**Your Environment**
* Plugin version: 0.6.0
* Platform: iOS
* OS version: 14.2
* Device manufacturer / model: iPhone 12 Pro Max (Simulator)
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.25.0-5.0.pre.54, on macOS 11.0.1 20B29 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (3 available)
* Plugin config
Using Example config

**To Reproduce**
1. Used example in ReadMe
2. Errors when calling:
```
BackgroundFetch.start().then((int status) {
                  print('[BackgroundFetch] start success: $status');
                }).catchError((e) {
                  print('[BackgroundFetch] start FAILURE: $e');
                });
```
3. Full error message:
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Null is not a valid value for the parameter 'error' of type 'Object'
#0      checkNotNullable (dart:_internal:382:5)
#1      _Completer.completeError (dart:async/future_impl.dart:21:5)
#2      BackgroundFetch.start.<anonymous closure>
package:background_fetch/background_fetch.dart:402
#3      _rootRunUnary (dart:async/zone.dart:1194:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:167:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:715:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:736:24)
#8      Future._completeError (dart:async/future_impl.dart:544:5)
#9      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#10     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
package:flutter/…/services/platform_channel.dart:1
<asynchronous suspension>

```

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by mdridley** [comment]
Debugging further, appears to be a platform exception. I have been able to confirm I followed the current iOS set up.

The error is because of 'completer.completeError(e.details);':
```
/// Start the background-fetch API.
  ///
  /// Your `callback` Function provided to [configure] will be executed each time a background-fetch event occurs. NOTE the [configure] method automatically calls [start]. You do not have to call this method after you first [configure] the plugin.
  ///
  static Future<int> start() {
    Completer completer = new Completer<int>();
    _methodChannel.invokeMethod('start').then((dynamic status) {
      completer.complete(status);
    }).catchError((dynamic e) {
      completer.completeError(e.details);
    });
    return completer.future;
  }
```
e.details is null, there should be a null check there. Still trying to figure out why the platform exception is happening. Possible iOS 14 issue?

**Comment by mdridley** [comment]
Platform Exception message code is 2, everything else is null
`PlatformException(2, null, null, null)`

**Comment by mdridley** [comment]
Can confirm, seems to be an issue with the iOS simulator 14+. Physical device is not throwing the error. Code handling should probably still be fixed as well.

**Comment by christocracy** [comment]
Will add `null` check in next release, thanks.
