### ISSUE TITLE
Application must extend android.app.Activity

### ISSUE THREAD

**Issue by itfuturz2020** [transistorsoft/flutter_background_fetch#177]
when i add a file 'Application.java', and add ".Application" in manifest file , it gives me 2 errors

`<activity
            android:name=".Application"`

it shows red line - `Application must extend android.app.Activity`
and in Application.java file

```
@Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
```

It shows and error in `registry` as 
```
Required type:
FlutterEngine
Provided:
PluginRegistry
```

I try to fix it by replace
`GeneratedPluginRegistrant.registerWith(registry);`
to
`GeneratedPluginRegistrant.registerWith((FlutterEngine) registry);`

but it crash my app so,
i dont know what to do with these 2 problems 
please help me to get out from this !

**Comment by christocracy** [comment]
Your app does not need a `registerWith` or `GeneratedPluginRegistrant.registerWith`.  You are doing something wrong.

See the [`Application.java` in /example](https://github.com/transistorsoft/flutter_background_fetch/tree/master/example/android/app/src/main/java/com/transistorsoft/flutter/backgroundfetch/backgroundfetchexample)
