### ISSUE TITLE
Background procssing task was not registered in AppDelegate didFinishLaunchingWithOptions

### ISSUE THREAD

**Issue by uc-dve** [transistorsoft/flutter_background_fetch#182]
**Your Environment**
* Plugin version: 0.6.0
* Platform: iOS
* OS version: 13.6
* Device manufacturer / model: iphone se
* Flutter info (`flutter info`, `flutter doctor`): flutter 1.22.2
* Plugin config

I have added two task id but still facing same issue. I have tried whole day but nothing happened. Please suggest me if i am missing something

![image](https://user-images.githubusercontent.com/28289763/106132876-8504d680-618a-11eb-91f5-6eb46fff8b37.png)

here is my AppDelegate.swift code

```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()
    //  if #available(iOS 10.0, *) {
    //   UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    // }
    GeneratedPluginRegistrant.register(with: self)
    UNUserNotificationCenter.current().delegate = self
    UIApplication.shared.setMinimumBackgroundFetchInterval(UIApplication.backgroundFetchIntervalMinimum)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
  
}
```
issue screenshot -
![image](https://user-images.githubusercontent.com/28289763/106132714-4cfd9380-618a-11eb-8656-fd1e443b7f24.png)

**Comment by christocracy** [comment]
>UIApplication.shared.setMinimumBackgroundFetchInterval(UIApplication.backgroundFetchIntervalMinimum)

Why are you doing this manually?  **Delete that line**.  `flutter_background_fetch` does this automatically.  Also, that is the [old *deprecated way* of enabling iOS fetch events](https://developer.apple.com/documentation/uikit/uiapplication/1623100-setminimumbackgroundfetchinterva?language=objc).  By using that line, you are disabling the new [`BGAppRefeshTask`](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtask?language=objc) API.

Here is the [`AppDelegate`](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/ios/Runner/AppDelegate.m) of the `/example` app in this repo.  I suggest you clone this repo and boot the `/example` app.

[here](https://github.com/transistorsoft/transistor-background-fetch/blob/master/ios/TSBackgroundFetch/TSBackgroundFetch/TSBackgroundFetch.m#L93-L107) is how the SDK *automatically* executes `setMinimumBackgroundFetchInterval`, by first checking if the device is running *LESS THAN* `iOS 13`.  *iOS 13+* uses the new `BGTaskScheduler` API.

```obj-c
- (NSError*) scheduleBGAppRefresh {
    if (fetchScheduled) return nil;
    
    NSLog(@"[%@ scheduleBGAppRefresh] %@", TAG, BACKGROUND_REFRESH_TASK_ID);
        
    NSError *error = nil;
    
    if (@available (iOS 13.0, *)) {
        if ([TSBGAppRefreshSubscriber useTaskScheduler]) {
            BGTaskScheduler *scheduler = [BGTaskScheduler sharedScheduler];
            BGAppRefreshTaskRequest *request = [[BGAppRefreshTaskRequest alloc] initWithIdentifier:BACKGROUND_REFRESH_TASK_ID];
            request.earliestBeginDate = [NSDate dateWithTimeIntervalSinceNow:minimumFetchInterval];
            [scheduler submitTaskRequest:request error:&error];
        } else {
            [self setMinimumFetchInterval];
        }
    } else {
        [self setMinimumFetchInterval];
    }
    if (!error) {
        fetchScheduled = YES;
    }
    return error;
}
```

**Comment by uc-dve** [comment]
I have deleted the code from AppDelegate.swift file
Now i am getting another error while using scheduleTask
![image](https://user-images.githubusercontent.com/28289763/106235518-d8296880-6220-11eb-9483-7a0c0d484902.png)

Here is my AppDelegate.swift code
![image](https://user-images.githubusercontent.com/28289763/106235593-fee79f00-6220-11eb-9ede-f0f20f208c0b.png)

**Comment by christocracy** [comment]
Boot your app in XCode and observe the native logs.

**Comment by wcoder** [comment]
@uc-dve 
`errorCode = 3` Seems like `BGTaskSchedulerErrorCodeNotPermitted = 3`
> The task request could not be submitted because the appropriate background mode is not included in the UIBackgroundModes array, or its identifier was not present in the BGTaskSchedulerPermittedIdentifiers array in the app's Info.plist.

**Comment by wcoder** [comment]
@christocracy Could you please add `iOS Troubleshooting` section to documentation, for example topics:
- `Unhandled Exception: PlatformException(1, BGTaskSchedulerErrorDomain, null, null)` — The app is running on Simulator which doesn’t support **background processing**. https://developer.apple.com/documentation/backgroundtasks/bgtaskschedulererrorcode/bgtaskschedulererrorcodeunavailable?language=objc
- `PlatformException (PlatformException(18446744073709551615, Background procssing tasks are only available with iOS 13+, null, null))` 
- `PlatformException (PlatformException(18446744073709551615, Background procssing tasks are only available with iOS 13+, null, null))`
