### ISSUE TITLE
Background Fetch and Sensors Plugin

### ISSUE THREAD

**Issue by davidegurgone** [transistorsoft/flutter_background_fetch#184]
Hi all,
I am developing an app for iOS and Android that is able to read from gyroscope and accelerometer also while in background.

I found this plugin that looks the right one to perform what I need.

The background process is not scheduled, it will run in background until it is stopped manually by the user through a regular button and I don't need to run it headless.

Do I need to run: ```BackgroundFetch.configure(...)``` before or I can run it once with: ```BackgroundFetch.scheduleTask(...)```

Is it possible to read sensors or launch Local Notifications from the background process?

Thanks, Davide

**Comment by christocracy** [comment]
>Do I need to run: BackgroundFetch.configure(...) before 

Yes.

>Is it possible to read sensors or launch Local Notifications from the background process?

You can do whatever  you want in the `callback` you provide.  You have exactly 30s of background-time to operate your sensors and call `.finish(taskId)`.  If you don't call `.finish(taskId)` in time, your app will force-terminated by the OS for bad behaviour.

Btw, `scheduleTask` on iOS seems to only run when the device is plugged into power.
