### ISSUE TITLE
How to pass build context to the background task callback?

### ISSUE THREAD

**Issue by marksustin** [transistorsoft/flutter_background_fetch#185]
I want to add localization to the text of notifications sent from the background fetch task, but I have to use the `.of(context)` method for that, but I can't because it's only available in the build method from widgets. Does somebody know how to implement that?

**Comment by marksustin** [comment]
Already found a solution. You can use `S.current.key` instead `S.of(context).key`

**Comment by spalenzuela** [comment]
> Already found a solution. You can use `S.current.key` instead `S.of(context).key`

@marksustin I got an error **Unhandled Exception: NoSuchMethodError: The method 'alarm_titleTe
xt' was called on null** in backgroundFetchHeadlessTask method using S.current.key solution (**S.current.alarm_titleText**). Any ideas?
