### ISSUE TITLE
[BUG] iOS - Error related to duplicated taskId 

### ISSUE THREAD

**Issue by Hystrick** [transistorsoft/flutter_background_fetch#187]
**Your Environment**
* Plugin version: 0.6.0
* Platform: iOS
* OS version: 13.7
* Device manufacturer / model: iPhone6s
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.2 20D64 darwin-x64, locale
    it-IT)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
 
[✓] Connected device (1 available)            

! Doctor found issues in 2 categories.

**To Reproduce**
1. Set up the plugin by following the instructions written on relative plugin section in pub.dev
2. Perform the setup on iOS and Android 
3. Build the app on XCodes

**Debug logs**
- ios XCode logs:
`Launch handler for task with `identifier` com.transistorsoft.fetch has already been registered`
<img width="1166" alt="background_fetch_error" src="https://user-images.githubusercontent.com/43847574/107216841-a2993200-6a0d-11eb-83b1-fc7b5e1da7e3.png">

**Additional context**
I'm testing the backgroundFetch both in Android and iOS. 
On Android I didn't found any problem and it works properly.
On iOS I've enable the "Backgroud fetch" and the "Background processing" even if I don't have any custom task to execute.
<img width="961" alt="app_capabilities" src="https://user-images.githubusercontent.com/43847574/107217770-f2c4c400-6a0e-11eb-8d1b-edab9921b423.png">
I've also add the "Permitted background task scheduler identifier" with one item that is called "com.transistorsoft.fetch" (but it can be anything else string).
<img width="960" alt="app_info" src="https://user-images.githubusercontent.com/43847574/107218066-6797fe00-6a0f-11eb-8c0a-25ebf4a1538e.png">
When I build the app XCode says that the build succeed, but immediately after XCode throw the above error and stop the execution.
I've also tryed to put a random string as taskId on the info.plist, but XCode throw the same error over and over

**Comment by christocracy** [comment]
Post your `dart` code.

**Comment by Hystrick** [comment]
`
class MyWidget extends StatelessWidget {

@override
  void initState() {
    super.initState();
    _initSyncPeriodic();
  }

  @override
  Widget build(BuildContext context) {
    return ...;
  }
}

Future<void> _initSyncPeriodic() async {
    // Init periodic fetch
    BackgroundFetch.configure(
      BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        forceAlarmManager: true,
      ),
      (String taskId) async {
        if (_connectionStatus == false) {
          return;
        }
        try {
          await _syncDataOneTime();
        } catch (e) {
          print(e.toString());
        }

        BackgroundFetch.finish(taskId);
      },
    );
  }

Future<void> _syncDataOneTime() async {
    final Box<int> stepsBox = Hive.box('steps');
    int todayDayNum = Jiffy(DateTime.now()).dayOfYear;
    int steps = stepsBox.get(todayDayNum);

    SessionStats sessionStats = await HiveStatsMethods.getSessionStats();

    await DailyUserDataService.syncData(steps != null ? steps : 0,
        sessionStats != null ? sessionStats.steps : 0);
  }
`

**Comment by christocracy** [comment]
Please learn to use [Github Syntax Highlighting](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by Hystrick** [comment]
Any news?
