### ISSUE TITLE
AAPT: error: attribute android:foregroundServiceType not found.

### ISSUE THREAD

**Issue by RGiVcardo** [transistorsoft/flutter_background_fetch#188]
**Your Environment**
* Plugin version: ^1.8.0
* Platform: Android (Flutter)
* Device manufacturer / model: Samsung
* Flutter info (`flutter info`, `flutter doctor`): 1.20.0

**Debug logs**
- Android: FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > Android resource linking failed

     D:\Demo\tech\tech_app\android\app\src\main\AndroidManifest.xml:61:9-63:56: AAPT: error: attribute android:foregroundServiceType not found.

     D:\Demo\tech\tech_app\android\app\src\main\AndroidManifest.xml:64:9-66:56: AAPT: error: attribute android:foregroundServiceType not found.

**Additional context**
When I try to build release apk it's giving error on line where I added backgroundgeolocation services in android manifest file

**Comment by christocracy** [comment]
`flutter_backgorund_fetch` does not use foreground-services.  Are you in the wrong repo?

**Comment by RGiVcardo** [comment]
No, I think so.

Please check attached image and let me know is it Ok, because I have captured that portion from demo code of yours.

Thanks.

![backgroundgeolocation](https://user-images.githubusercontent.com/44604490/107405234-1a11b300-6b2d-11eb-923d-e08ac548e999.PNG)

**Comment by christocracy** [comment]
You are posting an issue about *flutter_background_geolocation* in the *flutter_background_fetch* repo.

**Comment by RGiVcardo** [comment]
Ohh Sorry, let me move this case to there.
Thank you.
