### ISSUE TITLE
[BUG] iOS Background Activity not working

### ISSUE THREAD

**Issue by mamen2022** [transistorsoft/flutter_background_fetch#19]
**Your Environment**
* Plugin version: 0.1.2
* Platform: iOS
* OS version: 12.1.4
* Device manufacturer / model: iPhone 6 / iPhone 8
* Flutter info (`flutter info`, `flutter doctor`):

```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.3.8 at /Users/gmf/Documents/dev/flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gmf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0
```

* Plugin config
```
 BackgroundFetchConfig(
                minimumFetchInterval: 20,
                stopOnTerminate: false,
                enableHeadless: true,
                startOnBoot: true),
            _onBackgroundFetch)
```

Problem:
Hi,
I am creating this post because on iOS the background fetch doesn't seem to be running. On Android it's working perfectly, with the App sleeping or closed, but on iOS nothing happens. There is any way of testing or debugging this? With the Simulate tool, it works well and executes exactly what its expected. Can you give me some info? There is any other configuration needed? The Background Fetch works when sleeping and closed ?
 
Best Regards

**Comment by christocracy** [comment]
iOS Background Fetch is unpredictable.  It can take days to fire regularly after first being installed.  iOS uses a secret machine-learning algorithm to fire these events, taking into account time of day, frequency of usage, etc.

If it works in the simulator, your job is done.  The iOS background fetch API is nothing but a block box with a power `[ON]` / `[OFF]` switch.  There's nothing to go wrong and nothing to fix.
