### ISSUE TITLE
[BUG] Could not find job 999 in package com.xxx.xxx/ user 0

### ISSUE THREAD

**Issue by function2000** [transistorsoft/flutter_background_fetch#193]
**Your Environment**
* Plugin version:
* Platform: Android
* OS version: 10
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`      
- C:\Users\XXX\AppData\Local\Android\Sdk\platform-tools>adb shell cmd jobscheduler run -f com.xxx.xxx 999
Could not find job 999 in package com.xxx.xxx / user 0

**Additional context**

**Comment by christocracy** [comment]
The Config you provide the plugin is highly relevant to your issue.  You have not shown your Config.

**Comment by function2000** [comment]
Do you mean this?   ===>
  Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    try {
      int status = await BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        forceAlarmManager: true,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.ANY,
      ), _onBackgroundFetch, _onBackgroundFetchTimeout);
      print('[BackgroundFetch] configure success: $status');
      setState(() {
        _status = status;
      });

      // Schedule a "one-shot" custom-task in 10000ms.
      // These are fairly reliable on Android (particularly with forceAlarmManager) but not iOS,
      // where device must be powered (and delay will be throttled by the OS).
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 60000,
          periodic: false,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true
      ));

    } catch(e) {
      print('[BackgroundFetch] configure ERROR: $e');
      setState(() {
        _status = e;
      });
    }

**Comment by christocracy** [comment]
Please learn to use [Github Syntax Highlighting](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)
![](https://dl.dropbox.com/s/4dvjz5s1ft7mkog/Screen%20Shot%202021-02-23%20at%208.47.03%20AM.png?dl=1)

```dart
await BackgroundFetch.configure(BackgroundFetchConfig(
  forceAlarmManager: true
  .
  .
  .
))
```
When you use `forceAlarmManager: true`, the plugin no longer uses [`JobScheduler` ](https://developer.android.com/reference/android/app/job/JobScheduler) to schedule events.  There is **no way** to *simulate* events with [`AlarmManager`](https://developer.android.com/reference/android/app/AlarmManager) -- only `JobScheduler`

```
adb shell cmd jobscheduler run -f com.xxx.xxx 999
```

When attempting to *simulate* events, don't use `forceAlarmManager: true`
