### ISSUE TITLE
Understanding needed for IOS integration

### ISSUE THREAD

**Issue by arif2k17** [transistorsoft/flutter_background_fetch#194]
According to the readme file:
    `When your app is terminated, iOS no longer fires events — There is no such thing as stopOnTerminate: false for iOS.`
Does this mean if user closed the app after that background fetch will stop working? I am confused here. If it stops working then how my background scheduling work will be done?

**Comment by christocracy** [comment]
> Does this mean if user closed the app after that background fetch will stop working?

That's exactly what it means.

> my background scheduling work will be done?

Use a local-notification plugin to schedule a notification in the future.  Your code won't win unless the user actually clicks the notification, but that's your only option on iOS.
