### ISSUE TITLE
[BUG][Android] After killing application not getting any background call 

### ISSUE THREAD

**Issue by deep-flutter** [transistorsoft/flutter_background_fetch#20]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.3.9600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] Connected device (1 available)

• No issues found!

**To Reproduce**
1. Just run the app see the log when app is on foreground its working fine
2. When we killed application there no work done after termination of app
3) I am doing flutter cloud_storage database entry on firebase console when user killed like below 
4) 
```dart
 Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        forceReload: true,
        startOnBoot: true,
        enableHeadless: true
    ), () async {
      // This is the fetch-event callback.
      print('[BackgroundFetch] Event received');
      setState(() {
        _events.insert(0, new DateTime.now());

       // My firebase data addition code when we are getting background call.
        addData();
      });
      // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
      // for taking too long in the background.
      BackgroundFetch.finish();
    }).then((int status) {
      print('[BackgroundFetch] SUCCESS: $status');
      setState(() {
        _status = status;
      });
    }).catchError((e) {
      print('[BackgroundFetch] ERROR: $e');
      setState(() {
        _status = e;
      });
    });

    // Optionally query the current BackgroundFetch status.
    int status = await BackgroundFetch.status;
    setState(() {
      _status = status;
    });
    if (!mounted) return;
  }
```

**Comment by christocracy** [comment]
Are you [simulating Android fetch events](https://github.com/transistorsoft/flutter_background_fetch#large_blue_diamond-debugging) with `$ adb shell`?

**Comment by deep-flutter** [comment]
I think it is working in background may be there are some issue in my log that i am using for tracking using cloud_storage. 

C:\Users\AppData\Local\Android\sdk\platform-tools>adb shell cmd jobsche
duler run -f my.package.name 999
Running job [FORCED]

C:\Users\AppData\Local\Android\sdk\platform-tools>adb logcat *:S flutte
r:V, TSBackgroundFetch:V
--------- beginning of crash
--------- beginning of main
--------- beginning of system
03-27 10:12:01.359 28958 28958 D TSBackgroundFetch: - Background Fetch event rec
eived
03-27 10:12:01.374 28958 28958 D TSBackgroundFetch: - finish
03-27 10:12:01.374 28958 28958 D TSBackgroundFetch: - jobFinished
03-27 10:12:01.413 28958 28958 D TSBackgroundFetch: HeadlessJobService onStartJo
b
03-27 10:12:01.414 28958 28958 D TSBackgroundFetch: ?? [HeadlessTask]
03-27 10:12:01.602 28958 28958 D TSBackgroundFetch: [HeadlessTask] waiting for c
lient to initialize
03-27 10:12:01.821 28958 28992 I flutter : Observatory listening on http://127.0
.0.1:56688/
03-27 10:12:02.098 28958 28958 I TSBackgroundFetch: $ initialized
03-27 10:12:02.136 28958 28989 I flutter : [BackgroundFetch] Headless event rece
ived.
03-27 10:12:02.155 28958 28958 D TSBackgroundFetch: - finish
03-27 10:12:02.155 28958 28958 D TSBackgroundFetch: HeadlessJobService jobFinish
ed
03-27 10:22:31.917 31629 31629 D TSBackgroundFetch: - Background Fetch event rec
eived
03-27 10:22:31.926 31629 31629 D TSBackgroundFetch: - finish
03-27 10:22:31.926 31629 31629 D TSBackgroundFetch: - jobFinished
03-27 10:22:31.952 31629 31629 D TSBackgroundFetch: HeadlessJobService onStartJo
b
03-27 10:22:31.953 31629 31629 D TSBackgroundFetch: ?? [HeadlessTask]
03-27 10:22:32.099 31629 31629 D TSBackgroundFetch: [HeadlessTask] waiting for c
lient to initialize
03-27 10:22:32.289 31629 31664 I flutter : Observatory listening on http://127.0
.0.1:43783/
03-27 10:22:32.568 31629 31629 I TSBackgroundFetch: $ initialized
03-27 10:22:32.606 31629 31660 I flutter : [BackgroundFetch] Headless event rece
ived.
03-27 10:22:32.625 31629 31629 D TSBackgroundFetch: - finish
03-27 10:22:32.625 31629 31629 D TSBackgroundFetch: HeadlessJobService jobFinish
ed
03-27 10:42:18.258  1489  1489 D TSBackgroundFetch: - Background Fetch event rec
eived
03-27 10:42:18.266  1489  1489 D TSBackgroundFetch: - finish
03-27 10:42:18.266  1489  1489 D TSBackgroundFetch: - jobFinished
03-27 10:42:18.299  1489  1489 D TSBackgroundFetch: HeadlessJobService onStartJo
b
03-27 10:42:18.300  1489  1489 D TSBackgroundFetch: ?? [HeadlessTask]
03-27 10:42:18.452  1489  1489 D TSBackgroundFetch: [HeadlessTask] waiting for c
lient to initialize
03-27 10:42:18.643  1489  1526 I flutter : Observatory listening on http://127.0
.0.1:33081/
03-27 10:42:18.921  1489  1489 I TSBackgroundFetch: $ initialized
03-27 10:42:18.959  1489  1523 I flutter : [BackgroundFetch] Headless event rece
ived.
03-27 10:42:18.979  1489  1489 D TSBackgroundFetch: - finish
03-27 10:42:18.979  1489  1489 D TSBackgroundFetch: HeadlessJobService jobFinish
ed
03-27 10:57:04.324  1489  1489 D TSBackgroundFetch: - Background Fetch event rec
eived
03-27 10:57:04.326  1489  1489 D TSBackgroundFetch: - finish
03-27 10:57:04.326  1489  1489 D TSBackgroundFetch: - jobFinished
03-27 10:57:04.362  1489  1489 D TSBackgroundFetch: HeadlessJobService onStartJo
b
03-27 10:57:04.363  1489  1489 D TSBackgroundFetch: ?? [HeadlessTask]
03-27 10:57:04.367  1489  1523 I flutter : [BackgroundFetch] Headless event rece
ived.
03-27 10:57:04.368  1489  1489 D TSBackgroundFetch: - finish
03-27 10:57:04.368  1489  1489 D TSBackgroundFetch: HeadlessJobService jobFinish
ed

**Comment by deep-flutter** [comment]
Can any one tell why there no code is working when we receive background event. I have tried cloud storage entry & also database entry.
I am getting log using  simulating Android fetch events but there is no code is working when i received background event.

**Comment by christocracy** [comment]
Have you tried booting the `/example` in this repo?

**Comment by deep-flutter** [comment]
nop let me check.

**Comment by christocracy** [comment]
Closed for lack of feedback.
