### ISSUE TITLE
Mutilines and title format

### ISSUE THREAD

**Issue by dgofman** [transistorsoft/flutter_background_fetch#201]
Please can you show a Push Notification in Multiline. I believe is supporting by Android

https://tips.androidhive.info/2015/04/android-showing-push-notification-in-multiline/

**Comment by christocracy** [comment]
I have no idea what you are you talking about.

**Comment by dgofman** [comment]
@christocracy I tied to enter a body more than 20 characters, currently is truncated. I tried using <br>, \n and \r\n nothing is helped.

**Comment by christocracy** [comment]
BackgroundFetch has nothing to do with any kind of UI mechanisms.  It makes no sense to talk of notification in this repo.
