### ISSUE TITLE
[BUG] iOS onFetch method is never called

### ISSUE THREAD

**Issue by brneas** [transistorsoft/flutter_background_fetch#202]
**Your Environment**
* Plugin version: 0.7.1
* Platform: iOS
* OS version: 14.4
* Device manufacturer / model: iPhone SE (2nd Gen)
* Flutter info:
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
* Plugin config
I've tried a simple config like:
`BackgroundFetch.configure(
 BackgroundFetchConfig(
     minimumFetchInterval: 15,
     stopOnTerminate: false,
     startOnBoot: true,
     enableHeadless: true,
 ),
 _onBackgroundFetch,
 _onBackgroundFetchTimeout,
);`
I've tried a more advanced config like:
`BackgroundFetch.configure(
        BackgroundFetchConfig(
          minimumFetchInterval: 15,
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE,
        ),
        _onBackgroundFetch,
        _onBackgroundFetchTimeout,
      );`

**To Reproduce**
1. Use the following methods:

```dart
  Future<void> initPlatformState() async {
    try {
      int status = await BackgroundFetch.configure(
        BackgroundFetchConfig(
          minimumFetchInterval: 15,
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE,
        ),
        _onBackgroundFetch,
        _onBackgroundFetchTimeout,
      );
      print('[BackgroundFetch] configure success: $status');
    } catch (e) {
      print('[BackgroundFetch] configure ERROR: $e');
    }

    if (!mounted) return;
  }

  void _onBackgroundFetch(String taskId) async {
    locationModel.pingServer();

    BackgroundFetch.finish(taskId);
  }

  void _onEnable() async {
    _enabled = !_enabled;

    if (_enabled) {
      dynamic callback = (bg.State state) async {
        setState(() {
          _enabled = state.enabled;
        });

        bg.BackgroundGeolocation.changePace(_enabled).then((bool isMoving) {
          //print('[changePace] success $isMoving');
        }).catchError((e) {
          print('[changePace] ERROR: ' + e.code.toString());
        });
        BackgroundFetch.start();
      };
      bg.State state = await bg.BackgroundGeolocation.state;
      if (state.trackingMode == 1) {
        bg.BackgroundGeolocation.start().then(callback);
      } else {
        bg.BackgroundGeolocation.startGeofences().then(callback);
      }
    } else {
      dynamic callback = (bg.State state) {
        //print('[stop] success: $state');
        setState(() {
          _enabled = state.enabled;
        });
        BackgroundFetch.stop();
      };
      bg.BackgroundGeolocation.stop().then(callback);
    }
  }
```
2. Call `initPlatformState` in your `initState` method.
3. Use BackgroundGeolocation alongside.
4. On Android when the `_onEnable` method is called, background fetch calls the `_onBackgroundFetch` method every 15 minutes and BackgroundGeolocation works.  On iOS when the `_onEnable` method is called, background fetch never calls the `_onBackgroundFetch` method and BackgroundGeolocation  works.

**Debug logs**
> 2021-03-18 14:15:42.886500-0400 Runner[404:8576] [TSBackgroundFetch load]: (
> )
> 2021-03-18 14:15:42.886574-0400 Runner[404:8576] [TSBGAppRefreshSubscriber load]: {
> }
> 2021-03-18 14:15:43.038053-0400 Runner[404:8576] Metal API Validation Enabled
> 2021-03-18 14:15:43.319849-0400 Runner[404:8576] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
> 2021-03-18 14:15:43.332945-0400 Runner[404:8741] flutter: [BackgroundFetch] configure success: 2
> 2021-03-18 14:15:49.659726-0400 Runner[404:8576] [Client] {"msg":"#NullIsland Either the latitude or longitude was exactly 0! That's highly unlikely", "latIsZero":0, "lonIsZero":0}
> 2021-03-18 14:15:49.696891-0400 Runner[404:8576] [TSBackgroundFetch start] (null)
> 2021-03-18 14:15:49.844580-0400 Runner[404:8741] flutter: [http] success [HttpEvent {success: true, status: 200, responseText: 200}]
> 2021-03-18 14:15:49.997091-0400 Runner[404:8741] flutter: [http] success [HttpEvent {success: true, status: 200, responseText: 200}]
> 2021-03-18 14:16:37.070459-0400 Runner[404:8576] [TSBackgroundFetch stop] (null)
> 2021-03-18 14:16:40.489711-0400 Runner[404:8576] [TSBackgroundFetch start] (null)
> 2021-03-18 14:16:40.489820-0400 Runner[404:8576] [TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
> 2021-03-18 14:16:40.673820-0400 Runner[404:8741] flutter: [http] success [HttpEvent {success: true, status: 200, responseText: 200}]
> 2021-03-18 14:17:25.501334-0400 Runner[404:8576] [BackgroundTask] Background Task 5 ("Called by Runner, from -[BackgroundTaskManager createBackgroundTask]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by christocracy** [comment]
Have you tried simulating your iOS event?  When a simulated event fires, that's all you need to know that everything is working.

Waiting for an event to fire is pointless.

**Comment by brneas** [comment]
It looks like the simulated event works.

I assume this goes back to my email and your documentation:
> iOS can task days before Apple's machine-learning algorithm settles in and begins regularly firing events. Do not sit staring at your logs waiting for an event to fire. If your simulated events work, that's all you need to know that everything is correctly configured.

Do you have any references to this information or is it just from past experience?
Can you estimate how many days is "days"? Does the user need to be active on the device and have the app running for Apple's machine-learning algorithm to settle in and begin regularly firing events?

**Comment by christocracy** [comment]
I don't remember where I learned about it.  There's no docs.  You just need to be patient and trust that if simulated events work, that's all you need to know.

If you don't open your app daily, Apple stops firing events.
