### ISSUE TITLE
[BUG] Could not resolve dependencies

### ISSUE THREAD

**Issue by ronriley** [transistorsoft/flutter_background_fetch#204]
**Your Environment**
* Plugin version:
* '^0.7.0'
* Platform: iOS or Android
* Android
* OS version:
* N/A
* Device manufacturer / model:
* N/A
* Flutter info (`flutter info`, `flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_GB.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for
      more details.
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

* Plugin config

**To Reproduce**
1. Create a new app with the example app.
2. Try to build it

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Launching lib/main.dart on Pixel 3a in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/
       - file:/home/ron/newdev/flutter_app/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/ron/newdev/flutter_app/android/app/libs/com/transistorsoft/tsbackgroundfetch/
     Required by:
         project :app > project :background_fetch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 42s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
You didn't follow the *Android Setup*  in the README.

**Comment by banderberg** [comment]
@christocracy I followed the Android Setup and I get this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - [https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml]()
       - [https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml]()
       - [https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml]()
       - [https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml]()
       - fil[e:/C]():/flutter-dev/AutoMate/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
```

**Comment by christocracy** [comment]
- Post your android/build.grade

**Comment by banderberg** [comment]
@christocracy Thanks for the quick reply.

```
buildscript {
    ext.kotlin_version = '1.6.10'
    ext {
        compileSdkVersion   = 31                // or latest
        targetSdkVersion    = 31                // or latest
        appCompatVersion    = "1.1.0"           // or latest
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by christocracy** [comment]
Did you hear the news about jcenter?  It’s dead and causing weird issues like this.

get rid of jcenter in all you build.gradle files.

Search your dependencies for other plugins referencing jcenter.  Upgrade all your dependencies.

**Comment by banderberg** [comment]
I had not heard, thank you.  I'll do that and report back.

**Comment by christocracy** [comment]
https://blog.gradle.org/jcenter-shutdown

**Comment by banderberg** [comment]
I removed jcenter and found no mention of bintray anywhere.  I'm not sure how to search my dependencies.  At any rate, I removed jcenter from build.gradle, ran flutter clean, flutter pub get and flutter pub upgrade and I get the same error.

**Comment by christocracy** [comment]
> I'm not sure how to search my dependencies

Open your app/android folder in AndroidStudio.  It will show a grouped list of all your gradle files.  Observe each of them.

**Comment by banderberg** [comment]
So I found the dependency that was causing trouble.  The location package still references jcentral so I edited its build gradle and that error goes away.  But, I still get the same error only now there's no mention of jcentral bintray:

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/C:/flutter-dev/AutoMate/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
```

**Comment by banderberg** [comment]
I don't know why it wants to search file:/C:/flutter-dev/AutoMate/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml as that is not a thing.

**Comment by banderberg** [comment]
> > I'm not sure how to search my dependencies
> 
> Open your app/android folder in AndroidStudio. It will show a grouped list of all your gradle files. Observe each of them.

On my system flutter uses the gradle cache in my AppData folder - not one local to my project.

**Comment by christocracy** [comment]
I do not know what the problem is.  Generate a fresh new flutter hello world project and test the plugin in isolation.

**Comment by banderberg** [comment]
A new flutter app that I've added background_fetch to produces this on gradlew build (slightly different from above as it complains about lintVitalRelease

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/C:/flutter-dev/background_fetch_test/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch
```

**Comment by christocracy** [comment]
You did **not** correctly follow the [Setup Steps](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md).  You *think* you did, but you did not.

You did *not* drop this in the correct place.

```
maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
```

**Comment by christocracy** [comment]
There are **two** `repositories` sections in the root `build.gradle`.  You dropped into the first one you found.

The *Setup Steps* tell you to place the `maven url` under `allProjects`

**Comment by banderberg** [comment]
Thank you for your patient help Chris!

**Comment by claudiu-bele** [comment]
Might've been a change or i'm missing something?

> buildscript {
>     ext.kotlin_version = '1.7.10'
>     repositories {
>         google()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:7.3.1'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         // [required] background_fetch
>         maven { url "${project(':background_fetch').projectDir}/libs" }
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }


and 

> buildscript {
>     ext.kotlin_version = '1.7.10'
>     repositories {
>         google()
>         mavenCentral()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:7.3.1'
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> }
> 
> allprojects {
>     repositories {
>         google()
>         mavenCentral()
>         // [required] background_fetch
>         maven { url "${project(':background_fetch').projectDir}/libs" }
>     }
> }
> 
> rootProject.buildDir = '../build'
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> 
> task clean(type: Delete) {
>     delete rootProject.buildDir
> }
> 

I've made the changes in the manifest

Should i do a flutter pub run build_runner build or something? there is also no build folder with the libraries in it. Maybe its being tired, can you help me out, do you see anything obvious?

**Comment by christocracy** [comment]
Please learn to syntax highlight “fenced code blocks”:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

**Comment by claudiu-bele** [comment]
i know it, just cant find the key on this keyboard and got my glasses just today, formatting and sending now

I use 
- Flutter 3.7.12 • channel stable •
- background_fetch: 1.2.2

With the Flutter dependencies I use there is no jcenter issues, just some deprecation complaints that I'm just gonna just hide. 

Now this below compiles, maybe it was the ext.appcompat not present, maybe it was something else- idk- some rest was all that was needed, for anyone that needs help this is the setup that made it work for my setup, some libraries depend on different flutter and kotlin versions, thanks, and let's ascend to flutter God together

<details>
  <summary>Collapse/expand gradle files and manifest</summary>

## app/build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '2000000100'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '2.0.1'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // compatibility to java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        multiDexEnabled true
        applicationId "com.example.ajung"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21 // 19 because of firebase messaging, 21 cause localizations
        targetSdkVersion rootProject.ext.compileSdkVersion // for at least Stripe
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
    implementation 'androidx.window:window:1.0.0'
    implementation 'androidx.window:window-java:1.0.0'
}
```

## app/android/build.gradle
```
buildscript {
    ext {
        kotlin_version = '1.9.0'                // needed for Stripe
        compileSdkVersion   = 34                // or higher / as desired
        targetSdkVersion    = 34                // or higher / as desired
        appCompatVersion    = "1.4.2"           // or higher / as desired
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // [required] background_fetch
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
## AndroidManifest
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.shrek_online">

    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <!-- more here https://pub.dev/packages/flutter_local_notifications#-android-setup -->
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />

    <application
        tools:replace="android:label"
        android:label="Shrek MMO"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">

        <meta-data
            android:name="firebase_messaging_auto_init_enabled"
            android:value="false" />
        <meta-data
            android:name="firebase_analytics_collection_enabled"
            android:value="false" />

        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ActionBroadcastReceiver" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>

        <activity
            android:showWhenLocked="true"
            android:turnScreenOn="true"
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

</details>

**Comment by claudiu-bele** [comment]
does Flutter? 

you mention this in the Android setup

![image](https://github.com/user-attachments/assets/78c6ee23-4dbe-4ba5-9621-5e81028db710)

Btw check this out https://www.youtube.com/watch?v=oMHRtwJa-yU

**Comment by christocracy** [comment]
What flutter requires for Kotlin is not this plug-in’s concern.

**Comment by claudiu-bele** [comment]
aha, so you're saying that is for flutter, not for you, what JDK ranges do you support if i were to make pure Java? I love pure Java so interested, contributed to LibGDX if you know it


 did you check COMBOS?

**Comment by christocracy** [comment]
> did you check COMBOS?

No.  It’s irrelevant to this issue.

**Comment by claudiu-bele** [comment]
Not true, not sure what helped but maybe seeing that made it work

**Comment by claudiu-bele** [comment]
You didn't tell me, what JDKs work with the library?

**Comment by christocracy** [comment]
>You didn't tell me, what JDKs work with the library?

Any JDK that works with your Flutter app will work with this SDK.
