### ISSUE TITLE
[BUG] java.lang.NullPointerException on HeadlessTask.java:170 and BackgroundFetchConfig.java:342

### ISSUE THREAD

**Issue by josechagas** [transistorsoft/flutter_background_fetch#206]
**Your Environment**
* Plugin version: 0.7.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Nexus 5X
* Flutter info (`flutter info`, `flutter doctor`): 
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale
    pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (1 available)
* Plugin config

`BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.ANY
    ), backgroundFetchTask);
BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);`

**To Reproduce**
1.  I really do not know how to reproduce this error it was reported by Firebase Crashlytics

**Debug logs**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at com.transistorsoft.tsbackgroundfetch.BackgroundFetchConfig$1.run(BackgroundFetchConfig.java:342)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
       
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask$RegistrationTask.run(HeadlessTask.java:170)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Additional context**

**Comment by christocracy** [comment]
And I guess the device was reported to be a *Nexus 5x*?

**Comment by josechagas** [comment]
This is what Firebase Crashlytics said.

**Comment by christocracy** [comment]
This is a *fake* crash, invoked as a "test crash".
