### ISSUE TITLE
[BUG] - HeadlessTask.java:23: error: ApplicationInfoLoader is not public in io.flutter.embedding.engine.loader; cannot be accessed from outside package

### ISSUE THREAD

**Issue by markjoseultra** [transistorsoft/flutter_background_fetch#207]
**Your Environment**
* Plugin version: background_fetch 0.7.2 
* Platform: iOS or Android
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-PH)
    • Flutter version 1.22.4 at /Users/sparkle-star/Developer/flutter
    • Framework revision 1aafb3a8b9 (5 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sparkle-star/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM G950F (mobile) • ce07171744102cd10c • android-arm64 • Android 9 (API 28)

• No issues found!
* Plugin config

**To Reproduce**
1.  
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`
Launching lib/main.dart on SM G950F in debug mode...

lib/main.dart:1

/Users/sparkle-star/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.7.2/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/HeadlessTask.java:23: error: ApplicationInfoLoader is not public in io.flutter.embedding.engine.loader; cannot be accessed from outside package

import io.flutter.embedding.engine.loader.ApplicationInfoLoader;

                                         ^

/Users/sparkle-star/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.7.2/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/HeadlessTask.java:130: error: cannot find symbol

        FlutterApplicationInfo info = ApplicationInfoLoader.load(mContext);

                                      ^

  symbol:   variable ApplicationInfoLoader

  location: class HeadlessTask

/Users/sparkle-star/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.7.2/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/HeadlessTask.java:131: error: flutterAssetsDir is not public in FlutterApplicationInfo; cannot be accessed from outside package

        String appBundlePath = info.flutterAssetsDir;

                                   ^

3 errors

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':background_fetch:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

Exception: Gradle task assembleDebug failed with exit code 1

Exited (sigterm)

**Additional context**

I tried using this background_fetch 0.7.2 but I am getting this error, I was able to run the application before but I can't execute a code in the background so I tried using 0.2.0 but it is crashing,
 so I go to 0.7.2 and then this error comes up, thanks in advance.

regards,

-----------------------------------------------------------------------------------------------------------------------------------------------

image.png

**Comment by christocracy** [comment]
You will likely see your problem disappear when you upgrade to Flutter 2.

**Comment by rikinmprajapati** [comment]
I have been facing the same issue since today morning which @markjoseultra has reported.

**Comment by christocracy** [comment]
Either upgrade Flutter sdk or don't use the latest released version of this plugin.

What's wrong with updating to Flutter 2?  Have you tried it?

**Comment by rikinmprajapati** [comment]
The latest version of this plugin is 0.7.2, and the version which I'm using is 0.7.1 (which is working fine till yesterday)

Also upgrading the Flutter requires a lot of other changes in the app source.

**Comment by christocracy** [comment]
You are not required to opt-into nullsafety with Flutter 2.

**Comment by rikinmprajapati** [comment]
It's not about the only null safety, the other plugins affected on upgrading the Flutter which forces me to update them as well with required changes in the implementation.

**Comment by christocracy** [comment]
> with required changes in the implementation.

Example?

**Comment by rikinmprajapati** [comment]
whoever is facing this issue in spite of using the older version 0.7.1 try the below solution,

just update the version of background_fetch to 0.7.1 in the pubspec.lock file

**Comment by markjoseultra** [comment]
Thank you @christocracy and @rikinmprajapati I upgraded to flutter 2 its working now

**Comment by loonix** [comment]
Works for me when I changed:   `background_fetch: ^0.7.1` to  `background_fetch: 0.7.1`
