### ISSUE TITLE
[BUG] - Sharedpreferences is getting an error when being called inside background fetch method when app is terminated

### ISSUE THREAD

**Issue by markjoseultra** [transistorsoft/flutter_background_fetch#208]
**Your Environment**
* Plugin version: 0.7.1
* Platform: iOS and Android
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-PH)
    • Flutter version 1.22.4 at /Users/sparkle-star/Developer/flutter
    • Framework revision 1aafb3a8b9 (5 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sparkle-star/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**To Reproduce**
1. Create a new flutter application
2. use background_fetch: '0.7.1' and shared_preferences: ^0.5.12+4
3. create a headless method that utilizes shared preferences
4. exit the app and then trigger the background fetch using this command
adb shell cmd jobscheduler run -f com.example.app 999

**Debug logs**
I/flutter (29628): [BackgroundFetch] Headless event received in Sparkle Merchant.
I/flutter (29628): Executing local notification
E/flutter (29628): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

**Additional context**
Issue happens when sharedpreference is called in the background fetch when app is terminated

**Comment by christocracy** [comment]
The /example app in this repo accesses SharedPreferences in the headlessTask.

**Comment by markjoseultra** [comment]
Thank you @christocracy  I upgraded to flutter 2 its working now

**Comment by AhmetMelihSerter** [comment]
> The /example app in this repo accesses SharedPreferences in the headlessTask.

I am having the same problem.  It gives SharedPreferences and Path provider errors in hive and easylocation packages.

**Comment by christocracy** [comment]
Create for me fresh new Flutter *Hello World* that reproduces the issue.

Share that repo with me.

**Comment by AhmetMelihSerter** [comment]
> Create for me fresh new Flutter _Hello World_ that reproduces the issue.
> 
> Share that repo with me.

After creating a new flutter app and moving all my code, the problem was resolved. I checked my migrated code with git and there was no difference but it works right now. Thanks.

**Comment by christocracy** [comment]
Sometimes there are slight changes to the auto-generated flutter code that needs to be migrated.

Generating a new flutter app then simply migrating your /lib + added modules in pubspec.yaml is often the easiest path.
