### ISSUE TITLE
[BUG] [Android] Unable to debug headless background fetch events

### ISSUE THREAD

**Issue by gitboss** [transistorsoft/flutter_background_fetch#21]
Plugin version: 0.2.0
Platform: Android

1.  Run the example app in emulator from VS Code.

2.  Execute the following in Windows 10 command prompt cmd : 
adb shell am broadcast -a com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample.event.BACKGROUND_FETCH

3. Output : 
Broadcasting: Intent { act=com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample.event.BACKGROUND_FETCH flg=0x400000 }
Broadcast completed: result=0

4. However the event is neither logged by the example app in the emulator nor can we debug the code.

Note: Simulating the following other event works as expected - 
"adb shell cmd jobscheduler run -f com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample 999"

**Comment by christocracy** [comment]
That's right.  For devices run Android 21+, fetch uses the modern `JobScheduler` mechanism, ie:
```
adb shell cmd jobscheduler run -f com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample 999"
```

For all *older* device, it uses `AlarmManager`, ie:
```
adb shell am broadcast -a ...
```

The plugin uses *one* or the *other*, **not both**.
