### ISSUE TITLE
The background process is not working, when app is terminated.[BUG]

### ISSUE THREAD

**Issue by rkarthi33** [transistorsoft/flutter_background_fetch#210]
**Your Environment**
* Plugin version: Plugin version: 0.7.2
* Platform: Android
* OS version:  Mac OS 10.15.7
* Device manufacturer / model: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) 
* Flutter info (`flutter info`, `flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
* Plugin config
Flutter 2.0.4 Stable
Dart : 2.12.2
**To Reproduce**
1. Create a new flutter application
2. Use background_fetch: '0.7.2', path_provider: ^2.0.1 and shared_preferences: ^2.0.5
3. Background process works well when app is foreground but It didn't work when app is terminated.
4. My Android Version 9 (API 28)
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
You've not shown your Config.

**Comment by rkarthi33** [comment]
Here i have shared the code. Please check


https://github.com/rkarthi33/Backgroun-Process.git

**Comment by rkarthi33** [comment]
Config :

 // Configure BackgroundFetch.
    try {
      var status = await BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        forceAlarmManager: false,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE,
      ), _onBackgroundFetch, _onBackgroundFetchTimeout);
      print('[BackgroundFetch] configure success: $status');
      setState(() {
        _status = status;
      });

**Comment by christocracy** [comment]
You've not posted headless-task registration not have you posted any logs from `logcat`.

This is not magic.  It requires evidence.

**Comment by rkarthi33** [comment]
// headless-task registration



void backgroundFetchHeadlessTask(HeadlessTask task) async {
  var taskId = task.taskId;
  var timeout = task.timeout;
  if (timeout) {
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }

  print("[BackgroundFetch] Headless event received: $taskId");
  var timestamp = DateTime.now();

  var prefs = await SharedPreferences.getInstance();

  // Read fetch_events from SharedPreferences
  var events = <String>[];
  var json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();

  }
  // Add new event.
  events.insert(0, "$taskId@$timestamp [Headless]");
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));

  if (taskId == 'flutter_background_fetch') {
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "com.transistorsoft.customtask",
        delay: 5000,
        periodic: false,
        forceAlarmManager: false,
        stopOnTerminate: false,
        enableHeadless: true
    ));
  }
  //BackgroundFetch.finish(taskId);
}

void main() {
  // Enable integration testing with the Flutter Driver extension.
  // See https://flutter.io/testing/ for more info.
  runApp(MyApp());

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}

**Comment by christocracy** [comment]
Please learn to use syntax highlighting.  Edit your post:

https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

And provide logs

**Comment by rkarthi33** [comment]
2021-04-13 10:19:40.500 18587-18587/com.example.background_process D/TSBackgroundFetch: - configure
2021-04-13 10:19:40.501 18587-18587/com.example.background_process D/TSBackgroundFetch: - start
2021-04-13 10:19:40.501 18587-18587/com.example.background_process D/TSBackgroundFetch: - registerTask: flutter_background_fetch
2021-04-13 10:19:40.502 18587-18587/com.example.background_process D/TSBackgroundFetch: {
      "taskId": "flutter_background_fetch",
      "isFetchTask": true,
      "minimumFetchInterval": 15,
      "stopOnTerminate": false,
      "requiredNetworkType": 0,
      "requiresBatteryNotLow": false,
      "requiresCharging": false,
      "requiresDeviceIdle": false,
      "requiresStorageNotLow": false,
      "startOnBoot": true,
      "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
      "forceAlarmManager": false,
      "periodic": true,
      "delay": -1
    }

**Comment by mquadrant** [comment]
> Please learn to use syntax highlighting. Edit your post:
> 
> https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
> 
> And provide logs

No error but it is not working when app is totally closed

**Comment by christocracy** [comment]
>No error but it is not working when app is totally closed

You are providing *no information*, particularly whether you're talking about iOS or Android.
