### ISSUE TITLE
[QUESTION] - Is this plugin work for background process (periodic task) in both Android and iOS?

### ISSUE THREAD

**Issue by rrifafauzikomara** [transistorsoft/flutter_background_fetch#212]
Is this plugin work for background process (periodic task) in both Android and iOS? For example, I have a case like this:

I want to hit API every day (24 hours) in the background when the apps are `closed`/`kill`/`minimize` and work in both Android and iOS.

And I found this.

> scheduleTask is designed for low-priority tasks and will never run as frequently as you desire.

Can you give me an example about `low-priority tasks`? And in my case above, it's `low-priority tasks` or `high-priority tasks`?

**Comment by christocracy** [comment]
iOS stops when user terminates the app.
