### ISSUE TITLE
[BUG] Can't run project with background_fetch

### ISSUE THREAD

**Issue by rubenferreira97** [transistorsoft/flutter_background_fetch#213]
**Your Environment**
* Plugin version: ^1.0.0-nullsafety.2 or master
* Platform: Irrelevant, but Android 11
* OS version: Windows 10
* Device manufacturer / model: Xiaomi Redmi 9S

**To Reproduce**
1. Add `background_fetch: ^1.0.0-nullsafety.2` to `pubspec.yaml`
2. Run `flutter run`

**Error logs**
`[+11587 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[  +10 ms] Could not determine the dependencies of task ':app:processDebugResources'.
[   +4 ms] > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
[   +1 ms]    > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
[   +1 ms]      Searched in the following locations:
[   +2 ms]        - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
[   +4 ms]        - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/
[   +1 ms]        - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
[   +1 ms]        - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/
[   +1 ms]        - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
[   +1 ms]        - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/
[   +4 ms]        - file:/C:/Users/Eu/Desktop/app_autarquias/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
[   +3 ms]        - file:/C:/Users/Eu/Desktop/app_autarquias/android/app/libs/com/transistorsoft/tsbackgroundfetch/
[   +1 ms]        - https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
[   +3 ms]        - https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/
[   +2 ms]      Required by:
[   +1 ms]          project :app > project :background_fetch
[   +1 ms] * Try:
[   +6 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 11s`

**Additional context**
If I comment background_fetch on `pubspec.yaml` the project runs just fine.

**Comment by christocracy** [comment]
Duplicate #204.  Please search issues *before* posting a new one.
