### ISSUE TITLE
[BUG] Not able to simulate Background Fetch in iOS

### ISSUE THREAD

**Issue by luvishq** [transistorsoft/flutter_background_fetch#221]
**Your Environment**
* Plugin version: 0.7.2
* Platform: iOS
* OS version: 14.4.2
* Device manufacturer / model: Apple
* Flutter info (`flutter info`, `flutter doctor`): ```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)
```

* Plugin config : 
```
```
BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 60, // <-- minutes
            stopOnTerminate: false,
            enableHeadless: true,
            startOnBoot: true), (String taskId) async {
      // <-- Event callback
      // This callback is typically fired every 15 minutes while in the background.
      
      BackgroundFetch.finish(taskId);
    }, (String taskId) async {
      // <-- Task timeout callback
      // This task has exceeded its allowed running-time.  You must stop what you're doing and immediately .finish(taskId)
      BackgroundFetch.finish(taskId);
    });

```
```
**To Reproduce**
Steps to reproduce the behavior:
1. Followed all the setup requirements for iOS :
2. Enabled backgroud_fetch and remote_processing
3. Add identifier in Info.plist : ```
<dict>
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>com.transistorsoft.fetch</string>
	</array>
```
4. Followed the debugging steps, but i a getting the below error , as the event is not getting schdeuled on real device

**Debug logs**
- ios XCode logs, :
```
(lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateExpirationForTaskWithIdentifier:@"com.transistorsoft.fetch"]
2021-05-09 11:09:48.846010-0700 Runner[4268:1932997] Simulating expiration for task with identifier com.transistorsoft.fetch
2021-05-09 11:09:48.846468-0700 Runner[4268:1932997] Task with identifier <decode: missing data> is not currently being simulated
```

**Additional context**

I am not able to simulate in background and it seems it doesn't work on my real test app released through , can you please help me if i am doing something wrong here ?

**Comment by christocracy** [comment]
Are you trying to simulate a fetch event?  Why are you using `simulateExpirationForTaskWithIdentifier`

**Comment by christocracy** [comment]
See [README](https://github.com/transistorsoft/flutter_background_fetch#ios-1).  You are executing the *Simulate Task Expiration* command.

**Comment by luvishq** [comment]
@christocracy : I tried with this  as well , getting the below issue : 

```
(lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]

2021-05-09 12:50:37.937217-0700 Runner[4380:1971818] Simulating launch for task with identifier com.transistorsoft.fetch
2021-05-09 12:50:41.856827-0700 Runner[4380:1972049] No task request with identifier <decode: missing data> has been scheduled
```

**Comment by luvishq** [comment]
@christocracy : Is there anything that's it not working on iOS? I don't see the callback being executed ?

**Comment by christocracy** [comment]
There is nothing wrong with the plugin.  Review readme and your code.  Simulated tasks do **not** work in simulator, as noted in readme.

**Comment by johnzhu123** [comment]
> @christocracy : I tried with this as well , getting the below issue :
> 
> ```
> (lldb) e -l objc -- (void)[[BGTaskScheduler sharedScheduler] _simulateLaunchForTaskWithIdentifier:@"com.transistorsoft.fetch"]
> 
> 2021-05-09 12:50:37.937217-0700 Runner[4380:1971818] Simulating launch for task with identifier com.transistorsoft.fetch
> 2021-05-09 12:50:41.856827-0700 Runner[4380:1972049] No task request with identifier <decode: missing data> has been scheduled
> ```
> 
> Also, I was wondering background fetch not happening on my test flight release, it works well on Android but not sure why it's not working on iOS ?

it also happened to me .
I'm also try this on my device(14.7.1) and I configured  exactly as you described

**Comment by johnzhu123** [comment]
@christocracy what did you do to make it work

**Comment by johnzhu123** [comment]
@christocracy 
all right, you know
if I use Debug->Simulate Background Fetch to Simulate background fetch events .
it all worked!
but Simulating events for BGTaskScheduler API for iOS 13+
not working , the above error occurred
but my device ios version is 14.7.1

**Comment by christocracy** [comment]
> simulateExpirationForTaskWithIdentifier

You're trying to simulate a *timeout* (ie "Expiration").  You're using the wrong command.  Go back to the readme and use the proper command.
