### ISSUE TITLE
[Q] F-Droid builds are failing since it cannot parse the templatized maven url

### ISSUE THREAD

**Issue by vishnukvmd** [transistorsoft/flutter_background_fetch#222]
Hey,

We are unable to submit our app to F-Droid as it is unable to parse `${project(':background_fetch').projectDir}/libs`: https://gitlab.com/saurabhav.torres/fdroiddata/-/jobs/1281087106#L2213

Could you please tell us how we could work around this?

Thanks again for the library!

**Comment by christocracy** [comment]
I have no experience with F-Droid.

**Comment by vishnukvmd** [comment]
@christocracy Thanks for the response. I understand that this is a limitation with F-Droid's build process.

Is there any way I can include this library as an `aar` dependency?

**Comment by christocracy** [comment]
> Is there any way I can include this library as an aar dependency?

I don't know.

**Comment by vishnukvmd** [comment]
Thanks. I'll update this issue once I find a solution.

**Comment by vishnukvmd** [comment]
So I was able to work around this, but now F-Droid is [breaking the build](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9022#note_581741566) because there are `aar`s present in https://github.com/transistorsoft/flutter_background_fetch/tree/master/android/libs/com/transistorsoft/tsbackgroundfetch

Could you please tell me why these are needed?

**Comment by vishnukvmd** [comment]
@christocracy So I was able to work around this, but now F-Droid is [breaking the build](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9022#note_581741566) because there are `aar`s present in https://github.com/transistorsoft/flutter_background_fetch/tree/master/android/libs/com/transistorsoft/tsbackgroundfetch

Could you please tell me why these are needed?

**Comment by christocracy** [comment]
This plugin's code is implemented in an a typical Android aar library which is portable between all versions of the plugin for Cordova, React Native and Flutter.  There is nothing at all unusual about this and it is not going to change.

**Comment by vishnukvmd** [comment]
@christocracy Okay, I understand. 

I can configure the F-Droid server to first build these `aar`s, then this plug-in and then my app.

The last two steps are done, and I'd like some help with the first. Could you please tell me how you have generated these `aar`s that are within your `lib` folder?

**Comment by vishnukvmd** [comment]
So I found https://github.com/transistorsoft/transistor-background-fetch, and was able to modify the build scripts to push the generated artifacts to `mavenLocal`. This has solved the issue. Thank you for your support. :)
