### ISSUE TITLE
[BUG] With 1.0.0-nullsafety.2, compiling gives "Execution failed for task ':app:checkDebugAarMetadata'. "

### ISSUE THREAD

**Issue by hyouuu** [transistorsoft/flutter_background_fetch#223]
**Your Environment**
* Plugin version: 1.0.0-nullsafety.2
* Platform: Android
* OS version: Android 10.0 API 29
* Device manufacturer / model: Google Pixel 4 emulator
* Flutter info (`flutter info`, `flutter doctor`):
* [✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
* Plugin config
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

    int status = await BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE), (String taskId) async {
      // <-- Event handler
      // This is the fetch-event callback.
      print("[BackgroundFetch] Event received $taskId");

      // IMPORTANT:  You must signal completion of your task or the OS can punish your app
      // for taking too long in the background.
      BackgroundFetch.finish(taskId);
    }, (String taskId) async {
      // <-- Task timeout handler.
      // This task has exceeded its allowed running-time.  You must stop what you're doing and immediately .finish(taskId)
      print("[BackgroundFetch] TASK TIMEOUT taskId: $taskId");
      BackgroundFetch.finish(taskId);
    });
    print('[BackgroundFetch] configure success: $status');

**To Reproduce**
pub get then compile

**Debug logs**
- Android: `$ adb logcat` NA since compile unsuccessful

**Additional context**
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/Users/shawn.gong/LycheeIsle/PendoFlutter/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://maven.google.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://www.jitpack.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://google.bintray.com/exoplayer/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
See the readme and follow the *Android Setup Instructions*.

This issue has been reported many times.  Please search issues before posting a new one.

**Comment by hyouuu** [comment]
I did search for "Execution failed for task ':app:checkDebugAarMetadata'. " but couldn't find any previous reports. Reading the readme didn't give me a obvious hint - could you refer to a previous issue?

**Comment by hyouuu** [comment]
@christocracy

**Comment by christocracy** [comment]
What you want to search is "* Could not find any matches for com.transistorsoft:tsbackgroundfetch:+*".

You didn't follow the *Android Setup Instructions*" in the readme.

**Comment by hyouuu** [comment]
Got it thanks for sharing the lib!

**Comment by christocracy** [comment]
> Reading the readme didn't give me obvious hints

![image](https://user-images.githubusercontent.com/14999/119913458-f5024e00-bf2b-11eb-9073-eebf021731d6.jpeg)
