### ISSUE TITLE
Background task doesn't run after a while[BUG]

### ISSUE THREAD

**Issue by SebastianRuettger** [transistorsoft/flutter_background_fetch#23]
**Your Environment**
* Plugin version: 1.21
* Platform: Android
* OS version: 8.0.0
* Device manufacturer / model: OnePlus 3T
* Flutter info (`flutter info`, `flutter doctor`): Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Android Studio (version 3.2)
[√] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
* Plugin config

**To Reproduce**
1.  BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true)
2. call background task
3. don't use the app for a day

**Comment by christocracy** [comment]
The Android plugin uses [JobScheduler](https://medium.com/google-developers/scheduling-jobs-like-a-pro-with-jobscheduler-286ef8510129).  Jobs will be throttled based upon app usage and whether the device is plugged into power or not.  You won't get events fired *exactly* every 15 minutes.  They *will* be delayed.

**Comment by SebastianRuettger** [comment]
That's what I thought too, but I then won't get any events for days.

**Comment by christocracy** [comment]
If the user operates your app normally (ie opening it regularly), this shouldn’t be a problem.

**Comment by SebastianRuettger** [comment]
The problem there is, that the usecase has the user opening the app every couple of days and then seeing all events

**Comment by christocracy** [comment]
I suggest sending a server push to devices you haven’t heard from in a while.

**Comment by SebastianRuettger** [comment]
That's what I was afraid of, thank you anyway

**Comment by christocracy** [comment]
Are you *simulating* fetch events to make sure everything is “wired up” properly?

If simulated events run, nothing else to do.  See README to learn how to simulate Android fetch events with `adb`

**Comment by SebastianRuettger** [comment]
The events are called for a long time, but after about a day it just stops

**Comment by christocracy** [comment]
And are you *sure* you're calling `BackgroundFetch.finish()` *each* time?  If you fail to, Android will punish your app and fire events less frequently.

**Comment by SebastianRuettger** [comment]
i have two calls to BackgroundFetch.finish() one in the background method and one after the call to the background method, just to be safe

**Comment by christocracy** [comment]
>i have two calls to BackgroundFetch.finish() one in the background method and one after the call to the background method, just to be safe

Show me what you mean by this.

**Comment by SebastianRuettger** [comment]
`void backgroundFetch() async {
  await fetchNewEntries(() {});
  BackgroundFetch.finish();
}`

`BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true), () async {
      fetchNewEntries(() {
        setState(() {});
      }).then((_) {
        setState(() {});
        BackgroundFetch.finish();
      });
    }).then((int status) {
      print("status: $status");
      setState(() {});
    });`

i know the second one looks horrible, all the calls to setstate are more for testing

**Comment by christocracy** [comment]
syntax-highlighting *multiple lines* requires **3 backticks**, not one:
![](https://dl.dropbox.com/s/06kibhk3jwhsvbq/Screenshot%202019-04-23%2019.27.48.png?dl=1)

**Comment by christocracy** [comment]
```
BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true), () async {
      fetchNewEntries(() {
        setState(() {});
      }).then((_) {
        setState(() {});
        BackgroundFetch.finish();  // <--- Pointless.  Get rid of this.  You are not within a fetch-event.
      });
    }).then((int status) {
      print("status: $status");
      setState(() {});
    });
```

**Comment by christocracy** [comment]
Actually, forget what I said above, re (`//<--- Pointless`).  I see that's in the callback to your `#fetchNewEntries` method, which is correct.

**Comment by christocracy** [comment]
Are you simulating background-fetch events with `adb`?  See the README to see how.  Are the simulated fetch events firing?  If so, I think think it's the purpose of Android `JobScheduler`:  If the user doesn't interact with the app for a long time, `JobScheduler` events are throttled.

**Comment by SebastianRuettger** [comment]
i havent simulated events, but background events work´for a while

**Comment by christocracy** [comment]
And are you opening the app daily, like a regular user would?

**Comment by SebastianRuettger** [comment]
No, I keep forgetting, but my usecase would have the user opening the app only every couple of days anyway

**Comment by christocracy** [comment]
I suggest you behave as a “regular user” and observe the behavior over a week or two.  Hopefully you’re sending an http request to your server as evidence an event occurs.

There’s nothing else to do.

**Comment by SebastianRuettger** [comment]
i log the calls in sqflite since the http request is to a server i dont own
