### ISSUE TITLE
[BUG] Build fails on Flutter version 2.2.2

### ISSUE THREAD

**Issue by mikeryder** [transistorsoft/flutter_background_fetch#231]
**Your Environment**
* Plugin version: 1.0.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: Emulator
* Flutter info (`flutter info`, `flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1081], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

* Plugin config

**To Reproduce**
1. cmd> flutter create myapp
2. Add background_fetch: ^1.0.0 to pubspec.yml
3. Attempt to build

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Build output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/C:/P/myapp/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

Let me know if there is any additional information I can provide.

**Comment by christocracy** [comment]
Duplicate #204.  Please search issues *before* posting a new one.

You didn't follow the **required Setup Instructions** in the README

![](https://dl.dropbox.com/s/9skipzmt17ka3bv/Screen%20Shot%202021-06-28%20at%2012.56.51%20PM.png?dl=1)
