### ISSUE TITLE
[QUESTION] Is it possible to configure two task with two different intervals?

### ISSUE THREAD

**Issue by raja-karthik** [transistorsoft/flutter_background_fetch#235]
**Is it possible to configure two task with two different intervals?**

_One Task with interval of 15 minutes.
Another one with interval of 24 hours._

**Comment by christocracy** [comment]
It's easy enough to try and see.

**Comment by raja-karthik** [comment]
Tried with two configure task. It will be Re-configured. Then, How to change the **minimumFetchInterval** value for schedule custom task.

**Comment by christocracy** [comment]
There's no such thing as "2 configure tasks".  .configure() is to be called once.

**Comment by raja-karthik** [comment]
Fine. How to change the `minimumFetchInterval ` value for `scheduleTask`? Its default set to `15`

**Comment by christocracy** [comment]
minimumFetchInterval is not an option of .scheduleTask.

Are you reading the api docs?

**Comment by raja-karthik** [comment]
Yes. How can I achieve the following?

One Task with interval of 15 minutes.
Another one with interval of 24 hours.

Recommend any solution?

**Comment by christocracy** [comment]
Why don't you just use the default fetch task to run every 15 minutes and simply check the time to see if 24 hours has elapsed since the previous day?

**Comment by raja-karthik** [comment]
Fine. Thank you so much.
