### ISSUE TITLE
 TimeoutException after 0:15:00.000000: Time limit reached while waiting for position update.[BUG]

### ISSUE THREAD

**Issue by aartiaparekh** [transistorsoft/flutter_background_fetch#238]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
You have ignored the issue template and provided no information.

> Plugin version:
Platform: iOS or Android
OS version:
Device manufacturer / model:
Flutter info (flutter info, flutter doctor):
Plugin config
