### ISSUE TITLE
[BUG] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by MrEmii** [transistorsoft/flutter_background_fetch#239]
**Dev Environment**
* Plugin version: ^1.0.0-nullsafety.2
* Platform: Android
* OS version: 10
* Device manufacturer / model: LG LM-X520HM
* Flutter info (`flutter info`, `flutter doctor`):
```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale es_MX.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)
```

* Plugin config

**To Reproduce**
1. register Headless Task in main
2. debug app

**Debug logs**
- Android: `$ adb logcat`
```
08-16 23:37:20.150 10232 10341 I flutter : [BackgroundFetch] configure success: 2
08-16 23:37:23.788 10232 10341 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
08-16 23:37:23.788 10232 10341 E flutter : #0      BackgroundFetch.registerHeadlessTask (package:background_fetch/background_fetch.dart:615:50)
08-16 23:37:23.788 10232 10341 E flutter : #1      main (package:chek/main.dart:47:25)
08-16 23:37:23.788 10232 10341 E flutter : <asynchronous suspension>
08-16 23:37:23.788 10232 10341 E flutter : 

```

**Comment by Trteich** [comment]
I have very simmilar issue, but exception in another line

else mess : Null check operator used on a null value - #0      BackgroundFetch.registerHeadlessTask (package:background_fetch/background_fetch.dart:621:50)
I/flutter ( 6930): #1      BackgroundTask.schedulePeriodicalTask (package:step_tribe/util/background_task.dart:43:23)
I/flutter ( 6930): <asynchronous suspension>
