### ISSUE TITLE
[Question] iOS terminated process

### ISSUE THREAD

**Issue by nongtiny** [transistorsoft/flutter_background_fetch#241]
**Is your feature request related to a problem? Please describe.**

I have read the README in this project. It seems like iOS is impossible to work when it's in the terminated state.

I have a question about this package https://www.transistorsoft.com/shop/products/flutter-background-geolocation. Your team didn't mention that this will not work when iOS is in the terminated state. Is the task going to work when the iOS is in the terminated state for the `flutter-background-geolocation`?

What I'm trying to do with the background process is to submit the data to the server with HTTP request. There's no need to be the exact time, but it should be able to run at least one time a day.

Thanks for developing this great library and thanks in advance.

**Comment by christocracy** [comment]
Yes, `flutter_background_geolocation` is able to continue tracking after iOS app is terminated.  Once the iOS device moves about 200 meters beyond last known location, the OS automatically re-launches the app in the background and tracking resumes.  See `flutter_background_geolocation` API docs `Config.stopOnTerminate` for more information.

**Comment by Mayb3Nots** [comment]
Hi @christocracy,

I was wondering why this package cant do the same thing with what `fluter_background_geolocation` is doing and when IOS app is terminated just use `startMonitoringSignificantLocationChanges` to listen for changes and start the app? Is there a limitation that I am missing here?

**Comment by Mayb3Nots** [comment]
Ahh whops I think I might have messed up the package's functionality haha my bad.

But in my case I want to send the device's location every few hours. It would be nice if add an optional feature to allow the package to open the app in the background when user has moved. However I think it would be out of the package's scope. Thanks for fast reply.

**Comment by christocracy** [comment]
Background_fetch is never going to be involved with location apis.

use my background_geolocation.  You cannot have a location “every few hours” — only every kilometer useSignificantChangesOnly).  It is impossible with iOS.
