### ISSUE TITLE
Headless task not working in Redmi Note 7 pro

### ISSUE THREAD

**Issue by raja-karthik** [transistorsoft/flutter_background_fetch#244]
**Headless task working perfectly in samsung Tab A. But not working in Redmi note 7 pro and Note 5 pro.**

I have run the task in forground and background in Redmi note 7 pro / 5 pro  using `adb shell cmd jobscheduler run -f <my.package.id> 999`. It works fine. But I run after close the app., its not. 

Anything needs to be include ? or any suggestion to works with redmi note 7 pro / 5 pro. ?

**Comment by christocracy** [comment]
Have you tried consulting http://dontkillmyapp.com

**Comment by raja-karthik** [comment]
Yes. Tried. But can't helped me.

**Comment by christocracy** [comment]
Are you watching logs from adb logcat?

**Comment by raja-karthik** [comment]
Yes. Using `adb logcat *:S flutter:V, TSBackgroundFetch:V`

**Comment by christocracy** [comment]
Those are *filtered* logs.

**Comment by raja-karthik** [comment]
Getting headless task logs for samsung, using this `adb logcat *:S flutter:V, TSBackgroundFetch:V`, but not getting for Redmi.

**Comment by christocracy** [comment]
Observe **un-filtered** logs with:

```
$ adb logcat
```

**Comment by christocracy** [comment]
And what is the specific Android OS version?

**Comment by raja-karthik** [comment]
> And what is the specific Android OS version?

Device: Redmi Note 7 pro
OS Version: Android 10

**Comment by TMAnhoangthinh** [comment]
I have the same on this issue

**Comment by christocracy** [comment]
> I have the same on this issue

And you've provided no details (plugin version, device model/os version or logs), not have you specified whether you've applied http://dontkillmyapp.com.
