### ISSUE TITLE
[BUG] NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

### ISSUE THREAD

**Issue by KorbinianMossandl** [transistorsoft/flutter_background_fetch#247]
**Your Environment**
* Plugin version: 1.0.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: 
  Nexus 5X
  Model:MTC20F
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

* Plugin config
      minimumFetchInterval: 30,
      stopOnTerminate: false,
      enableHeadless: true,
      startOnBoot: true,
      requiredNetworkType: NetworkType.ANY,

**To Reproduce**
not sure, see additional context

**Debug logs**
NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

com.transistorsoft.flutter.backgroundfetch.HeadlessTask$b in run at line 1
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1113
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 588
java.lang.Thread in run at line 818

**Additional context**
we got this issue on our app reported via sentry, thus i am not sure how to reproduce. BackgroundFetch seems to work fine on all our test devices, so maybe it is a device specific thing. Still did want to report it in, in case this is something you want or even can fix on your end.

**Comment by christocracy** [comment]
Duplicate #161.  This is a "fake" crash produced by Google's testing system when an app is uploaded.

**Comment by simion** [comment]
![Screenshot 2021-09-18 at 15 47 08](https://user-images.githubusercontent.com/2630797/133889272-72f92e68-6c6f-4c62-8464-bd4fcf14473b.png)
This does seem like a bug.
