### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by bismarabia** [transistorsoft/flutter_background_fetch#252]
As I could see from the pub description, flutter web is currently not supported.

It would be great to add web support as well.

Any plan to work on web?

**Comment by christocracy** [comment]
No.  The concept of "background location" doesn't exist for browser app.  Much of the apis of this sdk don't exist in the browser:
- SQLite
- Motion api (accelerometer, gyroscope, magnetometer)
- Geofencing API

This sdk only makes sense for iOS / Android devices.
