### ISSUE TITLE
[Question] Is there any way to run on boot?

### ISSUE THREAD

**Issue by Babsky** [transistorsoft/flutter_background_fetch#254]
background_fetch: v1.0.1
I'm aware the plugin has a "startOnBoot" option but this starts the interval countdown. Is there any way to run on boot rather than wait for the interval period? 
My background job only needs to run once a day but I have set the minimumFetchInterval to 360 as I can't specify a time and I need it to run early in the day.

**Comment by christocracy** [comment]
Why don't you simply run a more frequent interval and keep track of the time the last event occurred (in shared_preferences).

When your desired interval has occurred, run your task, otherwise immediately call `BackgroundFetch.finish(taskId)`.

There's no harm running a task every 15min.

**Comment by Babsky** [comment]
Of course I have considered it but it seems pointless running it multiple times a day when it's only needed once, I thought it would be "cleaner" if it ran on boot. Also I'm wondering if my app is more likely to be killed by the OS if it runs a background task too often. I know there is a big issue around phone manufacturers killing apps. On a physical device, I've added my app to the "Don't optimise" list but the background task is still not running as it should, it only runs the first time after each re-installation. 
I will have to somehow handle devices that are not switched off daily as well so I might just go down your suggested route.  

Thanks

**Comment by christocracy** [comment]
> runs a background task too often.

This is not a concern since the plugin is using [JobScheduler](https://youtu.be/vBjTXKpaFj8?list=PLWz5rJ2EKKc-lJo_RGGXL2Psr8vVCTWjM) which intelligently time-slices jobs to run at the same time for all apps on the device.

You do not need to be concerned about Android terminating your app for using JobScheduler exactly as it's designed to be used.

**Comment by Babsky** [comment]
ok, thanks for that. 
I previously added a time check in the task that's run by the background fetch but found it didn't work, maybe the JobScheduler is the reason for that. I don't know what did or didn't work because the task triggers a notification, so I don't know if the task wasn't run or it did but the notification didn't work.
I shall persist
