### ISSUE TITLE
[README BUG] Recommended package version is unsound

### ISSUE THREAD

**Issue by trueb2** [transistorsoft/flutter_background_fetch#258]
**Additional context**
The README recommends to install an old package version that has unsound null safety. It does not compile (without --no-sound-null-safety).

1.0.3 is latest on pub.dev right now, but 0.7.0 is recommended on README. I have no problems building with 1.0.3
```
dependencies:
  background_fetch: '^0.7.0'
```

```
    Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:background_fetch

    For solutions, see https://dart.dev/go/unsound-null-safety
```

Is there any reason for this to look out for? There is an older PR out about this value as well.

**Comment by christocracy** [comment]
Obviously the readme is wrong.  Why not make a PR?

**Comment by trueb2** [comment]
I know some maintainers don't want trivial PRs from random contributors. Closing the issue here.

**Comment by christocracy** [comment]
To me, README PRs are the easiest and safest thing to merge.
