### ISSUE TITLE
Keeping it alive on iOS

### ISSUE THREAD

**Issue by Swepilot** [transistorsoft/flutter_background_fetch#261]
Dear @christocracy,

I've been using `flutter_background_fetch` for some time now and it does exactly what it's advertised to do, both on Android and iOS. Thank you for that. However, as you might suspect, the constant feedback from the users of my app is that they want true background service processing on iOS, as in working when the app is terminated.

In my case the background service involves making a http request and updating a record in a sqlite database based on the http response.

I have seen in your Geolocation package that you are able to keep the service alive even with the app terminated, so you are obviously deep into the workings of background processing on iOS. Is there any chance that could ever be added to the `flutter_background_fetch` package (even as a paid package), or is it just the fact that you are using location services that makes it possible to run while the app is terminated? If so is the only option, in your opinion, to resort to native iOS development?

Thanks!

**Comment by christocracy** [comment]
> Is there any chance that could ever be added

No.  iOS does not allow its background-fetch events to fire once app is terminated.  There is no way to do this short of taking your concern to Apple and pleading with them.

there is no way to do this at all.

yes, Apple gives location-updates special powers to operated in the terminated state.
