### ISSUE TITLE
[HELP] Plugin inside another plugin.

### ISSUE THREAD

**Issue by blkfry** [transistorsoft/flutter_background_fetch#262]
Hey guys I'm looking for some help on how I can setup this plugin inside a complex project.
The project has this structure:
- App1
- .......
- App7 
- Shared
  - common_lib -> this plugin integrates plugin1 and background_worker
  - plugin1
  - background_worker -> this plugin has background_fetch as a dependency

Each app knows about background_worker through the common_lib plugin.

My question is is how do I make android see the libs when the pluggin is included in another pluggin.
The line that I have no idea how to modify is 'url "${project(':background_fetch').projectDir}/libs'.

**Comment by christocracy** [comment]
I don’t know.  The plugin requires configuration in the root android/build.gradle.
