### ISSUE TITLE
[Not a bug] Headless tasks don't work because of some libraries

### ISSUE THREAD

**Issue by MXilian** [transistorsoft/flutter_background_fetch#263]
I'm just providing this information in case anyone finds it useful.

I found that headless tasks don't work because of the keyboard_visibility and custom_image_picker libraries. As soon as I removed them from the project, flutter_background_fetch started working fine.

Perhaps it would be possible to keep a list of incompatible libraries in the description?

**Comment by christocracy** [comment]
> Perhaps it would be possible to keep a list of incompatible libraries in the description?

That is infeasible.  

Perhaps you should investigate the source of the problem and/or raise an issue at those other repos?

**Comment by MXilian** [comment]
Of course, the problem connected with these other repo. But since it pops up exactly when trying to start a headless task, I posted information about this here: perhaps it will save someone time when looking for a problem.

**Comment by christocracy** [comment]
It’s well known that other libs have made the mistake of writing plugin initialization code assuming an Android Activity exists without doing a null check.

I suggest you capture as much log information as you can and raise issues with those other libs.
