### ISSUE TITLE
[BUG] Unresolved reference: FOREGROUND_SERVICE_IMMEDIATE

### ISSUE THREAD

**Issue by roshandroids** [transistorsoft/flutter_background_fetch#266]
**Your Environment**
* Plugin version: background_fetch: ^1.0.3
* Platform:  Android
* OS version: Android 11
* Device manufacturer / model: One Plus Nord

**Debug logs**

e: /Users/roshanshrestha/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (215, 53): Unresolved reference: S
e: /Users/roshanshrestha/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (216, 13): Unresolved reference: setForegroundServiceBehavior
e: /Users/roshanshrestha/.pub-cache/hosted/pub.dartlang.org/flutter_foreground_task-3.5.5/android/src/main/kotlin/com/pravera/flutter_foreground_task/service/ForegroundService.kt: (216, 55): Unresolved reference: FOREGROUND_SERVICE_IMMEDIATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_foreground_task:compileDebugKotlin'.
> Compilation error. See log for more details

**Comment by christocracy** [comment]
> What went wrong:
Execution failed for task ':flutter_foreground_task:

You are posting your error at the wrong GitHub repo.  Your error is with something called `flutter_foreground_task`
