### ISSUE TITLE
Could not find any matches for com.transistorsoft:tsbackgroundfetch:

### ISSUE THREAD

**Issue by mohas15** [transistorsoft/flutter_background_fetch#267]
**Your Environment**: Android Studio
* Plugin version:   background_fetch: ^1.0.3
* Platform: Flutter for both iOS and Android

Since yesterday flutter is not able to compile because of this package. I see that bintray is running again, but this package is not. All links printed out from Flutter gives 404:

```

`* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/user/StudioProjects/app/node_modules/react-native-background-fetch/android/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/home/user/StudioProjects/app/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch`

```

I have specified this as the readme told in build.gradle:
`        maven { url "$rootDir/../node_modules/react-native-background-fetch/android/libs" }`

build.gradle:
```

buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "$rootDir/../node_modules/react-native-background-fetch/android/libs" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Flutter Doctor:**
[✓] Flutter (Channel master, 2.9.0-1.0.pre.337, on Ubuntu 21.10 5.13.0-20-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2020.3)
[✓] VS Code
[✓] Connected device (1 available)
[✓] HTTP Host Availability

**Comment by christocracy** [comment]
Duplicate #204 

please *search* before posting.

**Comment by mohas15** [comment]
I did search before i posted, and I went through the issues. The package have been working fine until bintray went down yesterday, now it's not working, as I wrote in my issue.  What you linked has nothing to do with this issue, it's not asking about dependencies, it's telling me it can't get any version number.
