### ISSUE TITLE
[Question] Does this package register for a task with the identifier dev.flutter.background.refresh?

### ISSUE THREAD

**Issue by paulhulatt** [transistorsoft/flutter_background_fetch#269]
I am getting the following error on iOS:

[TSBackgroundFetch registerForTaskWithIdentifier: dev.flutter.background.refresh
*** Assertion failure in -[BGTaskScheduler _unsafe_registerForTaskWithIdentifier:usingQueue:launchHandler:], BGTaskScheduler.m:189
2022-02-04 15:05:07.880610+0000 Runner[632:66707] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Launch handler for task with identifier dev.flutter.background.refresh has already been registered'

I also have flutter_background_service in my project so are you using the same task identifier "dev.flutter.background.refresh"?

**Comment by christocracy** [comment]
Follow the [Setup Steps](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md#configure-infoplist) exactly as documented.

The *Permissted background task scheduler identifiers* ` com.transistorsoft.fetch` is **required**.

**Comment by paulhulatt** [comment]
Yes I understand that and it is working.  However, I now need to use flutter_background_service and when I try to add it's required "dev.flutter.background.refresh" to the list of _Permitted background task scheduler identifiers_ I get the error above from TSBackgroundFetch.  

It's almost as if this component is using the _Permitted background task scheduler identifiers_ array as a list of processes to register for itself?

**Comment by paulhulatt** [comment]
> Yes I understand that and it is working. However, I now need to use flutter_background_service and when I try to add it's required "dev.flutter.background.refresh" to the list of _Permitted background task scheduler identifiers_ I get the error above from TSBackgroundFetch.
> 
> It's almost as if this component is using the _Permitted background task scheduler identifiers_ array as a list of processes to register for itself?

Yes I understand that and it is working. However, I now need to use flutter_background_service and when I try to add it's required "dev.flutter.background.refresh" to the list of Permitted background task scheduler identifiers I get the error above from TSBackgroundFetch.

It's almost as if this component is using the Permitted background task scheduler identifiers array as a list of processes to register for itself?

**Comment by paulhulatt** [comment]
> Follow the [Setup Steps](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md#configure-infoplist) exactly as documented.
> 
> The _Permitted background task scheduler identifiers_ ` com.transistorsoft.fetch` is **required**.

Yes I understand that and it is working. However, I now need to use flutter_background_service and when I try to add it's required "dev.flutter.background.refresh" to the list of Permitted background task scheduler identifiers I get the error above from TSBackgroundFetch.

It's almost as if this component is using the Permitted background task scheduler identifiers array as a list of processes to register for itself?

**Comment by christocracy** [comment]
An app may only have one entry-point for iOS background-fetch.  You cannot have multiple plugins implementing iOS background-fetch.

You should just ignore the iOS Setup for flutter_background_service.
