### ISSUE TITLE
Why every 15 min? 

### ISSUE THREAD

**Issue by SGuzel** [transistorsoft/flutter_background_fetch#27]
Hi,
why is the minimum fetch time 15 min?

**Comment by christocracy** [comment]
Native api limitation, to prevent you from abusing the user’s battery.

**Comment by HElwy** [comment]
@christocracy may I ask if I can bypass this while the app is in development and running in debug mode?

**Comment by christocracy** [comment]
@HElwy No.  

[Simulate Fetch Events](https://github.com/transistorsoft/flutter_background_fetch#large_blue_diamond-debugging)

**Comment by HElwy** [comment]
Thank you for the quick response :smile:
