### ISSUE TITLE
[BUG] Cannot run backgroundFetchHeadlessTask when the app is closed/terminated.

### ISSUE THREAD

**Issue by philiposD** [transistorsoft/flutter_background_fetch#278]
I'm trying to make **backgroundFetchHeadlessTask** to run when the app is closed/terminated.
Unfortunately, I'm not getting any error when I try to close it, it just doesn't run the function after a while or when I close it.

The purpose was to have periodically a function to call and show a local notification / toast. (every X seconds/mins).

Want to mention that when the app is minimized, the **_onBackgroundFetch** is running accordingly.

**Your Environment**
* Plugin version: latest
* Platform: Android
* OS version: API 30
* Device manufacturer / model: emulator
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.2.2 20D80 darwin-x64, locale en-GI)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.65.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

* Plugin config: no special config  added.

**To Reproduce**
1. Open/Use example app
2. Update **pubspec.yml** by adding **fluttertoast** and **flutter_local_notifications** and **rxdart**.  Run flutter pub get
3. Replace code for main.dart
4. Run the app, check behavior.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

### Modified files:

Added app_icon.png (some random icon) under:
`....    /android/app/src/main/res/drawable/app_icon.png`

**pubspec.yml:**
```yml
name: background_fetch_example
description: Demonstrates how to use the background_fetch plugin.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0-nullsafety
  cupertino_icons: ^0.1.2
  fluttertoast: ^7.1.8
  flutter_local_notifications: ^9.4.0
  rxdart: any

dev_dependencies:
  test: ^1.5.1
  flutter_driver:
    sdk: flutter

  background_fetch:
    path: ../



# The following section is specific to Flutter.
flutter:
  uses-material-design: true
```

**main.dart**

```dart
import 'dart:async';
import 'dart:convert';

import 'package:background_fetch/background_fetch.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:rxdart/subjects.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:fluttertoast/fluttertoast.dart';

/// SharedPreferences data key.
const EVENTS_KEY = "fetch_events";

Future<void> _showNotification(String title) async {
  const AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails('your channel id', 'your channel name',
          channelDescription: 'your channel description',
          importance: Importance.max,
          priority: Priority.high,
          ticker: 'ticker');
  const NotificationDetails platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
      1, '$title', 'plain body', platformChannelSpecifics,
      payload: 'item x1');
}

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  var taskId = task.taskId;
  var timeout = task.timeout;

  Fluttertoast.showToast(
      msg: "This is a Toast message $taskId", // message
      toastLength: Toast.LENGTH_SHORT, // length
      gravity: ToastGravity.CENTER, // location
      timeInSecForIosWeb: 1 // duration
      );

  _showNotification("Background notif - app NOT RUNNING");

  if (timeout) {
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }

  print("[BackgroundFetch] Headless event received: $taskId");

  var timestamp = DateTime.now();

  var prefs = await SharedPreferences.getInstance();

  // Read fetch_events from SharedPreferences
  var events = <String>[];
  var json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  // Add new event.
  events.insert(0, "$taskId@$timestamp [Headless]");
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));

  if (taskId == 'flutter_background_fetch') {
    // DISABLED:  uncomment to fire a scheduleTask in headlessTask.
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "com.transistorsoft.customtask",
        delay: 5000,
        periodic: true,
        forceAlarmManager: false,
        stopOnTerminate: false,
        enableHeadless: true));
  }
  BackgroundFetch.finish(taskId);
}

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

void main() {
  // Enable integration testing with the Flutter Driver extension.
  // See https://flutter.io/testing/ for more info.
  runApp(MyApp());

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _enabled = true;
  int _status = 0;
  List<String> _events = [];

  @override
  void initState() {
    super.initState();
    initPlatformState();
    setupNotif();
  }

  void setupNotif() async {
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('app_icon');

    final IOSInitializationSettings initializationSettingsIOS =
        IOSInitializationSettings(
            requestAlertPermission: false,
            requestBadgePermission: false,
            requestSoundPermission: false,
            onDidReceiveLocalNotification: (
              int id,
              String title,
              String body,
              String payload,
            ) async {
              // didReceiveLocalNotificationSubject.add(
              //   null
              // );
            });
    const MacOSInitializationSettings initializationSettingsMacOS =
        MacOSInitializationSettings(
      requestAlertPermission: false,
      requestBadgePermission: false,
      requestSoundPermission: false,
    );
    final LinuxInitializationSettings initializationSettingsLinux =
        LinuxInitializationSettings(
      defaultActionName: 'Open notification',
      defaultIcon: AssetsLinuxIcon('icons/app_icon.png'),
    );
    final InitializationSettings initializationSettings =
        InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
      macOS: initializationSettingsMacOS,
      linux: initializationSettingsLinux,
    );

    String selectedNotificationPayload;

    final BehaviorSubject<String> selectNotificationSubject =
        BehaviorSubject<String>();

    await flutterLocalNotificationsPlugin.initialize(initializationSettings,
        onSelectNotification: (String payload) async {
      if (payload != null) {
        debugPrint('notification payload: $payload');
      }
      selectedNotificationPayload = payload;
      selectNotificationSubject.add(payload);
    });
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    // Load persisted fetch events from SharedPreferences
    var prefs = await SharedPreferences.getInstance();
    var json = prefs.getString(EVENTS_KEY);
    if (json != null) {
      setState(() {
        _events = jsonDecode(json).cast<String>();
      });
    }

    // Configure BackgroundFetch.
    try {
      var status = await BackgroundFetch.configure(
          BackgroundFetchConfig(
            minimumFetchInterval: 1,
            forceAlarmManager: true,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE,
          ),
          _onBackgroundFetch,
          _onBackgroundFetchTimeout);
      print('[BackgroundFetch] configure success: $status');
      setState(() {
        _status = status;
      });

      // Schedule a "one-shot" custom-task in 10000ms.
      // These are fairly reliable on Android (particularly with forceAlarmManager) but not iOS,
      // where device must be powered (and delay will be throttled by the OS).
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 10000,
          periodic: true,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true));
    } on Exception catch (e) {
      print("[BackgroundFetch] configure ERROR: $e");
    }

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

  void _onBackgroundFetch(String taskId) async {
    var prefs = await SharedPreferences.getInstance();
    var timestamp = DateTime.now();
    // This is the fetch-event callback.
    print("[BackgroundFetch] Event received: $taskId");
    _showNotification("Background notif - app RUNNING");

    // Fluttertoast.showToast(
    //     msg: "BACKGROUND, still running", // message
    //     toastLength: Toast.LENGTH_SHORT, // length
    //     gravity: ToastGravity.CENTER, // location
    //     timeInSecForIosWeb: 1 // duration
    //     );

    setState(() {
      _events.insert(0, "$taskId@${timestamp.toString()}");
    });
    // Persist fetch events in SharedPreferences
    prefs.setString(EVENTS_KEY, jsonEncode(_events));

    if (taskId == "flutter_background_fetch") {
      // Schedule a one-shot task when fetch event received (for testing).
      BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.transistorsoft.customtask",
          delay: 5000,
          periodic: false,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true,
          requiresNetworkConnectivity: true,
          requiresCharging: true));
    }
    // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
    // for taking too long in the background.
    BackgroundFetch.finish(taskId);
  }

  /// This event fires shortly before your task is about to timeout.  You must finish any outstanding work and call BackgroundFetch.finish(taskId).
  void _onBackgroundFetchTimeout(String taskId) {
    print("[BackgroundFetch] TIMEOUT: $taskId");
    BackgroundFetch.finish(taskId);
  }

  void _onClickEnable(enabled) {
    setState(() {
      _enabled = enabled;
    });
    if (enabled) {
      BackgroundFetch.start().then((status) {
        print('[BackgroundFetch] start success: $status');
      }).catchError((e) {
        print('[BackgroundFetch] start FAILURE: $e');
      });
    } else {
      BackgroundFetch.stop().then((status) {
        print('[BackgroundFetch] stop success: $status');
      });
    }
  }

  void _onClickStatus() async {
    var status = await BackgroundFetch.status;
    print('[BackgroundFetch] status: $status');
    setState(() {
      _status = status;
    });
  }

  void _onClickClear() async {
    var prefs = await SharedPreferences.getInstance();
    prefs.remove(EVENTS_KEY);
    setState(() {
      _events = [];
    });
  }

  @override
  Widget build(BuildContext context) {
    Fluttertoast.showToast(
        msg: "This is a Toast message in build", // message
        toastLength: Toast.LENGTH_SHORT, // length
        gravity: ToastGravity.CENTER, // location
        timeInSecForIosWeb: 1 // duration
        );

    const EMPTY_TEXT = Center(
        child: Text(
            'Waiting for fetch events.  Simulate one.\n [Android] \$ ./scripts/simulate-fetch\n [iOS] XCode->Debug->Simulate Background Fetch'));

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
            title: const Text('BackgroundFetch Example',
                style: TextStyle(color: Colors.black)),
            backgroundColor: Colors.amberAccent,
            foregroundColor: Colors.black,
            actions: <Widget>[
              Switch(value: _enabled, onChanged: _onClickEnable),
            ]),
        body: (_events.isEmpty)
            ? EMPTY_TEXT
            : Container(
                child: ListView.builder(
                    itemCount: _events.length,
                    itemBuilder: (context, index) {
                      var event = _events[index].split("@");
                      return InputDecorator(
                          decoration: InputDecoration(
                              contentPadding: EdgeInsets.only(
                                  left: 5.0, top: 5.0, bottom: 5.0),
                              labelStyle:
                                  TextStyle(color: Colors.blue, fontSize: 20.0),
                              labelText: "[${event[0].toString()}]"),
                          child: Text(event[1],
                              style: TextStyle(
                                  color: Colors.black, fontSize: 16.0)));
                    }),
              ),
        bottomNavigationBar: BottomAppBar(
            child: Container(
                padding: EdgeInsets.only(left: 5.0, right: 5.0),
                child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: <Widget>[
                      ElevatedButton(
                          onPressed: _onClickStatus,
                          child: Text('Status: $_status')),
                      ElevatedButton(
                          onPressed: _onClickClear, child: Text('Clear'))
                    ]))),
      ),
    );
  }
}
```

**Comment by christocracy** [comment]
Are you *simulating* your Android fetch events?

**Comment by philiposD** [comment]
No, I thought those fetch events are periodically simulated in the background, so the given code will execute.

**Comment by christocracy** [comment]
Simulate an event.  That’s all you need to know that it’s listening and operating correctly.

everything else is in the hands of the OS.

**Comment by philiposD** [comment]
Sorry but apparently I forgot to post and close this issue.
I have made it work right after when I reconfigured the **_headless task_** and **_onBrackgroundFetch_** callback.

```dart
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  var taskId = task.taskId;
  var timeout = task.timeout;

  if (timeout) {
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }

  print("[BackgroundFetch] Headless event received: $taskId");

  if (taskId == "flutter_background_fetch") {
    _showNotification("Background notif - app NOT RUNNING");
    BackgroundFetch.finish(taskId);
    return;
  }

  BackgroundFetch.finish(taskId);
}
```

```dart
void _onBackgroundFetch(String taskId) async {
  print("[BackgroundFetch] Event received: $taskId");

  if (taskId == "flutter_background_fetch") {
    _showNotification("Background _onBackgroundFetch - app running");
  }
  BackgroundFetch.finish(taskId);
}
```

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());

  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

```dart
  Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    int status = await BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            forceAlarmManager: true,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: NetworkType.NONE),
        _onBackgroundFetch, _onBackgroundFetchTimeout;
    print('[BackgroundFetch] configure success: $status');

    if (!mounted) return;
  }
```

**Comment by Prog13NetPlus** [comment]
can u help me ? i have maybe similar problem, i want to update my location for example every 2-3mins, i should use background-fetch and headless but i dont have idea from where to start :)

**Comment by christocracy** [comment]
Start by installing the /example app in this repo.

**Comment by Prog13NetPlus** [comment]
CEO Transistor Software. Creator of background-geolocation for Cordova, React Native and Flutter. iOS / Android location API specialist.
Though u should know what i am talking about and give some hint..

**Comment by christocracy** [comment]
You're posting at the **wrong** repo.

I create plug-in for **four** different platforms:  Cordova, Capacitor, React Native and Flutter.

Tech support is handled by posting an issue at the appropriate repo.  If you're using Cordova, the Flutter repo is the wrong place to seek support.

**Comment by Krutimeetmighty** [comment]
Hello,
i have created same example for notification that generates even if app is terminated.
but i want to generate notification for different like for water notification will ring at 12 pm for medicine it will generate at everyday 4 pm .
Thanks

**Comment by christocracy** [comment]
>but i want to generate notification for different like for water notification will ring at 12 pm for medicine it will generate at everyday 4 pm .

Analyze the time with each received event.
- if the current time is close to "12pm", show your notification.
- if the current time is close to "4pm", show your notifiction.

**Comment by Krutimeetmighty** [comment]
Hello, 
thanks for replay.
step 1: confiugrration
   var status = await BackgroundFetch.configure(
          BackgroundFetchConfig(
            minimumFetchInterval: 1,
            forceAlarmManager: true,
            stopOnTerminate: false,
            startOnBoot: true,
            enableHeadless: true,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
          ),
          _onBackgroundFetch,
          _onBackgroundFetchTimeout);
      print('[BackgroundFetch] configure success: $status');
 } on Exception catch (e) {
      print("[BackgroundFetch] configure ERROR: $e");
    }
    
   step 2 :  _onBackgroundFetch()
     void _onBackgroundFetch(String taskId) async {
    var prefs = await SharedPreferences.getInstance();
    var timestamp = DateTime.now();
    print("[BackgroundFetch] Event received: $taskId");
    switch (taskId) {
      case TASK_MEDITATION:
        showNotification(taskId: TASK_MEDITATION);
        scheduleNextDayReminder(taskId: TASK_MEDITATION);
    
        break;
   
      default:
        print(": $taskId");
    }
    
    print("Unknown task id: $taskId");

    setState(() {
      backgroundEvents.insert(0, "$taskId@${timestamp.toString()}");
    });
    prefs.setString(EVENTS_KEY, jsonEncode(backgroundEvents));
    
  }
  
  step :3 
  @pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  var taskId = task.taskId;
  var timeout = task.timeout;
  print("task id===================This is a Toast message}");

  if (timeout) {
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }
  print("[BackgroundFetch] Headless event received: $taskId");
  switch (taskId) {
    case TASK_MEDITATION:
      showNotification(taskId: TASK_MEDITATION);
      scheduleNextDayReminder(taskId: TASK_MEDITATION);
      break;
    default:
      print("Unknown task id: $taskId");
  }

  var timestamp = DateTime.now();

  var prefs = await SharedPreferences.getInstance();

  // Read fetch_events from SharedPreferences
  var events = <String>[];
  var json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  // Add new event.
  events.insert(0, "$taskId@$timestamp [Headless]");
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));
  
}
step :4
scheduleNextDayReminder({required String taskId}) {
  ReminderModel item = getReminderByTaskId(taskId: taskId);
  BackgroundFetch.scheduleTask(TaskConfig(
    taskId: item.taskId!,
    delay: calculateDelayUntilTomorrow(hour: item.hours!, minutes: item.minutes!),
    forceAlarmManager: true,
    stopOnTerminate: false,
    enableHeadless: true,
  ));
}

int calculateDelayUntilTomorrow({required int hour, required int minutes}) {
  final now = DateTime.now();
  final tomorrow = DateTime(now.year, now.month, now.day + 1, hour, minutes);
  return tomorrow.difference(now).inSeconds;
}
Future<void> showNotification({required String taskId}) async {
  ReminderModel item = getReminderByTaskId(taskId: taskId);
  await AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: item.index!,
      channelKey: 'scheduled_channel',
      title: item.title,
      body: item.hours.toString() + item.minutes.toString(),
      notificationLayout: NotificationLayout.Default,
    ),
    actionButtons: [
      NotificationActionButton(key: 'MARK_DONE', label: 'Mark Done'),
    ],
  );
}
when user click on swirch for meditaiton i am shceduling task with particular id and time
 Switch(
                    value: data!.isReminderOn!,
                    onChanged: (value) async {
                      print("================value${value}");
                      if (!data!.isReminderOn!) {
                        timeOfDay = await showTimePicker(
                            context: context,
                            initialTime: TimeOfDay.fromDateTime(
                              DateTime.now().add(Duration(minutes: 1)),
                            ),
                            builder: (BuildContext context, Widget? child) {
                              return child!;
                            });
                        BackgroundFetch.scheduleTask(TaskConfig(
                            taskId: data!.taskId!,
                            delay: calculateDelayForTimeOfDay(hour: timeOfDay!.hour, minute: timeOfDay!.minute),
                            periodic: false,
                            forceAlarmManager: true,
                            stopOnTerminate: false,
                            enableHeadless: true));
                      } else {
                        //   BackgroundFetch.finish(data!.taskId!);
                      }

                      setState(() {
                        list.forEach((element) {
                          if (element.index == widget.index) {
                            element.minutes = timeOfDay != null ? timeOfDay!.minute : 00;
                            element.hours = timeOfDay != null ? timeOfDay!.hour : 00;
                            element.isReminderOn = !data!.isReminderOn!;
                            data = element;
                            setState(() {});
                          }
                        });
                      });

                      setReminders(data: list);
                      await getReminders().then((value) {
                        list = value;
                      });
                      list.forEach((element) {
                        print("============${element.title}");
                      });
                    },
                  ),
         i get instsnt notification when i switch on then after at set time i am not getting notification .
