### ISSUE TITLE
When your app is terminated, iOS no longer fires events

### ISSUE THREAD

**Issue by desmeit** [transistorsoft/flutter_background_fetch#279]
In your docs you write:

`When your app is terminated, iOS no longer fires events`

Does that really mean that I cannot run functions if the App is terminated? I ask because it is described here that it should be possible:

https://www.hackingwithswift.com/example-code/system/how-to-run-code-when-your-app-is-terminated

**Comment by christocracy** [comment]
When an iOS app is terminated, the OS halts background-fetch events.

there no such thing as stopOnTerminate: false for iOS.

**Comment by MirceaX2Mobile** [comment]
@christocracy Hello Chris! I'm an iOS Developer and yes you can perform background fetch on iOS even if your app is terminated. Can I ask if the native iOS implementation for this framework uses BGTaskScheduler? Maybe thats why the framework doesn't support app termination on iOS.

**Comment by christocracy** [comment]
iOS halts background-fetch, regardless if using old api or latest BGTaskScheduler, if the *user* terminated the app.

Yes, the plugin uses BGTaskScheduler when available, falling back to old api when not.

**Comment by MirceaX2Mobile** [comment]
@christocracy Ok then, because if you are using the old api, the background fetch works when the app is terminated. I tested myself with a small app doing so requests when the app was closed.
