### ISSUE TITLE
performFetchWithCompletionHandler will be deprecated from iOS 13

### ISSUE THREAD

**Issue by sbd2015** [transistorsoft/flutter_background_fetch#28]
I've just found out performFetchWithCompletionHandler will be deprecated from iOS 13.
I'm not coming from iOS world and not sure if it will affact the app behavior.
Just curious to know your thoughts on it.

**Comment by christocracy** [comment]
This has been reported in the [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch/issues/159) version earlier this week.

**Comment by gmaxferr** [comment]
@christocracy do you have an enhancement release timeline? Particularly for this issue?
Thanks!

**Comment by christocracy** [comment]
September

**Comment by gokulanath** [comment]
@christocracy any update on this?

**Comment by christocracy** [comment]
No.  I’m in no hurry for this.  This api is being deprecated but it’s not going to go away for years.
