### ISSUE TITLE
[BUG] Shared Preference plugin not working for headless task

### ISSUE THREAD

**Issue by Jerinji2016** [transistorsoft/flutter_background_fetch#283]
**Your Environment**
* Plugin version:  1.0.3
* Platform: Android
* OS version: Android 10
* Device manufacturer / model:  Pixel 3 XL (emulator)
* Flutter info (`flutter info`, `flutter doctor`): 
   Flutter version : 2.10.4

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1586], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

I have set up the background_fetch as per the doc, when app is in foreground everything works fine,
But when I trigger a headless task, This issue happens!

Have I missed anything? And is there any example to register PlatformChannels in a headless task?

**Debug logs**
- Android: `$ adb logcat`
```
2022-04-14 14:00:14.438 11903-11903/com.dev.calendar D/TSBackgroundFetch: [BGTask] timeout: flutter_background_fetch
2022-04-14 14:00:14.438 11903-11903/com.dev.calendar D/TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
2022-04-14 14:00:14.439 11903-11940/com.dev.calendar I/flutter: _backgroundFetchHeadlessTask: Headless event received
2022-04-14 14:00:14.439 11903-11940/com.dev.calendar I/flutter: _backgroundFetchHeadlessTask: headless request timeout
2022-04-14 14:00:14.440 11903-11903/com.dev.calendar D/TSBackgroundFetch: - finish: flutter_background_fetch
2022-04-14 14:00:14.440 11903-11903/com.dev.calendar D/TSBackgroundFetch: - jobFinished
2022-04-14 14:00:14.441 11903-11940/com.dev.calendar E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

**Comment by patton88** [comment]
https://codegrepr.com/question/flutter-unhandled-exception-missingpluginexceptionno-implementation-found-for-method-getall-on-channel-plugins-flutter-io-shared_preferences/

After doing a lot of research, I found the answer. Add this to your code before you use shared preferences.
	SharedPreferences.setMockInitialValues({});
It is because if you use getAll where there is nothing, it will go crazy. I don’t think it is anything to do with iOS. If you even use normal getString, the internal program uses getAll so it will still crash

**Comment by Jerinji2016** [comment]
Wow.. worked like a charm...!

**Comment by Jerinji2016** [comment]
`SharedPreferences.setMockInitialValues({});` just avoid the exception from happenning.. 
Using that you might get null values while `sharedPref.getString("you-key")`..

I suggest you use 
`SharedPreferencesAndroid.registerWith();` for android and 
`SharedPreferencesIOS.registerWith()` for IOS.

You might have to explicitly type in files to import -
```
import 'package:shared_preferences_android/shared_preferences_android.dart';
import 'package:shared_preferences_ios/shared_preferences_ios.dart';
```

**Comment by whiteLT** [comment]
> `SharedPreferences.setMockInitialValues({});` just avoid the exception from happenning.. Using that you might get null values while `sharedPref.getString("you-key")`..
> 
> I suggest you use `SharedPreferencesAndroid.registerWith();` for android and `SharedPreferencesIOS.registerWith()` for IOS.
> 
> You might have to explicitly type in files to import -
> 
> ```
> import 'package:shared_preferences_android/shared_preferences_android.dart';
> import 'package:shared_preferences_ios/shared_preferences_ios.dart';
> ```

Should we use anything else now as SharedPreferencesIOS is deprecated and discontinued?

**Comment by Jerinji2016** [comment]
Not required I guess

**Comment by christocracy** [comment]
background_fetch has nothing to do with shared_preferences
