### ISSUE TITLE
registerTask failed to find BackgroundFetchConfig for taskId flutter_background_fetch

### ISSUE THREAD

**Issue by mohamedsogoba** [transistorsoft/flutter_background_fetch#286]
Hello I need help I use flutter 2.5
and background_fetch: ^1.0.3
I have followed the setup well https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md and am using the sample code from the documentation.
I have this error:
D/TSBackgroundFetch(1281): - registerTask: flutter_background_fetch
E/TSBackgroundFetch( 1281): - registerTask failed to find BackgroundFetchConfig for taskId flutter_background_fetch
I do not understand ?

**Comment by christocracy** [comment]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by mohamedsogoba** [comment]
1. Plugin 1.0.3
2. Android 
3. API 30
4. Device phusique Samsug 
5. 
![flutter doctor](https://user-images.githubusercontent.com/16210131/174491378-a1089dad-6f78-47c3-bc0f-5e627a59ff70.png)
6-logcat 
![fetch - Copie](https://user-images.githubusercontent.com/16210131/174491474-3ef5cd74-c9ae-4441-9b6d-21c96d8afa67.png)

help me

**Comment by christocracy** [comment]
- And where’s your code?
- don’t post screenshots of logs.  They are *text*.  Copy and pastable.

**Comment by christocracy** [comment]
See [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to learn how to syntax highlight pasted *code blocks* (including logs).

**Comment by mohamedsogoba** [comment]
Is Ok
