### ISSUE TITLE
Perform processing on data before posting to the server.

### ISSUE THREAD

**Issue by bulgarian-beast** [transistorsoft/flutter_background_fetch#287]
Hello, is it possible to add a "callback" parameter to bg.Config.

It would be nice to be able to make modifications on the data before posting them on the server, and also to be able to decide if we post the request or not from the client.

**Comment by christocracy** [comment]
I do not understand why adding a `callback` to `Config` would help with that.

also, `bg.Config` implies `BackgroundGeolocation` yet this is the background_fetch repo.
