### ISSUE TITLE
[BUG] Import of com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin

### ISSUE THREAD

**Issue by KorbinianMossandl** [transistorsoft/flutter_background_fetch#29]
**Your Environment**
* Plugin version: 0.2.0
* Platform: Android

I tried to enable headless mode but the import inside my Application.kt fails. It cannot resolve com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin even though the plugin is installed correctly and is working in my dart code.

**Comment by christocracy** [comment]
Need more info, including stacktrace and your Application.kt

**Comment by KorbinianMossandl** [comment]
Application.kt is exactly the same as on your guide.
Strange thing is, it will compile and it actually works. Maybe this is just an Android studio issue were it just thinks it cannot resolve the import but actually can? I am currently on Android Studio 3.4.1

**Comment by christocracy** [comment]
Your Application.kt is not supposed to be exactly like the guide, which is why I asked you to paste it.  You’re supposed to modify the namespace accordingly.

**Comment by KorbinianMossandl** [comment]
oh yes, i done that naturally. as i said, i found out that it will compile none the less and works without a problem even in headless mode. i think this is just a bug in Android studio.

**Comment by shinewanna** [comment]
Me either has this error.

**Comment by shinewanna** [comment]
Bro,I get the answer,he'll forgot to add backgroundfetch dependency in pubspec.yaml
