### ISSUE TITLE
BackgroundFetch.status always returing as 2(Denied). How can I change it to 3(Granted) ?

### ISSUE THREAD

**Issue by Pranit1804** [transistorsoft/flutter_background_fetch#291]
* Plugin version: **1.1.0**
* Platform:  **Android**
* OS version: **12**
* Device manufacturer / model: **Xiaomi Redmi Note 10 Pro**
* Flutter info (`flutter info`, `flutter doctor`):
* Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.5 21G72 darwin-arm, locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

* Plugin config
 BackgroundFetchConfig(
          minimumFetchInterval: 16,
          stopOnTerminate: false,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.ANY,
        ),

**To Reproduce**
I am always getting BackgroundFetch.status as 2 by which I mean it is denied and I don't why this is happening. Even I tried the demo application but there also the status was 2. Is it my phone issue? If yes, how can I solve it?

**Comment by christocracy** [comment]
Search iOS Settings for “background refresh”.  Enable accordingly.

![F05B8A2D-1ADF-4C5A-8A4F-82667EF7C5B0](https://user-images.githubusercontent.com/14999/190875522-7783dcb7-9444-4bae-93ec-c5cfc0d98876.png)

**Comment by Pranit1804** [comment]
I have an android device(Xioami Redmi note 10), how can I change setting for that?

**Comment by d95sld95** [comment]
Status 2 = available

See docs:
https://pub.dev/documentation/background_fetch/latest/background_fetch/BackgroundFetch/STATUS_AVAILABLE-constant.html

**Comment by christocracy** [comment]
Thanks @d95sld95, I didn’t catch that.
