### ISSUE TITLE
Black screen when using background fetch with flutter_local_notification

### ISSUE THREAD

**Issue by hosseinkhojany** [transistorsoft/flutter_background_fetch#298]
I am using background fetch and local notification. When I schedule a task, for example, for the next 30 minutes, everything works fine, and the program shows me a notification after 30 minutes, but when I click on the notification, everything goes black.

I put a log in the main method, when the background fetch trigger is triggered, it runs the whole program, and when I click on the notification, this happens. I have to prevent all program components from running.
Is there any other solution for this?

**Comment by Pulkit077** [comment]
@hosseinkhojany how did you fix it?

**Comment by hosseinkhojany** [comment]
> [@hosseinkhojany](https://github.com/hosseinkhojany) how did you fix it?

if you are using any flutter sound packages remove services of them from android manifest.xml it gona be fix

**Comment by Pulkit077** [comment]
Yes, I am using `audio_services` and `just_audio` which are required for my app's functionality. Is there any workaround ?

**Comment by hosseinkhojany** [comment]
> Yes, I am using `audio_services` and `just_audio` which are required for my app's functionality. Is there any workaround ?

So, then you need to merge them together and make single service for yours
