### ISSUE TITLE
[PROBLEM] Can't scan for ble devices in background

### ISSUE THREAD

**Issue by NickLou26** [transistorsoft/flutter_background_fetch#299]
* Plugin version: 1.1.2
* Platform: Android
* OS version: Android 13

I am trying to scan for ble devices in background once the app is killed. I tried to use this plugin to start a scan once the app is killed however the scan doesn't seem to be working in background. In my backgroundFetchHeadlessTask method, there is a http post request which works, but only the scan doesnt work. I am using flutter_beacon to scan the ble devices. This plugin seems to be working, but the flutter_beacon plugin doesn't work in the backgroundFetchHeadlessTask method. It works when the app is open, but not when killed. Is there any solutions for this?

Thanks!

**Comment by christocracy** [comment]
I have no experience with BLE beacons.
