### ISSUE TITLE
Import naming error @ Android setup for headless implementation

### ISSUE THREAD

**Issue by antoninoSTB** [transistorsoft/flutter_background_fetch#3]
Hi, you may want to change
`import com.transistorsoft.flutter.backgroundgeolocation.BackgroundFetchPlugin;`
with
`import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;`
in the android setup for headless mechanism wiki page.

**Comment by christocracy** [comment]
Fixed, thanks.
