### ISSUE TITLE
`minimumFetchInterval` in `TaskConfig`

### ISSUE THREAD

**Issue by Mohammad-Adam** [transistorsoft/flutter_background_fetch#300]
how to set a minimum fetch interval when calling `scheduleTask`?

**Comment by christocracy** [comment]
TaskConfig isn’t BackgroundFetch.  They are different.

TaskConfig has `interval` (when configured with `periodic: true`.

you don’t need to use scheduleTask.  You can just use the built-in, traditional BackgroundFetch task.

scheduleTask is only a recent addition.
