### ISSUE TITLE
Flutter 3 Support

### ISSUE THREAD

**Issue by haizadvnet** [transistorsoft/flutter_background_fetch#301]
**Is your feature request related to a problem? Please describe.**
Flutter 3 seems to throw error during compile if method in Android API is deprecated. In this case, I got error log telling me `[deprecation] Registrar in PluginRegistry has been deprecated`

**Describe the solution you'd like**
It would be great if this plugin can be used seamlessly on Flutter 3. My Flutter version 3.3.8

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by christocracy** [comment]
The plugin does support Flutter 3.

have you tried the /example app in this repo?

**Comment by haizadvnet** [comment]
My bad, I didn't tried the example app before. Turns out I need to update my JDK and upgrade the Android Studio 😃  Many thanks
