### ISSUE TITLE
[PROPOSAL] Missed option in installation guide

### ISSUE THREAD

**Issue by bambinoua** [transistorsoft/flutter_background_fetch#302]
In your installation guide you forgot to mention this:

And will set the correct `SystemCapabilities` for your target in the `project.pbxproj` file:

```
SystemCapabilities = {
  com.apple.BackgroundModes = {
    enabled = 1;
  };
};
```

**Comment by christocracy** [comment]
Is there something [missing here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md#configure-background-capabilities)?

**Comment by bambinoua** [comment]
> Is there something [missing here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-IOS.md#configure-background-capabilities)?

Yes.
In your [example's project.pbxproj](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/ios/Runner.xcodeproj/project.pbxproj) starting from row 175 there is a mentioned above code. Enabling checkboxes on Capabilities page does not update `project.pbxproj`.

I noticed this difference when considered the workmanager package. Here is their [installation guide](https://github.com/fluttercommunity/flutter_workmanager/blob/main/IOS_SETUP.md).

**Comment by christocracy** [comment]
I opened a fresh clone of the `/example`.  The required *background modes* are correctly configured in the `Info.plist`.

I see nothing wrong here.

<img width="1378" alt="Screen Shot 2022-11-15 at 1 39 18 PM" src="https://user-images.githubusercontent.com/14999/201999626-76ac1d6b-5a36-4856-a12d-ea02abef4125.png">
