### ISSUE TITLE
error while using the plugin

### ISSUE THREAD

**Issue by mkassir95** [transistorsoft/flutter_background_fetch#306]
Hello,

I am using this version `background_fetch: ^1.1.2`, 

I am getting this error while running the app 

> Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/C:/Users/user/StudioProjects/untitled36/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

**Comment by christocracy** [comment]
Duplicate #204 

you didn’t follow the *Required Setup Instructions* in the readme.
