### ISSUE TITLE
Does it run at exact specified time

### ISSUE THREAD

**Issue by GadepalliAditya1998** [transistorsoft/flutter_background_fetch#31]
Hey, I would like to know whether this plugin is able to run at exact specified time and in a periodic way and can be stopped from background. My use case is to fetch user location from GPS and store in SQFlite and does it handle Wake locks and device restarts? More important is will it be able to run on Chinese Rom mobiles like Mi, Honor?

**Comment by christocracy** [comment]
>run at exact specified time

No.

>in a periodic way

Yes

>does it handle Wake locks

Does not use WakeLock.  It uses Android JobScheduler.

>and device restarts?

Yes

>Chinese Rom mobiles like Mi, Honor?

Yes.

**Comment by GadepalliAditya1998** [comment]
How much may be the delay it might. Will the delay  be arbitrary or any
fixed value?.

**Comment by christocracy** [comment]
minimumFetchInterval is not exact.  The os will throttle this based upon device usage.  Sometime it could be once per hour.

If the user doesn’t open your app for a long period of time, maybe fetch occurs once per day.

**Comment by GadepalliAditya1998** [comment]
Thank you for your response
