### ISSUE TITLE
[BUG] Error when assembling the release application

### ISSUE THREAD

**Issue by LamaMen** [transistorsoft/flutter_background_fetch#310]
**Environment**
* Plugin version: 1.1.3
* Platform: Android
* Flutter info (`flutter info`, `flutter doctor`):
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

**To Reproduce**
1. Added a plugin to pubspec
2. Сonfigured the build for android according to the following [guide](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)
3. Added the code from the example to the application
4. Executing the command `fvm flutter build apk`
5. I get an error when building:
```
Running Gradle task 'assembleRelease'...                        

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_fetch:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/rodionov/developer/work/rem_coil/mobile/build/background_fetch/intermediates/merged_res/release/values/values.xml:2520: AAPT: error: resource android:attr/lStar not found.
```

**Additional context**
Perhaps this is due to the fact that the target (compile) version I have is 33, and the installation guide states that it is necessary to use 31. But I can't lower it below 32, because another plugin will break.

I will be grateful for any help!

**Comment by christocracy** [comment]
Post the following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by christocracy** [comment]
I compile and test [with `33` in the /example](https://github.com/transistorsoft/flutter_background_geolocation/blob/7ed550385ee8157d71d0af77d8d73f61ad8c702d/example/android/build.gradle#L4-L5).  It is not *necessary*.

**Comment by aeri** [comment]
Make sure to set correctly the ```ext``` block that is specified in [INSTALL-ANDROID.md](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md).

That particular error may derive from omitting that block in the ```build.gradle``` file

**Comment by imobdev-git** [comment]
@LamaMen  did you get solution for this ? I am having this same issue and getting this error while making a release apk. Please guide.

**Comment by christocracy** [comment]
https://github.com/transistorsoft/flutter_background_fetch/issues/310#issuecomment-1381028641
