### ISSUE TITLE
[BUG] Turning off background fetch on Android is not detected

### ISSUE THREAD

**Issue by marcellplentific** [transistorsoft/flutter_background_fetch#311]
**Your Environment**
* Plugin version: 1.1.2
* Platform: Android
* OS version: 10
* Device manufacturer / model: Xiao Mi 9T
* Flutter doctor:
```
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.1 22C65 darwin-arm, locale en-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```
* Plugin config
```
BackgroundFetch.configure(
  BackgroundFetchConfig(
    minimumFetchInterval: minimumIntervalMinutes,
    stopOnTerminate: true,
    startOnBoot: false,
    enableHeadless: false,
    forceAlarmManager: false,
    requiredNetworkType: NetworkType.ANY,
    requiresBatteryNotLow: false,
    requiresStorageNotLow: false,
    requiresCharging: false,
    requiresDeviceIdle: false,
  ),
  callback,
  onTimeout,
);
```

**To Reproduce**
1. Turn of background data in the OS app settings, or restrict background data by turning on data saving mode
2. `BackgroundFetch.status` still returns 2

**Additional context**
This issues is duplication from https://github.com/transistorsoft/flutter_background_fetch/issues/268#issuecomment-1367324599

**Comment by christocracy** [comment]
Background fetch has nothing to do with background data, or *data* in general.

this plugin is nothing more than a periodic task-timer, implemented with Android JobScheduler / AlarmMaanger.

Android background-fetch has no way of being disabled by settings.

**Comment by marcellplentific** [comment]
Okay, thank you for the clarification.
