### ISSUE TITLE
Question: Can WorkManager be used in conjunction with this plugin?

### ISSUE THREAD

**Issue by bryanrideshark** [transistorsoft/flutter_background_fetch#315]
**Is your feature request related to a problem? Please describe.**
This is more of a question - we are transitioning from a Cordova app into Flutter and want to make sure we have the right plan before we proceed.

Can we configure BackgroundGeolocation using WorkManager, or do we need to use BackgroundFetch?

If we _need_ to use BackgroundFetch, does that prevent us from also using WorkManager in the same application?

**Describe the solution you'd like**
Would just like to know the philosophy - are we forced to choose between WorkManager and BackgroundFetch, or can we use them both?

If we have to choose between the two, are we prevented from using BackgroundGeolocation in WorkManager?

Thank you, and my apologies if this was in the docs and I didn't find it.

**Comment by christocracy** [comment]
`background_fetch` basically *equals* `workmanager`.

`background_geolocation` *requires* `background_fetch`.

I don't think there's anything that `workmanager` does that `background_fetch` doesn't already do.

**Comment by bryanrideshark** [comment]
When you say "requires" - that doesn't mean it will _break_ if we use WorkManager correct? It just has a dependency on it?

We can still use WorkManager tasks, or other headless Dart, to invoke methods on BackgroundGeolocation?

**Comment by christocracy** [comment]
The plugin isn’t affected by other plugins.

**Comment by christocracy** [comment]
What do you think work_manager is doing for you that background_fetch doesn’t?

they do the same thing.
