### ISSUE TITLE
[BUG?] Headless task not executing immediately after reboot

### ISSUE THREAD

**Issue by muilenheinz** [transistorsoft/flutter_background_fetch#320]
Hi! I am not really sure if this is a bug or just the intended behavior. I update a widget with your plugin. Everything works fine, until I restart my phone. The headless task then gets executed after the given time interval. But what I expected was the task to be run immediately after the reboot and then again in the given interval. Is it supposed to work like that? Or is it in another way possible to execute a function with your plugin just after the reboot of the phone?

**Your Environment**
* Plugin version: 1.1.4
* Platform: Android
* OS version: TirmaisuPrivacySandbox
* Device manufacturer / model: Google Pixel 2 (emulated), same behavior on (physical) Motorola moto g10

* Flutter info (`flutter info`, `flutter doctor`):
/home/muilenheinz/snap/flutter/common/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.7.2, on Ubuntu 22.04.1 LTS 5.15.0-10058-tuxedo, locale en_US.UTF-8)
    • Flutter version 3.7.2 on channel stable at /home/muilenheinz/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32fb2f948e (2 days ago), 2023-02-08 07:30:10 -0800
    • Engine revision f40b73f8a4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /home/muilenheinz/Android/Sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.0.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3)
    • IntelliJ at /snap/intellij-idea-ultimate/401
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 13 (API 33) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Ubuntu 22.04.1 LTS 5.15.0-10058-tuxedo

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
Process finished with exit code 0

* Plugin config
await BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.ANY,
        startOnBoot: true,
        forceAlarmManager: false
    ),

**To Reproduce**
1. download provided example
2. execute the app, then restart the phone
3. The logs then do not show the log message provided in the headless method, just after 15 minutes of waiting

**Debug logs**
2-10 13:20:35.466  2399  2399 D TSBackgroundFetch: BootReceiver: android.intent.action.BOOT_COMPLETED
02-10 13:20:35.498  2399  2399 D TSBackgroundFetch: ☯️  onCreate
02-10 13:20:35.548  2399  2399 D TSBackgroundFetch: ☯️  HeadlessMode? true
02-10 13:20:36.274  3517  3517 D TSBackgroundFetch: BootReceiver: android.intent.action.BOOT_COMPLETED
02-10 13:20:36.282  3517  3517 D TSBackgroundFetch: ☯️  onCreate
02-10 13:20:36.333  3517  3517 D TSBackgroundFetch: ☯️  HeadlessMode? true
02-10 13:20:36.463  3517  3517 D TSBackgroundFetch: - start
02-10 13:20:36.465  3517  3517 D TSBackgroundFetch: - registerTask: flutter_background_fetch
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch: {
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "taskId": "flutter_background_fetch",
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "isFetchTask": true,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "minimumFetchInterval": 15,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "stopOnTerminate": false,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "requiredNetworkType": 0,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "requiresCharging": false,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "requiresDeviceIdle": false,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "requiresStorageNotLow": false,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "startOnBoot": true,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "forceAlarmManager": true,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "periodic": true,
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch:   "delay": -1
02-10 13:20:36.466  3517  3517 D TSBackgroundFetch: }

Additional context
On the Pixel 2, I also set the battery restrictions to "unrestricted", as supposed by dontkillmyapp.com, but that did not change the behavior

**Comment by muilenheinz** [comment]
That would be fine. But the headless task just fires after 15 minutes (or whatever the minimumFetchInterval is) for the first time and not after 30 seconds.

**Comment by christocracy** [comment]
That’s correct.  Why should an event fire just because the device booted?
