### ISSUE TITLE
[TSBackgroundFetch start] (null) when BackgroundFetch.start() for IOS

### ISSUE THREAD

**Issue by alberlevi98** [transistorsoft/flutter_background_fetch#321]
await BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 1,
        forceAlarmManager: false,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE
    ), _onBackgroundFetch, _onBackgroundFetchTimeout);

BackgroundFetch.start();

in the print command it says [TSBackgroundFetch start] (null) and does not trigger my _onBackgroundFetch method.

**Comment by christocracy** [comment]
The issue template is not optional.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by alberlevi98** [comment]
Plugin version : 1.1.3
Platform : IOS physical phone not simulator.
OS :16.1.1
Device : iPhone SE

Reproduce)
1-  BackgroundFetch.configure
2- BackgroundFetch.start()
3- debugprint says [TSBackgroundFetch start] (null) also  [BackgroundFetch] configure success: 2

**Comment by christocracy** [comment]
Are you *simulating* events?

**Comment by alberlevi98** [comment]
No using real device.

**Comment by christocracy** [comment]
See readme and learn to simulate events.

**Comment by alberlevi98** [comment]
I know but success code is 2 is it mean successfull?

**Comment by christocracy** [comment]
https://github.com/transistorsoft/flutter_background_fetch/blob/master/lib/background_fetch.dart#L393

**Comment by christocracy** [comment]
Do simulated events work?

**Comment by alberlevi98** [comment]
yes worked thanks
