### ISSUE TITLE
How to save variables for next iterations in terminate mode

### ISSUE THREAD

**Issue by meridorkobi** [transistorsoft/flutter_background_fetch#323]
`background_fetch` works fine in terminate mode.
The function uses constants and initializes variables on each iteration.
I would like to save initiated variables for next iteration?
I know  `SharedPreferences` is one option is it the best way? 
or?

**Comment by christocracy** [comment]
shared_preferences is an excellent option (as long as the data is not large).

For large amounts of data, use SQLite database.
