### ISSUE TITLE
hi, how to keep a mqttclient runing in background with this lib/?

### ISSUE THREAD

**Issue by luohao123** [transistorsoft/flutter_background_fetch#329]
what I need is just runing mqtt client in background, is there any easily way to do this in this lib?

**Comment by christocracy** [comment]
This lib has nothing at all to do with any kind of connection to a server.

this is merely a periodic callback locally on the device.  What you choose to do within your callback is purely up to you.

**Comment by luohao123** [comment]
@christocracy I know, what I ask, is is that possible call the MqttClient class inside the callback (which is the whole module class in my app), and then send notifictions as well as saving the message to sql once the new message got?

**Comment by christocracy** [comment]
What you do in your own callback is up to you.   The plug-in has no opinion about what you do in your callback function.

**Comment by luohao123** [comment]
@christocracy  thanks, I think it twice, how can I make sure my mqtt client keep alive inside this callback function? to restart it in callback?

**Comment by christocracy** [comment]
Your callback has a finite time to run (eg iOS 30s).  You must call .finish(taskId) before your time expires.

you don’t get to “keep things alive”.

**Comment by luohao123** [comment]
@christocracy when i call MqttClient.reconnnect() inside callback func, does the mqtt client can be bring up even though it might disconnect for another 10 minutes?

**Comment by christocracy** [comment]
I have no idea.  I have experience with sockets.

what you do in your callback is your resonsibility.

**Comment by luohao123** [comment]
it's same as sockets, may i ask how do u deal with sockets?

**Comment by christocracy** [comment]
Did you read what I said?

> I have experience with sockets.
