### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abtpltd** [transistorsoft/flutter_background_fetch#330]
**FAILURE: Build failed with an exception.**
AAPT: error: resource android:attr/lStar not found.
**Error Details:**
FAILURE: Build failed with an exception.

* What went wrong:
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\WorkSpaceDrive\FlutterWorkSpace2022\rocketsales\build\background_fetch\intermediates\merged_res\release\values\values.xml:2520: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
![Screenshot 2023-05-22 001354](https://github.com/transistorsoft/flutter_background_fetch/assets/101341361/ec3af4e5-50aa-4270-97f0-035d0d0342b1)

**Comment by christocracy** [comment]
You have an insufficient supportLibVersion.

**Comment by abtpltd** [comment]
> You have an insufficient supportLibVersion.

how can i add supportLibVersion

**Comment by abtpltd** [comment]
android/build.gradle: kidly assist what to add inside android/build.gradle

**Comment by christocracy** [comment]
Post your android/build.gradle!

**Comment by abtpltd** [comment]
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Follow the Setup Guides.  You ignored part of it.

https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#androidbuildgradle

**Comment by abtpltd** [comment]
Thanks its working Now
