### ISSUE TITLE
in release apk

### ISSUE THREAD

**Issue by mostafasaadamin** [transistorsoft/flutter_background_fetch#334]
* What went wrong:
Execution failed for task ':background_fetch:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\mostafa.saad\.gradle\caches\transforms-3\829ec5b3852dca3951301ad740b00dff\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by christocracy** [comment]
Post your `android/build.gradle`

**Comment by christocracy** [comment]
Duplicate #330
