### ISSUE TITLE
BUILD FAILED WHEN RUNNING IN ANDROID DEVICE

### ISSUE THREAD

**Issue by MS07062000** [transistorsoft/flutter_background_fetch#335]
**Your Environment**
* Plugin version: Latest from git
* Platform: Android
* OS version: Funtouch OS_10.5
* Device manufacturer / model: VIVO 1951

ERROR WHEN RUNNING APP:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - file:/C:/Users/user/Desktop/To-Do-List Map/to_do_list_app/android/app/libs/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
       - https://jitpack.io/com/transistorsoft/tsbackgroundfetch/maven-metadata.xml
     Required by:
         project :app > project :background_fetch

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

**android/build.gradle**

buildscript {
    ext.kotlin_version = '1.7.10'
    ext {
       compileSdkVersion   = 33                // or latest
       targetSdkVersion    = 33                // or latest
       appCompatVersion    = "1.6.1"           // or latest
    }
    repositories {
        google()
        mavenCentral()
        maven {
           // [required] background_fetch
           url "${project(':background_fetch').projectDir}/libs"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // classpath 'com.android.tools.build:gradle:4.2.2'

    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Search issues “ Could not find any matches for ”

this has been posted dozens of times before.

**Comment by MS07062000** [comment]
Yes , I got it resolved

**Comment by christocracy** [comment]
> if enableHeadless: true,
stopOnTerminate: true,

That config wouldn’t make sense.  stopOnTerminate takes precedence.  

enableHeadless: true **requires** stopOnTerminate: false.
