### ISSUE TITLE
Does registerHeadlessTask run while the app is running ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [transistorsoft/flutter_background_fetch#340]
In the example app, `registerHeadlessTask` is called after `runApp`.
However, I'd like the task to run whether the app is running or not (and as such, need to register it before `runApp`), is this possible with this package ? If yes, is it possible on both Android and iOS ?

**Comment by christocracy** [comment]
Headless mode is *Android only*.  iOS has no concept of headless.

If iOS device is detected to be moving after terminate, the OS will completely launch your app in the background, just as it launched from home-screen.
