### ISSUE TITLE
[BUG] Crash when calling bgGeo.BackgroundGeolocation.stop().  java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient'

### ISSUE THREAD

**Issue by emaddoma** [transistorsoft/flutter_background_fetch#342]
**Your Environment**
* Plugin version: 4.12.2
* Platform: Android
* OS version: API 33
* Device manufacturer / model: Emulator
* Flutter info (`flutter info`, `flutter doctor`): [✓] Flutter (Channel stable, 3.7.12, on macOS 13.4.1 22F770820d darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
* Plugin config 
build.gradle

ext {
        compileSdkVersion = 33
        targetSdkVersion = 33
        minSdkVersion = 21
        appCompatVersion = "1.4.2"
        playServicesVersion = "21.0.1"
    }

+--- project :flutter_background_geolocation
|    +--- com.transistorsoft:tslocationmanager:+ -> 3.4.4
|    +--- org.greenrobot:eventbus:3.3.1
|    |    \--- org.greenrobot:eventbus-java:3.3.1
|    +--- com.squareup.okhttp3:okhttp:3.12.13
|    |    \--- com.squareup.okio:okio:1.15.0
|    +--- com.github.tony19:logback-android:3.0.0
|    +--- org.slf4j:slf4j-api:2.0.7
|    +--- io.github.nishkarsh:android-permissions:2.1.6
|    |    +--- androidx.appcompat:appcompat:1.4.1 -> 1.4.2 (*)
|    |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.1.0
|    |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.6.0 (*)
|    |    \--- org.parceler:parceler-api:1.1.12
|    +--- com.google.android.gms:play-services-location:20.0.0 -> 21.0.1 (*)

+--- project :geolocator_android
|    +--- com.google.android.gms:play-services-location:21.0.1

**To Reproduce**
1. Once permissions are granted, I call a routine to start the bgGeo service...
2. bgGeo.BackgroundGeolocation.stop() and it crashes

**Debug logs**
- Android: 
- E/AndroidRuntime(27967): FATAL EXCEPTION: pool-17-thread-4
E/AndroidRuntime(27967): Process: com.maverickgaming.app, PID: 27967
E/AndroidRuntime(27967): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~tTZ_bq8iVPSsywqhWgH9PQ==/com.maverickgaming.app-8MRlwn_pgaKza1PvcPiFfg==/base.apk)
E/AndroidRuntime(27967):        at com.transistorsoft.xms.g.location.FusedLocationProviderClient.removeLocationUpdates(Unknown Source:50)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.location.TSLocationManager.removeLocationUpdates(Unknown Source:40)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:86)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(Unknown Source:2)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw(Unknown Source:0)
E/AndroidRuntime(27967):        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(27967):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/AndroidRuntime(27967):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/AndroidRuntime(27967):        at java.lang.Thread.run(Thread.java:1012)

**Additional context**
I've read all related issues and made recommended changes to no avail.

**Comment by christocracy** [comment]
Duplicate https://github.com/transistorsoft/flutter_background_geolocation/issues/933.

You're posting (and/or searching) at the wrong repo.  This has already been posted several times.
