### ISSUE TITLE
on IOS 17 and 16.6.1 headless is not working

### ISSUE THREAD

**Issue by Ahmadgnoor** [transistorsoft/flutter_background_fetch#347]
is this Info enough .?

**Vs Code**
* Plugin version: 1.2.1
* Platform: iOS  
* OS version: 17

* Device manufacturer / model: Iphone 11

* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.5.2 22G91 darwin-x64, locale
    en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.82.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
* Plugin config

````
```
@pragma('vm:entry-point')
_backgroundFetchHeadlessTask(HeadlessTask task) async {
  try {
    var taskId = task.taskId;
    var timeout = task.timeout;
    if (timeout) {
      BackgroundFetch.finish(taskId);
      return;
    } 

    if (taskId == "flutter_background_fetch") {
      DartPluginRegistrant.ensureInitialized();
      await BackgroundServiceForAvailability.putLinguistOffline(
          loadServices: true, checkStatus: true, showNotification: true);
    }
    BackgroundFetch.finish(taskId);
  } catch (e) {}
}

````
```

-----

````
```
 int result = await BackgroundFetch.configure(
          BackgroundFetchConfig(
              minimumFetchInterval: 15,
              forceAlarmManager: true,
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: true,
              requiresBatteryNotLow: false,
              requiresCharging: false,
              requiresStorageNotLow: false,
              requiresDeviceIdle: false,
              requiredNetworkType: NetworkType.ANY),
          _onBackgroundFetch,
          _onBackgroundFetchTimeout);
      print("BackgroundFetch.configure: $result");
    } catch (e) {
      print(e.toString());
    }
````
```

**Comment by Ahmadgnoor** [comment]
before IPhone upgradation working fine but now it's not working

**Comment by christocracy** [comment]
[Learn to syntax highlight code-blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by Ahmadgnoor** [comment]
Please check now the code is formated.

**Comment by christocracy** [comment]
>Platform: iOS

The api docs clearly state that “Headless” is an Android-only mechanism.  There’s no such thing as “headless” iOS and there’s no such thing as `stopOnTerminate: false` for iOS background-fetch.  Apple does not allow background-fetch events after app terminate.

**Comment by Ahmadgnoor** [comment]
> > Platform: iOS
> 
> The api docs clearly state that “Headless” is an Android-only mechanism. There’s no such thing as “headless” iOS and there’s no such thing as `stopOnTerminate: false` for iOS background-fetch. Apple does not allow background-fetch events after app terminate.

My App is in minimized not in terminated state. I know you told this before .

**Comment by Ahmadgnoor** [comment]
Please reopen and considered it as a bug

**Comment by christocracy** [comment]
Your issue title states:  “ on IOS 17 and 16.6.1 headless is not working”.

headless = terminated.

The readme documents how to simulate events.  If simulated events work, that’s all you need to do.  Everything else is up to Apple.  It can take days to regularly fire events.  Make sure to periodically open the app to show Apple’s algorithm that the app is not dormant.

**Comment by christocracy** [comment]
It is not a bug.

**Comment by Ahmadgnoor** [comment]
And Thank you for your immediate  reply

**Comment by christocracy** [comment]
Simulate events.

**Comment by Ahmadgnoor** [comment]
> Simulate event
working .. but client is not understanding the point that you told me

**Comment by christocracy** [comment]
Simulated events working = plug-in working. 

I’m not concerned with your client.

**Comment by Ahmadgnoor** [comment]
yep i know. ok thank you

**Comment by Ahmadgnoor** [comment]
@christocracy just one question. why this is show 

[TSBackgroundFetch removeListener] WARNING:  Failed to find listener for identifier: flutter_background_fetch
