### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abtpltd** [transistorsoft/flutter_background_fetch#350]
FAILURE: Build failed with an exception.
Execution failed for task ':background_fetch:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\WorkspaceDrive\FlutterWorkspace\rocketvan\build\background_fetch\intermediates\merged_res\release\values\values.xml:2520: AAPT: error: resource android:attr/lStar not found.
flutter doctor:
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.3636], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.0)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

**Comment by abtpltd** [comment]
What went wrong:
Execution failed for task ':background_fetch:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\WorkspaceDrive\FlutterWorkspace\mynewapp\build\background_fetch\intermediates\merged_res\release\values\values.xml:2520: AAPT: error: resource android:attr/lStar not found.

**Comment by christocracy** [comment]
Review the Android Setup Instructions linked in the readme and pay close attention to the instructions related `ext` params in `android/build.gradle‘

**Comment by abtpltd** [comment]
android/build

buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
configurations.all {
    resolutionStrategy {
        force 'androidx.core:core:1.6.0'
        force 'androidx.core:core-ktx:1.6.0'
    }
}

**Comment by abtpltd** [comment]
android/app/build

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace "com.africa.rocketvan"
    //background_fetch
    //compileSdkVersion rootProject.ext.compileSdkVersion
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.africa.rocketvan"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 21 //flutter.minSdkVersion
        //background_fetch
        //targetSdkVersion rootProject.ext.targetSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }
        
    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }

    //Tofix: Could not resolve all artifacts for configuration ':image_picker_android:debugUnitTestRuntimeClasspath'
    lintOptions {
        disable 'InvalidPackage'
        disable "Instantiatable"
        checkReleaseBuilds false
        abortOnError false
    } 
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.multidex:multidex:2.0.1"
    implementation platform('com.google.firebase:firebase-bom:32.0.0')
    implementation 'com.google.firebase:firebase-analytics'
}

**Comment by christocracy** [comment]
Yes, you've posted your `android/build.gradle` proving you **ignored** the Setup Instructions telling you to add a block of `ext` params.

Read the Setup Instructions **and perform EVERY SINGLE STEP**.  Omit **nothing**.

**Comment by christocracy** [comment]
I don't need to see your `app/build.gradle`

**Comment by abtpltd** [comment]
send: Setup Instructions for android file link

**Comment by christocracy** [comment]
**Read the README!**

**Comment by abtpltd** [comment]
yes i have done all steps.
and flutter debuggin is working well.
But when m trying to build release:
flutter build apk --no-shrink
FAILURE: Build failed with an exception.
Execution failed for task ':background_fetch:verifyReleaseResources'.
\build\background_fetch\intermediates\merged_res\release\values\values.xml:2520: AAPT: error: resource android:attr/lStar not found.

**Comment by abtpltd** [comment]
is there some dependency need to inside android sdk. or build.gradle

**Comment by christocracy** [comment]
> yes i have done all steps.

Post your updated `android/build.gradle`

And [learn to syntax highlight codeblocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)

**Comment by abtpltd** [comment]
![image](https://github.com/transistorsoft/flutter_background_fetch/assets/101341361/3bdd506d-42a6-4f9a-966c-54a7abdca91a)

let try this.

**Comment by christocracy** [comment]
Just **follow the damn Setup Instructions** and do **everything it tells you to do!**
