### ISSUE TITLE
[BUG] Method finish should return a Future<void>, not void

### ISSUE THREAD

**Issue by tony-ditchlabs** [transistorsoft/flutter_background_fetch#351]
`BackgroundFetch.finish(taskId);` has a return type of `void`. But it directly calls `_methodChannel.invokeMethod('finish', taskId);`, which has a return type of `Future<void>`.

This makes it very difficult to catch any exceptions from that call (specifically, the `MissingPluginException` that is expected to be thrown in a testing environment).

**Comment by tony-ditchlabs** [comment]
Reopen please, still valid.

**Comment by christocracy** [comment]
Fixed and published to `1.3.4`
