### ISSUE TITLE
[QUESTION] [iOS] Hardcoded PLUGIN_ID and BACKGROUND_FETCH_TASK_ID: can that become an issue?

### ISSUE THREAD

**Issue by MathieuPierfitte** [transistorsoft/flutter_background_fetch#354]
Hi,

I am playing with your plugin and I quite like it so far, however I am concerned about some IDs that are hardcoded in [BackgroundFetchPlugin.m](https://github.com/transistorsoft/flutter_background_fetch/blob/3c3008b86ff500b3455002208a48a5bfa745625e/ios/Classes/BackgroundFetchPlugin.m#L4-L7). How would it behave if I happened to have 2 Flutter apps installed on my phone that would both use this plugin? Would they both run normally in the background, or would only the last one that called [configure(...)](https://github.com/transistorsoft/flutter_background_fetch/blob/3c3008b86ff500b3455002208a48a5bfa745625e/lib/background_fetch.dart#L430-L462) end up running?

Also, I am considering calling [stop()](https://github.com/transistorsoft/flutter_background_fetch/blob/3c3008b86ff500b3455002208a48a5bfa745625e/lib/background_fetch.dart#L514-L517) myself when the user logs out. Does that mean I would end up stopping background fetching for other Flutter apps that use this plugin too?

I assume apps are sandboxed into their own environment by iOS even for the background fetching part, otherwise it would be too easy to "kill" another app's background activity by simply copying their plugin ID and/or task IDs, but I'd rather double check first.

Cheers 🙂

**Comment by christocracy** [comment]
> How would it behave if I happened to have 2 Flutter apps installed on my phone that would both use this plugin?

It's not an issue.  You can safely use identical ids with different apps.
