### ISSUE TITLE
[BUG] Upgraded gradle and android:lStar error

### ISSUE THREAD

**Issue by bradrushworth** [transistorsoft/flutter_background_fetch#358]
Using Android SDK 34. Min SDK 23.

gradle-wrapper.properties
`
distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip
`

I was getting an error regarding this line:
`<attr name="android:lStar"/>`

It looked like this issue: https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found

This is because Gradle has changed the way gradle configuration files work in most recent versions. See https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

Following this module's instructions no longer fully worked: https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md

To fix this, you need to change in app/build.gradle:
```
android {
    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
    }
}
dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
}

// And possibly
tasks.register("prepareKotlinBuildScriptModel") {}
```

In settings.gradle:
```
//include ":home_widget"
include ":background_fetch"
include ":app"
```

In android/build.gradle:
```
allprojects {
    ext {
        compileSdkVersion = 34
        targetSdkVersion = 34
        appCompatVersion = "1.6.1"
        lifeCycleRuntimeVersion = "2.7.0"
        lifeCycleExtensionsVersion = "2.2.0"
    }

    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}
```

**Comment by christocracy** [comment]
Thanks, I'll keep my eye on this.

**Comment by sonuPrasas010** [comment]
wit will cause 
`
* What went wrong:
Execution failed for task ':app:lintVitalAnalyzeRelease'.
> Could not resolve all files for configuration ':app:detachedConfiguration3'.
   > Failed to transform FakeDependency.jar to match attributes {artifactType=_internal-d8-desugar-methods, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for D8BackportedMethodsGenerator: /home/sonu/.gradle/android/FakeDependency.jar.
         > Cannot invoke "com.android.tools.r8.internal.JT.warning(com.android.tools.r8.Diagnostic)" because "this.d" is null

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 43s
Running Gradle task 'assembleRelease'...                          103.8s

┌─ Flutter Fix ──────────────────────────────────────────────────────────────┐
│ [!] The shrinker may have failed to optimize the Java bytecode.            │
│ To disable the shrinker, pass the `--no-shrink` flag to this command.      │
│ To learn more, see: https://developer.android.com/studio/build/shrink-code │
└────────────────────────────────────────────────────────────────────────────┘
Gradle task assembleRelease failed with exit code 1
sonu@Sonu:~/projects/flutter/H-ATTENDANCE$ `

**Comment by FaFre** [comment]
I am compiling with sdk 35 and got this error as well. After looking at the example code there is a section in the build file to be added which is missing in the setup guide:

```
ext {
    compileSdkVersion   = 34
    targetSdkVersion    = 34
}
```

If not added it will fall back to sdk 28, which seems to cause issues with newer sdk's. @christocracy I guess this should be probably added in the setup guides as well?
