### ISSUE TITLE
"Simulate background fetch" does not work in iOS

### ISSUE THREAD

**Issue by ali-almas** [transistorsoft/flutter_background_fetch#359]
After running the app on the real device I want to simulate background fetch but unfortunately, no events are fired. I tested an example app that is provided inside your repository, the same problem also happens there. I use iOS 17. What can be the problem?

**Comment by christocracy** [comment]
Ignored issue template and you didn't show exactly how you're executing simulated events,

**Comment by ali-almas** [comment]
I try to simulate it like Xcode->Debug->Simulate Background fetch

**Comment by ali-almas** [comment]
So you mean Xcode->Debug->Simulate this one will not work? It will only work like executing lldb command?

**Comment by christocracy** [comment]
Read the readme
