### ISSUE TITLE
[BUG] iOS building stopped working (error: could not find or use auto-linked framework 'Symbols')

### ISSUE THREAD

**Issue by fellipetav** [transistorsoft/flutter_background_fetch#364]
**Your Environment**
* Plugin version: 1.2.2
* Platform: iOS
* OS version: indifferent
* Device manufacturer / model: indifferent
* Flutter info (`flutter info`, `flutter doctor`):

```tcl
[!] Flutter (Channel [user-branch], 3.13.8, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta), locale en-BR)
    ! Flutter version 3.13.8 on channel [user-branch] at /Users/barbara/Documents/dev/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 6c4930c4ac (5 months ago), 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/barbara/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64 (Rosetta)
    • Chrome (web)    • chrome • web-javascript • Google Chrome 122.0.6261.94

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

* Plugin config

**To Reproduce**
1. Using the described environment, with https://pub.dev/packages/background_fetch at version `^1.2.2`; 
2. Delete pod folder and do `pod install` again to be sure about any dependencies caching;
3. Flutter pub get and stuff...
4. Build on Xcode against a simulator (iPhone 14 or whichever regarding your `MinimumOSVersion`);

**Debug logs**
- ios XCode logs, 

![image](https://github.com/transistorsoft/flutter_background_fetch/assets/43867160/5a2e69fa-1e8f-450d-b41d-5f2e518bf49b)

**Additional context**
- I've also tested using the Flutter version 3.19.1 and got the same result.
- I've tested checking out at a recent created tag of my project, **which was working well using the same described environment and also using this lib at the same version**. It does not work anymore since yesterday (even using CodeMagic, which worked before).
- I've tested checking out at a previous tag which doesn't use this lib and the problem does not occur.

I would really appreciate if anyone can help me out.

**Comment by fellipetav** [comment]
maybe related to #198

**Comment by christocracy** [comment]
>[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)

If you upgrade your XCode to latest, the symbol `BGHealthResearchTask` will be recognized.

**Comment by christocracy** [comment]
I will have to release a new version with more care to check this symbol exists before referencing it.

**Comment by sohamD07** [comment]
Hi @christocracy, any solution for this issue? I've also facing this issue for the last 2-3 days. 

flutter doctor info - 

[✓] Flutter (Channel stable, 3.16.8, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta), locale en-IN)
    • Flutter version 3.16.8 on channel stable at /Users/user/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (7 weeks ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.87.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 487DDEEC-A870-4778-AEB3-A4E641843187 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.3.1
      22E772610a darwin-arm64 (Rosetta)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      122.0.6261.111

[✓] Network resources
    • All expected network resources are available.

• No issues found!

![image](https://github.com/transistorsoft/flutter_background_fetch/assets/63590114/abb18361-6807-4713-8cec-595990d6102d)

**Comment by christocracy** [comment]
You can't upgrade your XCode?

**Comment by christocracy** [comment]
Duplicate #363.

`v1.2.4` is released with this symbol `BGHealthResearchTaskRequest` removed.

**Comment by sohamD07** [comment]
Thanks @christocracy, it is working now.

**Comment by fellipetav** [comment]
Thanks, @christocracy , for both approaches 😄 !

I'm gonna test it.

**Comment by fellipetav** [comment]
Update the lib worked well.
