### ISSUE TITLE
[BUG] Android setup docs inconsistent

### ISSUE THREAD

**Issue by dev-abir** [transistorsoft/flutter_background_fetch#365]
**Your Environment**
* Plugin version: 1.2.4
* Platform: Android
* OS version: Android 13

I was following [android setup guide](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md). Notice that in `android/build.gradle` it asks to set `compileSdkVersion` and `targetSdkVersion` inside `ext` block. Whereas, in `android/app/build.gradle` it referes to `rootProject.ext.minSdkVersion` (`minSdkVersion rootProject.ext.minSdkVersion` in `defaultConfig` block). It isn't defined and is definitely not going to work.

I had to consult the example to understand the issue. In the example, they are just not referring to `minSdkVersion` in `android/app/build.gradle`.

**To Reproduce**
1. Follow the docs to setup the plugin, specifically Android ([here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)).

**Comment by christocracy** [comment]
However, `minSdkVersion` is unnecessary for `background_fetch` (`background_geolocation` *does* have a minimum, so is required to be managed there).

For `background_fetch` here, I simply removed the reference to `minSdkVersion` in the [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)
