### ISSUE TITLE
[BUG]  AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by sonuPrasas010** [transistorsoft/flutter_background_fetch#369]
* What went wrong:
Execution failed for task ':background_fetch:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/sonu/projects/flutter/H-ATTENDANCE/build/background_fetch/intermediates/merged_res/release/values/values.xml:2520: AAPT: error: resource android:attr/lStar not found.
 **This above is full bug report**

**Comment by Z6P0** [comment]
Same here. It stopped working since latest Flutter upgrade. Works in debug mode but not in release.

**Comment by christocracy** [comment]
Post both your gradle files.

nobody is specifying what version of the plug-in they’re using.

**Comment by Z6P0** [comment]
build.gradle:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

Using latest plugin version and latest Flutter version.

**Comment by christocracy** [comment]
First-of-all, the maven repo jcenter() [has been deprecated since 2021](https://blog.gradle.org/jcenter-shutdown).

second, you’ve not fully implemented the Android setup instructions linked in the readme (the `ext` vars).

I suggest you generate a fresh hello-world app and compare the changes in the default build.gradle with those in your own app.

you’ve failed to properly upgrade your app with the latest requirement of the latest flutter SDK.  That’s why you have problems.

**Comment by waqaseusopht** [comment]
I am getting same issue
[BUG] AAPT: error: resource android:attr/lStar not found.
This my bulid.gradle file

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
See my comment above: https://github.com/transistorsoft/flutter_background_fetch/issues/369#issuecomment-2119292134

you did not fully implement the Setup Instructions (`ext` vars).  Go back and review the Setup Instructions.

**Comment by YumanYIN** [comment]
I just have added below code in `android/build.gradle` after `allprojects{}`, and use them in `android/app/build.gradle` as the presentation of the help doc [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md), it has solved the problem on my side. 
```
ext {
    compileSdkVersion   = 34
    targetSdkVersion    = 34
    appCompatVersion    = "1.7.0"
}
```

**Comment by skgaurav-web** [comment]
I am using Flutter 3.24.0 • channel stable , while building resale apk i am getting ...
.gradle\caches\transforms-3\f58020c91a078450a7656e43f041db18\transformed\core-1.13.1\res\values\values.xml:113:5-122:25: AAPT: error: resource android:attr/lStar not found.
Can anyone help me in this

**Comment by YumanYIN** [comment]
> I am using Flutter 3.24.0 • channel stable , while building resale apk i am getting ... .gradle\caches\transforms-3\f58020c91a078450a7656e43f041db18\transformed\core-1.13.1\res\values\values.xml:113:5-122:25: AAPT: error: resource android:attr/lStar not found. Can anyone help me in this

Try to add below `ext` code in `android/build.gradle` under `allprojects{}`, and use them in `android/app/build.gradle` as the presentation of the help doc [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)
```
allprojects {
 ...
} 

ext {
    compileSdkVersion   = 34
    targetSdkVersion    = 34
    appCompatVersion    = "1.7.0"
}
```

**Comment by sahilsharma17** [comment]
I have tried this but the problem is same, can not build the release apk.
I guess it is some issue with the new release and dependencies.

**Comment by YumanYIN** [comment]
> I have tried this but the problem is same, can not build the release apk. I guess it is some issue with the new release and dependencies.

I'm also using Flutter 3.24.0, but I can build the release APK. 
You can try to do the below code in the `android/app/build.gradle` :
```
android {
    def buildConfig = rootProject.extensions.getByName("ext")
    
    compileSdk buildConfig.compileSdkVersion 

    defaultConfig {
       ...
       targetSdkVersion buildConfig.targetSdkVersion
       ...
    }
    ...
}
```
If the problem is still there, you need to post your `android/build.gradle` and `android/app/build.gradle` to help you analyse the reason.

**Comment by Aziz-T** [comment]
This problem is related to the compileSdkVersion and targetSdkVersion of the plugins. This problem occurs because the compileSdkVersion and targetSdkVersion of some plugins are outdated. Either go to the source files of the plugin in your project and make the compileSdkVersion and targetSdkVersion versions the same as your project (version 34 compatible), or add the code block below to the build.gradle file in your project directory.

`subprojects {
    afterEvaluate {
        android {
            compileSdkVersion 34
        }
    }
}`

This code is a Gradle configuration script used in Android projects. The subprojects block allows you to configure certain settings for all subprojects (modules) in the project. The android block inside defines Android-related configuration settings, and the compileSdkVersion 34 line allows projects to be compiled with Android API 34.

**Comment by christocracy** [comment]
Post both your .gradle files.

**Comment by Aziz-T** [comment]
### app/build.gradle

`allprojects {
    repositories {
        google()
        mavenCentral()
    }
}


rootProject.buildDir = "../build"

subprojects {
    afterEvaluate {
        android {
            compileSdkVersion 34
        }
    }
}


subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
`

**Comment by christocracy** [comment]
Post the **entire** contents of **both** your gradle files:
1. Android/build.grae
2. Android/app.build.gradle

**Comment by YumanYIN** [comment]
> ### app/build.gradle
> `allprojects { repositories { google() mavenCentral() } }
> 
> rootProject.buildDir = "../build"
> 
> subprojects { afterEvaluate { android { compileSdkVersion 34 } } }
> 
> subprojects { project.buildDir = "${rootProject.buildDir}/${project.name}" } subprojects { project.evaluationDependsOn(":app") }
> 
> tasks.register("clean", Delete) { delete rootProject.buildDir } `

You have not added ` maven { url "${project(':background_fetch').projectDir}/libs" }` in `allprojects` , follow this doc: [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)
```
allprojects {
    repositories {
        google()
        mavenCentral()
        // [required] background_fetch
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }
}

```

**Comment by christocracy** [comment]
@Aziz-T i suggest you consult with the required Android Setup Instructions, linked in the readme and carefully follow ALL the instructions.

**Comment by marcusee** [comment]
I upgraded cupertino_icons to the latest version and it works now hope this helps someone.

**Comment by CodeDeveloper19** [comment]
If you are like me and have updated to the new Flutter version, You can consider this temporary solution
https://github.com/livekit/client-sdk-flutter/issues/569#issuecomment-2275686786

**Comment by christocracy** [comment]
My plug-ins never hard-code [sdk versions](https://github.com/transistorsoft/flutter_background_fetch/blob/c585fa5e159f81b1c13227dbde1f211fc100f93d/android/build.gradle#L39), they read them from `ext` vars in your `build.gradle`.  All plugin authors *should* do this but most don’t.

we learned to do this years ago in the React Native world.

**Comment by abtpltd** [comment]
> nsformed\core-1.13.1\res\values\values.xml:113:5-122:25: AAPT: error: resource android:attr/lStar not found.
> Can anyone help me in this

bhai tera huaa kya, m b pareshaan hu

**Comment by abtpltd** [comment]
> I am using Flutter 3.24.0 • channel stable , while building resale apk i am getting ... .gradle\caches\transforms-3\f58020c91a078450a7656e43f041db18\transformed\core-1.13.1\res\values\values.xml:113:5-122:25: AAPT: error: resource android:attr/lStar not found. Can anyone help me in this


rootProject.buildDir = "../build"
******************** ADD GIVEN LINE AND TRY BABY********************
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}
******************** BUS YHI TAK PASTE KRNA BETAA*************
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by SatyawanHajar** [comment]
> This problem is related to the compileSdkVersion and targetSdkVersion of the plugins. This problem occurs because the compileSdkVersion and targetSdkVersion of some plugins are outdated. Either go to the source files of the plugin in your project and make the compileSdkVersion and targetSdkVersion versions the same as your project (version 34 compatible), or add the code block below to the build.gradle file in your project directory.
> 
> `subprojects { afterEvaluate { android { compileSdkVersion 34 } } }`
> 
> This code is a Gradle configuration script used in Android projects. The subprojects block allows you to configure certain settings for all subprojects (modules) in the project. The android block inside defines Android-related configuration settings, and the compileSdkVersion 34 line allows projects to be compiled with Android API 34.

ext {
    compileSdkVersion   = 34
    targetSdkVersion    = 34
    appCompatVersion    = "1.7.0"
}

subprojects { afterEvaluate { android { compileSdkVersion 34 } } }

it working for me for release build in latest flutter 3.24 version.

**Comment by axelasa** [comment]
I am facing the same problem, 
below is m app level build.gradle
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

android {
    namespace "com.panda.panda_rider"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.panda.panda_rider"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 34
        targetSdkVersion 34
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {}

**Comment by christocracy** [comment]
Search "*AAPT: error: resource android:attr/lStar not found.*":

https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found

**Comment by RahajulAminRaju** [comment]
> background_fetch
the problem is with background_fetch package that you used in pubspec.yaml. comment this package then make the build. it will must work.

note: the to find the problem: when you get the error check the direction first.ERROR:/home/sonu/projects/flutter/H-ATTENDANCE/build/background_fetch/intermediates/merged_res/release/values/values.xml:2520: AAPT: error

 so here: search immediate folder after build folder. here immediate folder is 'background_fetch'. so, the problem is in backgroudn fetch package. there may have file missing when the package is downloaded. this is why the error came.

**Comment by christocracy** [comment]
No.  This error is typically associated with the Android dependency `appcompat`.

check your `appCompatVersion`.  

https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidbuildgradle

people having problems with this likely have multiple plugins importing different versions of this dependency.

Consult https://maven.google.com `appcompat`.

to see a dependency tree of your app, execute:

```console
$ ./gradlew app:dependencies
```

**Comment by christocracy** [comment]
This plug-in is happy to import any version of `appcompat` that you wish.  As the Setup Instructions remark “*or higher / as desired*”

```gradle
{
  appCompatVersion    = "1.4.2" // or higher / as desired
}
```

**Comment by diegocontini** [comment]
I was facing this issue, and finded a fix to my case. 
Sharing just in case help someone.

In my case, the issue was the PDF package and PRINTING package. 

Upgraded to this versions and fixed the issue: 
pdf: ^3.11.1
printing: ^5.13.2

If you use firebase too, consider reading this PR: https://github.com/firebase/flutterfire/pull/13200

**Comment by r0755466** [comment]
Can someone help I have currently an similar problem output: 

->Execution failed for task ':gdpr_dialog:verifyReleaseResources'.
->Android resource linking failed
ERROR :C:\Users\name\Desktop\app\newflutter\build\gdpr_dialog\intermediates\merged_res\release\values\values.xml:196: AAPT: error: resource android:attr/lStar not found.

**My current versions are:** 
Flutter **3.24.1** • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 5874a72aa4 (2 weeks ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2

Channel ->Stable 

The problem is that it only happens when i run the release mode on the debug mode it works. 
Have tried to update the **app/build.gradle** & **android/build.gradle** but still have the same error. 

Also tried to upgrade the dependencies of my pubspec.yaml:
checking first using flutter pub outdated
Upgraded for: flutter pub upgrade --major-versions

_I checked an tried:_
https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found

_i checked an tried:_ 
https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidbuildgradle

**My current App/build.gradle looks as next:** 

buildscript {
    ext.kotlin_version = '1.8.0' 

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'  // or 8.0.2 for Java 11+
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'  
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "${project(':background_fetch').projectDir}/libs" }
    }

   
    configurations.all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
            force "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        }
    }

}

   ext {
    
    compileSdkVersion   = 34
    targetSdkVersion    = 34
    // Had an error with the compiler changed from 1.7 to 1.6.1 works now 
    appCompatVersion    = "1.6.1"
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**My current Android/build.gradle looks as next:** 

pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}

include ":app"

Thank you for any help !

**Comment by christocracy** [comment]
Show me the result of the following command (it’s a lot of output)

```
$ cd android 
$ ./gradlew app:dependencies
```

**Comment by christocracy** [comment]
Try version `1.3.6` (just released).  I've removed the android dependency `androidx.appcompat:appcompat` from the plugin's `build.gradle` (it turns out it's not required).

**Comment by a-v-ebrahimi** [comment]
Add this to android/build.gradle

subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android { compileSdkVersion 34 }
            }
        }
}

**Comment by christocracy** [comment]
In version `1.3.7`, I have removed the `appcompat` dependency.

This plugin does not require this if you provide the required `ext` vars (including `ext.compileSdkVersion`)  in your root `build.gradle`, as documented in the [Android Setup Instructions](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidbuildgradle)

**Comment by Godse-07** [comment]
settings.gradle

pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    // START: FlutterFire Configuration
    id "com.google.gms.google-services" version "4.3.15" apply false
    // END: FlutterFire Configuration
    id "org.jetbrains.kotlin.android" version "2.0.21" apply false
}

include ":app"


and build.gradle


buildscript {
    ext.kotlin_version = '2.0.21'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}



and app/build.gradle 


plugins {
    id "com.android.application"
    // START: FlutterFire Configuration
    id 'com.google.gms.google-services'
    // END: FlutterFire Configuration
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader("UTF-8") { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty("flutter.versionCode")
if (flutterVersionCode == null) {
    flutterVersionCode = "1"
}

def flutterVersionName = localProperties.getProperty("flutter.versionName")
if (flutterVersionName == null) {
    flutterVersionName = "1.0"
}

android {
    namespace "com.example.woman_safety"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.example.woman_safety"
        minSdkVersion 23 // Keep this as 23 if it's required for your app
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
![Screenshot 2024-10-14 151911](https://github.com/user-attachments/assets/74f0b4bf-d3c9-4772-b26a-633552d19a27)

**Comment by christocracy** [comment]
This plug-in does not use Kotlin.

**Comment by Godse-07** [comment]
how to resolve it?

**Comment by christocracy** [comment]
I have no idea.  The plug-in has nothing to do with Kotlin version.

**Comment by arham-anees** [comment]
> This problem is related to the compileSdkVersion and targetSdkVersion of the plugins. This problem occurs because the compileSdkVersion and targetSdkVersion of some plugins are outdated. Either go to the source files of the plugin in your project and make the compileSdkVersion and targetSdkVersion versions the same as your project (version 34 compatible), or add the code block below to the build.gradle file in your project directory.
> 
> `subprojects { afterEvaluate { android { compileSdkVersion 34 } } }`
> 
> This code is a Gradle configuration script used in Android projects. The subprojects block allows you to configure certain settings for all subprojects (modules) in the project. The android block inside defines Android-related configuration settings, and the compileSdkVersion 34 line allows projects to be compiled with Android API 34.

worked for me

**Comment by ahmedevcode** [comment]
Adding this workaround on our android/build.gradle has resolved the issue for us.

subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}

**Comment by Godse-07** [comment]
@ahmedevcode thank you. It works

**Comment by sampaiopedrodev** [comment]
> ###
> **[Aziz-T](/Aziz-T) ** commented [Aug 14, 2024](#issuecomment-2288110601) •

this works for me, tks man

**Comment by gabuldev** [comment]
> In version `1.3.7`, I have removed the `appcompat` dependency.
> 
> > Add this to android/build.gradle
> 
> ```groovy-gradle
> subprojects {
>         afterEvaluate { project ->
>             if (project.hasProperty('android')) {
>                 project.android { compileSdkVersion 34 }
>             }
>         }
> }
> ```
> 
> _This plugin_ does not require this if you provide the required `ext` vars (including `ext.compileSdkVersion`) in your root `build.gradle`, as documented in the [Android Setup Instructions](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidbuildgradle)
> 
> Of course, _other_ plugins may have hard-coded `compileSdkVersion`, requiring that override, but this plugin does not.

This work for me <3

**Comment by Rajkumar07793** [comment]
I found a solultion you can add below line in  build.gradle of related package

`
dependencies {
  implementation 'androidx.core:core-ktx:1.6.0' 
}
`

**Comment by Godse-07** [comment]
@goofyhuang 

Open `android/build.gradle.kts` and update `compileSdk`, `targetSdk`:
```kotlin
buildscript {
    extra.apply {
        set("compileSdkVersion", 34)
        set("targetSdkVersion", 34)
        set("minSdkVersion", 21)
    }
}
```

Then open `android/app/build.gradle.kts` and make sure the `android` block looks like this:
```kotlin
android {
    compileSdk = 34
    defaultConfig {
        applicationId = "com.example.te"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }
}
```

Clean & rebuild - I think this will work!

**Comment by Godse-07** [comment]
@christocracy done
