### ISSUE TITLE
Any Possibility of running tasks when the app is terminated in iOS?

### ISSUE THREAD

**Issue by AvishkaG** [transistorsoft/flutter_background_fetch#370]
In your documentation, I see that **_when your app is terminated, iOS no longer fires events._** However, with BGTaskScheduler, Apple provides the ability to run tasks even when the app is terminated. You have implemented this feature into the plugin as well here https://github.com/transistorsoft/flutter_background_fetch/pull/76.

I would like to know if, in the latest version of the background_fetch plugin, it is possible to execute Flutter code periodically, even when the app is terminated, for **both Android & iOS**? Because the documentation does not say such thing but you have implemented BGTaskScheduler. I am confused a bit.

And here I meant by 'Terminate' state is , the app is not in the app switcher.

**Comment by christocracy** [comment]
> However, with BGTaskScheduler, Apple provides the ability to run tasks even when the app is terminated

What makes you think that?

**Comment by AvishkaG** [comment]
https://github.com/transistorsoft/flutter_background_fetch/issues/279#issuecomment-1097944845 That is what I understood after reading this. Correct me If I am wrong. And if I am wrong is there any possible way to run tasks when the app is killed or app is forced quit?

**Comment by christocracy** [comment]
There is no possible way for iOS to fire events when the app is terminated.
