### ISSUE TITLE
iOS Background service trying to make it alive.

### ISSUE THREAD

**Issue by A-Eric-J** [transistorsoft/flutter_background_fetch#377]
First of all, thank you for the plugin you've implemented.
I've read the documentation and noticed that the plugin wakes the app every 15 minutes. This means that every task I want to keep running will restart every 15 minutes. Is that correct?
I want to use a WebSocket to receive packets in the background service. Does this mean that after 15 minutes, the socket will close and I can reopen it again after 15 minutes according to the logic? 
I want to develop an iOS app (for flutter and iOS native) , and use webSocket in the background service and I want to being notify when a packet is sent to me, and do some tasks. this is what I want.
I mean that I want the Background service be always alive to hear to that opened socket.
Can I implement this using this plugin?
Thank you.

**Comment by christocracy** [comment]
Why not try it and see?  See the readme to learn how to simulate events.
