### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Anurag-Dubey12** [transistorsoft/flutter_background_fetch#378]
i am facing a problem such as:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':printing:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\abcom\Documents\Software\gully_app\build\printing\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

can anyone help me i am not getting any solution 

file name:app/build.gradle
plugins {
    id "com.android.application"
    id "kotlin-android"
    id "dev.flutter.flutter-gradle-plugin"
    id "com.google.gms.google-services"
    id 'com.google.firebase.crashlytics'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}
android {
    namespace "com.nileegames.gullyteam"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
 def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.nileegames.gullyteam"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        manifestPlaceholders = [
                auth0Domain : "YOUR_AUTH0_DOMAIN",
                auth0Scheme : "YOUR_AUTH0_SCHEME",
                applicationName : "com.nileegames.gullyteam.Gully Team"

        ]
    }

     signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }
}

flutter {
    source '../..'
}

dependencies {

}

file name:android/build.gradle

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
You ignored the issue template and the most crucial parts of it:

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**Comment by Anurag-Dubey12** [comment]
PS C:\Users\abcom\Documents\Software\gully_app> flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.93.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.


pubspec.yaml


name: gully_app
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  get: ^5.0.0-release-candidate-6
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  device_preview: ^1.1.0
  logger: ^2.0.1
  firebase_auth: ^4.8.0
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.1
  json_annotation: ^4.9.0
  intl: any
  image_picker: ^1.0.5
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.6
  mime: ^1.0.4
  http: ^1.2.1
  permission_handler: ^11.0.1
  geolocator: ^12.0.0
  cached_network_image: ^3.3.1
  geocoding: ^2.1.1
  socket_io_client: ^2.0.3+1
  flutter_widget_from_html: ^0.14.11
  firebase_messaging: ^14.7.10
  get_storage: ^2.1.1
  flutter_native_contact_picker: ^0.0.5
  flutter_cache_manager: ^3.3.1
  restart_app: ^1.2.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.2.5
  firebase_crashlytics: ^3.4.18
  share_plus: ^7.2.2
  package_info_plus: ^6.0.0
  app_links: ^4.0.1
  connectivity_widget: ^2.0.0
  flashy_tab_bar2: ^0.0.10
  photo_view: ^0.14.0
  iconsax: ^0.0.8
  pdf: ^3.8.4
  printing: ^5.9.3
  file_picker: ^5.2.0
  flutter_localizations:
    sdk: flutter
  razorpay_flutter: ^1.3.0
#  flutter_media_downloader: ^1.0.4
  # connectivity_plus: ^6.0.1

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/.
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
          weight: 700
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 600
        - asset: assets/fonts/GothamMedium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Light.otf
          weight: 300
        - asset: assets/fonts/Gotham-Thin.otf
          weight: 100

**Comment by Anurag-Dubey12** [comment]
> You ignored the issue template and the most crucial parts of it:
> 
> **Your Environment**
> 
> * Plugin version:
> * Platform: iOS or Android
> * OS version:
> * Device manufacturer / model:
> * Flutter info (`flutter info`, `flutter doctor`):
> * Plugin config




PS C:\Users\abcom\Documents\Software\gully_app> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
X Android license status unknown.
Run flutter doctor --android-licenses to accept the SDK licenses.
See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
X Visual Studio not installed; this is necessary to develop Windows apps.
Download at https://visualstudio.microsoft.com/downloads/.
Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.93.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

pubspec.yaml

name: gully_app
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+2

environment:
sdk: ">=3.3.0 <4.0.0"

dependencies:
get: ^5.0.0-release-candidate-6
pin_code_fields: ^8.0.1
flutter:
sdk: flutter

cupertino_icons: ^1.0.2
flutter_svg: ^2.0.7
device_preview: ^1.1.0
logger: ^2.0.1
firebase_auth: ^4.8.0
google_sign_in: ^6.1.4
firebase_core: ^2.15.1
json_annotation: ^4.9.0
intl: any
image_picker: ^1.0.5
google_maps_flutter: ^2.5.0
google_places_flutter: ^2.0.6
mime: ^1.0.4
http: ^1.2.1
permission_handler: ^11.0.1
geolocator: ^12.0.0
cached_network_image: ^3.3.1
geocoding: ^2.1.1
socket_io_client: ^2.0.3+1
flutter_widget_from_html: ^0.14.11
firebase_messaging: ^14.7.10
get_storage: ^2.1.1
flutter_native_contact_picker: ^0.0.5
flutter_cache_manager: ^3.3.1
restart_app: ^1.2.1
carousel_slider: ^5.0.0
url_launcher: ^6.2.5
firebase_crashlytics: ^3.4.18
share_plus: ^7.2.2
package_info_plus: ^6.0.0
app_links: ^4.0.1
connectivity_widget: ^2.0.0
flashy_tab_bar2: ^0.0.10
photo_view: ^0.14.0
iconsax: ^0.0.8
pdf: ^3.8.4
printing: ^5.9.3
file_picker: ^5.2.0
flutter_localizations:
sdk: flutter
razorpay_flutter: ^1.3.0

flutter_media_downloader: ^1.0.4
connectivity_plus: ^6.0.1
dev_dependencies:
build_runner: ^2.4.12
json_serializable: ^6.8.0
flutter_test:
sdk: flutter
flutter_lints: ^2.0.0

flutter:
generate: true
uses-material-design: true
assets:
- assets/images/.
fonts:
- family: Gotham
fonts:
- asset: assets/fonts/Gotham-Black.otf
weight: 700
- asset: assets/fonts/Gotham-Bold.otf
weight: 600
- asset: assets/fonts/GothamMedium.ttf
weight: 500
- asset: assets/fonts/Gotham-Light.otf
weight: 300
- asset: assets/fonts/Gotham-Thin.otf
weight: 100

**Comment by christocracy** [comment]
Why are you posting an issue at the GitHub repo for a plugin you’re not even using?

**Comment by Anurag-Dubey12** [comment]
> Why are you posting an issue at the GitHub repo for a plugin you’re not even using?

Actually I am trying to build a flutter application but I am facing some issue and I don't know how to solve it so I am just asking for help.

**Comment by christocracy** [comment]
I’m here to support *my* plug-ins, not provide generalized support to the world.

you’re not using my stuff.
