### ISSUE TITLE
registerHeadlessTask  doesn't work with me 

### ISSUE THREAD

**Issue by EmanFateen** [transistorsoft/flutter_background_fetch#38]
Your Environment

Plugin version: 0.2.0
Platform: iOS or Android
OS version: 9
Device manufacturer / model: Xiaomi note 6 
Flutter info (flutter info, flutter doctor):
Plugin config 

To Reproduce

    close the application
    I receive nothing

Debug logs
[ I have an issue I can't debug but I run the app and wait 15 min to receive the result]

Additional context

Here is my Andriod Application.java

```
package com.mowakeb.hepsitezim;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application  extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}

```

my main 
``
```
void main() async {


  // Enable integration testing with the Flutter Driver extension.
  // See https://flutter.io/testing/ for more info.
  runApp(new LoginPage());




  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

and finally the function 

```
/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');

  SharedPreferences prefs = await SharedPreferences.getInstance();

  // Read fetch_events from SharedPreferences
  List<String> events = [];
  String json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  // Add new event.
  events.insert(0, new DateTime.now().toString() + ' [Headless]');
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));

  BackgroundFetch.finish();
}
```

**Comment by christocracy** [comment]
The issue template is not *optional*, it's *required*

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by christocracy** [comment]
Edit your issue and apply the required issue template, in addition to the code you're using.  How can I help you with 0 information??

**Comment by EmanElmasry** [comment]
Your Environment

    Plugin version: 0.2.0
    Platform: iOS or Android
    OS version: 9
    Device manufacturer / model: Xiaomi note 6 
    Flutter info (flutter info, flutter doctor):
    Plugin config 

To Reproduce
Steps to reproduce the behavior:
1.  close the application 
2. I receive nothing


Debug logs
    [ I have an issue I can't debug but I run the app and wait 15 min to receive the result]

Additional context
Add any other context about the problem here.

**Comment by christocracy** [comment]
Please take everything you just posted, *edit your original post*, and paste it *there*.

**Comment by EmanElmasry** [comment]
okay Done

**Comment by christocracy** [comment]
Now edit your issue since again and provide the code you’re using

**Comment by EmanElmasry** [comment]
done

**Comment by christocracy** [comment]
> but I run the app and wait 15 min to receive the resul

Why are you *waiting*?  You can simulate fetch events, as [documented in the README](https://github.com/transistorsoft/flutter_background_fetch#large_blue_diamond-debugging)

**Comment by EmanElmasry** [comment]
> 
> 
> > but I run the app and wait 15 min to receive the resul
> 
> Why are you _waiting_? You can simulate fetch events, as [documented in the README](https://github.com/transistorsoft/flutter_background_fetch#large_blue_diamond-debugging)

I received this error 

> '$' is not recognized as an internal or external command,
> operable program or batch file.

no problem with waiting 15 min But I have a big problem that this not working :(

**Comment by christocracy** [comment]
`$` IS AN EXAMPLE OF A TERMINAL PROMPT!  

Execute the command **WITHOUT** the `$`.

**Comment by billymahmood** [comment]
< your.application.id > is this the app bundle id?

**Comment by christocracy** [comment]
Yes
