### ISSUE TITLE
Background process is not available/running when App is closed/terminated

### ISSUE THREAD

**Issue by halhwadi** [transistorsoft/flutter_background_fetch#383]
**Your Environment**: 
 Windows 11 home
* Plugin version:* ^1.3.7
* Platform: iOS or Android **(Android)**
* OS version: Android 12
* Device manufacturer / model: Galaxy A12
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4317], locale en-AE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2024.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

* Plugin config
**main.dart file:**

```
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;
  bool isTimeout = task.timeout;
  if (isTimeout) {
    // This task has exceeded its allowed running-time.
    // You must stop what you're doing and immediately .finish(taskId)
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }
  print('[BackgroundFetch] Headless event received.');
  // Do your work here...
  BackgroundFetch.finish(taskId);
}
void main() async{
  //Running main App
WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```
 **// Initialize Background Fetch**
 ```
 void initBackgroundFetch() async {
    BackgroundFetch.configure(
      BackgroundFetchConfig(
        minimumFetchInterval: 15, // The minimum interval for fetching in minutes
        stopOnTerminate: false,   // Continue running after the app is terminated
        startOnBoot: true,        // Start background fetch when the device boots up
        enableHeadless: true,     // Enable the headless task to run in the background
      ), (String taskId) async {
      print("[BackgroundFetch] taskId: $taskId");

    // Fetch location
      Position position = await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.high);

      // Send the location to the server
      postlocation(position.latitude, position.longitude, disturb_me);
      print('background fetch is triggered');
      print('lat: ${position.latitude}, long: ${position.longitude}');

      // Complete the background task
      BackgroundFetch.finish(taskId);
    },
    );
  }

@override
  void initState() {
    WidgetsBinding.instance.addObserver(this);
   .
   .
   .
    initBackgroundFetch();
    super.initState();
}
```

**To Reproduce**
1. Run the the App
2. Check the run logs which shows that flutter_background_fetch (jobId: 999) job has been created (see the details below):
[io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)] [io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)]
D/TSBackgroundFetch(13984): - configure
D/TSBackgroundFetch(13984): - start
D/TSBackgroundFetch(13984): - registerTask: flutter_background_fetch (jobId: 999)
D/TSBackgroundFetch(13984): {
D/TSBackgroundFetch(13984):   "taskId": "flutter_background_fetch",
D/TSBackgroundFetch(13984):   "isFetchTask": true,
D/TSBackgroundFetch(13984):   "minimumFetchInterval": 15,
D/TSBackgroundFetch(13984):   "stopOnTerminate": false,
D/TSBackgroundFetch(13984):   "requiredNetworkType": 0,
D/TSBackgroundFetch(13984):   "requiresBatteryNotLow": false,
D/TSBackgroundFetch(13984):   "requiresCharging": false,
D/TSBackgroundFetch(13984):   "requiresDeviceIdle": false,
D/TSBackgroundFetch(13984):   "requiresStorageNotLow": false,
D/TSBackgroundFetch(13984):   "startOnBoot": true,
D/TSBackgroundFetch(13984):   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
D/TSBackgroundFetch(13984):   "forceAlarmManager": false,
D/TSBackgroundFetch(13984):   "periodic": true,
D/TSBackgroundFetch(13984):   "delay": -1

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`
there is no job/process when checking the job id number on mobile device:
$ adb shell ps | grep 999
adb shell ps | grep flutter_background_fetch

**Additional context**

**Comment by christocracy** [comment]
Are you simulating events?

**Comment by halhwadi** [comment]
Sorry I didn't understand your questions, I downloaded the code on android device and tested it, There is no API call after app got killed/closed at all, I need to get the user location even when app is closed and that's why I use flutter background fetch package.
again i run the App from android studio terminal "Flutter run" and got this log:
tworkCallbackForUid(ConnectivityManager.java:5380)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(Con
nectivityManager.java:5347)] 

> [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:5321)] [dev.fluttercommunity.p
> lus.connectivity.ConnectivityBroadcastReceiver.onListen(ConnectivityBroadcastReceiver.java:56)] [io.flutter.plugin.common.EventChannel$IncomingStrea
> mRequestHandler.onListen(EventChannel.java:218)] [io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197
> )] [io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)] [io.flutter.embedding.engine.dart.DartMessenger.lambda$dis
> patchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)] [io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)]
> D/TSBackgroundFetch(27878): - configure
> D/TSBackgroundFetch(27878): Re-configured existing task
> I/TSBackgroundFetch(27878): - cancel taskId=flutter_background_fetch, jobId=999
> D/TSBackgroundFetch(27878): {
> D/TSBackgroundFetch(27878):   "taskId": "flutter_background_fetch",
> D/TSBackgroundFetch(27878):   "isFetchTask": true,
> D/TSBackgroundFetch(27878):   "minimumFetchInterval": 15,
> D/TSBackgroundFetch(27878):   "stopOnTerminate": false,
> D/TSBackgroundFetch(27878):   "requiredNetworkType": 0,
> D/TSBackgroundFetch(27878):   "requiresBatteryNotLow": false,
> D/TSBackgroundFetch(27878):   "requiresCharging": false,
> D/TSBackgroundFetch(27878):   "requiresDeviceIdle": false,
> D/TSBackgroundFetch(27878):   "requiresStorageNotLow": false,
> D/TSBackgroundFetch(27878):   "startOnBoot": true,
> D/TSBackgroundFetch(27878):   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
> D/TSBackgroundFetch(27878):   "forceAlarmManager": false,
> D/TSBackgroundFetch(27878):   "periodic": true,
> D/TSBackgroundFetch(27878):   "delay": -1
> D/TSBackgroundFetch(27878): }

**Comment by halhwadi** [comment]
Its working once I moved the the backend API call to register task code in Main.dart 


```
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;
  bool isTimeout = task.timeout;
  if (isTimeout) {
    // This task has exceeded its allowed running-time.
    // You must stop what you're doing and immediately .finish(taskId)
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }
  print('[BackgroundFetch] Headless event received.');
  // Do your work here...
// Send the location to the server
  postlocation(position.latitude, position.longitude, disturb_me);
  BackgroundFetch.finish(taskId);
}
```
