### ISSUE TITLE
[BUG] AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by ugur010** [transistorsoft/flutter_background_fetch#384]
PS C:\xampp\htdocs\Mobile app> flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 3688 bytes (99.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_barcode_scanner:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\xampp\htdocs\Mobile app\build\flutter_barcode_scanner\intermediates\merged_res\release\values\values.xml:6135: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 15s
Running Gradle task 'assembleRelease'...                           15,8s
Gradle task assembleRelease failed with exit code 1
PS C:\xampp\htdocs\Mobile app>

**Comment by christocracy** [comment]
>Execution failed for task ':flutter_barcode_scanner

Why are you posting your issue here at `background_fetch`?

**Comment by ugur010** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_barcode_scanner:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\xampp\htdocs\Mobile app\build\flutter_barcode_scanner\intermediates\merged_res\release\values\values.xml:6135: AAPT: error: resource android:attr/lStar not found.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 51s
Running Gradle task 'assembleRelease'...                           52,0s
Gradle task assembleRelease failed with exit code 1
PS C:\xampp\htdocs\Mobile app\android>

**Comment by ugur010** [comment]
Can you help me? My project has not been finished for 2 days because of this plugin.

**Comment by christocracy** [comment]
> flutter_barcode_scanner

Do you understand that this is **not** the barcode scanner GitHub repo?  This is background_fetch.
