### ISSUE TITLE
Background fetch event not received after the first time

### ISSUE THREAD

**Issue by jagan999** [transistorsoft/flutter_background_fetch#4]
I configured your plugin on Android Nougat. It fired once at the 11th minute from app startup but after that it's not firing any fetch event. Any tips on what I might be missing?

**Comment by jagan999** [comment]
Yes, I'm executing Background.finish in my callback. Even though the interval is not exact, shouldn't I expect the fetch event to be triggered at least after 30 minutes?
Interestingly, the fetch event fired again when my app came to the foreground. Anything I'm doing wrong? I thought the events will fire even if the app is NOT in the foreground and even if it gets killed (i have headless mode on)

**Comment by christocracy** [comment]
What is your Device model / OS.

My Pixel @ 9.0 gets quite regular fetch events.  Typically every 10-15 minutes while plugged into power, regardless if running in background, foreground or terminated with `enableHeadless: true`.

**Comment by jagan999** [comment]
You're probably right that the event firing frequency may be very low if the device is not plugged in. Let me check and revert. Thanks for the prompt replies. Appreciate it.

**Comment by christocracy** [comment]
I've been running the `/example` app on my device (plugged in) for the last 2 hours:
![](https://dl.dropboxusercontent.com/s/gkf1nsu5e6wzcex/Screenshot%202018-11-13%2014.02.57.png?dl=1)

**Comment by jagan999** [comment]
I did the following overnight and have the following observations:

- Made my app go to the background. Put my phone on power overnight. Fetch events triggered every 15 mins from 10pm to 11.58pm and then stopped, even though the phone was on power

- At 6am, I pulled out the power. No events were triggered until I opened the app. Then fetch events started every 15 mins even after my app went background. 

- I force stopped my app to check if headless events are received. No events were received when the app was terminated.

This doesn't seem to work reliably or I'm doing something wrong. Can you pl provide recommendations to debug/fix this issue?

**Comment by christocracy** [comment]
I asked you above:

>What is your Device model / OS.

**Comment by jagan999** [comment]
Sorry, I thought I replied. My device model is ASUS Z011D and the OS is Android 7.1.2

**Comment by christocracy** [comment]
Show me logs after simulating a fetch:
```
$ adb shell cmd jobscheduler run -f <your.application.id> 999
```

```
$ adb logcat *:S flutter:V, TSBackgroundFetch:V
```

**Comment by jagan999** [comment]
ok, will do right now. What's meant to be supplied to <your.application.id>?

**Comment by christocracy** [comment]
@jagan999 your *Android application id*, what else?

**Comment by jagan999** [comment]
Here's the output from the terminal

c:\Users\srinivasanj\AppData\Local\Android\Sdk\platform-tools>adb shell cmd jobscheduler run -f com.moneyguru.flutterapp 999
Running job [FORCED]

c:\Users\srinivasanj\AppData\Local\Android\Sdk\platform-tools>adb logcat *:S flutter:V, TSBackgroundFetch:V
--------- beginning of system
--------- beginning of main
11-14 06:59:39.739 30138 30166 I flutter : Observatory listening on http://127.0.0.1:33910/
11-14 09:57:06.488 25191 25191 D TSBackgroundFetch: - Background Fetch event received
11-14 09:57:06.495 25191 25191 D TSBackgroundFetch: - finish
11-14 09:57:06.495 25191 25191 D TSBackgroundFetch: - jobFinished
11-14 09:57:06.544 25191 25191 D TSBackgroundFetch: HeadlessJobService onStartJob
11-14 09:57:06.545 25191 25191 D TSBackgroundFetch: ≡ƒÆÇ [HeadlessTask]
11-14 09:57:07.287 25191 25222 I flutter : Observatory listening on http://127.0.0.1:33413/
11-14 09:57:07.288 25191 25191 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
11-14 09:57:08.790 25191 25191 I TSBackgroundFetch: $ initialized
11-14 09:57:09.147 25191 25219 I flutter : INFO: 2018-11-14 09:57:09.101306: [BackgroundFetch] Headless event received.
11-14 09:57:09.179 25191 25219 I flutter : INFO: 2018-11-14 09:57:09.178718: System scheduler invoked at 2018-11-14T09:57:09.175587
11-14 09:57:09.540 25191 25219 I flutter : INFO: 2018-11-14 09:57:09.540093: In System scheduler - Connectivity=ConnectivityResult.wifi
11-14 09:57:09.650 25191 25191 D TSBackgroundFetch: - finish
11-14 09:57:09.650 25191 25191 D TSBackgroundFetch: HeadlessJobService jobFinished
11-14 09:57:29.259 20560 20560 D TSBackgroundFetch: - Background Fetch event received
11-14 09:57:29.262 20560 20581 I flutter : [BackgroundFetch] Event received
11-14 09:57:29.263 20560 20560 D TSBackgroundFetch: - finish
11-14 09:57:29.263 20560 20560 D TSBackgroundFetch: - jobFinished
11-14 10:00:53.181 25903 25903 D TSBackgroundFetch: - Background Fetch event received
11-14 10:00:53.187 25903 25903 D TSBackgroundFetch: - finish
11-14 10:00:53.187 25903 25903 D TSBackgroundFetch: - jobFinished
11-14 10:00:53.251 25903 25903 D TSBackgroundFetch: HeadlessJobService onStartJob
11-14 10:00:53.251 25903 25903 D TSBackgroundFetch: ≡ƒÆÇ [HeadlessTask]
11-14 10:00:53.923 25903 25903 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
11-14 10:00:53.950 25903 25932 I flutter : Observatory listening on http://127.0.0.1:52971/
11-14 10:00:55.591 25903 25903 I TSBackgroundFetch: $ initialized
11-14 10:00:55.916 25903 25927 I flutter : INFO: 2018-11-14 10:00:55.867458: [BackgroundFetch] Headless event received.
11-14 10:00:55.960 25903 25927 I flutter : INFO: 2018-11-14 10:00:55.960378: System scheduler invoked at 2018-11-14T10:00:55.957883
11-14 10:00:56.384 25903 25927 I flutter : INFO: 2018-11-14 10:00:56.384300: In System scheduler - Connectivity=ConnectivityResult.wifi
11-14 10:00:56.539 25903 25903 D TSBackgroundFetch: - finish
11-14 10:00:56.539 25903 25903 D TSBackgroundFetch: HeadlessJobService jobFinished

**Comment by christocracy** [comment]
Looks perfect.  Inconsistencies are likely related to the device.

**Comment by jagan999** [comment]
ok thanks. I'll proceed to use this with the assumption that it will work just fine on another device.

**Comment by christocracy** [comment]
Are you running the `/example` app in this repo?  If not, do so.  Keep it running in the background (not Headless) for a few days.  It prints timestamp of each fetch event to a list.

**Comment by jagan999** [comment]
Works fine. Closing this issue
