### ISSUE TITLE
Question about 'providing a short period of background running-time'

### ISSUE THREAD

**Issue by DartMen** [transistorsoft/flutter_background_fetch#40]
Is it known how lengthy a 'short period of background running-time' is with real world experiences on the 2 major platforms?

Are processes interrupted or killed when the 'short period' is exceeded? And if this is the case, do we get notified by the OS (on both platforms) if a running background task is about to be killed?

Is there any in-depth information about this?

How would one handle/survive killed background tasks, is there a known recovery strategy?

I am considering the use of flutter_background_fetch for my use-case which is to periodically upload a few megabytes of data, but it is vital this upload process should not be interrupted.

Thanks a lot for providing this plugin!

**Comment by christocracy** [comment]
- iOS provides **exactly** 30s.  iOS does fire a callback on the native side when a task is “force finished”, which you’ll see in the logs, but the plugin doesn’t relay this to your Dart code.
- Android is more lenient.  You *should* get as long as necessary to complete your task but you might be penalized if you take *too* long to call #finish, in that the OS might wait longer before firing the *next* event.

**Comment by DartMen** [comment]
Thanks for your fast reply!

Well that would be a bit challenging when one is on a slow connection.

**Comment by christocracy** [comment]
iOS designed, for example, so something like a sports app could *fetch* the latest scores so that when user opens app, it immediately shows recent scores immediately.

It wasn’t designed for periodically *uploading* large amounts of data.
