### ISSUE TITLE
BuildContext in headless task

### ISSUE THREAD

**Issue by apaolino** [transistorsoft/flutter_background_fetch#41]
I would to launch a notification (using flutter_local_notifications extension) with a translated message in my headless task. The translation extension needs a BuildContext instance in order to work. 
How could I resolve this?

**Comment by christocracy** [comment]
I will look into it.

**Comment by christocracy** [comment]
Can you show me some example code of what you're trying to do?  What is this "translation extension"?

**Comment by apaolino** [comment]
Hi, 
the translation extension I'm referring to is ["easy_localization"](https://pub.dev/packages/easy_localization).  I tought a BuildContext instance was needed to use it but I've resolved simply by instantiating AppLocalizations object in this way:

```
AppLocalizations _appLocalization = await EasylocaLizationDelegate(
            locale: _defaultLocale,
            path: Constants.LOCALES_ASSETS_TRANLATION_PATH)
        .load(_defaultLocale);

await _appLocalization.load();
```

**Comment by christocracy** [comment]
>Is there way to access the context? 

I  don't know.  That's a general *Flutter* question.  Why do you need `Context` for localization?

**Comment by christocracy** [comment]
Why not *poke* your user's language into `shared_preferences` *when you do* have `Context`?

Then read it from `shared_preferences` in the headless state.
