### ISSUE TITLE
HeadlessTask.java:error: method findAppBundlePath in class FlutterMain cannot be applied to given types[BUG]

### ISSUE THREAD

**Issue by pacifio** [transistorsoft/flutter_background_fetch#45]
**Environment**
ubuntu 18.04
openjdk version "1.8.0_222"
* Plugin version: latest
* Platform: Android
* OS version: API 28
* Device manufacturer / model: emulator
* Error info
```
/home/$USER/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.3.0/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/HeadlessTask.java:139: error: method findAppBundlePath in class FlutterMain cannot be applied to given types;
        args.bundlePath = FlutterMain.findAppBundlePath();              
                                     ^                                  
  required: Context                                                     
  found: no arguments                                                   
  reason: actual and formal argument lists differ in length             
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':background_fetch:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 0s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         1.5s
Gradle task assembleDebug failed with exit code 1
```

* Plugin config
As shown in the Android setup.md

**Additional context**
I followed the complete setup and the app didn't even started ... I can show you code if needed ... but it's showing the error above and it does not even build the app itself . Please help me .

**Comment by christocracy** [comment]
$ flutter doctor.

Pleas don’t write “Plugin version: latest”.  It becomes more meaningless with each new commit.

**Comment by christocracy** [comment]
I've found the issue.  Flutter `1.9.1` deprecated a method `FlutterMain.findAppBundlePath(Context)` so I updated the code to the new method signature `FlutterMain.findAppBundlePath()` (no `Context`).  This broke for those not running latest flutter.

Will be fixed and released in the next few minutes.

**Comment by christocracy** [comment]
`0.3.1` is released with fix.

**Comment by christocracy** [comment]
And in the future, *please* don't ignore any of the issue template, *especially* `flutter doctor`.  Your flutter version was the reason for the crash.

**Comment by ThinkDigitalSoftware** [comment]
Since flutter 1.9.1 stable now, shouldn't it be the version this package is compatible with, and anyone on older versions should use version constraints until they update?

**Comment by christocracy** [comment]
It's a little more complex than that, since `background_fetch` is primarily designed as a companion for my larger [flutter_background_geolocation]().  

In this case, the deprecated [FlutterMain.findAppBundlePath](https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/view/FlutterMain.java#L319-L327) method is merely a change in signature; both return the same static `sFlutterAssetsDir`.  The provided `Context` instance is no longer used.

**Comment by prkhrv** [comment]
I am still getting Headless Task using Depreciated API error, What i am Doing Wrong? should i specify version 0.3.2 ? in pubspec.yaml?

**Comment by christocracy** [comment]
Ignore it.  It’s a warning, not an error.  I know exactly what it is and it’s of no consequence.

**Comment by prkhrv** [comment]
@christocracy Ok,cool
