### ISSUE TITLE
[BUG] Headless Task keep stopping the app

### ISSUE THREAD

**Issue by AmitaiMazliah** [transistorsoft/flutter_background_fetch#46]
**Your Environment**

Plugin version: ^0.2.0
Platform: Android
OS version: emulator running on API 29
Device manufacturer / model: emulator
Flutter info  flutter doctor:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/amazliah/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/amazliah/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/amazliah/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Amitai’s iPhone           • 7edd26a6799275901fd814f834d50eea0707af99 • ios         • iOS 12.1.4
    • iPhone Xʀ                 • 992F0FBD-B1E7-41B9-B8B5-5A5546709EE2     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

Plugin config
```
BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            enableHeadless: true,
            startOnBoot: true), () async {
      // This is the fetch-event callback.
      print('[BackgroundFetch] Event received hfdhfdhdhfdhdh');

      Firestore.instance
          .collection('steps')
          .document('1')
          .setData({'value': DateTime.now()});

      // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
      // for taking too long in the background.
      BackgroundFetch.finish();
    }).then((int status) {
      print('[BackgroundFetch] configure success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    });
```
**To Reproduce**
1. Run the app on emulator
2. Close the app
3. Force background fetch with adb shell cmd jobscheduler run -f com.example.amitai_awesome_app 999
4. Log at emulator as app gives error popup, also logs give error

**Debug logs**

> Process: com.example.amitai_awesome_app, PID: 24213
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(HeadlessTask.java:47)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)
        at android.app.job.JobService$1.onStartJob(JobService.java:62)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)

**Additional context**

I'm trying to use headless task of my android emulator but when I'm forcing a background fetch after closing the app, it's crashing.

My Application.kt
```
package com.example.amitai_awesome_app

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
  override fun onCreate() {
    super.onCreate();
    BackgroundFetchPlugin.setPluginRegistrant(this);
  }

  override fun registerWith(registry: PluginRegistry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

The headless task code is:

```
/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');

  BackgroundFetch.finish();
}
```

**Comment by christocracy** [comment]
Ignored issue template:

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by AmitaiMazliah** [comment]
Fixed

**Comment by christocracy** [comment]
Not quite:

>Flutter info (flutter info, flutter doctor):

**Comment by jpandaconnor** [comment]
@christocracy

Hi, as @AmitaiMazliah has rectified the issue to follow the template, could you follow up on the issue above. I am finding the headless implementation to be a pain especially on the Android platform. Alongside the error provided that intermittently occurs,  I am myself receiving the following on running the command:

`./adb shell cmd jobscheduler run -f PACKAGENAME 999`

Error:

10-13 20:46:14.788 31617 31617 D TSBackgroundFetch: - Background Fetch event received
10-13 20:46:14.823 31617 31617 D TSBackgroundFetch: - finish
10-13 20:46:14.823 31617 31617 D TSBackgroundFetch: - jobFinished
10-13 20:46:14.865 31617 31617 D TSBackgroundFetch: HeadlessJobService onStartJob
10-13 20:46:14.871 31617 31617 D TSBackgroundFetch: 💀 [HeadlessTask]

My code looks pretty much like the above. Thanks

**Comment by christocracy** [comment]
@jpandaconnor Show me your stacktrace.  This is not an error, it's normal output.
```
10-13 20:46:14.788 31617 31617 D TSBackgroundFetch: - Background Fetch event received
10-13 20:46:14.823 31617 31617 D TSBackgroundFetch: - finish
10-13 20:46:14.823 31617 31617 D TSBackgroundFetch: - jobFinished
10-13 20:46:14.865 31617 31617 D TSBackgroundFetch: HeadlessJobService onStartJob
10-13 20:46:14.871 31617 31617 D TSBackgroundFetch: 💀 [HeadlessTask]
```

>I am finding the headless implementation to be a pain especially on the Android platform

Headless is an *Android-only* mechanism.  There's no such thing as headless iOS.

**Comment by AmitaiMazliah** [comment]
Any ideas about the error log I posted?

I'm posting again the stack trace

> Process: com.example.amitai_awesome_app, PID: 24213
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.(HeadlessTask.java:47)
at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)
at android.app.job.JobService$1.onStartJob(JobService.java:62)
at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)

**Comment by christocracy** [comment]
The lastest version of [`background_fetch`](https://pub.dev/packages/background_fetch/versions/0.3.2#-readme-tab-) is `0.3.2`

**Comment by martinarlando** [comment]
any update for this issue? I use the latest version of `background_fetch`

**Comment by christocracy** [comment]
It’s not a problem caused by the plugin.  It’s an issue with your setup or another plugin.

Try the /example app in this repo.  You’ll find no such issue.
