### ISSUE TITLE
[BUG] PlatFormException due to no service.

### ISSUE THREAD

**Issue by Jayant2204** [transistorsoft/flutter_background_fetch#47]
**Your Environment**
* Plugin version: 0.3.1
* Platform: iOS or Android : Android
* OS version: API 28
* Device manufacturer / model: Emulator (Pixel3A)
* Flutter info (`flutter info`, `flutter doctor`): $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

• No issues found!
* Plugin config : BackgroundFetch.configure(
        BackgroundFetchConfig(
            minimumFetchInterval: 15,
            stopOnTerminate: false,
            enableHeadless: false,
            requiresBatteryNotLow: false,
            requiresCharging: false,
            requiresStorageNotLow: false,
            requiresDeviceIdle: false,
            requiredNetworkType: BackgroundFetchConfig.NETWORK_TYPE_ANY),

**To Reproduce**
1. Copy the example app.
2. remove the 3 variables _status, _enable, _events and add bgStatus (does same thing as _status)
3. run in debug-mode (Error occurred in release mode as well)
4. Exception -> Exception has occurred.
PlatformException (PlatformException(error, No such service ComponentInfo{com.baseapp.powersense/com.transistorsoft.tsbackgroundfetch.FetchJobService}, null))

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`
$ adb logcat *:S flutter:V, TSBackgroundFetch:V
--------- beginning of crash
--------- beginning of main
09-30 16:48:32.193  3902  3902 W TSBackgroundFetch: - Configuration error:  {forceReload: false, jobService: null} is incompatible with stopOnTerminate: false:  Enforcing stopOnTerminate: true.
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch: - configure: {
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "minimumFetchInterval": 15,
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "stopOnTerminate": true,   
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "requiredNetworkType": 1,  
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "requiresCharging": false,
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "requiresDeviceIdle": false,
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "requiresStorageNotLow": false,
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "startOnBoot": false,
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch:   "forceReload": false
09-30 16:48:32.193  3902  3902 D TSBackgroundFetch: }
09-30 16:48:32.204  3902  3902 D TSBackgroundFetch: - start
09-30 16:48:32.213  3902  4113 I flutter : [BackgroundFetch] configure ERROR: Throw of null.
09-30 16:48:32.213  3902  4113 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'NullThrownError' is not a subtype of type 'int'
09-30 16:48:32.213  3902  4113 E flutter : #0      _MyAppState.initPlatformState.<anonymous closure>.<anonymous closure> (package:powersense/main.dart:90)
09-30 16:48:32.213  3902  4113 E flutter : #1      State.setState (package:flutter/src/widgets/framework.dart:1141)
09-30 16:48:32.213  3902  4113 E flutter : #2      _MyAppState.initPlatformState.<anonymous closure> (package:powersense/main.dart:89)
09-30 16:48:32.213  3902  4113 E flutter : #3      _rootRunUnary (dart:async/zone.dart:1132)
09-30 16:48:32.213  3902  4113 E flutter : #4      _CustomZone.runUnary (dart:async/zone.dart:1029)
09-30 16:48:32.213  3902  4113 E flutter : #5      _FutureListener.handleError (dart:async/future_impl.dart:155)
09-30 16:48:32.213  3902  4113 E flutter : #6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690)
09-30 16:48:32.213  3902  4113 E flutter : #7      Future._propagateToListeners (dart:async/future_impl.dart:711)
09-30 16:48:32.213  3902  4113 E flutter : #8      Future._completeError (dart:async/future_impl.dart:530)
09-30 16:48:32.213  3902  4113 E flutter : #9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578)
09-30 16:48:32.213  3902  4113 E flutter : #10     _rootRun (dart:async/zone.dart:1124)
09-30 16:48:32.213  3902  4113 E flutter : #11     _CustomZone.run (dart:async/zone.dart:1021)
09-30 16:48:32.213  3902  4113 E flutter : #12     _CustomZone.runGuarded (dart:async/zone.dart:923)
09-30 16:48:32.213  3902  4113 E flutter : #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963)
09-30 16:48:32.213  3902  4113 E flutter : #14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
09-30 16:48:32.213  3902  4113 E flutter : #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
09-30 16:48:32.213  3902  4113 E flutter :

**Additional context**
 i'm trying to fetch shared preferences and call a REST api after SharedPref to compare a single value in order to send notification to the user.

**Comment by Jayant2204** [comment]
It worked after adding Headless and enabling it. along with flutter clean.

**Comment by JeasonLaung** [comment]
how did you reslove this problem?
I met it and I can't find how to do

**Comment by christocracy** [comment]
He explained how.

> It worked after adding Headless and enabling it. along with flutter clean.

**Comment by netofontess** [comment]
> how did you reslove this problem?
> I met it and I can't find how to do

I have the same problem. I don't understand either. Already enabled the Headless in the configuration parameters, need to do something else?

Tks!

**Comment by christocracy** [comment]
@netofontess where’s your stacktrace?

**Comment by netofontess** [comment]
> @netofontess where’s your stacktrace?

Sry @christocracy ... I solved my problem. I was forgetting to do flutter clean. This is extremely important when enabling Headless.
Tk's again.
