### ISSUE TITLE
[BUG] Building release apk fails - Plugin 'com.android.library' not found.

### ISSUE THREAD

**Issue by LampeMW** [transistorsoft/flutter_background_fetch#50]
**Your Environment**
* Plugin version: 0.3.2
* Platform: Android
* OS version: MacOS Catalina
* Flutter info (`flutter info`, `flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

• No issues found!
```
* Plugin config

**To Reproduce**
1. Run `flutter build apk --release`
2.
3.
4.

**Debug logs**
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/m/Github/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.3.2/android/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'background_fetch'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s


The plugin background_fetch could not be built due to the issue above.
```

**Additional context**
After updating to background_fetch 0.3.2, I am encountering this error when building a release apk or app bundle.  If I switch back to an older release, such as 0.1.2, this error goes away and I can successfully build.  
If I run the app in debug mode on an emulator or physical device using 0.3.2, it runs successfully.  If I build an apk using --debug instead of --release, it builds successfully.

**Comment by MrFane** [comment]
I'm facing this problem too dude. Have you solved it so far?

**Comment by mbartn** [comment]
Hi, 
stack trace shows you path to the build.gradle file
`Build file '/Users/m/Github/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.3.2/android/build.gradle' line: 3`

I solved the issue by going to the file and adding this piece of code at the beginning.
```
buildscript {
  repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.1'
    }
}
```

**Comment by mbartn** [comment]
Hi,
for me the problem was in another library - described here: 
https://github.com/flutter/flutter/issues/42310

and I fixed it by changing 
`compileSdkVersion 27` to `compileSdkVersion 28` in app/build.gradle in newly added lib

**Comment by TheUnriashol** [comment]
This is definitely a bug but does not affect the release apk build. It still generates de apk files and they work without any issue, the background task still runs. I was unable to test the headless task since I am having some plugin issues with it. But should still work, at least that is what I have experienced with the project that I am currently working on.
