### ISSUE TITLE
Obsolete variables with new gradle version

### ISSUE THREAD

**Issue by galves93** [transistorsoft/flutter_background_fetch#51]
If this isn't a bug, sorry, but when a run following the documentation and the gradle version is 4.10.2, it run's ok.
But if i update de version of gradle to 5.4.1, flutter give me the following error:

**API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()

API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.**

i'd like to know if there's a way to solve this?
Thank's !

**Comment by christocracy** [comment]
`background_fetch` is not responsible for this.  See the [build.gradle](https://github.com/transistorsoft/flutter_background_fetch/blob/master/android/build.gradle)

**Comment by galves93** [comment]
Can you help me solve this problem?

**Comment by christocracy** [comment]
It's only a warning.  One of your other plugins must be using these methods in their `build.gradle`.  Open your `/android` app in Android Studio and search each plugin's `build.gradle` for the offending methods.

**Comment by galves93** [comment]
Worked here, i'd like to sorry you, i done a stupid thing here, hahaha...
but thanks a lot for the help... have a nice week!
