### ISSUE TITLE
[BUG] Finished with error: Gradle task assembleProductionDebug failed with exit code 1

### ISSUE THREAD

**Issue by angel1st** [transistorsoft/flutter_background_fetch#52]
**Your Environment**
* Plugin version: 0.3.2
* Platform: iOS or Android - Android
* OS version: Windows 10
* Device manufacturer / model: NA
* Flutter info (`flutter info`, `flutter doctor`):
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.805], locale en-US)

> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.5)
> [√] Connected device (1 available)

> • No issues found!

* Plugin config

**To Reproduce**
Follow [Headless Mechanism Steps](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#headless-mechanism-with-enableheadless-true)
1. Added `Application.kt` file
2. Amend `AndroidManifest.xml` - I think this is were issue lays, since there is already `android:name`  tag with value `io.flutter.app.FlutterApplication`
3. When application is compiled, I have got 
> Finished with error: Gradle task assembleProductionDebug failed with exit code 1

**Comment by christocracy** [comment]
- Post your `Application.kt`
- Post your `AndroidManifest.xml`
- Post your entire build stacktrace.

**Comment by angel1st** [comment]
Here they are:

build stacktrace:
> E:\Project>flutter build apk --target="lib/config/main_production.dart" --flavor=production --split-per-abi
Initializing gradle...                                              0.9s
Resolving dependencies...                                          18.8s
Running Gradle task 'assembleProductionRelease'...
Running Gradle task 'assembleProductionRelease'... Done            75.1s
Gradle task assembleProductionRelease failed with exit code 1

`Application.kt`
```

package com.example.app

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

`AndroidManifest.xml`
```

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.app">
    <!-- Required permission for geolocation package
        -->
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name=".Application"
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"
        android:label="app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

```

**Comment by christocracy** [comment]
```
$ cd android 
$ ./gradlew assembleRelease
```

**Comment by angel1st** [comment]
Here it is:

> E:\Working\kidlocator\android>gradlew assembleRelease

> Configure project :app
WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard.
.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

> Task :app:compileFlutterBuildDevelopmentReleaseArm
Target file "lib/main.dart" not found.

> Task :app:compileFlutterBuildDevelopmentReleaseArm FAILED
>          *********************************************************
> WARNING: This version of device_info will break your Android build if it or its dependencies aren't compatible with AndroidX.

>          *********************************************************
>1 actionable task: 1 executed

**Comment by christocracy** [comment]
You *have* updated your app for AndroidX, right?

**Comment by christocracy** [comment]
[Flutter AndroidX Migration](https://flutter.dev/docs/development/androidx-migration)

**Comment by angel1st** [comment]
Yes, I have - `android\gradle.properties`
```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by angel1st** [comment]
One more note - if I remove `android:name=".Application"` from `AndroidManifest.xml` I can compile the app

**Comment by christocracy** [comment]
Dude...you have the `android:name` attribute *twice*:
```
android:name=".Application"
        android:name=".MainActivity"
        tools:replace="android:label"
        android:name="io.flutter.app.FlutterApplication"  // <-- delete this
```

**Comment by christocracy** [comment]
Your `Application` extension *IS* an instance of `io.flutter.app.FlutterApplication`:
```java
class Application : FlutterApplication()

}
```

**Comment by angel1st** [comment]
thanks, man, this one does the trick. 
One more question - when `initPlatformState` is executed, the service is initially started, however, my app logic requires the service to start, when the app goes into background mode and stopped, when it is in foreground. So the question is - can I execute `initPlatformState` AND keep the service stopped?

**Comment by christocracy** [comment]
>I believe however it would be good to add replace android:name tag into Android config guide...

If you'd operated upon your flutter Android app, by opening `/your_app/android` in Android Studio, the IDE will tell you immediately you're doing something wrong.
![](https://dl.dropbox.com/s/qaehoo2uxe0o99r/Screenshot%202019-11-01%2014.04.52.png?dl=1)

>is executed, the service is initially started, however, my app logic requires the service to start, 

Background Fetch doesn't use services.

**Comment by angel1st** [comment]
ok, then, I will rephrase my question - immediately after `initPlatformState` is executed, background fetch starts and a callback starts to be called approx. every 15 mins. Can I execute `initPlatformState ` but postpone `callback` executions? The most obvious workaround is if I call `BackgroundFetch.stop()` right after `initPlatformState` completes. Any other options?

**Comment by christocracy** [comment]
> Any other options?

 No
