### ISSUE TITLE
Do not splash screen at each run

### ISSUE THREAD

**Issue by htsnet** [transistorsoft/flutter_background_fetch#55]
First, thank you for this great package!

Each time that the background runs I see the splash screen appears and disappears (if I am using the cellphone).

There is a way to change some parameter to avoid the splash screen to be shown?

Thanks

**Comment by christocracy** [comment]
I don’t know what you mean.  The plugin has nothing to do with anything you mention.

**Comment by htsnet** [comment]
> I don’t know what you mean. The plugin has nothing to do with anything you mention.

Uhn. Than, I need to search more to understand why it is happening in my app in Android. 

Thanks
