### ISSUE TITLE
Why do we need two functions : configure and registerHeadlessTask?

### ISSUE THREAD

**Issue by vifird** [transistorsoft/flutter_background_fetch#57]
Why do we need two functions : configure and registerHeadlessTask?
I known `registerHeadlessTask` only works on Android, how about`configure`?
if `configure` works on Android too, two callback functions will run.

I do by following the [example code](https://pub.dev/packages/background_fetch#large_blue_diamond-example).

**Comment by christocracy** [comment]
>Why do we need two functions : configure and registerHeadlessTask?

`#configure` is used to perform initial configuration of the plugin, providing desired settings.  This is run in your *Application* widget for both iOS and Android.

`registerHeadlessTask` must be initialized *outside* of your *Application* widget (Widgets do not exist in the Android terminated state).

`registerHeadlessTask` for iOS is simply a `noop` -- it does nothing.

You do not *have* to `registerHeadlessTaask` for Android if you have nothing do in the Android terminated state.
