### ISSUE TITLE
When should i run registerHeadlessTask? Will it be re-registed?

### ISSUE THREAD

**Issue by vifird** [transistorsoft/flutter_background_fetch#58]
With setting `startOnBoot=true`, `stopOnTerminate=false`, and excuting `BackgroundFetch.registerHeadlessTask(headlessTaskCallback)` after app started (as example).

**Question 1**: When device rebooted without starting my app (has started app once before rebooting), will `headlessTaskCallback` run?

**Question 2**: When my app started, `headlessTaskCallback` was registed, and will run after terminated; when the user starts my app again, `headlessTaskCallback` will registed again. Will there be two same callback run? And why(or how to deal with it)?

**Comment by christocracy** [comment]
>Question 1:

Yes.

>Question 2: Will there be two same callback run?

Of course not.  If the app is headless, headless-callback runs.  If the app is not headless, your listener provided to `#configure` runs.
