### ISSUE TITLE
What can we do in headlessTaskCallback?

### ISSUE THREAD

**Issue by vifird** [transistorsoft/flutter_background_fetch#59]
Can we do widgets' things in `headlessTaskCallback`(`BackgroundFetch.registerHeadlessTask(headlessTaskCallback)`)?

We need to connect database in `headlessTaskCallback`, and database need `getApplicationDocumentsDirectory()` of `path_provider` to find path, but `path_provider` needs to run `WidgetsFlutterBinding.ensureInitialized();`(Widgets initializing things) before `getApplicationDocumentsDirectory()`, so what we should do about it?

**Comment by christocracy** [comment]
>Can we do widgets' things in

There is no UI in headless context, thus no widgets.

>We need to connect database in...so what we should do about it?

I don't know.  Try it.
