### ISSUE TITLE
Cannot run released app.

### ISSUE THREAD

**Issue by ariefwijaya** [transistorsoft/flutter_background_fetch#6]
I have no problem for debug app + background_fetch. but when i try to release my app that using background_fetch, my app failed to launch without print any error. Is it a bug or we should configure something for release?

**Comment by christocracy** [comment]
If an app fails to launch, there *must* be evidence in the logcat.

I’m aware of *no* issue related to release.

**Comment by christocracy** [comment]
Closed for lack of feedback.
