### ISSUE TITLE
Background task not getting triggered by the OS, forced working ok

### ISSUE THREAD

**Issue by vualeks** [transistorsoft/flutter_background_fetch#60]
Hi,

as far as I can say, I configured everything correctly and when I force task with "adb shell cmd jobscheduler run -f XXX_f3 999" or debug background task with Xcode, the task is executed and everything works as expected, but when I leave the app on (with 15min or whichever minimum interval) the task never gets triggered. I've followed plugin logs with "adb logcat *:S flutter:V, TSBackgroundFetch:V" and there wasn't anything suspicious, only normal output when I forced the task. It is making a network call and showing a local notification using flutter_local_notifications. Do you maybe have some idea what could be wrong, what am I missing?

**Comment by christocracy** [comment]
If it works with simulated request, that’s confirmation everything is fine.

**Comment by vualeks** [comment]
Except that it never gets triggered by the OS so its main thing is kind of not working at all. I was hoping for maybe some suggestions what to check why doesn't it get triggered after the minimum interval timeout?

**Comment by eastrd** [comment]
What OS does your android use?

**Comment by vualeks** [comment]
It is a custom rom, LineageOS. The thing is that I kinda got it to work afterwards, but it works very unreliably. On iOS I got the task called once and never more, on Android it sometimes works and sometimes just stops getting called at all. I guess that's the best that you can get.

**Comment by abner01061998** [comment]
@vualeks  did you solve it? and how?
