### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by mjafartp** [transistorsoft/flutter_background_fetch#61]
* Plugin version: 0.3.2
* Platform: Android
* OS version: 7.0
* Device manufacturer / model: Samsung Galaxy A5 2016
* Flutter info (`flutter info`, `flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)

```
* Plugin config
minimumFetchInterval: 15,
stopOnTerminate: false,
enableHeadless: true,
startOnBoot:true

**To Reproduce**
1. Selecting data from SharedPreferences on background 

**Debug logs**
- Android: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask$1.run(:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

SharedPreferences Plugin Ver : 0.5.6

**Comment by christocracy** [comment]
I've upgrade the `/example` app in this repo to use `shared_preferences: ^0.5.6` and upgraded to flutter `v1.12.13+hotfix.5`.

The `/example` does not crash.

The example has a command for simulating a fetch event.  After cloning this repo and running the app:
```
$ cd example
$ ./scripts/simulate-fetch
```

You can execute `simulate-fetch` while the app is terminated to engage the headless-task.
```
12-12 12:52:02.572  7493  7493 D TSBackgroundFetch: - Background Fetch event received
12-12 12:52:02.578  7493  7547 I flutter : [BackgroundFetch] Event received
12-12 12:52:02.601  7493  7493 D TSBackgroundFetch: - finish
12-12 12:52:02.601  7493  7493 D TSBackgroundFetch: - jobFinished
12-12 12:52:08.192  7682  7682 D TSBackgroundFetch: - Background Fetch event received
12-12 12:52:08.204  7682  7682 D TSBackgroundFetch: - finish
12-12 12:52:08.204  7682  7682 D TSBackgroundFetch: - jobFinished
12-12 12:52:08.227  7682  7682 D TSBackgroundFetch: HeadlessJobService onStartJob
12-12 12:52:08.228  7682  7682 D TSBackgroundFetch: 💀 [HeadlessTask]
12-12 12:52:08.464  7682  7682 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
12-12 12:52:08.745  7682  7731 I flutter : Observatory listening on http://127.0.0.1:39187/QxElFBwnIjw=/
12-12 12:52:09.413  7682  7682 I TSBackgroundFetch: $ initialized
12-12 12:52:09.478  7682  7719 I flutter : [BackgroundFetch] Headless event received.
12-12 12:52:09.729  7682  7682 D TSBackgroundFetch: - finish
12-12 12:52:09.729  7682  7682 D TSBackgroundFetch: HeadlessJobService jobFinished
12-12 12:52:11.949  7682  7682 D TSBackgroundFetch: - Background Fetch event received
12-12 12:52:11.949  7682  7682 D TSBackgroundFetch: - finish
12-12 12:52:11.949  7682  7682 D TSBackgroundFetch: - jobFinished
12-12 12:52:11.974  7682  7682 D TSBackgroundFetch: HeadlessJobService onStartJob
12-12 12:52:11.975  7682  7682 D TSBackgroundFetch: 💀 [HeadlessTask]
12-12 12:52:11.990  7682  7719 I flutter : [BackgroundFetch] Headless event received.
12-12 12:52:12.078  7682  7682 D TSBackgroundFetch: - finish
12-12 12:52:12.078  7682  7682 D TSBackgroundFetch: HeadlessJobService jobFinished
```

**Comment by dkobia** [comment]
FYI -- This is something I'm running into, only with specific devices. Example a `Nexus 5X` with `Android 6.0.1`.

**Comment by christocracy** [comment]
@dkobia 

>Plugin version: ?

**Comment by dkobia** [comment]
@christocracy `0.5.5`. Sorry should have mentioned that.

**Comment by heyajohnny** [comment]
I have the same error, but it only happens with a Google Play test run of my app.

It's something from FireBase / CrashLytics in combination with Google Play that tests your application with a Nexus 5X with Android 6.0.1.

![image](https://user-images.githubusercontent.com/20553716/94372720-615c5180-0100-11eb-973a-fa084192e52e.png)

I've also tested it with a Nexus 5X with Android 6.0.1 emulator and the error never occured, It also never occured with any other android version,  so I think it is an issue with Google Play.

**Comment by bismarabia** [comment]
I'm also getting the exact same logs in Firebase/Crashlytics, on the exact same device Nexus 5X Android 6.0.1
Any fix on this??

**Comment by christocracy** [comment]
@bismarabia Read [this comment above](https://github.com/transistorsoft/flutter_background_fetch/issues/61#issuecomment-699671078)

**Comment by nemoryoliver** [comment]
Getting the same issue on Nexus 5X

**Comment by KoheiKanagu** [comment]
The same issue occurred on the Nexus 5X Android 6.0.1.
Another stack trace was also recorded in Crashlytics at the same time.
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.content.Context com.transistorsoft.flutter.backgroundfetch.HeadlessTask.mContext' on a null object reference
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.access$000(HeadlessTask.java:31)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask$TaskRunner.run(HeadlessTask.java:197)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```       

Plugin version is `0.6.0`

**Comment by christocracy** [comment]
>It's something from FireBase / CrashLytics in combination with Google Play that tests your application with a Nexus 5X with Android 6.0.1.

**Comment by mjafartp** [comment]
this error because of Google simulate crash to test in play console.

**Comment by BansookNam** [comment]
![스크린샷 2020-12-24 오전 11 10 42](https://user-images.githubusercontent.com/7719604/103050833-ad704280-45d8-11eb-9365-45562adc0a44.png)
This error is still reproducing on LGE devices.
I think it needs to be protected for NPE.

**Comment by christocracy** [comment]
There are many users who have posted in the issues that these are likely play console *simulating* a crash.

**Comment by kaciula** [comment]
I am also seeing this issue on the Nexus devices.

I am not using background fetch at all on Android and yet I get these crashes. How can this be?

I am protecting all relevant code with 

`if (Platform.isIOS)`

It does not make sense to say that Google simulates a crash. It never "simulated" crashes in all my other apps when not using this package.

This is an edge case I suggest should be dealt with in the package.

**Comment by christocracy** [comment]
What are you worried about if it's a simulated crash on a Nexus 5x device?

**Comment by kaciula** [comment]
@christocracy I'm worried that the package is running some code on my Android devices although I explicitly call its methods only on iOS devices.

**Comment by christocracy** [comment]
>I'm worried that the package is running some code on my Android

It is not.  This is the plugin initialization hook required by any Flutter plugin.  By default, the plugin loads its configuration from SharedPreferences (which requires an Android `Context` instance) in order to determine if you *have* implemented the plugin.  If you haven't implemented the plugin, then nothing will be found in SharedPreferences and nothing happens.
