### ISSUE TITLE
Unable to build apk after flutter Interact upgrade

### ISSUE THREAD

**Issue by kazi41571** [transistorsoft/flutter_background_fetch#62]
FAILURE: Build failed with an exception.

* Where:
Build file 'E:\sdk\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\background_fetch-0.3.2\android\build.gradle' line: 3
While 
* What went wrong:
A problem occurred evaluating root project 'background_fetch'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to
get full insights.

* Get more help at https://help.gradle.org

**Comment by kazi41571** [comment]
I think i found the solution also.

Put this code above the 'apply plugin' line

buildscript {

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

**Comment by christocracy** [comment]
@kazi41571 show me your file `android/build.gradle`

**Comment by kazi41571** [comment]
This is my android/build.gradle

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}
subprojects {
    project.configurations.all {
	resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.0.1"
            }
	}
    }    
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Please learn to use syntax-highlighting.  You wrap your code in 3-backticks.

**Comment by kazi41571** [comment]
Thanks for the tip.

**Comment by aweiand** [comment]
Hi!
I'm have the same error and don't now how to fix... my android/build.grande:

```buildscript {
    ext.kotlin_version = "1.3.50"
    repositories {
        google()
        jcenter()
    }

    ext {
        compileSdkVersion = 28                // or higher
        targetSdkVersion = 28                // or higher
        appCompatVersion = "1.0.2"           // or higher
        playServicesLocationVersion = "17.0.0"  // or higher
    }


    dependencies {
        classpath "com.android.tools.build:gradle:3.6.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by christocracy** [comment]
Plugin version?

**Comment by aweiand** [comment]
> Plugin version?

  flutter_background_geolocation: ^1.7.3

**Comment by christocracy** [comment]
What version of *background_fetch*?

**Comment by aweiand** [comment]
In my pubspec.yml i didn't put.
But in pubspec.lock it's 
``` 
 background_fetch:
    dependency: transitive
    description:
      name: background_fetch
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.5"

**Comment by aweiand** [comment]
I need to declare in pubspec.yml ?

> What version of _background_fetch_?

I need to declare in pubspec.yml , explicitly?

**Comment by christocracy** [comment]
background_fetch is *automatically* installed as a dependency of background_geolocation

**Comment by christocracy** [comment]
Create a fresh new Flutter hello world app and Install the plugin into it.  See if the error continues.

**Comment by aweiand** [comment]
> background_fetch is _automatically_ installed as a dependency of background_geolocation

Why works in debug mode and not in release? I'ts normal?

**Comment by christocracy** [comment]
Both the `flutter_background_fetch/example` (in this repo) and `flutter_background_geolocation/example` build successfully for *release* (I just submitted the latest build of background-geolocation's `/example` to Play Store last week.

**Comment by christocracy** [comment]
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CA)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.41.1)
[✓] Connected device (3 available)
```

**Comment by aweiand** [comment]
This line shows an error:
`proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"`

And viewing your example, what is this in the manifest, where I find this encryption password?
`<meta-data android:name="com.transistorsoft.locationmanager.ENCRYPTION_PASSWORD" android:value="transistorsoft" />`

I`m still having error in compile just for release, debug it`s okay.

My flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by christocracy** [comment]
>This line shows an error:

What error?  Your *own app* or `flutter_background_geolocation/example`?

>And viewing your example, what is this in the manifest

See `Config.encrypt`.  You are probably not using that option so ignore it.

**Comment by aweiand** [comment]
> > This line shows an error:
> 
> What error? Your _own app_ or `flutter_background_geolocation/example`?
> 
Sorry my mistake

> > And viewing your example, what is this in the manifest
> 
> See `Config.encrypt`. You are probably not using that option so ignore it.

Ok (but i didn't find this file)

Off-Topic: How I can change the bundleID for transistorsoft? Explain, in IOS Apple doesn't allow the same of I used in Android, now I will change to same on two stores....

Still have errors on my app:
```
Launching lib/main.dart on Redmi Note 8 in release mode...
Running Gradle task 'assembleRelease'...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':shared_preferences:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/aweiand/.gradle/caches/transforms-2/files-2.1/8fe844fcb35a147ee616b8d6c4c84d30/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/aweiand/.gradle/caches/transforms-2/files-2.1/8fe844fcb35a147ee616b8d6c4c84d30/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':url_launcher:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/aweiand/.gradle/caches/transforms-2/files-2.1/8fe844fcb35a147ee616b8d6c4c84d30/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     /Users/aweiand/.gradle/caches/transforms-2/files-2.1/8fe844fcb35a147ee616b8d6c4c84d30/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin background_fetch...
Running Gradle task 'assembleAarRelease'...


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/aweiand/flutter/.pub-cache/hosted/pub.dartlang.org/background_fetch-0.5.5/android/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'background_fetch'.
> Plugin with id 'com.android.library' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Finished with error: The plugin background_fetch could not be built due to the issue above.
```

**Comment by christocracy** [comment]
None of your latest errors are related to any of my stuff.  I suggest you create a brand new Flutter app and copy your `/lib` file and dependencies from `pubspec.yaml` into a fresh new app.  Your app is corrupt.

**Comment by aweiand** [comment]
I've found the problem!
It was two dependencies out of dated....
Thank you so much!! Your plugin is fantastic!

**Comment by KhalilAbdeljawad** [comment]
I faced the same problem but I found the app-release.apk in its folder and it works well!!!

**Comment by VolodymyrBiryuk** [comment]
I have a similar error:
```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/volodymyrbiryuk/.gradle/caches/transforms-1/files-1.1/appcompat-1.0.2.aar/2bca09a46f578b948ea912c097103e54/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  /Users/volodymyrbiryuk/git/mast/mpg/m-lab/app/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  /Users/volodymyrbiryuk/.gradle/caches/transforms-1/files-1.1/core-1.1.0.aar/d04f22428cabc263b61dbe6315ec03da/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  /Users/volodymyrbiryuk/.gradle/caches/transforms-1/files-1.1/core-1.1.0.aar/d04f22428cabc263b61dbe6315ec03da/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

@aweiand Which outdated dependencies did you remove/update to make it work?

**Comment by christocracy** [comment]
@VolodymyrBiryuk 

Post the following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by aweiand** [comment]
> I have a similar error:
> 
> ```
> 
> * What went wrong:
> Execution failed for task ':app:processDebugResources'.
> > Android resource linking failed
>   /Users/volodymyrbiryuk/.gradle/caches/transforms-1/files-1.1/appcompat-1.0.2.aar/2bca09a46f578b948ea912c097103e54/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
> 
>   /Users/volodymyrbiryuk/git/mast/mpg/m-lab/app/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
> 
>   /Users/volodymyrbiryuk/.gradle/caches/transforms-1/files-1.1/core-1.1.0.aar/d04f22428cabc263b61dbe6315ec03da/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/fontVariationSettings not found.
> 
>   /Users/volodymyrbiryuk/.gradle/caches/transforms-1/files-1.1/core-1.1.0.aar/d04f22428cabc263b61dbe6315ec03da/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/ttcIndex not found.
> 
>   error: failed linking references.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> ```
> 
> @aweiand Which outdated dependencies did you remove/update to make it work?

I update all those

**Comment by christocracy** [comment]
@aweiand see my last comment above.
