### ISSUE TITLE
how show notification in headless task

### ISSUE THREAD

**Issue by mojanimator** [transistorsoft/flutter_background_fetch#67]
hi . in my headless function, i need to check for updates from database and show notification to users.
this is ok but when user click on notification i need to open my app. this function need context for 
Navigator.push(
      context,
      new MaterialPageRoute(builder: (context) => MyApp()),
    );
how  can send context to backgroundFetchHeadlessTask in BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

**Comment by christocracy** [comment]
I don’t understand.  Once your application is launched, it’s no longer headless.

**Comment by AlaaEldeenYsr** [comment]
@mojanimator 
How did you show a notification when app is killed ? Did you use local_notification package ?

**Comment by spalenzuela** [comment]
> @mojanimator
> How did you show a notification when app is killed ? Did you use local_notification package ?

Any updates??? I want to show a local notification even the app was closed or device restarted. Regards

**Comment by Tienisto** [comment]
Use `flutter_local_notifications` library to show a notification inside background fetch callback
