### ISSUE TITLE
[BUG] Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected

### ISSUE THREAD

**Issue by W2YAdmin** [transistorsoft/flutter_background_fetch#71]
**Your Environment**
environment:
  sdk: ">=2.1.0 <3.0.0"

* Plugin version:  '^0.2.0'

* Platform: Android

* OS version: Android 9

* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, Microsoft Windows [Version 10.0.19041.21], en-IN)
[√] Android toolchain - develop for Android (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (1 available)
• No issues found!

**To Reproduce**
Steps to reproduce the behaviour:
1. Created a simple app which uses Gmaps and the default example code
2. Tried updating the Android project using the steps provided
3. Added Application.kt file with the code provided
4. Tried compiling the app I got this error:

e: P:\Flutter\TEST\test_maps\android\app\src\main\kotlin\com\example\test_maps\Application.kt: (16, 44): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
- have you upgraded your upp?  See https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

- review the plugin’s setup docs.  It changed with upgrade to Flutter 1.12

**Comment by W2YAdmin** [comment]
Yes I did upgrade actually am facing the issue after upgrading only.

**Comment by W2YAdmin** [comment]
Ohh please disregard this bug I was using the old version of the plugin!
