### ISSUE TITLE
Incompatibility with  flutter_background_geolocation

### ISSUE THREAD

**Issue by santiagohdzb** [transistorsoft/flutter_background_fetch#72]
**Is your feature request related to a problem? Please describe.**
Sort of, I'm using flutter background location from you _(which works great btw)_ and I would like to use this library to do some work while in background. But if I configure this plugin, my configuration would not take effect... I guess my callback is ignored when the Background Fetch event is triggered.

**Describe the solution you'd like**
It would be great to be able to use this library to register and execute my own callback along with the one flutter background location already has

Thank you!

**Comment by christocracy** [comment]
background_fetch (also created by me) was designed as a companion to background_geolocation, and is imported as a dependency *of it*.

background_fetch is *designed to be compatible with* background_geolocation.

**Comment by christocracy** [comment]
I’m closing this.  This is not a feature request and you’ve provided no information, logs, plugin version.

**Comment by santiagohdzb** [comment]
Yeah, well I think I did not explained this correctly.

This is the situation: if I try to use  flutter_background_geolocation alone it works great, ok... but what if I want to use this plugin also? I can not because when I register my callback it would not be executed... instead gets ignored because flutter_background_geolocation registered a callback already
  
  ios: 12.4.4
  background_fetch: ^0.3.2
  flutter_background_geolocation: ^1.3.2

those are the versions I'm using. I'm not sure if this is a feature request or an issue

**Comment by christocracy** [comment]
The latest version of [flutter_background_geolocation](https://pub.dev/packages/flutter_background_geolocation) is `1.6.1`, which imports [background_fetch](https://pub.dev/packages/background_fetch) @ `0.4.0`.

>but what if I want to use this plugin also?

They are *absolutely* designed to work **together**.  It's expected you'll use them both.  I do in the background_geolocation SampleApp.

I'd start by installing the latest version of flutter_background_geolocation.  You're doing something wrong on your end.  There is no issue with the two plugins working together.  They've worked together for over six years through Cordova, React Native and Flutter.
