### ISSUE TITLE
[BUG] Can't use a MethodChannel.invoke method in a headless task

### ISSUE THREAD

**Issue by Skyost** [transistorsoft/flutter_background_fetch#73]
**Your Environment** Windows 10 x64.
* Plugin version: 0.4.0
* Platform: Android
* OS version: Android 9.0.
* Device manufacturer / model: Emulator.
* Flutter info (`flutter info`, `flutter doctor`):
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [version 10.0.17763.973], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!
```
* Plugin config
```dart
BackgroundFetchConfig(
  minimumFetchInterval: 15, // <- Testing purposes
  stopOnTerminate: false,
  enableHeadless: true,
  requiredNetworkType: BackgroundFetchConfig.NETWORK_TYPE_ANY,
)
```

**To Reproduce**
1. Open the app so that `background_fetch` can register a headless task.
2. Try to use a `MethodChannel.invoke` method in the task.

**Debug logs**
```
2020-01-31 01:20:13.519 6843-6863/fr.skyost.timetable.dev E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method account.get on channel my_channel)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      AndroidUserRepository._read (package:unicaen_timetable/model/user.dart:147:53)
    <asynchronous suspension>
    #2      UserRepository.get (package:unicaen_timetable/model/user.dart:105:27)
    #3      headlessSyncTask (package:unicaen_timetable/main.dart:24:76)
    #4      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:437:15)
    #5      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
    #6      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
    #7      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
    #8      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
    #9      _rootRun (dart:async/zone.dart:1126:13)
    #10     _CustomZone.run (dart:async/zone.dart:1023:19)
    #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #12     _invoke3 (dart:ui/hooks.dart:302:10)
    #13     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
```

**Additional context:**

Here's the code I'm trying to use in a headless task :

```dart
MethodChannel('my_channel').invoke('method')
```

Oh and the method `method` is registered in the Android side.

**Comment by christocracy** [comment]
Have you [Upgraded your pre 1.12 Android Project](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?

**Comment by Skyost** [comment]
In fact I've created this project using flutter v1.12.

**Comment by christocracy** [comment]
Show me where you’re creating this method channel on the native side

**Comment by Skyost** [comment]
In my main activity :

```kotlin
override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
  GeneratedPluginRegistrant.registerWith(flutterEngine)
  MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler{
    call, result -> handleMethod(call, result)
  }
}

private fun handleMethod(call: MethodCall, result: MethodChannel.Result) {
  when(call.method) {
    "method" -> {
      // Do things...
      result.success(user)
      return
    }
    else -> result.notImplemented()
  }
}
```

So I tried to add the part I forgot in my Application class but I got a compile error saying "_Application.kt: (16, 48): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected_"

Here's my Application.kt :

```kotlin
class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        BackgroundFetchPlugin.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}
```

Oh and I added in my `AndroidManifest.xml` :

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="fr.skyost.timetable">

    <uses-permission
        android:name="android.permission.AUTHENTICATE_ACCOUNTS"
        android:maxSdkVersion="22" />
    <uses-permission
        android:name="android.permission.GET_ACCOUNTS"
        android:maxSdkVersion="22" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission
        android:name="android.permission.MANAGE_ACCOUNTS"
        android:maxSdkVersion="22" />
    <uses-permission android:name="android.permission.WRITE_SYNC_SETTINGS" />

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        tools:replace="android:label"
        android:name=".Application"
        android:label="@string/app_name"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher">
        
        <!-- ... -->

        <!-- Don't delete the meta-data below.
        This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by christocracy** [comment]
The "headless" means there is not `MainActivity`.  `MainActivity` *IS* the "head" of your application.

You must create your method-channel in the `Application.kt`.

**Comment by christocracy** [comment]
Another name for "headless" could be "activity-less"

**Comment by Skyost** [comment]
Oh that's okay thanks for your answer ! I will definitely do that.

And please can you tell me why I have a compile error saying "Application.kt: (16, 48): Type mismatch: inferred type is PluginRegistry but FlutterEngine was expected" ?

**Comment by christocracy** [comment]
Where did you get that code for your Application.kt, it’s wrong.  That’s pre-1.12 code

**Comment by Skyost** [comment]
Hmm, got it from [here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#flutter--112-1). What code should I use now ?

**Comment by christocracy** [comment]
Yes, well then read that doc again and ask yourself “what version of Flutter sdk am I using?”.

The plugin no longer requires Application extension for anything.

If you want to create a custom Application class, consult with Fluttet sdk docs, not here.

**Comment by Skyost** [comment]
Alright.

**Comment by Skyost** [comment]
I closed this issue as this is not a bug but the intended behavior but how can I create my method channel in my `Application.kt` as I need to have a binary messenger (which is provided by the flutter engine in `configureFlutterEngine`) ?

**Comment by christocracy** [comment]
You can see an example of a suitable `FlutterApplication` extension in the [/example](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/example/android/app/src/main/java/com/transistorsoft/flutterbackgroundgeolocationexample/Application.java) app.

Where a `Context` instance is required within `FlutterApplication`, you can use `this` within `onCreate` or `getApplicationContext()`.

**Comment by Skyost** [comment]
Thank you @christocracy, will check it out soon !

**Comment by Skyost** [comment]
Just checked the example `FlutterApplication`. So, I see that you're not implementing `PluginRegistrantCallback` at all so I've removed it. My `onCreate` method now looks like this :

```kotlin
override fun onCreate() {
  super.onCreate()
  FlutterMain.ensureInitializationComplete(applicationContext, null)

  val engine = FlutterEngine(applicationContext)

  val entrypoint: DartEntrypoint = createDefault()
  engine.dartExecutor.executeDartEntrypoint(entrypoint)

  GeneratedPluginRegistrant.registerWith(engine)
  MethodChannel(engine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler { call, result ->
            handleMethod(call, result, this)
}
```

(Well, the only thing I did was putting everything that was in the `registerWith` method back in the `onCreate` method).     
I'll try it and see if it works.

**Comment by Skyost** [comment]
I think I'm gonna do all my operations outside my register function as you did [here](https://github.com/transistorsoft/flutter_background_fetch/issues/7).

**Comment by christocracy** [comment]
Your code above isn't going to work.  It's far more tricky to create a custom `MethodChannel` in the headless context.  It's easy in the foreground case, in the context of the `MainActivity`.

However, I did some experimenting.  I can offer an event-handler on `BackgroundFetch`'s `HeadlessTask` class to offer you a reference to its `FlutterEngine`.  In the `Application#onCreate`, you'll do something like this:

**NOTE**:  This `onInitialized` event handler isn't yet public.  I have it working on my local copy only.

```java
HeadlessTask.onInitialized(new HeadlessTask.InitializedCallback() {
            @Override
            public void onStarted(FlutterEngine engine) {
                Log.d("TSBackgroundFetch", "********* engine started: " + engine);
                new MethodChannel(engine.getDartExecutor().getBinaryMessenger(), "channel_foo").setMethodCallHandler(new MethodChannel.MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
                        Log.d("TSBackgroundFetch", "**************** Application method call handler: " + call.method);
                        result.success(true);
                    }
                });
            }
        });
```

*main.dart*:
```dart
/// Create a custom MethodChannel
const MethodChannel _methodChannel = const MethodChannel("channel_foo");

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask(String taskId) async {
  print("[BackgroundFetch] Headless event received: $taskId");

  // execute a method on custom EventChannel
  _methodChannel.invokeMethod('test');
}
```

02-01 16:01:18.381 29525 29525 D TSBackgroundFetch: *********************** MainApplication
02-01 16:01:18.392 29525 29525 D TSBackgroundFetch: - Background Fetch event received
02-01 16:01:18.427 29525 29525 D TSBackgroundFetch: - finish: com.transistorsoft.fetch
02-01 16:01:18.427 29525 29525 D TSBackgroundFetch: - jobFinished
02-01 16:01:18.441 29525 29525 D TSBackgroundFetch: HeadlessJobService onStartJob: com.transistorsoft.fetch
02-01 16:01:18.441 29525 29525 D TSBackgroundFetch: 💀 [HeadlessTask com.transistorsoft.fetch]
02-01 16:01:18.720 29525 29525 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-01 16:01:18.943 29525 29577 I flutter : Observatory listening on http://127.0.0.1:40081/OUS9S3jVjvo=/
02-01 16:01:19.694 29525 29525 I TSBackgroundFetch: $ initialized
02-01 16:01:19.695 29525 29525 D TSBackgroundFetch: ********* engine started: io.flutter.embedding.engine.FlutterEngine@f639884
02-01 16:01:19.753 29525 29563 I flutter : [BackgroundFetch] Headless event received: com.transistorsoft.fetch
02-01 16:01:19.767 29525 29525 D TSBackgroundFetch: **************** Application method call handler: test

```


```

**Comment by christocracy** [comment]
Btw, why do you even *need* to write a custom `MethodChannel`?  What are you doing on the native side that you can't do via some 3rd-party plugin?

**Comment by Skyost** [comment]
> However, I did some experimenting. I can offer an event-handler on `BackgroundFetch`'s `HeadlessTask` class to offer you a reference to its `FlutterEngine`. In the `Application#onCreate`, you'll do something like this:

Wow great ! Is this available in the current plugin version ?

> Btw, why do you even _need_ to write a custom `MethodChannel`? What are you doing on the native side that you can't do via some 3rd-party plugin?

In fact I need to access a device account. I need to manage it (create, update and remove it from my app) and with `background_fetch`, I get the account (username / password) then I synchronize it with my server.

**Comment by pento** [comment]
I've been running into the same problem, and coincidentally I noticed that the fix [is in development](https://github.com/transistorsoft/flutter_background_fetch/tree/BGTaskScheduler). In [my initial testing](https://github.com/pento/TidyWeather/pull/38), it seems to be working well. 🙂

**Comment by Skyost** [comment]
@pento Out of curiosity, are you using `background_fetch` as a mean to synchronize your data at a given interval ? If so, is it working well for you ?

**Comment by christocracy** [comment]
I have a large refactor coming in branch #BGScheduler that’s almost ready for release.

This version introduces a new method #scheduleTask for running arbitrary oneshot/ periodic tasks.

BacgroundGeolocationConfig also introduces new Android-only option #forceAlarmManager to bypass JobScheduler (which is optimized to conserve battery) for more precise minimumFetchInterval.

**Comment by christocracy** [comment]
@Skyost If you want to try the branch `BGTaskScheduler`, you can implement this in your `MainApplication` (I use Java, you'll have to convert to Swift), modifying the method-channel name "channel_foo" as desired.

### Install from Git
```
dependencies:
  background_fetch:
    git:
      url: https://github.com/transistorsoft/flutter_background_fetch
      ref: BGTaskScheduler
```

```java
public class Application  extends FlutterApplication {
    @Override
    public void onCreate() {        
        super.onCreate();
        
        HeadlessTask.onInitialized(new HeadlessTask.OnInitializedCallback() {
            @Override
            public void onInitialized(FlutterEngine engine) {
                new MethodChannel(engine.getDartExecutor().getBinaryMessenger(), "channel_foo").setMethodCallHandler(new MethodChannel.MethodCallHandler() {
                    @Override
                    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                        result.success(true);
                    }
                });
            }
        });
    }
}
```

**Comment by christocracy** [comment]
@Skyost If you try `BGTaskScheduler` branch, you'll also want to read the **Breaking Changes** in [CHANGELOG](https://github.com/transistorsoft/flutter_background_fetch/blob/BGTaskScheduler/CHANGELOG.md#050---2020-01-03)

**Comment by Skyost** [comment]
@christocracy Thank you so much ! But as I am not in a hurry, I think I'm gonna wait for a stable release. Your help and your code snippets are greatly appreciated tho.

**Comment by christocracy** [comment]
@Skyost I'd *really* appreciate some feedback on implementing this branch.  If it works for you, it's pretty much ready to go as-is.

**Comment by Skyost** [comment]
@christocracy Oh that's okay, no problem. I'm gonna add it in my project and I will give you some feedback at the end of the week (something like thursday or friday). But I can only test on Android, not on iOS.

**Comment by pento** [comment]
> Out of curiosity, are you using `background_fetch` as a mean to synchronize your data at a given interval ? If so, is it working well for you ?

Yah, my use case is to fetch data from an API every 30 minutes, in a `background_fetch` headless task. It then has to do a `MethodChannel.invokeMethod()` call, to update an Android home screen widget. I was getting [the same exception as you described earlier](https://github.com/transistorsoft/flutter_background_fetch/issues/73#issuecomment-581063213) when the app is closed.

I'm running into a separate issue with getting the current location in the headless task, it appears to be a known issue in the [`geolocator` package](https://pub.dev/packages/geolocator). (It's only a hobby project which may generate revenue some time in the future, so I may just have to live with the bugs until I can replace my hacky workarounds with @christocracy's excellent [`flutter_background_geolocation` package](https://pub.dev/packages/flutter_background_geolocation). 🙂)

**Comment by Skyost** [comment]
@christocracy     
Just tested and it works perfectly on Android, thank you ! I still have a little question : is it possible to use third party flutter plugins in a headless task ?

**Comment by christocracy** [comment]
`shared_preferences` is a 3rd party plugin I use [in the example](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/lib/main.dart#L17), right?

**Comment by Skyost** [comment]
@christocracy You've made a point 😁
