### ISSUE TITLE
[BUG] Non-directory inputs must have .jar extension

### ISSUE THREAD

**Issue by giudon010** [transistorsoft/flutter_background_fetch#77]
**Your Environment**
* Plugin version: ^0.5.0
* Platform: Android
* OS version: Android 8.1.0
* Device manufacturer / model: G2

**To Reproduce**
1. Compiling version 0.5.0

Compiling goes wrong with the following error "Non-directory inputs must have .jar extension", when the build tries to reference tsbackgroundfetch-0.4.0.aar

Best regards and thank you for your wonderful plugin

**Comment by christocracy** [comment]
clean the build

**Comment by giudon010** [comment]
> clean the build

already tried to do a flutter clean but with no effect. Thank you for your fast reply

**Comment by christocracy** [comment]
cd android 
./gradlew clean

**Comment by giudon010** [comment]
> cd android
> ./gradlew clean

Thank you very much. Now it works like a charm.

Just another question: what can I do with deprecated parameter forceReload? Can I simply remove it, or it needs to be replaced with something other?

**Comment by christocracy** [comment]
forceReload has nothing to do with forceAlarmManager.  Just delete it.

**Comment by giudon010** [comment]
> forceReload has nothing to do with forceAlarmManager. Just delete it.

Thank you Chris
