### ISSUE TITLE
[BUG] Non-directory inputs must have .jar extension

### ISSUE THREAD

**Issue by ratkoamanovic** [transistorsoft/flutter_background_fetch#78]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
1. Just switch from working project with 0.4.0 
2. Add taskIds where necessary
3. Run project
4.

**Debug logs**
Launching lib\main.dart on AOSP on IA Emulator in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_fetch:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Non-directory inputs must have .jar extension: C:\_ratko\flutter\.pub-cache\hosted\pub.dartlang.org\background_fetch-0.5.0\android\libs\tsbackgroundfetch-0.4.0.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Additional context**

**Comment by christocracy** [comment]
Duplicate #77

**Comment by ratkoamanovic** [comment]
Thank you very much
