### ISSUE TITLE
Synchronisation between custom task and background repeating task

### ISSUE THREAD

**Issue by ratkoamanovic** [transistorsoft/flutter_background_fetch#80]
**Is your feature request related to a problem? Please describe.**
Can't synchronize tasks

**Describe the solution you'd like**
Mutex for default background task and custom tasks

**Describe alternatives you've considered**
Stopping task with id kills task and is not waiting for a task to finish

**Additional context**

**Comment by christocracy** [comment]
I don’t know what you mean by “synchronize” tasks.

**Comment by ratkoamanovic** [comment]
I mean that all code from one task finishes before any code from custom task starts

**Comment by christocracy** [comment]
Each task operates independently.  That's not going to change.

**Comment by ratkoamanovic** [comment]
![image](https://user-images.githubusercontent.com/18152229/74741047-68fb7400-525c-11ea-9d9d-2da5594e9ac7.png)
but this is happening

**Comment by christocracy** [comment]
I don't know what you're trying to show me.  Show me with *code*.

**Comment by ratkoamanovic** [comment]
Oh I solved it I synchronized two calls with global boolean, thank you very much for your help and fast replies and sorry for bothering you :D
