### ISSUE TITLE
Background service killed and not restarted anymore

### ISSUE THREAD

**Issue by giudon010** [transistorsoft/flutter_background_fetch#83]
**Your Environment**
* Plugin version: ^0.5.0
* Platform: Android
* OS version: Android 8.0.0
* Device manufacturer / model: HUAWEI P10

Hello Chris,
for first I want to say that your plugin is wonderful and want to thank you very much for it.

I have noticed a remote case, where my background service is killed (seems that it happen when I start alot of Apps, but I don't know if it's Android that kill my background service, because is a so difficult case to reproduce with the debugging cable attached to my device).
This is so strange, because my background service, isn't started anymore after this event happen. Even if I restart the phone, the background service isn't started. The only way to restart the background service, is to manually start the App.

I only noticed the following strange line whitin the background service is killed:

> 02-24 09:18:19.691  2030  2030 I HwCoreAppHelperService: LocalReceiver receives:android.intent.action.PACKAGE_RESTARTED,pkg:[MY APP PACKAGE],uid:10125 

Can it happen because I do not have disabled battery optimization on my App? Is battery optimization a problematic event even if I restart the device?

Do you know any method to debug this remote but extremely bad case?

Thank you in advance

**Comment by christocracy** [comment]
Is this your own custom service?  What are you doing in this service?  How is it being started?

**Comment by giudon010** [comment]
> 
> 
> Is this your own custom service? What are you doing in this service? How is it being started?

I started that background service thanks to your plugin, as follows:

```
// Platform messages are asynchronous, so we initialize in an async method.
Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        startOnBoot: true,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE
    ), (String taskId) async {
      // This is the fetch-event callback.
      debugPrint("[BackgroundFetch] Event received $taskId");

      await executeBatchJobs();

      // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
      // for taking too long in the background.
      BackgroundFetch.finish(taskId);
    }).then((int status) {
      debugPrint('[BackgroundFetch] configure success: $status');
    }).catchError((e) {
      debugPrint('[BackgroundFetch] configure ERROR: $e');
    });

    BackgroundFetch.start().then((int status) {
      debugPrint('[BackgroundFetch] start success: $status');
    }).catchError((e) {
      debugPrint('[BackgroundFetch] start FAILURE: $e');
    });
}

void main() async {
    MaterialApp(
       ...
    );

	// Register to receive BackgroundFetch events after app is terminated.
	// Requires {stopOnTerminate: false, enableHeadless: true}
	BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);

	initPlatformState();
}
```
I use it only to communicate with my web-api, and it works well (even for days) until Android kill it (I think that is Android, because it happens only when I start a lot of Apps in a very short time).

**Comment by christocracy** [comment]
Show me the following code:
- `backgroundFetchHeadlessTask'
- `executeBatchJobs`

**Comment by giudon010** [comment]
Code is following:

```
void backgroundFetchHeadlessTask(String taskId) async {
  debugPrint("[BackgroundFetch] Headless event received $taskId");

  await executeBatchJobs();

  BackgroundFetch.finish(taskId);
}
```

```
Future<void> executeBatchJobs() async {
  try {
    await getRemoteConfigurations();
  } catch (error, stackTrace) {
    debugPrint('[executeBatchJobs] ERROR: $error');
  }
}
```

Anyway Chris, after hours of pain I found the problem. This explains the reason why this problem occurs only on one (on the Huawei) of the four devices that I am using for testing my app. **OS kills my app**, and finally I catched it in the logs.
Tomorrow I will share my analysis (here) with you and the community, because I think that other developers are also experiencing the same problem, and maybe we can solve it togheter.

**Comment by giudon010** [comment]
Following is the result of my analysys:

Yesterday I started a fresh session of my App (UI and background service) at 10:15 A.M.
During the day it was softly killed from OS, and then automatically restarted 12 times, until the 13th time reached, and it was hardly killed from OS (It means that the app can't be accessed anymore, even across phone restart, until it is manually restarted by the user).
Following are the logcat records that shows the killing records of my App:
```
02-26 10:16:01.686 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 8102:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 10:32:21.945 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 11385:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 10:57:53.022 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 16545:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 11:44:36.369 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 23624:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 12:03:49.911 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 27759:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 12:16:10.166 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 32268:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 13:09:58.129 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 4664:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 13:54:47.184 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 12416:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 14:09:34.533 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 31198:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 14:24:30.353 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 4834:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 14:36:23.359 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 12426:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 16:17:49.669 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 14675:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: true
02-26 17:23:51.725 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{0 18137:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: false
```

Trying to look better what had happened at 17:23:51, compared to other times:

```
02-26 17:23:40.549 D/JobServiceContext( 1109): Scheduling time out for 'com.transistorsoft.tsbackgroundfetch.FetchJobService' jId: 999, in 18 s
02-26 17:23:40.591 I/ash     ( 2031): pkg android calling: [MY_APP_PACKAGE], pid: 18137 ,type: bindservice
02-26 17:23:40.591 I/ash     ( 2031): [MY_APP_PACKAGE] { hibernation duration=1752421 UptimeDuration=347624 } transition to: doze reason:be_called_bindservice
02-26 17:23:40.598 I/PGServer( 2031): report state:6 event type:2 pid:0 uid:10125 pkg:[MY_APP_PACKAGE] to pid: 1109
02-26 17:23:40.598 I/ash     ( 2031): Unfreeze [MY_APP_PACKAGE] OK !
02-26 17:23:40.599 I/PGManagerService( 1109): proxyBroadcast:[[MY_APP_PACKAGE]] proxy:false
02-26 17:23:40.600 I/ash     ( 2031): unproxy [MY_APP_PACKAGE] broadcast OK !
02-26 17:23:40.600 I/ash     ( 2031): Unpending [MY_APP_PACKAGE] alarm OK !
02-26 17:23:40.601 D/APwPowerPolicy( 2031): gps pkg: [MY_APP_PACKAGE] uid:10125 duration:24935
02-26 17:23:40.601 I/APwPowerPolicy( 2031): ignore smart optimize and unkown gps pkg: [MY_APP_PACKAGE] duration:24935
02-26 17:23:40.604 I/ash     ( 2031): nap package: [MY_APP_PACKAGE], visible: false
02-26 17:23:40.643 D/JobServiceContext( 1109): handleServiceBound for 2a7b79b #u00000/999 [MY_APP_PACKAGE]/com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 17:23:40.643 D/JobServiceContext( 1109): Scheduling time out for 'com.transistorsoft.tsbackgroundfetch.FetchJobService' jId: 999, in 8 s
02-26 17:23:40.739 D/TSBackgroundFetch(18137): - Background Fetch event received
02-26 17:23:40.743 D/TSBackgroundFetch(18137): 💀 [HeadlessTask flutter_background_fetch]
02-26 17:23:40.746 D/JobServiceContext( 1109): doCallback of : JobStatus{2a7b79b #u00000/999 [MY_APP_PACKAGE]/com.transistorsoft.tsbackgroundfetch.FetchJobService u=0 s=10125 TIME=-16m18s545ms:-11m18s545ms PERSISTED READY} v:VERB_STARTING
02-26 17:23:40.747 D/JobServiceContext( 1109): Scheduling time out for 'com.transistorsoft.tsbackgroundfetch.FetchJobService' jId: 999, in 600 s
02-26 17:23:40.820 I/flutter (18137): [BackgroundFetch] Headless event received flutter_background_fetch
02-26 17:23:43.050 D/TSBackgroundFetch(18137): - finish: flutter_background_fetch
02-26 17:23:43.050 D/TSBackgroundFetch(18137): - jobFinished
02-26 17:23:43.050 D/JobServiceContext( 1109): doCallback of : JobStatus{2a7b79b #u00000/999 [MY_APP_PACKAGE]/com.transistorsoft.tsbackgroundfetch.FetchJobService u=0 s=10125 TIME=-16m20s849ms:-11m20s849ms PERSISTED READY} v:VERB_EXECUTING
02-26 17:23:48.665 I/ash     ( 2031): screen off trigger to hibernation: [MY_APP_PACKAGE]
02-26 17:23:51.718 D/ProcessCleaner( 1109): [aware_mem] start process cleaner setPackageStoppedState
02-26 17:23:51.721 I/ActivityManager( 1109): Killing 18137:[MY_APP_PACKAGE]/u00000 (adj 902): iAwareF[SmartClean](cch-empty)
02-26 17:23:51.725 D/ActivityManager( 1109): cleanUpApplicationRecord app: ProcessRecord{3b7d464 18137:[MY_APP_PACKAGE]/u00000}, app.bad: false, restarting: false, allowRestart: false
02-26 17:23:51.725 I/ash     ( 2031): clear_nap unproxy gps : [MY_APP_PACKAGE]
02-26 17:23:51.726 D/GpsFreezeProc( 1109): removeFreezeProcess enter
02-26 17:23:51.726 D/GpsFreezeProc( 1109): removeFreezeProcess pkg:[MY_APP_PACKAGE]
02-26 17:23:51.727 I/ash     ( 2031): unproxy gps:[MY_APP_PACKAGE],uid:10125,result:true
02-26 17:23:51.727 I/ash     ( 2031): [MY_APP_PACKAGE] { doze duration=11125 UptimeDuration=11124 } transition to: end, reason:not_running
02-26 17:23:51.729 I/ash     ( 2031): remove app record pkg: [MY_APP_PACKAGE]
02-26 17:23:51.736 D/ProcessCleaner( 1109): [aware_mem] process cleaner success pid:18137,uid:10125,[MY_APP_PACKAGE],[[MY_APP_PACKAGE]],mHasShownUi:false,null,class:0,0,0,0,adj:902 is killed
02-26 17:23:51.747 D/ProcessCleaner( 1109): [aware_mem] start process cleaner cleanPackageRes, clnAlarm:true, hasPerceptAlarm:false, isNative:false, cleanResult: false
02-26 17:23:51.750 W/AwareLog( 1109): SchedLevelBoost: onProcessDied config not set!
02-26 17:23:51.750 E/HsmCoreServiceImpl( 2005): onTransact in code is: 102
02-26 17:23:51.750 I/MediaProcessHandler( 2005): processOp opType: 1, uid: 10125, pid: 18137
02-26 17:23:51.750 W/MediaProcessHandler( 2005): remove target not exist, maybe the UI process: uid: 10125, pid: 18137
02-26 17:23:51.750 I/MediaProcessHandler( 2005): executedCallBack opType: 1 mMediaStatusObservers.size=0
02-26 17:23:51.755 V/AlarmManager( 1109): UninstallReceiver onReceive action:android.intent.action.PACKAGE_RESTARTED
02-26 17:23:51.765 I/HwCoreAppHelperService( 2005): LocalReceiver receives:android.intent.action.PACKAGE_RESTARTED,pkg:[MY_APP_PACKAGE],uid:10125
02-26 17:23:51.765 D/CarrierSvcBindHelper( 2044): No carrier app for: 0
02-26 17:23:51.767 D/HwBastetService( 1109): BroadcastReceiver android.intent.action.PACKAGE_RESTARTED
02-26 17:23:51.768 E/NfcNci  ( 4083): NfcUtils error: APP do not have nfc permission
02-26 17:23:51.769 E/NfcNci  ( 4083): NfcUtils error: APP do not have nfc permission
02-26 17:23:51.779 I/AppManager( 2031): dependence has been existed:3188 -> 2829
02-26 17:23:51.785 V/BroadcastQueue( 1109): Finished with ordered broadcast BroadcastRecord{53b7294 u0 android.intent.action.PACKAGE_RESTARTED}
02-26 17:23:51.787 I/HwAlarmManagerService( 1109): hwSetAlarm listenerTag: *job.delay*
02-26 17:23:51.788 I/JobScheduler.Time( 1109): mNextDelayExpiredElapsedMillis: 25800000
02-26 17:23:51.794 I/HwAlarmManagerService( 1109): hwSetAlarm listenerTag: *job.deadline*
02-26 17:23:51.794 I/JobScheduler.Time( 1109): mNextJobExpiredElapsedMillis: 27300000
02-26 17:23:51.794 D/HwGpsPowerTracker( 1109): LocalReceiver receives:android.intent.action.PACKAGE_RESTARTED
02-26 17:23:51.948 V/HwActivityManagerService( 1109): cleanupPackageNotifications, userId=0|[[MY_APP_PACKAGE]]
```

 I noticed that:

1. Few minutes back, the background service was executed without any errors;
2. The last time that my App was killed from OS, the field "allowRestart" was setted to "false";
3. App was killed by the ProcessCleaner (SmartClean);
4. The ProcessCleaner was started few Times more, before the last time, with the following tasks: LowMem PowerGenie SystemManager and LowMemQuick , but the task that hadrdly killed my background service/App was the SmartClean Task.

After my App was killed:

```
02-26 19:09:46.454 I/ActivityManager( 1109): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:[MY_APP_PACKAGE] cmp=com.android.settings/.applications.InstalledAppDetails} from uid 10247
02-26 19:09:46.703 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 19:09:46.733 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:31:07.727 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:31:07.819 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:31:08.055 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:31:08.110 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:32:11.443 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:32:11.497 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:32:17.213 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:32:17.273 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:32:42.513 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:32:42.527 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:35:22.258 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:35:22.296 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:35:35.299 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:35:35.341 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:40:08.752 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:40:08.787 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:40:15.077 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
02-26 20:40:15.111 W/ProcStatsManager(27547): No process [MY_APP_PACKAGE]/10125 for service com.transistorsoft.tsbackgroundfetch.FetchJobService
```

Nor the App and the background service was executed anymore, even across device restart.

Trying to look what ProcessCleaner does, seems to be that Huawei (and other companies too) have some customization services that automatically kills background services, based on theri algorithms.

Is there any known solutions to solve this BIG issue? Maybe trying to use the broadcast "android.intent.action.PACKAGE_RESTARTED" (I know that it isn't catchable from the killing App, but maybe there is something other that escapes me) ? Or maybe trying to restart the background service less times during the day, scheduling it every 2 hours instead of 15 minutes?

**Comment by giudon010** [comment]
> 
> 
> > Is there any known solutions to solve this BIG issue?
> 
> Huawei is well-known to aggressively terminate background process. There are no developer solutions against some particular manufacturer's "hand-of-god" process cleaner.

Ok, I hope we will find it togheter. 

> 
> > Maybe trying to use the broadcast "android.intent.action.PACKAGE_RESTARTED"
> 
> See [ACTION_PACKAGE_RESTARTED](https://developer.android.com/reference/android/content/Intent#ACTION_PACKAGE_RESTARTED)
> 
> > Broadcast Action: The user has restarted a package, and all of its processes have been killed. **All runtime state associated with it (processes, alarms, notifications, etc) should be removed**. **Note that the restarted package does not receive this broadcast**. The data contains the name of the package.
> 
> This broadcast is for cleaning up one's terminated process, removing alarms, scheduled jobs, etc.
> 

Oh ok. I was thinking to use it like a "watchdog". To be more precise, a sort of external service that monitor the main App for this event, and restart it automatically, but I think that this is to complex to realize it.

> > Or maybe trying to restart the background service less times during the day, scheduling it every 2 hours instead of 15 minutes?
> 
> I have no idea. I own a _Huawei P20 Lite @ 8.0.0_ (in addition to 10 other Android devices). I will let the `/example` app run headless and monitor its performance.

Good to know that you are also testing it on your own device.

I am also doing some additional tests, because it happened again today. I started the App yesterday at 21:20, and it was killed today at 12:11.

I am doing following analysis/tests:

1. Actually the only "manual" solution that I found (I tested it on other Apps, I am waiting to test it on mine too) is to disable the automatic "App launch" for the App. In addition I also tried to ignore battery optimizations for my personal App, but it doesn't change anything;
2. Now I am testing to schedule my background service to be executed every 180 minutes. I started my App Today at 14:30, and the background service was correctly resumed at 17:21, so it's still alive. I'll monitor it and let you know;
3. I am trying to launch an external App that show a local scheduled notification (I scheduled it for tomorrow). I want to know if this App will be killed by the OS or not until tomorrow;
4. I am also analyzing (my last solution) the methods described here: https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it to let the user know about this issue, and let it change manually what I reported on point 1.

I would like to know which kind of checks the algorithm does to kill the Apps, because I haven't found nothing on internet about it.

**Comment by giudon010** [comment]
Hello Chris,
about the point 2 in my last message, even if I scheduled my Job every 180 minutes, it was killed after 7 hours. I also did another test, on which I simply commented everything inside my Job (I wanted to be sure that I didn't nothing bad there) and scheduled it to be executed in 15 minutes, but it was killed in one day.

I have also experienced a problem with DuraSpeed (a Process Cleaner by Mediatek) on another device, and I am repeating the test.

I still haven't found an acceptable solution.

What about your test on P20 Lite?

**Comment by giudon010** [comment]
Finally I implemented a section in my App to disable battery optimizers and launchers. I tried almost everything, but nothing worked cross-devices. It has nothing todo launching many apps together with the "killers". You can schedule your job once per day, but it will be killed. The game is not worth the candle. So now I scheduled my job to be executed every 15 minutes.

Please, let me know if you have news with your tests Chris.

**Comment by DrMicio** [comment]
Hi,
do you have a solution for this problem? I'm having the same issue on my Honor 8 (Android 8.0)

**Comment by christocracy** [comment]
See http://dontkillmyapp.com
