### ISSUE TITLE
[BUG] iOS performFetchWithCompletionHandler Warning

### ISSUE THREAD

**Issue by murilinhoPs** [transistorsoft/flutter_background_fetch#85]
**Your Environment**
* Plugin version: github version on pubspec.yaml
* Platform: iOS 
* OS version: 13.3
* Device manufacturer / model: simulator ios 13.3

**To Reproduce**
1. Start the backgroundTask (configure())
2.In Xcode, click Debug -> SimulateBackgrounFetch
3.Do it again: In Xcode, click Debug -> SimulateBackgrounFetch
4. in the console will return: 
 Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called.`

**Debug logs**
- `BackgroundFetch AppDelegate received fetch event
[TSBackgroundFetch performFetchWithCompletionHandler]
[TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
Warning: Application delegate received call to -application:performFetchWithCompletionHandler: but the completion handler was never called.`

**Problem*
I'm testing the backgrounFetch only on iOS, I'm not using it on android. The first time I test it on iOS simulator in Xcode with Debug -> SimulateBackgrounFetch it works, but if I do this again return a error message about CompletionHandler (the message I send at DebugLogs). I don't know what to do, and if is right returning this message and I know this is deprecated on iOS 13 or higher but I don't know what to do.....

**Comment by christocracy** [comment]
Show me your code.

**Comment by murilinhoPs** [comment]
Future<void> initializePlugin() async {
          BackgroundFetch.configure(
            BackgroundFetchConfig(
              minimumFetchInterval: 15,
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: false,
              requiresBatteryNotLow: false,
              requiresCharging: false,
              requiresStorageNotLow: false,
              requiresDeviceIdle: false,
              requiredNetworkType: NetworkType.ANY,
            ),
            _onBackgroundFetch)
        .then((int status) {
      print('[BackgroundFetch] configure success: $status');
    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    }
    }

I call this method from a button to start it and I have another method to stop the background_fetch. Do you need more code, like the swift code?

**Comment by christocracy** [comment]
Show me `_onBackgroundFetch`

**Comment by murilinhoPs** [comment]
the code _onBackgroundFecth -> 

 _onBackgroundFetch(String taskId) async {
    print('TaskId: $taskId');

    await AppModule.to.bloc<LocationBloc>().broadcastPosition();

    print(
        "[BackgroundFetch] Event received: ${AppModule.to.bloc<LocationBloc>().geoValue.latitude}");

    BackgroundFetch.finish(taskId);
  }

I'm getting the user location from a bloc.
