### ISSUE TITLE
Checking if a task is still alive

### ISSUE THREAD

**Issue by voivoed** [transistorsoft/flutter_background_fetch#86]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to check on the status of my background task (still alive or not running anymore).

Currently I use a background task to automatically backup user data to a remote storage, and to periodically check on the user status. I've been testing the app for a few weeks and logs on my server tell me everything seems to be working fine on both iOS and Android, but I'm about to release the app and it makes me nervous that I don't know FOR SURE if the task is still up and running of if the device killed it for some reason (like I see in some of the other threads here). I would like to be able to check the task and see if it's alive, if that's possible.

**Describe the solution you'd like**
Just some method I could call? Or, alternatively, can I simply call configure() again?  Would that create multiple tasks running in the background, or would it just keep the current task running (or restart it if it died)?

Thanks! I truly appreciate the work you put in this library.

**Comment by christocracy** [comment]
Just re-schedule it.  The current task will be cancelled and a new one scheduled with current delay.

**Comment by voivoed** [comment]
But is there a way to check the status of the task? Is that even possible?

**Comment by giudon010** [comment]
> 
> 
> But is there a way to check the status of the task? Is that even possible?

In my personal case/experience, when a background task is killed, the main process is killed too, and so, to check if the task is still alive, I simply go to: Settings->Applications->My Application Detail and check if the "Force stop" button is enabled: if yes the task is still alive, otherwise not.

**Comment by Keader** [comment]
@christocracy i'm having a issue about status too.
We have no way to know if has tasks running?
Status is always STATUS_AVAILABLE to me.
Maybe just a public method, checking if _eventsFetch is empty or something to know if background fetch is running or not

**Comment by christocracy** [comment]
Unless you call `stop()`, it's running by default as soon as you call `#configure`.
