### ISSUE TITLE
"Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d9cf1ba) but could not find and invoke the GeneratedPluginRegistrant."

### ISSUE THREAD

**Issue by lipocodes** [transistorsoft/flutter_background_fetch#89]
Your Environment:  Windows 10

Plugin version:  0.5.4

* Platform:  Android

* OS version: 7

* Device manufacturer / model:  Xiaomi Redmi4

* Flutter info:
[√] Flutter (Channel master, v1.15.19-pre.17, on Microsoft Windows [Version 10.0.18362.719], locale he-IL)
    • Flutter version 1.15.19-pre.17 at D:\Backup material\flutter\flutter
    • Framework revision 5b0a79dbdb (3 days ago), 2020-03-08 21:16:01 -0400
    • Engine revision 981c03631e
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Lior.LIPO\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Lior.LIPO\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Redmi 4A • 65cb5487d340 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

* Plugin config:
```dart
 minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        startOnBoot: true,
        requiredNetworkType: NetworkType.NONE
```

**To Reproduce**
1.  Set he plugin to intervals of 15 minutes.

2. In Android/MyApp.java  (same path as MainActivity.java):
```java
import io.flutter.app.FlutterApplication;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MyApp extends FlutterApplication implements PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        // AlarmService.setPluginRegistrant(this);
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }
    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith((FlutterEngine) registry);
    }
}
```
  
3.  In the BackgroundFetch callback, put a command making use  of Flutter plugin:
    Like:
```dart
     SharedPreferences prefs = await SharedPreferences.getInstance();
      bool yesNo =  prefs.getBool('debt'); 
```
4. View the error you get (in console)  every 15 minutes.  It implies it can't initialize the app's plugins.

Cheers,
Lior

**Comment by christocracy** [comment]
In [0.4.0], the plugin was updated to latest [*Flutter Plugin API V2*](https://github.com/transistorsoft/flutter_background_fetch/blob/master/CHANGELOG.md#040---2019-12-17).  Have you [upgraded your pre 1.12 Android project](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?

With `1.12+`, the plugin's Android Setup *no longer requires* a custom `Application.java`.

**Comment by lipocodes** [comment]
I use Flutter SDK 1.15.  It's a project I created a month ago.

**Comment by lipocodes** [comment]
I use Flutter 1.15.

I implemented the follwowing instructions: [https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md](url)

**Comment by christocracy** [comment]
If you're using Flutter SDK `>= 1.12`, why are you implementing code in your custom Application class?

>If you've upgraded your Flutter SDK to 1.12 (or higher) AND Upgraded Your Android Project, there are **no additional steps required — everything is now automatic**.

![](https://dl.dropbox.com/s/v1bn1rzzmff0fm3/Screenshot%202020-03-12%2009.57.40.png?dl=1)

**Comment by lipocodes** [comment]
You're right, I omitted the custom class, but yet I'm getting the error:  

" Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)"

**Comment by christocracy** [comment]
Your issue is with `plugins.flutter.io/shared_preferences`, not `background_fetch`.

Have you tried the `/example` app in this repo?

**Comment by lipocodes** [comment]
Yes, it's an issue with SharedPreferences in background code.

Thanks for your help!

**Comment by lipocodes** [comment]
If I use plugins inside the callback, like SharedPreferences,  do I need to register it custom Application class?

**Comment by christocracy** [comment]
See the [/example](https://github.com/transistorsoft/flutter_background_fetch/tree/master/example) app in this repo.  

The example app does *nothing* in `Application.java`.  The example app implements `SharedPreferences` in both the app and headless-task.

**Comment by lipocodes** [comment]
When I use your https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/lib/main.dart

as my code,  and I close my app, I still get the same error.

**Comment by christocracy** [comment]
I'm not talking about simply the code in `lib/main.dart` &mdash; I'm talking about the **whole** app itself.

Clone *this* repo and launch the `/example` app itself.

There's something wrong with your Flutter app's Android setup.

**Comment by lipocodes** [comment]
Thank you for your great help!

**Comment by himanshudeshmukh** [comment]
> Your issue is with `plugins.flutter.io/shared_preferences`, not `background_fetch`.
> 
> Have you tried the `/example` app in this repo?

I'm not getting the solution of this problem please help me with this

**Comment by christocracy** [comment]
@himanshudeshmukh What is the problem you're having?

**Comment by himanshudeshmukh** [comment]
@christocracy 

### i'm not able to use url_launcher as everytime i build my app it shows error _missingpluginexception(no implementation found for method launch on channel flutter_webview_plugin)_

this is where i'm having trouble.

**Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@6e15265) but could not find 
and invoke the GeneratedPluginRegistrant.**

and this is my mainActivity.java code

_import io.flutter.plugins.GeneratedPluginRegistrant;
import android.os.Bundle; // required for onCreate parameter
import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this.getFlutterEngine());
}
}_


please help me

**Comment by christocracy** [comment]
I suggest you create a fresh new “Hello World” app and experiment with a simple test case.

**Comment by himanshudeshmukh** [comment]
@christocracy

i've tried that and worked successfully as app opened gmail on button click but not working with my current project where i really need that

please help me to resolve this

**Comment by himanshudeshmukh** [comment]
@christocracy 
if you say , we can connect on anydesk so that you can examine my problem more efficiently

**Comment by christocracy** [comment]
I need 24 hours notice for scheduling:
https://shop.transistorsoft.com/products/remote-development-consulting-1-hour

**Comment by himanshudeshmukh** [comment]
> I need 24 hours notice for scheduling:
> https://shop.transistorsoft.com/products/remote-development-consulting-1-hour

please help me

**Comment by himanshudeshmukh** [comment]
### i'm having this error
**Unhandled Exception: MissingPluginException(No implementation found for method canLaunch on 
channel plugins.flutter.io/url_launcher)**

and this statement comes at the time of  app build
**W/FlutterActivity(30125): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@6e15265) but could not find 
and invoke the GeneratedPluginRegistrant.**

how can i resolve this error and ,how i'll be able to use url_launcher

**Comment by christocracy** [comment]
I suggest you migrate your `/lib` folder into a freshly generated Flutter app, in addition to all added 3rd party dependencies from old `pubspec.yaml` into the freshly generated Flutter app's `pubspec.yaml`.

**Comment by himanshudeshmukh** [comment]
@christocracy 
 tried this also but same error

**Comment by christocracy** [comment]
@himanshudeshmukh create a *simple* "Hello World" project which reproduces the issue and share that Github repo with me.

**Comment by himanshudeshmukh** [comment]
**_@christocracy  hey im fetching data from firebase cloud and i want to store that data in a variable of type double how can do that_**

**Comment by christocracy** [comment]
@himanshudeshmukh 

The title of this *closed* issue is:

> "Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d9cf1ba) but could not find and invoke the GeneratedPluginRegistrant."

Your question doesn’t seem relevant to this topic.

**Comment by himanshudeshmukh** [comment]
https://github.com/transistorsoft/flutter_background_fetch/issues/89#issuecomment-657204780

> @himanshudeshmukh
> 
> The title of this _closed_ issue is:
> 
> > "Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d9cf1ba) but could not find and invoke the GeneratedPluginRegistrant."
> 
> Your question doesn’t seem relevant to this topic.

the problem is solved it took reinstallation of flutter

**Comment by himanshudeshmukh** [comment]
@christocracy 

**Unhandled Exception: type 'StreamBuilder<QuerySnapshot>' is not a subtype of type 'double' i'm facing this error**

"Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d9cf1ba) but could not find and invoke the GeneratedPluginRegistrant."
this error resolved
