### ISSUE TITLE
Access non static functions of MyApp in backgroundFetchHeadlessTask

### ISSUE THREAD

**Issue by ayush221b** [transistorsoft/flutter_background_fetch#9]
In the backgroundFetchHeadlessTask method, I need to access the showNotification() method, which I created inside the _MyAppState class of my Application. The showNotification method implements the [flutter_local_notifications](https://pub.dartlang.org/packages/flutter_local_notifications) plugin functionality and hence cannot be made static.

**Comment by christocracy** [comment]
Why don't you move your `showNotification` method into a simple static lib file and import it into both your `_MyAppState` as well as headless contexts?

**Comment by ayush221b** [comment]
I am sorry if I am being naive, but here's my [main.dart](https://gist.github.com/ayush221b/85e284c004d3fbffeae58e3440640232) file, where I tried to implement the background_fetch and flutter_local_notifications together. Can you please look at it once, and tell me the approach I need to follow? Thanks.

**Comment by christocracy** [comment]
Have you figured this out yet?

**Comment by lucasmatoscc** [comment]
How is this task? I'm also unable to perform local notifications

**Comment by lucasmatoscc** [comment]
@ayush221b 
Did you fix this?
