### ISSUE TITLE
I want to perform action for each hour in background, how do we do this.

### ISSUE THREAD

**Issue by Satish-Eruvaka** [transistorsoft/flutter_background_fetch#92]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
Read the README.  See config `minimumFetchInterval (minutes`)
