### ISSUE TITLE
[BUG] No getting any event in background mode in ios.

### ISSUE THREAD

**Issue by khuntdhams** [transistorsoft/flutter_background_fetch#93]
**Your Environment** 
* Plugin version:  0.5.4
* Platform: iOS

**Comment by christocracy** [comment]
Duplicate #70

**Comment by khuntdhams** [comment]
Thanks for the plugin!

But one another question is Can we get any event in terminated mode in iOS by this plugin?

**Comment by christocracy** [comment]
No.  Apple stops firing events when *user* terminates the app.

**Comment by khuntdhams** [comment]
okay. Thank you.
