### ISSUE TITLE
Module 'background_fetch' not found in IOS

### ISSUE THREAD

**Issue by Satish-Eruvaka** [transistorsoft/flutter_background_fetch#94]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**

**Comment by christocracy** [comment]
Ignored issue template.  Edit your issue to provide the requested info.

**Comment by christocracy** [comment]
Closed for ignoring issue template.
