### ISSUE TITLE
[BUG] Android-Periodic Task Works On Emulator But Not On Phone

### ISSUE THREAD

**Issue by rickpalo** [transistorsoft/flutter_background_fetch#95]
**Your Environment**
* Plugin version: 0.5.4
* Platform: Android
* OS version: 9
* Device manufacturer / model: Samsung Galaxy Note 8
* Flutter info (`flutter info`, `flutter doctor`):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/...
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/...
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/...
    • ANDROID_SDK_ROOT = /home/...
    • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Android Studio (version 3.6)
    • Android Studio at /snap/android-studio/84/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Connected device (1 available)
    • SM N950U • ce061716e205382f017e • android-arm64 • Android 9 (API 28)

• No issues found!

* Plugin config: 
```dart
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        forceAlarmManager: false,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        requiredNetworkType: NetworkType.NONE,
```
**To Reproduce**
1. Use repository example code ([main.txt](https://github.com/transistorsoft/flutter_background_fetch/files/4339472/main.txt))

2. Change every 'periodic' option to 'true'
3.  Using emulator (Android SDK built for x86, Android Version 10), start debug, put app in the background and task fires ~ every 15 minutes
4. Using phone, 
 4a.  start debug, initial tasks fire
 4b. Put app into background, manually fire task - works ok
 4c.  Wait 30 minutes for periodic tasks to fire - Nothing in the log
 4d. Manually fire task - Nothing in the log
 4e.  Bring the app to the foreground, periodic tasks fire followed by the manually fired task.

**Debug logs**
- ios -None
- Android: 
[logcat.txt](https://github.com/transistorsoft/flutter_background_fetch/files/4339433/logcat.txt)

**Comment by christocracy** [comment]
- See http://dontkillmyapp.com
- Try using `forceAlarmManager: true`

**Comment by rickpalo** [comment]
The recommendations at http://dontkillmyapp.com fixed it.  Thanks!
