### ISSUE TITLE
[BUG] Execution failed for task ':background_fetch:mergeDebugJavaResource'.

### ISSUE THREAD

**Issue by YannBrrd** [transistorsoft/flutter_background_fetch#99]
**Your Environment**
* Plugin version: 0.5.4
* Platform: Android
* OS version: API 26
* Device manufacturer / model: Nexus 4
* Flutter info (`flutter info`, `flutter doctor`):
D:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [version 10.0.18363.720], locale fr-FR)
    • Flutter version 1.15.17 at D:\flutter
    • Framework revision 2294d75bfa (2 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\yannb\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\yannb\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\yannb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
Process finished with exit code 0
* Plugin config

**To Reproduce**
1. Building my project

** Issue **

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_fetch:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Non-directory inputs must have .jar extension: C:\Users\yannb\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\background_fetch-0.5.4\android\libs\tsbackgroundfetch-0.4.2.aar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
cd android
./gradlew clean

**Comment by YannBrrd** [comment]
Thx
